### ISSUE TITLE
Neutralino.storage.getKeys() is not a function

### ISSUE THREAD

**Issue by shmox75** [neutralinojs/neutralinojs#1000]
**Describe the bug**
I get Neutralino.storage.getKeys() is not a function even by ading storage.* in the nativeAllowList configuration.

when I do console.log(this._ns.Neutralino.storage); I get {setData: ƒ, getData: ƒ} as you note there is no getKeys function.

Please note that I'm building on Angular framework and native os functions are working well.

**Comment by danidre14** [comment]
Upgrade to neutralinos latest version in both binary and client. Get keys was recently added.
Please close this issue when solved.

**Comment by shmox75** [comment]
Sorry to ask, but "neutralino update" command did not fix it. May I ask you how to update ?

**Comment by danidre14** [comment]
Yes. Update both your binary and client library to versions that support this feature.

Update the `neutralino.config.json` file with the following options:
 `cli.binaryVersion` with `4.8.0`
 `cli.clientVersion` with `3.7.0`
Then save, and enter `neu update` in the terminal to fetch the required versions that supports this feature.

**Comment by shmox75** [comment]
> 3.7.0

Done, thanks. I'll close.
