### ISSUE TITLE
function: getEnvs is undefined.

### ISSUE THREAD

**Issue by humbass** [neutralinojs/neutralinojs#1001]
**Describe the bug**
os.getEnvs  is unidefined.

os.getEnv ok,    no arguments description  but "USER"

**Specifications**  
OS: macOS Monterey

Neutralinojs binaries: v4.7.0
Neutralinojs client: v3.6.0
Project version: v1.0.0

**Comment by danidre14** [comment]
Update to neutralino latst version.

**Comment by shalithasuranga** [comment]
Hey.. the missing function will be available when you use the latest Neutralinojs versions as @danidre14 mentioned. Thanks for reporting the issue :tada:
