### ISSUE TITLE
macOS (arm64): Native APIs never respond

### ISSUE THREAD

**Issue by denisw** [neutralinojs/neutralinojs#1005]
**Describe the bug**

On macOS 10.15 (arm64), the communication between the app and Neutralino server does not seem to work correctly. When calling a native API such as `Neutralino.os.getEnv()`, the returned Promise is never resolved.

**To Reproduce**

1. Create an empty project with `neu create napp --template neutralinojs/neutralinojs-zero`
2. In `neutralino.config.js`, add `"os.*"` to `"nativeAllowList"`.
3. Replace `www/index.html` with the following:
  ```html
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
      <title>Hello Neutralinojs</title>
    </head>
    <body>
      <script src="neutralino.js"></script>
      <script>
        function show(text) {
          const pre = document.createElement('pre');
          pre.textContent = text;
          document.body.appendChild(pre);
        }

        async function showConfig() {
          show('Getting config');
          const config = await Neutralino.app.getConfig();
          show('Got config');
          show(JSON.stringify(config));
        }

        showConfig();
      </script>
    </body>
  </html>
   ```
4. Run the app with `neu run`.

**Expected behavior**

I see "Getting config", "Got config", and the app configuration as JSON in the app window.

**Actual behavior**

I see only "Getting config" and nothing else happens.

**Specifications**  

 - OS: macOS arm64
 - Neutralinojs version: v4.8.0
 - Neutralinojs client library version: v3.7.0
 - Neutralinojs CLI version: v9.3.1

**Additional context**

The very same app works as expected on Windows x64. This problem seems to be specific to macOS, or even to macOS arm64.

I also noticed that there is no binary for macOS arm64 in `bin/` - the x64 one is used instead. Maybe this is a problem?

**Comment by danidre14** [comment]
This is the expected behavior. You forgot to call
```Neutralino.init()``` at the top of your code.

Once you do that, the server is properly connected to and initialized, and other Neu calls work.

If this is successful please close this Issue as solved, since it is an error on your end.

**Comment by denisw** [comment]
Oh, my bad! Of course, I should have added `Neutralino.init()`. After I did that, the example worked as expected. Thanks! 👍 

I have still one remaining issue: an `<input type="file">` pops up a file picker when clicked on Windows for me, but not on macOS (drag and drop from the file manager onto the input works on both platforms). I'll file a separate issue for that, though.

**Comment by danidre14** [comment]
Awesome!
Yes, that may be a separate issue with the files. And be sure to check Google on whether that's a problem with your platform's (mac) native browser system by default. As it may ve that, and not necessarily an issue with neu.

**Comment by denisw** [comment]
After some investigation, I found out that the macOS webview setup is apparently incomplete. See #1014.
