### ISSUE TITLE
Add proper file server

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#101]
- [x] Suggestion

Current way of serving files only support js,css in assets and only index.html in root. Create separate cpp and create improved file server.

**Comment by masterjg** [comment]
So there's no way to serve images for example? I've tried to set favicon and it doesn't look like it is possible currently?

**Comment by shalithasuranga** [comment]
Thanks @masterjg for mentioning that. We need to support image files too. Yeah! currently only way is using base64 to display the graphical contents

**Comment by shalithasuranga** [comment]
Closing this since now it has basic MIME types support which is required for application development
