### ISSUE TITLE
Neutralino.debug.log does not log to STDOUT on Windows

### ISSUE THREAD

**Issue by Elanis** [neutralinojs/neutralinojs#1018]
Hi !

When trying to improve my benchmark, I encountered an issue, when I try to log using `Neutralino.debug.log();` on a neutralino app on Windows, it doesn't log anything to STDOUT or STDERR (I tried on git bash and CMD). When trying the exact same project on Linux, it works perfectly.

You can also see that it logs less information than Linux version (might be an hint).

When logging to file, everything logs without problem.

**To Reproduce**
Start the [minimal example](https://github.com/neutralinojs/neutralinojs-minimal), and use `Neutralino.debug.log('test', 'INFO');` in the console or inside the showInfo() function for example.

**Expected behavior**
It should log to console.

**Specifications**  
 - OS: Windows 11 21H2, x64
 - neu CLI: v9.3.1
 - Neutralinojs binaries: v4.6.0
 - Project version: v1.0.0
 - Node version: 18.10.0

Thanks !

**Comment by shalithasuranga** [comment]
Hello @Elanis, thanks for reporting this issue. This bug was fixed and the fix will be released with the next version :tada:

**Comment by Elanis** [comment]
Amazing, thanks! :)

**Comment by Elanis** [comment]
I can confirm it works :) Thanks again!
