### ISSUE TITLE
Neutralino .js cannot be called in index.html in TypeScript projects, indicating that the file cannot be found, and whether there is a neutralino .js that supports the TypeScript version

### ISSUE THREAD

**Issue by qilecms** [neutralinojs/neutralinojs#1024]
Neutralino .js cannot be called in index.html in TypeScript projects, indicating that the file cannot be found, and whether there is a neutralino .js that supports the TypeScript version

**Comment by BeyondMagic** [comment]
https://github.com/cbenriquez/neutralinojs-types/

**Comment by shalithasuranga** [comment]
Closing this since now TypeScript developers can use the `@neutralinojs/lib` NPM library with inbuilt TS definitions. Also, now the CLI copies a separate TS definitions file to projects for developers who don't use this NPM library.

Thanks :tada:
