### ISSUE TITLE
Mistype in function name

### ISSUE THREAD

**Issue by Bolderaysky** [neutralinojs/neutralinojs#1032]
**Describe the bug**
In [window.h](../blob/main/api/window/window.h) there's mistype in function name. Function `void setAwaysOnTop(bool onTop);` has to be `void setAlwaysOnTop(bool onTop);`. In .cpp file this function has correct name. This can lead to some bugs due to fact that there's no prototype for this function in .h (because of mistake in name).

**To Reproduce**
Doesn't need to be reproduced.

**Expected behavior**
Function has to be `void setAlwaysOnTop(bool onTop);` instead of not correct `void setAwaysOnTop(bool onTop);`

**Screenshots/Screen recordings**
There's no need in screenshots.

**Specifications**  
 - OS: Any
 - Neutralinojs version: v4.8.0
 - Neutralinojs client library version: Doesn't figure in issue
 - Neutralinojs CLI version: Doesn't figure in issue

**Comment by shalithasuranga** [comment]
Hey @Bolderaysky, thanks for reporting this :tada:
