### ISSUE TITLE
MacOS BigSur error when run [11.6.1 - latest update for hackintosh i7 4790K ]

### ISSUE THREAD

**Issue by lacvietanh** [neutralinojs/neutralinojs#1038]
neu: INFO Starting process: neutralino-mac_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Volumes/AkiVN/AkiDEV/NeutralinoJS/test/test/bin/neutralino-mac_x64 (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Volumes/AkiVN/AkiDEV/NeutralinoJS/test/test/bin/neutralino-mac_x64
neu: INFO neutralino-mac_x64 was stopped with success code 0
![image](https://user-images.githubusercontent.com/72616454/204066562-743081c1-a16a-4556-a45e-626a0c567fd4.png)

**Comment by lacvietanh** [comment]
--- Global ---
neu CLI: v9.3.1

--- Project: test (js.neutralino.sample) ---
Neutralinojs binaries: v4.9.0
Neutralinojs client: v3.8.0
Project version: v1.0.0

**Comment by wgbbiao** [comment]
没有解决办法？

**Comment by shalithasuranga** [comment]
Closing this since the latest version implements a fix for this. Thanks for reporting and discussing :tada:
