### ISSUE TITLE
Tray localization

### ISSUE THREAD

**Issue by serg-co** [neutralinojs/neutralinojs#1040]
**Describe the bug**
Tray localization not working.

**Screenshots/Screen recordings**
![tray](https://user-images.githubusercontent.com/77325397/204600071-94707e3b-5ca7-486c-9512-6d35c7070a0a.png)

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: 4.9.0
 - Neutralinojs client library version: 3.8.0

**Additional context**
ru_RU

**Comment by shalithasuranga** [comment]
Closing this since now the Neutralinojs Windows version support Unicode characters. Thanks :tada:
