### ISSUE TITLE
Neutralino application doesn't run on windows10(with error code 3221226505)

### ISSUE THREAD

**Issue by allazward** [neutralinojs/neutralinojs#1043]
### Describe the bug
Neutralino application on windows10(x64) doesn't work despite woriking well on windows11(x64)

### To Reproduce
input below command on windows command prompt
1. npm install -g @neutralinojs/neu
1. neu create test
1. CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
1. cd test
  neu run
and display nothing,though i got below message
neu: WARNING neutralino-win_x64.exe was stopped with error code 3221226505

### Specifications
OS: Windows 10 x64
Neutralinojs version: v4.7.0
Neutralinojs client library version: v3.6.0
Neutralinojs CLI version: v9.3.1

### message details
```
C:\works\test >neu run
neu: INFO Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
neu: WARNING neutralino-win_x64.exe was stopped with error code 3221226505
```
mode(window) and all the other configurations leave default

**Comment by JConan** [comment]
Hello,

have you tried since then the version 4.11 ?

**Comment by Sbelletier** [comment]
Hi,
I face a similar issue. 

```neu update```  fails to update to v4.11/4.12 (no error it is just stuck to the current version) so here's the setup i tested with : 


``` 
--- Global ---
neu CLI: v9.6.0

--- Project: headless (js.neutralino.sample) ---
Neutralinojs binaries: v4.10.0
Neutralinojs client: v3.8.2
Project version: v1.0.0
```

running `neu run` gives the same error BUT `neu build` works.
trying to run the created windows exe returns the following error

![image](https://github.com/neutralinojs/neutralinojs/assets/15371062/1f27acf8-f248-4259-a0fc-ac854ddc5363)

(sorry for the french) text basically says the WebView2Loader dll is missing.

So... can we fix it by installing WebView2 directly as per the guide ?
Unfortunately no dice : 

![image](https://github.com/neutralinojs/neutralinojs/assets/15371062/627b168e-e8e2-45a6-a494-a7cf5de4144a)

Seems that it _is_ actually installed on my machine. 
Supposition : linking on windows is failing for some reason

**Comment by akentovsky** [comment]
Application assembly does not work under windows 10 requires WebView2Loader.dll
What do you advise to do?

**Comment by shalithasuranga** [comment]
Hi.. we no longer use the `WebView2Loader.dll` depdendency with app bundles. Please use the latest framework (CLI, and client library) version.

Thanks :tada:

**Comment by Fav** [comment]
mybe you can follow these step
1. download webview2loader.dll
2. copy webview2loader.dll to  youapp/bin
3. neu run
