### ISSUE TITLE
Appending binary files are corrupted on Windows.

### ISSUE THREAD

**Issue by DavidRockin** [neutralinojs/neutralinojs#1053]
**Describe the bug**
Hello, just to start off I discovered this neat tool last night and have been hacking away. And I want to say I'm quite pleased with this so far, as it's allowed me to develop something pretty quickly. So, thank you VERY MUCH for your project. I'm the lead developer for a game, and I'm developing a launcher for the game. When it requests the manifest from our server, the launcher is able to figure out which platform-build it can use, and the manifest contains the file size and a SHA1 hash to verify things downloaded correctly. This lead me to notice appending binary data corrupts the files on Windows.

I've tested this on Linux, and it works correctly. As the file downloads, the binary data is appended correctly, and the file is valid (same size, same SHA1 checksum and can be opened.)

However on Windows, the file sizes will increase slightly, and thus corrupting the entire file, which appears to be caused by the appending fs methods not handling binary correctly? Likely due to line encodings? (see: #619)

**To Reproduce**
I've managed to write a little sample script to generate a temporary buffer, and write the entire buffer to a file, and then a test case of it appending chunks of the buffer to a file. The written buffer works well as expected, however when appending binary data is when the file gets corrupted.

```js
Neutralino.init();

async function sha1Sum(buf) {
    return await crypto.subtle.digest('sha-1', buf)
        .then(a => Array.from(new Uint8Array(a))
        .map(z  => z.toString(16).padStart(2,'0')).join(''));
}

Neutralino.events.on('ready', async () => {
    let buff = new ArrayBuffer(1024 * 1024);
    let view = new Uint8Array(buff);

    for (let i = 0; i < buff.byteLength; ++i) {
        view[i] = i % 256;
    }

    let i = 0;
    const fn = 'test.bin';
    console.log('filename = ' + fn + ', sha1 = ', await sha1Sum(buff));

    await Neutralino.filesystem.writeBinaryFile('good_'+fn, buff);

    while (i < buff.byteLength) {
        const chunk = buff.slice(i, i + 500);
        console.log('chunk = ', chunk.byteLength);
        await Neutralino.filesystem.appendBinaryFile('corrupt_' + fn, chunk);
        i += chunk.byteLength;
    }
});
```

**Expected behavior**
The generated `good_test.bin` is ok, and the `corrupt_test.bin` should be **EXACTLY** the same as the previous file, with the same file size and same exact SHA1 hash.

**Screenshots/Screen recordings**
Here's a hex dump of both files (expected on the left, corrupted one on the right) and you can see there's `0x0D` (carriage return) where it's not supposed to be there.

![image](https://user-images.githubusercontent.com/1907079/210441552-2ee0f9b4-fffd-4f55-baf3-80eb9160b59e.png)

**Specifications**  
 - OS: Windows 10 x64 (22H2 Build 19045.2364) & Linux 5.19.17
 - Neutralinojs version: 4.9.0
 - Neutralinojs client library version: 3.8.0
 - Neutralinojs CLI version: 9.3.1

*Note: you can enter the `neu version` command to find these details*

**Comment by shalithasuranga** [comment]
Hey @DavidRockin thanks for your pull request, it's now merged
