### ISSUE TITLE
Icon missing when app is pinned to taskbar on Windows

### ISSUE THREAD

**Issue by globules-io** [neutralinojs/neutralinojs#1057]
**Describe the bug**
When pinning to taskbar on Windows, the icon changes to a "default icon".

**Expected behavior**
Icon should stay the same

**Specifications**  
 - OS: Windows 10 x64
 -  "binaryVersion": "4.9.0",
 - "clientVersion": "3.8.0"

**Comment by parteekcoder** [comment]
can you please assign me this issue

**Comment by cevznriny** [comment]
There are a couple of ways to fix this.

- Easy way:
Just change the icon in the shortcut properties in windows explorer.

- Better way:
Compile an ico file into a res file and add it to the bz build list.
1. Find or create a windows myicon.ico file.
2. Create an icon.rs file with the contents: id ICON "myicon.ico"
3. Compile the icon.rs file into an icon.res file: rc.exe /r icon.rs
4. Add icon.rs to buildzri.config.json: 
```
    "source": {
        "*": [
            "*.cpp",
             "icon.res",
            "auth/*.cpp",
            "server/*.cpp",
            "api/*/*.cpp",
            "lib/tinyprocess/process.cpp",
            "lib/easylogging/easylogging++.cc",
            "lib/platformfolders/platform_folders.cpp",
            "lib/clip/clip.cpp",
            "lib/clip/image.cpp",
            "lib/infoware/src/**/*.cpp",
            "lib/efsw/src/efsw/*.cpp"
        ],
```

5. Rebuild exe: python scripts/bz.py

You can find a bit more info here:
[ Add resources to executable](https://caiorss.github.io/C-Cpp-Notes/resources-executable.html)

rc.exe is somewhere in the MSVC SDK.
Mine is: C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64\rc.exe

It would be nice if a default ico file was included in neutralinojs so you could just replace it.

**Comment by globules-io** [comment]
Any update with this? It's been a year...

**Comment by hschneider** [comment]
As a workaround, you can add an icon-resource with these build scripts. After this it also shows up when pinned:

https://github.com/hschneider/neutralino-build-scripts

-- Harald

**Comment by CosmoMyzrailGorynych** [comment]
I'll modify neutralino-cli so it builds windows executables with proper icons and metadata.

**Comment by CosmoMyzrailGorynych** [comment]
Well, that was easy.
![изображение](https://github.com/neutralinojs/neutralinojs/assets/3174357/8caf128d-19a9-4107-9756-90ef35e34eb7)
PR coming soon, cleaning up the code.

**Comment by shalithasuranga** [comment]
https://github.com/neutralinojs/neutralinojs-cli/pull/268 fixed this issue. Thanks so much for reporting this issue and starting a discussion :tada:
