### ISSUE TITLE
Center Screen with Neutralino.window.center()?

### ISSUE THREAD

**Issue by adelriosantiago** [neutralinojs/neutralinojs#1059]
It would be great to be able to center the Neutralino screen with `{modes: { window: { centered: true } }}` at _neutralino.config.json_ or via `Neutralino.window.center()`.

Related: https://github.com/neutralinojs/neutralinojs/pull/500, https://stackoverflow.com/questions/75151758/how-to-center-neutralinojs-screen

**Comment by ashu26jha** [comment]
Greetings @adelriosantiago ! I have  answered your question on stackoverflow. Do check my answer at [stackoverflow](https://stackoverflow.com/questions/75151758/how-to-center-neutralinojs-screen). Also I have attached the[ image link ](https://i.stack.imgur.com/dHSLG.png)please do check it.

**Comment by shalithasuranga** [comment]
Fixed via #1108
Thanks for reporting and discussing this :tada:
