### ISSUE TITLE
UDP and TCP bridge to JS ?

### ISSUE THREAD

**Issue by globules-io** [neutralinojs/neutralinojs#1060]
Sort of a feature request and a question at the same time.
Is it possible to implement C++ extensions/libraries like https://github.com/sewenew/redis-plus-plus ?  Would a JS to C++ bridge possible ? I guess the question would be, is it planned to be able to add some plugins maybe? The same way Cordova does it with native code?
Maybe a broader approach would be a UDP and/or TCP bridge to JS?
NeutralinoJS is a great tool but aside from AJAX, there isn't much communication possible.
Thanks

**Comment by danidre14** [comment]
Contrary to your belief, Neutralino does not use AJAX for communication. Rather, Websockets are used [https://neutralino.js.org/docs/].

To answer your question on extensions, see the documentation for creating/using extensions [https://neutralino.js.org/docs/how-to/extensions-overview].

**Comment by globules-io** [comment]
Never pretended it uses AJAX, the "extensions" are compiled executables, not really extensions.

**Comment by globules-io** [comment]
Would rather close this ticket than getting that kind of replies. Waste of time.

**Comment by danidre14** [comment]
In your message, you stated:

> NeutralinoJS is a great tool but aside from AJAX, there isn't much communication possible.

Which gave me the understanding that you understood AJAX being used. Forgive me if I'm misunderstanding your communication.

Also, not everyone using Neutralino uses Cordova, (neither do I), so I'm not sure what you mean when you explain "use extensions the same way Cordova does it"

If this is a feature request, can you specify how you'd expect extensions to look, as well as the flow with code samples of its usage?

Additionally, before proposing requests, browsing the docs to grasp the Neutralino architecture would also help guide you on whether your proposals may be possible.

Going back to your statement:

> NeutralinoJS is a great tool but aside from AJAX, there isn't much communication possible.

Can you also explain what you mean by this?

Cheers.
