### ISSUE TITLE
Improve Clipboard API

### ISSUE THREAD

**Issue by manavagr1108** [neutralinojs/neutralinojs#1062]
**Is your feature request related to a problem? Please describe.**
 - Add more API functions to clipboard to read/write images or urls with hyperlink.

**Describe the solution you'd like**

- Few more functions like
`
Neutralino.clipboard.readImage([image],() => {
...
})
`
`
Neutralino.clipboard.writeImage([image],() => {
...
})
`

**Comment by Sadaf-A** [comment]
Greetings @shalithasuranga ! I wanted to work on this could you please assign me

**Comment by shalithasuranga** [comment]
Hello, @Sadaf-A, thanks for the interest. I'ved assigned you to this issue :tada:, Please let me know if you have questions

**Comment by Sadaf-A** [comment]
@shalithasuranga I think we can close this now since the requested feature has been implemented

**Comment by shalithasuranga** [comment]
Great! @Sadaf-A, thanks for reminding me about this. I'll close this issue then :tada:
