### ISSUE TITLE
No mac_arm64 executable

### ISSUE THREAD

**Issue by boblund** [neutralinojs/neutralinojs#1066]
**Describe the bug**
neu: INFO Error: ENOENT: no such file or directory, chmod 'bin/neutralino-mac_arm64'

**To Reproduce**
1. On Macbook air M1 with Big Sur
2. npm install -g @neutralinojs/neu
3. neu create myapp
4. cd myapp
5. neu run
6. Get message in **Describe the bug**

**Expected behavior**
myapp runs

**Comment by chris-deep** [comment]
New here, just did the same thing and found this ticket.  I see a mac x64 build.  What's the proper run / terminal command to try the Intel binary on Mac?  Thanks!

**Comment by ernest-rudnicki** [comment]
I had the same problem, I went back to my old project with new version of neutralino and when I was trying to run the app it crashed with error that there's is not `mac_arm64` executable.

I found an easy fix for that though. When you run `neu update` it downloads the binary files for OS. Look into that file and change the name of `neutralino-mac_x64` to `neutralino-mac_arm64` and it should work.

@shalithasuranga I am not sure if that was changed by the update of Mac OS or on the side of neutralino, but changing the name of the file for mac executables that are downloaded by `neu update` looks like an easy fix for that problem.

**Comment by shalithasuranga** [comment]
Hello.. seems like the Neutralinojs app template (https://github.com/neutralinojs/neutralinojs-minimal) had an older framework version reference that doesn't contain a dedicated ARM executable for Mac. I've updated the versions now. Could you please check again?

Thanks
