### ISSUE TITLE
Neutralino.window.move permission error

### ISSUE THREAD

**Issue by seuai** [neutralinojs/neutralinojs#1071]
**Describe the bug**
code:  "NE_RT_NATPRME"
message: "Missing permission to execute the native method: window.move"

**To Reproduce**
1. neu create myapp
2. cd myapp
3. neu run
4. Inspector tool open
5. "await Neutralino.window.move(10, 5);" typing Enter
6. See error

**Screenshots/Screen recordings**
![image](https://user-images.githubusercontent.com/29100776/219308368-dc0d6287-a824-437a-bf56-92b3c81a28e5.png)

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: v4.9.0
 - Neutralinojs client library version: v3.8.0
 - Neutralinojs CLI version: v9.4.0

**Comment by NimishKashyap** [comment]
This error is also occurring on Linux (Ubuntu 20.04)

**Comment by JConan** [comment]
Hello, did you add permission to nativeAllowList ? 
it is in the neutralino.config.json file
