### ISSUE TITLE
Weird characters if stream size is larger than file size with filesystem.updateOpenedFile

### ISSUE THREAD

**Issue by AckerApple** [neutralinojs/neutralinojs#1075]
**Describe the bug**
If I stream read a file and ask for it to be streamed in slices larger than the actual file size, I get odd characters added to end of string

filesystem.updateOpenedFile(fileId, 'readAll', chunkSize)

**To Reproduce**
1. const fileId = await Neutralino.filesystem.openFile( filePath )
2. await Neutralino.filesystem.updateOpenedFile(fileId, 'readAll', chunkSize)
3. IF the chunkSize is greater than the file size, console log and see extra characters added on

**Expected behavior**
Just like when you stream a file in Chrome or Edge using FileReader, if the slicing size is larger than the file size you only get the file contents and no more

**Screenshots/Screen recordings**
Sorry I'm fixed the issue and moved on

**Specifications**  
- neu CLI: v9.4.0
- Neutralinojs binaries: v4.9.0
- Neutralinojs client: v3.8.0
- MacOsx

**Additional context**
To solve the issue, before I stream read a file I look at the file size and reduce chunkSize if file size less than chunkSize

**Comment by shalithasuranga** [comment]
Hey @AckerApple, Thanks for reporting this issue. This was fixed and will be released with the next version
