### ISSUE TITLE
New project/sample not running

### ISSUE THREAD

**Issue by BigBadWouf** [neutralinojs/neutralinojs#1092]
Hi,

I cannot start sample project if i just follow steps from get started. 

```shell
npm i -g @neutralinojs/neu
neu create myapp
cd myapp && neu run
``` 

give the error : 
```shell
bin/neutralino-linux_x64: bin/neutralino-linux_x64 : cannot execute binary file : Exec() format error
``` 

Same error with build. I dont try on other system.
To solve it, i need to clone the github repository and compile the cli tool, and copy the neutralino-linux_x64 in my sample project.

My system : 
```shell
$ uname -a
Linux Desktop 5.15.106-1-MANJARO #1 SMP PREEMPT Wed Apr 5 09:58:14 UTC 2023 x86_64 GNU/Linux
``` 

Neutralino version : 
```shell
$ neu version
  _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___ 
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/     
--- Global ---
neu CLI: v9.5.0

--- Project: myapp (js.neutralino.sample) ---
Neutralinojs binaries: v4.10.0
Neutralinojs client: v3.8.2
Project version: v1.0.0
```

**Comment by Developer-42** [comment]
[I have the same problem.](https://github.com/neutralinojs/neutralinojs/issues/1093) Are you also working with an older NPM version?

**Comment by shalithasuranga** [comment]
Seems like this issue was occured due to corrupted binary file data. Please try using the latest Neutralinojs version :tada:
