### ISSUE TITLE
Cannot run new project/binary

### ISSUE THREAD

**Issue by Developer-42** [neutralinojs/neutralinojs#1093]
**Description**
Older projects work, but when I create a new one, it cannot run the executable.

**To Reproduce**
Run
```shell
neu create testapp
cd testapp && neu run
```
Output:
```shell
neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
bin/neutralino-linux_x64: bin/neutralino-linux_x64: Cannot run file (translated from German)
neu: WARNING neutralino-linux_x64 was stopped with error code 126
``` 

**Expected behavior**
A working default project.

**Specifications**  
 - OS: Manjaro Linux x86_64 with Gnome Desktop (Wayland)
 - Neutralinojs **binaries**: v4.10.0
 - Neutralinojs client library version: v3.8.2
 - Neutralinojs CLI version: global v9.5.0

**Additional context**
This also happens after I run `chmod +x neutralino-linux_x64`. I just installed neutralino globally with NPM version 8.19.2-1, which is the current version in the community repo installed with pamac. For some reason, it's not updated to 9.6.4 yet. In case this is unexpected, I installed it with sudo: `sudo npm install -g @neutralinojs/neu`

**Comment by swwind** [comment]
Same here, what did it downloaded?

**Comment by Developer-42** [comment]
Is this problem unclear, or is nobody going to address it for other reasons? I already experienced this bug years ago on Linux Mint, and it's still not a priority.

**Comment by KTibow** [comment]
I fixed this issue by upgrading my dependencies

**Comment by Developer-42** [comment]
I confirm that the issue is fixed with nodejs and npm installed with apt under Debian.
