### ISSUE TITLE
Windows 11 can't run sample - spawn unknown error

### ISSUE THREAD

**Issue by ken444** [neutralinojs/neutralinojs#1094]
PS C:\Users\****\Downloads\node\myapp> neu run
neu: INFO Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
neu: INFO Error: spawn UNKNOWN 

PS C:\Users\****\Downloads\node\myapp> neu version
 _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
neu CLI: v9.5.0

--- Project: myapp (js.neutralino.sample) ---
Neutralinojs binaries: v4.10.0
Neutralinojs client: v3.8.2
Project version: v1.0.0

**Comment by 09silverware** [comment]
Have the same issue on Windows 10, fresh install of Neu. So it's not Windows 11 specific.
Tried setting ExecutionPolicy to Bypass, and that did not change anything.
Defender picked up nothing, so it's not that either.

```
C:\Users\<snip>\Code\osb>neu run
neu: INFO Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
neu: INFO Error: spawn UNKNOWN
```

```
--- Global ---
neu CLI: v9.5.0

--- Project: osb (js.neutralino.sample) ---
Neutralinojs binaries: v4.10.0
Neutralinojs client: v3.8.2
Project version: v1.0.0
```

**Comment by 09silverware** [comment]
Redownloading the latest release binaries (4.11.0) resolved this for me
https://github.com/neutralinojs/neutralinojs/releases

**Comment by shalithasuranga** [comment]
Closing the issue since these issues don't happen with the latest Neutralinojs version on Windows :tada: Thanks for reporting and discussing :)
