### ISSUE TITLE
Calling Neutralino.app.exit() on Mac does not work.

### ISSUE THREAD

**Issue by aleph1** [neutralinojs/neutralinojs#1095]
**Describe the bug**
The neutralinojs application should exit, but nothing happens.

**To Reproduce**
1. On a Mac, clone a bare bones example neutralinojs app that creates “exit” and “exit and kill” buttons https://github.com/aleph1/neutralino-exit-broken
2. Click the exit button, Neutralino.app.exit() is called but the app does not exit. 
3. Click the exit and kill button, Neutralino.app.exit() is called followed by Neutralino.app.killProcess() but the app does not exit. 

**Expected behavior**
Clicking the exit button should exit the application. The same issue occurs when trying to exit with a keypress listener, basically Neutralino.app.exit() does nothing in all cases.

This is a major bug as it effectively prevents being able to release an app that can be exited in any way other the clicking the close button as part of the window’s chrome.

**Specifications**  
 - OS: macOS 11 arm64 x64
 - Neutralinojs version: v4.11.0
 - Neutralinojs client library version: v3.0.2
 - Neutralinojs CLI version: v9.5.0

**Comment by perminder-17** [comment]
//assign

**Comment by hschneider** [comment]
Tested on latest macOS 14.1.1:
Neutralino.app.exit(); works as expected and the app closes immediately.

**Comment by shalithasuranga** [comment]
Hello @hschneider, thanks for testing. Looks like we can close this issue :tada:
