### ISSUE TITLE
I can build app from source and run test pass, but cannot run new project through neu

### ISSUE THREAD

**Issue by ICEJM1020** [neutralinojs/neutralinojs#1096]
**Describe the bug**

I followed the tutorial on the website, both https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app and https://neutralino.js.org/docs/getting-started/using-frontend-libraries. I have successfully done everything, but once I run the `neu run`, I will get a lot of unrecognizable output with error code 2, like this:
![Screenshot from 2023-04-21 19-11-07](https://user-images.githubusercontent.com/38009758/233631859-62f07637-994f-468a-a707-5c292943d2bc.png)

![Screenshot from 2023-04-21 19-10-48](https://user-images.githubusercontent.com/38009758/233631786-47a17019-e2e4-44a1-ae0e-f502445a7fe9.png)

 At first, I thought this is because of my libstdc++ or other dependencies error, so I try to build from source. But actually I finish all build work and pass most test (except 3 extension), like this:

![Screenshot from 2023-04-21 19-10-17](https://user-images.githubusercontent.com/38009758/233632325-145bb30f-9c8f-4fad-84f4-54d704943b56.png)

I also try to uninstall and re-install neu, but I still cannot run the tutorial app.

**To Reproduce**
Just follow the tutorial.

**Expected behavior**
I hope it could run......

**Specifications**  
 - OS: Ubuntu 22.04
 - Neutralinojs version: v4.10.0
 - Neutralinojs client library version:  v3.8.2
 - Neutralinojs CLI version:  v9.5.0

**Comment by shalithasuranga** [comment]
Please check the latest  codebase. There are no issues with the GNU/Linux platform tests. Thanks so much for reporting this issue :tada:
