### ISSUE TITLE
error when running after build

### ISSUE THREAD

**Issue by seuai** [neutralinojs/neutralinojs#1099]
**Describe the bug**

**To Reproduce**
1. neu create myapp
2. cd myapp
3. neu build
4. ./dist/myapp/myapp-win_x64.exe
5. window close immediately

"neu run" command no issue

**Expected behavior**
/js/neutralino.js load error

**Screenshots/Screen recordings**
window closes immediately

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: v4.11.0
 - Neutralinojs client library version: v3.8.2
 - Neutralinojs CLI version: v1.0.0

**Comment by shalithasuranga** [comment]
Hello @seuai could you please verify that this issue happens with the latest Neutralinojs version? We can re-open this issue when we can discuss more about this particular issue :) Thanks for posting this
