### ISSUE TITLE
Unable to use native API

### ISSUE THREAD

**Issue by orizzontiholding** [neutralinojs/neutralinojs#1101]
I have this configuration for my vite vue neutralino app

```
{
    "applicationId": "js.neutralino.zero",
    "version": "1.0.0",
    "defaultMode": "window",
    "documentRoot": "/front-end/dist/",
    "url": "/",
    "enableServer": true,
    "enableNativeAPI": true,
    "nativeAllowList": [
        "app.*",
        "filesystem.*",
        "window.*",
        "os.*"
    ],
    "modes": {
        "window": {
            "title": "GDA - Tool rifatturazione",
            "width": 1280,
            "height": 720,
            "minWidth": 400,
            "minHeight": 200,
            "icon": "/front-end/dist/icon.png"
        }
    },
    "cli": {
        "frontendLibrary": {
            "patchFile": "/front-end/index.html",
            "devUrl": "http://localhost:5173/"
        },
        "binaryName": "standalone",
        "resourcesPath": "/front-end/dist/",
        "extensionsPath": "/extensions/",
        "binaryVersion": "4.10.0",
        "clientVersion": "3.8.2"
    }
}
```{
    "applicationId": "js.neutralino.zero",
    "version": "1.0.0",
    "defaultMode": "window",
    "documentRoot": "/front-end/dist/",
    "url": "/",
    "enableServer": true,
    "enableNativeAPI": true,
    "nativeAllowList": [
        "app.*",
        "filesystem.*",
        "window.*",
        "os.*"
    ],
    "modes": {
        "window": {
            "title": "Demo App",
            "width": 1280,
            "height": 720,
            "minWidth": 400,
            "minHeight": 200,
            "icon": "/front-end/dist/icon.png"
        }
    },
    "cli": {
        "frontendLibrary": {
            "patchFile": "/front-end/index.html",
            "devUrl": "http://localhost:5173/"
        },
        "binaryName": "standalone",
        "resourcesPath": "/front-end/dist/",
        "extensionsPath": "/extensions/",
        "binaryVersion": "4.10.0",
        "clientVersion": "3.8.2"
    }
}
```
I've imported into the `index.html` file that is used to build the vue app the neutralino script by including it from node_modules folder in this way
`<script src="node_modules/@neutralinojs/lib/dist/neutralino.js"></script>`

Whan I'm using the following command to start neutralino
`npx @neutralinojs/neu run --frontend-lib-dev -- --window-enable-inspector`
The window will open correctly, and I'm able to see the the application, but the main problem is that if I try to change the mode in config file of neutralino, and save, the modification will be not applied. Also I've noticed that the `NL_` globals are not loaded and I'm unable to use the native api. 

I've used the following way to load the globals and the auth file after create a symlink into the src folder of my vue project but without success. This is what I have in my main,.js file of the vue app (entry point)

```js
import { createApp } from 'vue'
import App from './App.vue'
//
import '@popperjs/core'
import 'bootstrap/dist/js/bootstrap.min.js'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
//
import { init, window } from '@neutralinojs/lib'
import authInfo from './auth_info.json'


const app = createApp(App)
app.mount('#app')
//
if( !window.NL_PORT ){
    console.log(authInfo, window)
    window.NL_PORT = authInfo.port
    window.NL_TOKEN = authInfo.accessToken
}

init()
```
I'm on a windows 11, is there a way to fix this??

**Comment by ShivangRawat30** [comment]
@orizzontiholding Firstly, the mode in your Neutralino configuration file is set to "window" with a specific title, icon, width, and height. However, you mentioned that you are using the default Neutralino window when you run the application. Try this 
npx @neutralinojs/neu run --mode=window
This should open the window with the title, icon, width, and height as defined in the config file.
Secondly, it seems like you are trying to use the Native API but the globals are not loaded. 
Try moving the Neutralino initialization code to before mounting the app, like this:


if( !window.NL_PORT ){
    console.log(authInfo, window)
    window.NL_PORT = authInfo.port
    window.NL_TOKEN = authInfo.accessToken
}

init()

const app = createApp(App)
app.mount('#app')

I hope this helps.

**Comment by orizzontiholding** [comment]
> @orizzontiholding Firstly, the mode in your Neutralino configuration file is set to "window" with a specific title, icon, width, and height. However, you mentioned that you are using the default Neutralino window when you run the application. Try this npx @neutralinojs/neu run --mode=window This should open the window with the title, icon, width, and height as defined in the config file. Secondly, it seems like you are trying to use the Native API but the globals are not loaded. Try moving the Neutralino initialization code to before mounting the app, like this:
> 
> if( !window.NL_PORT ){ console.log(authInfo, window) window.NL_PORT = authInfo.port window.NL_TOKEN = authInfo.accessToken }
> 
> init()
> 
> const app = createApp(App) app.mount('#app')
> 
> I hope this helps.

At the moment I've moved to electron that will let me use the native API without problems. 
The neutralino app that I was developing originally is in stand-by, I've tried the suggested solution, but if I initialize neutralino before the vue app, I will get a blank screen.

**Comment by orizzontiholding** [comment]
> Hello @orizzontiholding, thanks for posting this. These HMR-related issues are fixed in the latest CLI version. Please check the update tutorial: https://neutralino.js.org/docs/getting-started/using-frontend-libraries
> 
> Thanks 🎉

I will check the new version of the tutorial. It will be nice to have a vue 3 implementation tutorial. 
Thak you for the help, I'll let you know

**Comment by shalithasuranga** [comment]
Welcome :) Sure, we'll introduce a Vue template soon as the existing React template, then Vue developers can easily initialize a project just with the `neu create` command :tada:
