### ISSUE TITLE
Neutralino.filesystem.createWatcher only works on first run

### ISSUE THREAD

**Issue by rooomFelix** [neutralinojs/neutralinojs#1104]
**Describe the bug**
Neutralino.filesystem.createWatcher only works on the first run. After reload it creates the following error:
Uncaught (in promise) {code: 'NE_FS_UNLCWAT', message: 'Unable to create watcher for path: E:\\Data\\Projects\\hello-world'}

**To Reproduce**
let watcherId = await Neutralino.filesystem.createWatcher("E:\\Data\\Projects\\hello-world");
    Neutralino.events.on('watchFile', (evt) => {
        if(watcherId == evt.detail.id) {
            console.log(evt.detail);
        }
    });
    console.log(`ID: ${watcherId}`);

**Expected behavior**
watcher should work even after refresh

**Specifications**  
 - OS: [e.g. Windows 11 x64]
 - Neutralinojs version: [e.g. v4.11.0]
 - Neutralinojs client library version: [e.g. v3.3.0]
 - Neutralinojs CLI version: [e.g. v9.5.1]

**Comment by shalithasuranga** [comment]
Hey @rooomFelix, thanks for reporting this issue. Now we fixed this issue by returning the watcherId if there is an existing watcher for the given path. The fix will be released soon with the next framework release.

Thanks :tada:
