### ISSUE TITLE
Combined with the framework, writing like this does not work

### ISSUE THREAD

**Issue by github-ZH-cn** [neutralinojs/neutralinojs#1105]
![image](https://github.com/neutralinojs/neutralinojs/assets/67533362/323b01af-5e58-49bd-bc01-65b104a4d515)
How to solve it

**Comment by JConan** [comment]
Hi, it is not working because your vue app is not connected to the "backend Native API".

You can check example here :
https://neutralino.js.org/docs/getting-started/using-frontend-libraries/

**Comment by github-ZH-cn** [comment]
I hope to add a template for React or Vue


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neutralinojs/neutralinojs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 凌晨5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neutralinojs/neutralinojs] Combined with the framework, writing like this does not work (Issue #1105)





 
Hi, it is not working because your vue app is not connected to the "backend Native API".
 
You can check example here :
 https://neutralino.js.org/docs/getting-started/using-frontend-libraries/

**Comment by shalithasuranga** [comment]
Closing this since it's already answered by @JConan. This issue can be solved by calling `init()` as explained in the [official documentation](https://neutralino.js.org/docs/getting-started/using-frontend-libraries/#initializing-native-api-with-neutralinojslib): . Thanks :tada:
