### ISSUE TITLE
Unable to load schema from 'https://raw.githubusercontent.com/neutralinojs/neutralinojs/main/schemas/neutralino.config.schema.json': connect ETIMEDOUT 49.44.79.236:443.

### ISSUE THREAD

**Issue by Iamam305** [neutralinojs/neutralinojs#1124]
Unable to load schema from 'https://raw.githubusercontent.com/neutralinojs/neutralinojs/main/schemas/neutralino.config.schema.json': connect ETIMEDOUT 49.44.79.236:443.

**To Reproduce**
create new app using neu create myapp command and this bug will be there

**Comment by nicorac** [comment]
Are you behind a proxy?

**Comment by Iamam305** [comment]
> Are you behind a proxy?

no, but I think there is something wrong with my internet provider (jio), none of raw.githubusercontent.com urls aee working for me, qhen I switched the isp it worked. so I am closing this issue. I would like to request to move the schema to other schema hosting platforms
