### ISSUE TITLE
Can't get example app to run, error code 3221225781 (windows 10)

### ISSUE THREAD

**Issue by Insomnia88** [neutralinojs/neutralinojs#1125]
**Describe the bug**
I just installed the new version of node, npm and neutralinojs, used the example in the "get started" section of the docs and try to run it via "neu run". I receive the error "neu: WARNING neutralino-win_x64.exe was stopped with error code 3221225781"

**To Reproduce**
1. Download neutralinojs via npm
2. Start a new project with "neu create myapp"
3. Try to run the project with "cd myapp" & "run myapp"
4. See the error

**Expected behavior**
It should run without causing any errors

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: 4.10.0
 - Neutralinojs client library version: 3.8.2
 - Neutralinojs CLI version: 9.6.0
 - npm version: 9.7.1
 - nodejs: 18.16.0

**Comment by Insomnia88** [comment]
It works when using this workaround
https://github.com/neutralinojs/neutralinojs/issues/1094#issuecomment-1519029563

**Comment by Meistermagier** [comment]
can confirm this trick works for me aswell? Is there maybe a problem in the distributed binaries of the release version?

**Comment by shalithasuranga** [comment]
Closing the issue since these issues don't happen with the latest Neutralinojs version on Windows :tada: Thanks for reporting and discussing :)
