### ISSUE TITLE
Non-latin characters in Windows 11 tray menu with v4.13.0

### ISSUE THREAD

**Issue by jouni-kantola** [neutralinojs/neutralinojs#1128]
**Describe the bug**
After updating to `v4.13.0` texts in the Windows 11 tray menu are no longer using Latin characters. Problem doesn't occur after rolling back to `v4.11.0`.

![image](https://github.com/neutralinojs/neutralinojs/assets/2670127/cfd05c7b-f051-4196-bb03-c1b9ea0927fe)

**To Reproduce**
1. `npx @neutralinojs/neu create myapp`
1. `cd .\myapp\`
1. `npx @neutralinojs/neu update`
1. `npx @neutralinojs/neu run`
1. Click tray icon to show tray menu items. Menu item texts are not Latin characters in v4.13.0.

**Expected behavior**
Is there a configuration option that should be set? If no, tray menu item texts should stay as Latin characters after version upgrade.

**Specifications**  
 - OS: Windows 11 x64
 - neu CLI: v9.6.0
 - Neutralinojs binaries: v4.13.0
 - Neutralinojs client: v3.11.0

**Comment by jouni-kantola** [comment]
Also happens in `v4.13`. Updating issue to reflect easier repro after https://github.com/neutralinojs/neutralinojs-minimal/commit/6afe89c38cb6dee83203cb8fd525335d6350bd4b.

**Comment by jouni-kantola** [comment]
I tried with latest nightly after the PR was merged and tray now looks good. ✔️
![image](https://github.com/neutralinojs/neutralinojs/assets/2670127/7f227a30-f363-4553-bc15-adfe6eb49d88)

**Comment by shalithasuranga** [comment]
Thanks for testing and posting results @jouni-kantola :tada:
