### ISSUE TITLE
the extension does not working

### ISSUE THREAD

**Issue by exment** [neutralinojs/neutralinojs#1129]
**Describe the bug**
after run neu build
run program, the extension does not working...
and unable to find any logs

**To Reproduce**
run neu build

**Specifications**  
 - OS: mac os m1 12.6, mac os 12.6,windows 10
 - Neutralinojs version: all
 - Neutralinojs client library version: all
 - Neutralinojs CLI version: all

**Additional context**
in dist directory, mac os ,double click executable file，in terminal，show extension log.
besides (package app) the extension does not working...
on windows the extension does not working too...

**Comment by shalithasuranga** [comment]
Hello @exment could you please verify that this issue happens with the latest Neutralinojs version? We can re-open this issue when we can discuss more about this particular issue :) Thanks for posting this
