### ISSUE TITLE
neutralino-win_x64.exe was stopped with error code 3221225595

### ISSUE THREAD

**Issue by Heartnett** [neutralinojs/neutralinojs#1130]
**Describe the bug**
Cannot run a neutralinojs boilerplate project on windows 11 x64. 
`neutralino-win_x64.exe` produces error code `3221225595`

**To Reproduce**
1. Open up your terminal to run the following commands
2. Create a project - `npx @neutralinojs/neu create test-app`
3. Run the project - `cd test-app && npx @neutralinojs/neu run`
4. Produces the following output:
```
neu: INFO Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
neu: WARNING neutralino-win_x64.exe was stopped with error code 3221225781
```

**Expected behavior**
Run a neutralinojs project without issues.

**Screenshots/Screen recordings**
![image](https://github.com/neutralinojs/neutralinojs/assets/11403655/cf3b568c-8f2f-48fe-9405-95cadb4ff6d9)
![image](https://github.com/neutralinojs/neutralinojs/assets/11403655/585e6c50-b18a-4e95-9205-0cf48a8b8a25)

**Specifications**  
 - OS: Windows 11 Pro x64 Version 10.0.22621 Build 22621
 - Neutralinojs version: v4.10.0
 - Neutralinojs client library version: v3.8.2
 - Neutralinojs CLI version: v9.6.0

**Comment by cd-FileX** [comment]
Try it with [this](https://github.com/neutralinojs/neutralinojs/issues/1094#issuecomment-1519029563)
