### ISSUE TITLE
Mac OS bundle - storage handle

### ISSUE THREAD

**Issue by owlysk** [neutralinojs/neutralinojs#1131]
Hi,
I try to make Apple bundle for my neutralino application, but I have a issue with storage feature. My application is using storage feature, which is working great after run in terminal. But in Apple bundle app, I can't update any storage file - because apple app bundle is read-only.
Is there any suggestion to make storage writeable or any workaround to make this work?
Thanks

**Comment by offe** [comment]
Could you share some information on how you make your app bundle? Also, do you have a minimal example showing how the storage feature is not working?

**Comment by owlysk** [comment]
Hi,
I made manual bundle (just zip with directory structure I found in another issues):
- [https://github.com/neutralinojs/neutralinojs/issues/577](https://github.com/neutralinojs/neutralinojs/issues/577)
- [https://github.com/neutralinojs/neutralinojs/issues/884](https://github.com/neutralinojs/neutralinojs/issues/884)

I don't think, this is bug (terminal script after ```neu build --release``` ) works fine - it's not write protected because is in ordinary directory. 
But if I made bundle (wrap app into zip with specific directory structure), whole bundle is read-only (I think it is MAC OS limitation), so I am looking for workaround how to deal with it.

As example, you can use bundle in this issue [https://github.com/owlysk/CodeTimer/issues/1](https://github.com/owlysk/CodeTimer/issues/1) and you can try save any settings.

Thank you

**Comment by owlysk** [comment]
Recently I tried to replace settings files in bundle with symlink to files located in app directory, where should be app data stored for macOS. That doesn't work :(

Nobody is making bundle for macOS with neutralino storage?

**Comment by hschneider** [comment]
Create a macOS app bundle with this build-script:
https://github.com/hschneider/neutralino-build-scripts

It relocates the Neutralino resources to the bundle's Resources folder, which is writeable without breaking the code-signature and notarization.

**Comment by hschneider** [comment]
@shalithasuranga I think you can close this, because the build-scripts solve all macOS App Bundle related issues. I verified that .storage works with app bundles.
