### ISSUE TITLE
The current Webkit2gtk version that's used is obsolete, please update it.

### ISSUE THREAD

**Issue by rempas** [neutralinojs/neutralinojs#1132]
**Is your feature request related to a problem? Please describe.**
The current "webkit2gtk" version used is obsolete. Have a look at [this](https://blogs.gnome.org/mcatanzaro/2023/03/21/webkitgtk-api-for-gtk-4-is-now-stable/) blog post for more information.

**Describe the solution you'd like**
The better solution is to update to webkitgtk-6.0 which is the latest version that uses the latest GTK4. But at least, webkit2gtk-4.1 which is the latest GTK3 version would be more proper.

**Describe alternatives you've considered**

**Additional context**

Thanks for your time reading this and your work with the library! If I can help on anything else, let me know!

**Comment by Developer-42** [comment]
Out of curiosity, is a user who only has the latest webkitgtk installed able to run a built neutralino app in this case? So is the outdated version only a problem for the developer or for any user on Linux too?

**Comment by rempas** [comment]
> Out of curiosity, is a user who only has the latest webkitgtk installed able to run a built neutralino app in this case? So is the outdated version only a problem for the developer or for any user on Linux too?

If you are asking me, I stop using neutralino (not because the Webkit2gtk is out of date) so I cannot say for sure. But if I had to guess, I would say that it would probably not work, as Gtk4 is a major release and it breaks compatibility with Gtk3. However, while targeting different different Gtk versions, Webkit2gtk isn't a major update so maybe the API stays the same and it may work.

**Comment by Developer-42** [comment]
@rempas Thanks for the answer. Do you recommend Electron or something else?

**Comment by rempas** [comment]
> @rempas Thanks for the answer. Do you recommend Electron or something else?

You're welcome! I was planning to use JS for building a commercial project, but I finally not do it. So, I will not use anything. For now, I create [Nemesis](https://codeberg.org/rempas/nemesis) and If I ever go back to using JS, I may look into neutralino. I wouldn't recommend Electron, however. It's too heavy and bloated, even for a web technology.

**Comment by rempas** [comment]
Also, regardless the Webkit2Gtk version, I just looked the blog page again, and I was very wrong. The new Webkit2Gtk version is 6.0 which is a major update. So now, I'm certain that people who only have that won't be able to use neutralino. Hence, I will search for something else If I ever come back to use JS...

**Comment by shalithasuranga** [comment]
Fixed via #1307 (see the last comment for more info). Thanks so much for reporting this issue and starting a discussion :tada:

**Comment by rempas** [comment]
> Fixed via #1307 (see the last comment for more info). Thanks so much for reporting this issue and starting a discussion 🎉

My pleasure! Have a beutiful day!

**Comment by shalithasuranga** [comment]
> > Fixed via #1307 (see the last comment for more info). Thanks so much for reporting this issue and starting a discussion 🎉
> 
> My pleasure! Have a beautiful day!

Have a beautiful day to you too :tada: cheers!
