### ISSUE TITLE
Error on launching sample applications in windows 7

### ISSUE THREAD

**Issue by wbgl** [neutralinojs/neutralinojs#1133]
In all three sample applications, on launching I get error:
in Liteman-win.exe and Litepy, on launching, it shows this error: "Entry Point Not Found" SetProcessDpiAwarenessContext couldnt be located in dynamic link library USER32.dll.
In "fonline_name_colorizing" application, on launching it shows nothing, and the applicationwill be crashed. then Windows suggests a familiar message: "do you want debug?"

**To Reproduce**

**Expected behavior**

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.

**Specifications**  
 - OS: [e.g. Windows 10 x64]
 - Neutralinojs version: [e.g. v4.3.0]
 - Neutralinojs client library version: [e.g. v3.3.0]
 - Neutralinojs CLI version: [e.g. v9.1.2]

*Note: you can enter the `neu version` command to find these details*

**Additional context**

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue @wbgl. I am closing this since we have #486 to track this problem :)
