### ISSUE TITLE
Windows Tray concatenates Unicode codepoints in menuItems text

### ISSUE THREAD

**Issue by MatthiGamer** [neutralinojs/neutralinojs#1149]
**Problem**
I'm on Windows and the text on the menu items concatenates all the unicode strings to chinese characters.
Example: In the default example there is already text there. But instead of "Version" I get this:
![grafik](https://github.com/neutralinojs/neutralinojs/assets/29986457/bfac1a4e-98fa-424a-b5df-8c242e0d9cd8)

**Findings**
I looked more into it and found out, that the Unicode Codepoints get concatenated. Instead of \u0056 and \u0065 ("Ve") you get \u0056\u0065 (Some Chinese thing)

**Screenshots**
![grafik](https://github.com/neutralinojs/neutralinojs/assets/29986457/cd1947f5-135a-48f1-9acb-7437c2a74909)
This example tray is displayed like that:
![grafik](https://github.com/neutralinojs/neutralinojs/assets/29986457/471dfa15-aa19-4a65-b4b0-528431dd5f19)

**Specifications**
 - OS: Windows 10 x64
 - Neutralinojs version: v4.13.0
 - Neutralinojs client library version: v3.11.0
 - Neutralinojs CLI version: v9.6.1

**Comment by jouni-kantola** [comment]
Is this a dupe of #1128? If yes, then you can use the Nightly version.

**Comment by MatthiGamer** [comment]
> Is this a dupe of #1128? If yes, then you can use the Nightly version.

Seems like it. Thank you.
