### ISSUE TITLE
I can't read many files error is too generic: NE_RT_NATRTER/Users/ackerapple/projects/services/megacade/main/myapp/neutralino.config.json

### ISSUE THREAD

**Issue by AckerApple** [neutralinojs/neutralinojs#1151]
**Describe the bug**
I can read a lot of files but not all. The fs error is too generic. Wish error gave me more details.

I get just: "Native method execution error occurred. Make sure that you've provided required parameters properly."

```
await Neutralino.filesystem.updateOpenedFile(fileId, 'read', chunkSize) <--- code breaks inside here
```

**To Reproduce**
1. Read various different files, especially files created on Windows but being read on a Mac
2. I suspect maybe its that files were written on a Windows machine that are being read on a Mac?

**Expected behavior**
Expect more clear error details. Chrome browser can stream read all these same files no problem. Expect Neu to read them too

**Specifications**  
--- Global ---
neu CLI: v9.6.1

--- Project: mega-aide (js.mega-aide.app) ---
Neutralinojs binaries: v4.13.0
Neutralinojs client: v3.11.0
Project version: v1.0.0
*Note: you can enter the `neu version` command to find these details*

**Screenshots/Screen recordings**
![image](https://github.com/neutralinojs/neutralinojs/assets/7964429/251cb31f-5a1b-49ef-b148-18ab25f9a7d2)

**Comment by shalithasuranga** [comment]
Hey @AckerApple thanks for reporting this issue with screenshots. This happens when we try to read binary files, so we've added `readBinary` and `readAllBinary` actions which will return an ArrayBuffer via the `dataBinary` action. This fix will be released with the next release and you can test nightly builds tomorrow. 

Thanks :tada:

**Comment by AckerApple** [comment]
Thank you kindly. I will wait a few days and then try to find where I can acquire a nightly build.

Truly hope a meaningful error message might be there for when this issue occurs. I am wondering that if I go back and try NeutralinoJs again with this new readBinary/readAllBinary, how can I ensure all files can be handled or would I just read all files using readBinary/readAllBinary?

Your message is appreciated and gives me hope to try Neutralinojs again if this gets solved.

**Comment by shalithasuranga** [comment]
Hey.. welcome and thanks for your response. Yeah, I agree there are some generic runtime errors that can be replaced with meaningful ones. Regarding this fix, we can use `read`, `readAll`, and `data` (output event) for working with plain text files and `readBinary`, `readAllBinary`, and `dataBinary` (output event) for working with binary files, the same as we use `readFile` and `readBinaryFile`.. These events are not documented yet, but you can test with the nightly builds. Let me know if you have more questions :tada:
