### ISSUE TITLE
Portable application not working on macOS

### ISSUE THREAD

**Issue by ramiel** [neutralinojs/neutralinojs#1152]
**Describe the bug**
I have an app that uses an extension. When I build it for release it works perfectly but if I change the filename on MacOS adding `.app` extensions (like suggested by [documentation](https://neutralino.js.org/docs/distribution/overview#creating-a-portable-application-package-for-macos)), it stops working

**To Reproduce**
Create an app with an extensions that sends some message to the main app. 
Build for release.
Rename the macos binary adding the .app extensions

**Expected behavior**
It should work as expected

**Specifications**  
 - OS: [e.g. Windows 10 x64]
 - Neutralinojs version: v4.10.0
 - Neutralinojs client library version: v3.8.2
 - Neutralinojs CLI version: v9.6.1

**Comment by hschneider** [comment]
Create a macOS app bundle with this build-script. The result can be code-signed and notarized:
https://github.com/hschneider/neutralino-build-scripts

**Comment by hschneider** [comment]
@shalithasuranga I think you can close this, because the build-scripts solve all macOS App Bundle related issues.

**Comment by shalithasuranga** [comment]
Sure @hschneider, thanks :tada: we can include these tooling in the documentation's [distribution page](https://neutralino.js.org/docs/distribution/overview) I think. Once we get our [community builder CLI plugin](https://github.com/neutralinojs-community/neutralinojs-builder) (which generates MSI, DEB-like installers) ready, we can update the "Creating application installers" section by adding new pages, by keeping this build script related pages. 

Perhaps, we can do like this:

- Create three pages and link them properly replacing dummy links that reside under "Creating a portable application package"
- Each page may explain the manual approach in brief and how to use your tool
   i.e., Outline for "Creating a portable application package for Linux"
   - Overview: Intro to Linux app packages, manual and build-script-based method
   - Manual app bundle creation (no detailed explanation needed -- I think we can add links for external learning resources with brief explanations)
   - Creating app bundles with `neutralino-build-scripts`
   - Automating app bundle creation (i.e., Showing a simple GitHub action workflow that make releases with cross-platform app bundles)

Once we complete these pages in documenation, with your permission, we can add your build scripts repo to https://github.com/neutralinojs-community :tada:

Please let me know your ideas :tada: Thanks :)

**Comment by hschneider** [comment]
Sounds great :-) You got my permission to act like proposed.
