### ISSUE TITLE
Specify CWD for os.execCommand

### ISSUE THREAD

**Issue by phil294** [neutralinojs/neutralinojs#1153]
This seems to be impossible currently? Isn't that crucial to running commands? What am I missing?

**Is your feature request related to a problem? Please describe.**
I can't have a command be executed inside a certain directory.

**Describe the solution you'd like**
Provide an option to set cwd. For example, node's `child_process`'s `exec` offers a `cwd` option too.

**Describe alternatives you've considered**
I could do `execCommand("cd /my/dir; my-command")` but that would obviously limit me to a specific platform.

**Additional context**

**Comment by shalithasuranga** [comment]
Hey @phil294, thanks for posting this feature request. It's added and will be released with the next version. You can try nightly builds tomorrow to test this feature too :tada:
