### ISSUE TITLE
Ability to have a development and production config file

### ISSUE THREAD

**Issue by lumin888** [neutralinojs/neutralinojs#1162]
**Is your feature request related to a problem? Please describe.**
Node has the ability to specify different config files, e.g. a default and development one. Could we have something similar for neutralino.config.json?

**Describe the solution you'd like**
A mechanism to allow a different config file for development and when you build a release. Perhaps some internal CLI command can be used to allow that to happen?

**Comment by shalithasuranga** [comment]
Hello @lumin888, now this feature is implemented. You can use the `--config-file=/neutralino-dev.config.json` option with the framework binary. It's also possible to access config file name from the app via the `NL_CONFIGFILE` global variable. This feature will be released soon with the next release but you can also experiment with next nightly builds. 

Thanks :tada:
