### ISSUE TITLE
Recursive filesystem API

### ISSUE THREAD

**Issue by KTibow** [neutralinojs/neutralinojs#1164]
Requesting
1. Recursively create a directory (eg creating `thing1/thing2` creates all required things)
2. Recursively delete a directory (eg deleting `thing` deletes the whole directory even if it has stuff)

I can already do this with custom implementations but it's slower to do that. This is basic functionality that you can find in utilities like `rm` and `mkdir`.

**Comment by Sadaf-A** [comment]
Greetings @shalithasuranga ! could you assign this to me I would love to work on it

**Comment by shalithasuranga** [comment]
Hello @Sadaf-A, thanks for your interest regarding this issue. Could you please describe how you are planning to implement this before you start working on it. Then we can assign this to you and continue I think :tada:  I think you can briefly describe API changes and implementation approach :)

**Comment by Sadaf-A** [comment]
> Hello @Sadaf-A, thanks for your interest regarding this issue. Could you please describe how you are planning to implement this before you start working on it. Then we can assign this to you and continue I think :tada:  I think you can briefly describe API changes and implementation approach :)

https://github.com/neutralinojs/neutralinojs/blob/main/api%2Ffilesystem%2Ffilesystem.cpp#L132-L138

if this is the current implementation we can iterate through the path and create the directories sequentially

**Comment by KTibow** [comment]
Given that this project uses C++17, this should be as simple as using `std::filesystem::create_directories(path)`

**Comment by Sadaf-A** [comment]
> Given that this project uses C++17, this should be as simple as using `std::filesystem::create_directories(path)` or `std::filesystem::remove_all(path)` (although it seems that `std::filesystem` isn't used elsewhere in the code, not sure what the reasoning is)

yes @shalithasuranga requesting your opinion

**Comment by shalithasuranga** [comment]
Hello @KTibow, please check https://github.com/neutralinojs/neutralinojs/issues/625. I think there was some issues specially on macOS versions. But I think we can use std::filesystem if possible since we can improve the existing Neutralinojs filesystem API a lot. Thanks :tada:

**Comment by Sadaf-A** [comment]
@shalithasuranga so which approach do you think is best

**Comment by shalithasuranga** [comment]
Hi @Sadaf-A, I think first we need to try using std::filesystem, continue using it if there are no build/run-time issues in all platforms. Thanks :tada:  As I mentioned, there were some issues while using it on some platforms. Please check past Github issues for more information (I think you can search for "filesystem")

**Comment by Sadaf-A** [comment]
```cpp
json removeDirectory(const json &input) {
    json output;
    if(!helpers::hasRequiredFields(input, {"path"})) {
        output["error"] = errors::makeMissingArgErrorPayload();
        return output;
    }
    string path = input["path"].get<string>();
    #if defined(__linux__) || defined(__APPLE__) || defined(__FreeBSD__)
    if(rmdir(path.c_str()) == 0) {
    #elif defined(_WIN32)
    if(RemoveDirectory(helpers::str2wstr(path).c_str())) {
    #endif
        output["success"] = true;
        output["message"] = "Directory " + path + " was removed";
    }
    else{
        output["error"] = errors::makeErrorPayload(errors::NE_FS_RMDIRER, path);
    }
    return output;
}
```
Hey @shalithasuranga there seems a curly bracket missing in this function also I will be fixing this in the PR also
