### ISSUE TITLE
Show current port number when running in cloud mode

### ISSUE THREAD

**Issue by hschneider** [neutralinojs/neutralinojs#1169]
When running 

` neu run -- --mode=cloud`

the current port should be printed to the terminal.

Currently this requires to configure a fixed port, because it is required when entering the URL in the browser.

**Comment by shalithasuranga** [comment]
Hello @hschneider thanks for posting this. Please enable logging for the app (already enabled in the sample app) and check. You will see something like: `js.neutralino.sample is available at http://localhost:<random_port>/resources/#cloud ` 

Thanks :tada:
