### ISSUE TITLE
Add global var NL_ARCH to reflect currentCPU architecture

### ISSUE THREAD

**Issue by hschneider** [neutralinojs/neutralinojs#1180]
We can determine the OS by reading NL_OS, but not the CPU architecture like x64 or arm64.
This is important, when writing e.g. a custom installer which needs to download the correct binary.

A global NL_ARCH var would solve this.

**Comment by shalithasuranga** [comment]
Hello @hschneider, thanks for creating this feature request issue. `NL_ARCH` (which returns the same value as `computer.getArch()`) was added and it will be released with the next version. Thanks :tada:

**Comment by hschneider** [comment]
Thannks!
