### ISSUE TITLE
How to use stdout and stdin

### ISSUE THREAD

**Issue by Hill-98** [neutralinojs/neutralinojs#1181]
I want to write a program in Neutralinojs, but I need to use stdin and stdout to communicate with the parent process. I noticed that Neutralinojs doesn't seem to have this capability. Is that correct?

**Comment by shalithasuranga** [comment]
Hello @Hill-98, do you need to communicate with the Neutralinojs framework process? For that, you can use the framework's WebSocket connection. If you need to communicate with a child process, you can use the `os.spawnProcess` function.

**Comment by Hill-98** [comment]
@shalithasuranga Thanks for your reply, but it's neither of those, I need to communicate with the parent process.

like this:
`cat some.txt | neutralinojs-program | grep some`

Can I handle stdin and stdout?

**Comment by KamakshiOjha** [comment]
Neutralinojs allows communication with the parent process using standard input (stdin) and standard output (stdout). This can be useful for exchanging data and commands between Neutralinojs applications and their parent processes.

Receiving Data from Parent Process (stdin):

const { stdin } = require('@neutralinojs/neu');

stdin.on('data', (data) => {
    console.log(`Received data from parent process: ${data}`);
    // Process the received data as needed
});

Sending Data to Parent Process (stdout):

const { stdout } = require('@neutralinojs/neu');

// Send data to the parent process
stdout.write('Data to send to the parent process\n');


 Bidirectional Communication:

const { stdin, stdout } = require('@neutralinojs/neu');

// Listen for data from the parent process
stdin.on('data', (data) => {
    console.log(`Received data from parent process: ${data}`);

    // Process the received data and send a response
    const response = `Processed: ${data}`;
    stdout.write(response);
});

**Comment by LIZA1608** [comment]
good one

**Comment by noob-coder497** [comment]
To send data from Neutralino to the parent process, you can write to the stdout stream. Here's an example in JavaScript:
// Send data to the parent process
function sendDataToParent(data) {
    console.log(JSON.stringify(data));
}
In this example, JSON.stringify(data) converts the data into a JSON string, and console.log writes it to the stdout stream. You can call this function whenever you want to send data to the parent process.

To receive data in Neutralino from the parent process, you can read from the stdin stream. Here's an example:
// Read data from stdin
process.stdin.on('data', (data) => {
    const receivedData = JSON.parse(data);
    handleReceivedData(receivedData);
});

// Handle the received data
function handleReceivedData(data) {
    // Process the received data
    console.log('Received data from parent process:', data);
}
In this example, the process.stdin.on event listener is used to listen for data on the stdin stream. When data is received, it is parsed using JSON.parse to convert it from a JSON string to a JavaScript object. You can then handle the received data in the handleReceivedData function.
Hope this helps.

**Comment by shalithasuranga** [comment]
Hello everyone, now we have added `readProcessInput(readAll=true/false), writeProcessOutput(), and writeProcessError()` functions. We'll release them with the next framework version soon. Thanks for reporting and discussing this :tada:

**Comment by Hill-98** [comment]
Cool! I'll give it a try.

**Comment by Hill-98** [comment]
@shalithasuranga Are these implemented correctly only on Linux?

I found that Windows didn't work. It seems to be because the Windows version works in "Window mode" instead of "Console mode". As far as I understand, one Windows program cannot implement both modes at the same time, so is it possible to provide another binary for Windows separately? (Like: `neutralino-win_x64_console.exe`)

**Comment by shalithasuranga** [comment]
Hey @Hill-98, thanks for posting this info. Mm. yeah, according to internet documentations, I also found the same thing you've mentioned about Windows executables. The issue is that I couldn't test this feature on Windows since our Azure sponsorship was terminated. Looks like we need to get some help from a contributor until I re-apply for the Azure sponsorship. Thanks :tada:
