### ISSUE TITLE
Communication with Parent Process using stdin and stdout

### ISSUE THREAD

**Issue by KamakshiOjha** [neutralinojs/neutralinojs#1183]
Neutralinojs allows communication with the parent process using standard input (stdin) and standard output (stdout). This can be useful for exchanging data and commands between Neutralinojs applications and their parent processes.

Receiving Data from Parent Process (stdin):

const { stdin } = require('@neutralinojs/neu');

stdin.on('data', (data) => {
console.log(Received data from parent process: ${data});
// Process the received data as needed
});

Sending Data to Parent Process (stdout):

const { stdout } = require('@neutralinojs/neu');

// Send data to the parent process
stdout.write('Data to send to the parent process\n');

Bidirectional Communication:

const { stdin, stdout } = require('@neutralinojs/neu');

// Listen for data from the parent process
stdin.on('data', (data) => {
console.log(Received data from parent process: ${data});

// Process the received data and send a response
const response = `Processed: ${data}`;
stdout.write(response);
});

**Comment by shalithasuranga** [comment]
Closing this as a duplicated of #1181, Thanks so much for reporting this issue :tada:
