### ISSUE TITLE
Windows Crash if User Directory has Special Character

### ISSUE THREAD

**Issue by thorin8k** [neutralinojs/neutralinojs#1189]
**Describe the bug**
Application crashes without logging anything if launched as an user with an Special Character (spanish `ñ` in my case) in the username.

I suspect that the problem when accessing to the C:\Users\<username> directory, or writing something there.

**To Reproduce**
1. Create a simple aplication
2. Create an user in windows with an `ñ` in its name
3. Launch the application
4. The aplication crashes without error

**Expected behavior**
Application should not crash

**Screenshots/Screen recordings**
--

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: 4.14.1
 - Neutralinojs client library version: 3.12.0
 - Neutralinojs CLI version: 10.1.0

**Additional context**
I've tried in the same machine with other users and it works nice.

Also, i've tried starting the application in cloud mode and works so the problem may be when storing something from the window.

**Comment by Eliastik** [comment]
I encountered the same issue when using an account with special character "é" on Windows 11

**Comment by dhruvgupta0503** [comment]
Can I work on this issue . I will try my best to solve it

**Comment by shalithasuranga** [comment]
This issue was fixed and the fix will be released with the next version soon. Thanks for reporting and discussing this issue :tada:
