### ISSUE TITLE
Bug in upcoming Extension binding?

### ISSUE THREAD

**Issue by hschneider** [neutralinojs/neutralinojs#1191]
Can you please give some more details about the upcoming changes?

That's what I see so far:

Extensions now get the connect info as JSON via stdin:
```json
{
  "nlConnectToken": "e1GshfpfjAGXKxc1bCMMmaxHEaa5TIDcPt5VuAwmMjO29W2Y",
  "nlExtensionId": "extPython",
  "nlPort": "63765",
  "nlToken": "Gz_fUDzhBN0BEESY1PMjsGgbu0GtHT_ujiLlzbpz4jdmbLjz.e1GshfpfjAGXKxc1bCMMmaxHEaa5TIDcPt5VuAwmMjO29W2Y"
}

```

The websocket URL from the extension's side looks something like that and it seems to connect without error:
```
ws://127.0.0.1:63765?extensionId=extPython&connectToken=7sj7Ap-zLATL113muco_Lr0X_tgU7dvRm_1DNEK_Eu76kNyH
```

However, I get this in the dev-console during further conversation:
```
WebSocket connection to 'ws://localhost:64163/' failed: There was a bad response from the server.
```

What is the new data package struct?
Did I miss something else?

Thank you very much, 
Harald

**Comment by hschneider** [comment]
Before I get the above error in the dev-console, the extension receives these events from the app:
```
IN:  {"data":"extPython","event":"extClientConnect"}
IN:  {"data":1,"event":"clientConnect"}
IN:  {"data":null,"event":"windowBlur"}
IN:  {"data":null,"event":"windowFocus"}
```
So the websocket seems to be intact and authenticated before it breaks.

**Comment by hschneider** [comment]
I see the websocket connection working stable into one direction, from the app to the exstension.
The other direction seems to be broken.

With other words: The extension receives e.g. all window events from the app, but it cannot send data to the app.

**Comment by hschneider** [comment]
Solved it:
`neu update` did not update `neutralino.js`.
So replacing it manually from the nightly build did the trick.

**Comment by shalithasuranga** [comment]
Hello @hschneider thanks for working on this issue. Please check more details about all upcoming v5 changes from [CHANGELOG.md](https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#unreleased). We'll update docs with the new release most probably by end of this month :tada:
