### ISSUE TITLE
Implement `window.transparent` configuration option for Windows

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#1201]
Currently, the `window.transparent` config prop is only implemented in GNU/Linux and macOS as follows:

- GNU/Linux: Window transparency is set in the [`webview.h`](https://github.com/neutralinojs/neutralinojs/blob/d8cf72c737d0ad3b598904661a63ba18c15654c2/lib/webview/webview.h#L473) file and the webview transparency is set in the [same file](https://github.com/neutralinojs/neutralinojs/blob/d8cf72c737d0ad3b598904661a63ba18c15654c2/lib/webview/webview.h#L579).
- macOS: Window transparency is set in the [`macwindow.mm`](https://github.com/neutralinojs/neutralinojs/blob/d8cf72c737d0ad3b598904661a63ba18c15654c2/lib/webview/macwindow.mm#L19) file and the webview transparency is set in the [`webview.h`](https://github.com/neutralinojs/neutralinojs/blob/d8cf72c737d0ad3b598904661a63ba18c15654c2/lib/webview/webview.h#L839) file

Similarly, we need to implement this conditional transparency feature in Windows too. 
- Window transparency: https://stackoverflow.com/questions/3970066/creating-a-transparent-window-in-c-win32
- Webview2 transparency: https://stackoverflow.com/questions/67838739/how-to-use-transparency-in-webview2

**Comment by FireNdIce3** [comment]
Hi I would like to work on this issue, Can you please explain this issue a bit ?
Thanks

**Comment by shalithasuranga** [comment]
Thanks so much for your interest @FireNdIce3. I've update the issue description. Please check and let us know if you have more questions :tada:

**Comment by FireNdIce3** [comment]
Sure!
Thanks

**Comment by officeneerajsaini** [comment]
Hi @shalithasuranga ,
I want to work on this issue. Could you please provide more details about the problem? Additionally, I am a Linux user; am I able to contribute to the resolution of this issue?

**Comment by shalithasuranga** [comment]
Hi @officeneerajsaini, thanks so much for your interest. Please check the updated issue description. This issue requires writing some Windows-specific code, so it needs to be compiled on Windows. Maybe you can use a Windows VM on Linux?

**Comment by officeneerajsaini** [comment]
So, do we fix this issue now, or wait for the GSoC proposal? I found just one problem in this GSoC-related repository; are there any more things we need to look into

**Comment by shalithasuranga** [comment]
@officeneerajsaini This task is not a GSoC 2024 task, so contributors can work on this issue and send pull requests, so you also can send a pull request for this one even before sending a proposal (We've mentioned about this on Discrod). 

Note: Btw, this issue requires some experience in Neutralinojs internals, so if you are getting started with the codebase, you can find other issue that has the `gsoc` label on it in other repos as well.

**Comment by officeneerajsaini** [comment]
> @officeneerajsaini This task is not a GSoC 2024 task, so contributors can work on this issue and send pull requests -- you also can send a pull request for this one even before sending a proposal (We've mentioned about this on Discrod).
> 
> Note: Btw, this issue requires some experience in Neutralinojs internals, so if you are getting started with the codebase, you can find other issue that has the `gsoc` label on it in other repos as well.

Very well then, I am so excited to work on this issue. I have some experience in open source; just a few days ago, I merged my pull request on Node.js documentation issues. For this contribution, I need your help to resolve this issue. Could you please explain the details of this issue?

**Comment by shalithasuranga** [comment]
Great @officeneerajsaini, I recently updated this issue's description with the goal of this task. We basically need to implement the missing Window/webview transparency feature for the Windows platform. It's already done for other two platforms. Please let me know if you have questions regarding task details :tada: Thanks

**Comment by FireNdIce3** [comment]
Hi @shalithasuranga 
I'd be also working on this issue as I'd like to contribute in GSoC as well but I think understanding the codebase first will be better and solving this issue would be a great opportunity to start
Thanks

**Comment by Basti-def** [comment]
Hi,
I am looking forward to get this fixed because I really want to use this feature. 
If I understood right: you will fix this while gsoc (1. may) ?
Thanks

**Comment by Basti-def** [comment]
> I am so excited to work on this issue

Hi,
do you still planing to work on that issue? 
Seems like it can't be done for gsoc.
What is the current state of this Issue?

I'm curious to see how the issue develops. 
Thanks

**Comment by officeneerajsaini** [comment]
is this issue still open ?

**Comment by Basti-def** [comment]
@officeneerajsaini yes but it can be closed. The feature was added in a Pullrequest already.

**Comment by officeneerajsaini** [comment]
> > I am so excited to work on this issue
> 
> Hi @officeneerajsaini , do you still planing to work on that issue? Seems like it can't be done for gsoc. What is the current state of this Issue?
> 
> I'm curious to see how the issue develops. Thanks

sorry for delay reply
