### ISSUE TITLE
Neutralino.storage don't work when the app is launched in a directory path with special characters on Windows

### ISSUE THREAD

**Issue by Eliastik** [neutralinojs/neutralinojs#1207]
**Describe the bug**
When using Neutralino.storage API on Windows and launching the app in a directory path with special characters, an exception is thrown when reading data.

**To Reproduce**
1. Create an app writing then reading storage data using the Neutralino API. For example:
```
await Neutralino.storage.setData("test", "test");
await Neutralino.storage.getData("test");
```
3. Compile the app with `neu build`
4. Create a directory with a special character (for example: "Téléchargements")
5. Move the app exe file and resource.neu file into this directory
6. Run the app

**Expected behavior**
The API is working as expected, not throwing an exception.

**Actual behavior**
Got an exception with code "NE_ST_NOSTKEX" and "Unable to find storage key" when reading the data.
Also a directory with wrong name is created ("TÃ©lÃ©chargement").

**Specifications**  
 - OS: Windows 10/11 x64
 - Neutralinojs version: v5.0.0
 - Neutralinojs client library version: v5.0.0
 - Neutralinojs CLI version: v2.1.0

**Comment by shalithasuranga** [comment]
This issue was fixed and the fix will be released soon with the next framework release. Thanks for reporting this issue :tada:
