### ISSUE TITLE
Execute a shell command and emit events triggered by stdOut

### ISSUE THREAD

**Issue by hschneider** [neutralinojs/neutralinojs#1208]
**Is your feature request related to a problem? Please describe.**
When executing long-running shell commands, it is not possible to track progress. even if the command sends progress info via stdOut. We can display an infinite progress bar or another indicator to the user, but there is no real live-info.

**Describe the solution you'd like**
- Each data sequence terminated with a linefeed, coming from stdOut is read into a buffer.
- Next a JS event is triggered in the frontend, called e.g. **progress**.
- This event receives the buffered, raw data  as a string for further processing.
- The buffer is cleared and the next line is read from stdOut.
- Loop until command terminates.
- When the command has been terminated an additional event called **progress_end** could be triggered.

**Describe alternatives you've considered**
No alternatives, as far as I can see ....

**Comment by JustPilz** [comment]
https://neutralino.js.org/docs/api/os/#osspawnprocesscommand-cwd

But `curl` push progress data in stdErr

**Comment by hschneider** [comment]
Right, so the same for stdErr would be useful, maybe the events should be better named **cmd_stdout** and **cmd_stderr** triggered line by line and **cmd_start** and **cmd_end** triggered before start and after end of the external process.

**Comment by hschneider** [comment]
Ooops - missed this one: **os.spawnProcess(command, cwd)**
@JustPilz Thanks for the hint. 
Think we can close this :-)
