### ISSUE TITLE
`Open with → Choose another app` function not working

### ISSUE THREAD

**Issue by jerrygreen** [neutralinojs/neutralinojs#1212]
In windows, there's an ability to choose an app as default for opening files:

![image](https://github.com/neutralinojs/neutralinojs/assets/13215662/b80e54cc-482f-4b51-84df-ecc15f9e2ba8)

Currently if you try to do this, what you get is this error:

![image](https://github.com/neutralinojs/neutralinojs/assets/13215662/03f2ff23-ad68-40bd-8f6f-f4de786474f4)

```
/neutralino.config.json file is missing or corrupted.
```

**Describe the solution you'd like**
To have some ability to open files using «Open with», with Neutralino apps.

**Describe alternatives you've considered**
Electron :\

**Comment by Sadaf-A** [comment]
@jerrygreen Hey, I just tested this on `windows 11` and it is working as expected I hope you are talking about the `os.showOpenDialog` method. Which windows version are you using?

**Comment by jerrygreen** [comment]
Urgh, it’s not _exactly_ my use-case you’re describing. Here, I’m not using `os.showOpenDialog()`

If I understand correctly from what I read from the docs, `os.showOpenDialog()` is meant to use to open files for, _internally_ – from within the app.

What I describing here, is when user opens the file from the system, then the system calls the program, i.e. program initiated _externally_.

Say, I have `.md` files, and I want assign this extension to my little program, which is markdown viewer. So when I double-click a markdown file from finder/nautilus/explorer – my program is automatically started by system, and the program opens corresponding file immediately. That’s just an example. That’s just an example. Like, a markdown viewer.

In my use-case, I wanted to make a program to preview 3D model, which I did and it’s working, but I don’t know how to assign `.gltf` extension to my program as a default program opening this kind of files. It’s a bit different use-case than `os.showOpenDialog()`

It seems it’s not possible to do with Neutralino currently, but I might be mistaken. Docs don’t say about this much.

My specs:

```
OS: Windows 10 x64 (22H2)
Neutralinojs version: v5.0.0
Neutralinojs client library version: v5.0.0
Neutralinojs CLI version: v11.0.0
```

**Comment by jerrygreen** [comment]
On another glance into the docs, I think I might have found the thing, actually. It might be this:

- [`openedFile (event)`](https://neutralino.js.org/docs/api/events/#event-types:~:text=openedFile,-Occurs%20for%20each)
  Occurs for each read action and whenever stream cursor reaches EOF.

Not gonna check it for the time rn, to know whether it works from external call or not, since I'm onto other projects already.

Might be useful for others if they come by from google, though. Seems like it's exactly the thing I needed.

**Comment by Ayush-sss** [comment]
I want to work on this issue. @jerrygreen  Please assign me this issue. I will try my best to fix this bug.

**Comment by OrigamingWasTaken** [comment]
> Urgh, it’s not _exactly_ my use-case you’re describing. Here, I’m not using `os.showOpenDialog()`
> 
> If I understand correctly from what I read from the docs, `os.showOpenDialog()` is meant to use to open files _internally_ – from within the app.
> 
> What I describing here, is when user opens the file from the system, then the system calls the program, i.e. program initiated _externally_.
> 
> Say, I have `.md` files, and I want assign this extension to my little program, which is markdown viewer. So when I double-click a markdown file from finder/nautilus/explorer – my program is automatically started by system, and the program opens corresponding file immediately. That’s just an example.
> 
> In my use-case, I wanted to make a program to preview 3D model, which I did and it’s working, but I don’t know how to assign `.gltf` extension to my program as a default program opening this kind of files – when I do assign the extension to my program, this error occurs while opening the file.
> 
> Basically, it’s a bit different use-case than `os.showOpenDialog()`
> 
> It seems it’s not possible to do with Neutralino currently, but I might be mistaken. I haven't found an example in docs. It seems like I need some kind of event listener for this.
> 
> My specs:
> 
> ```
> OS: Windows 10 x64 (22H2)
> Neutralinojs version: v5.0.0
> Neutralinojs client library version: v5.0.0
> Neutralinojs CLI version: v11.0.0
> ```

I had actually the same problem (on macos) and my temporary fix was to create within the app, some sort of URL-Scheme handler that would get launched and receive the file, then forward them to the main neutralino app. This handler can be made in powershell, etc...

**Comment by shalithasuranga** [comment]
I just tested this on Windows. It works as expected and the second element of the `NL_ARGS` contains the selected file.

**Comment by OrigamingWasTaken** [comment]
> I just tested this on Windows. It works as expected and the second element of the `NL_ARGS` array contains the selected file. Thanks for reporting and starting a discussion 🎉

Sorry to talk in a closed issue, but is this behavior the same on Mac?
