### ISSUE TITLE
Deprecated Warning 

### ISSUE THREAD

**Issue by dhruvgupta0503** [neutralinojs/neutralinojs#1220]
**Describe the bug**
When the command npm i -g @neutralinojs/neu is executed to run the dev server deprecation warning is shown

**To Reproduce**
1. Install the package 
2. Run the command

**Expected behavior**
There should be no warning.

**Screenshots/Screen recordings**
![image](https://github.com/neutralinojs/neutralinojs/assets/108184993/550d654d-aba9-48c4-8ea8-2621337fb754)

 

**Additional context**

**Comment by Sadaf-A** [comment]
@shalithasuranga I believe this belongs to `neutralinojs-cli` repo 
I have opened PR there!

**Comment by dhruvgupta0503** [comment]
So is this issue resolved or not?

**Comment by Sadaf-A** [comment]
> So is this issue resolved or not?
> 

I have opened a PR for it which hasn't been reviewed yet
You can also give it a shot and open a PR yourself!
