### ISSUE TITLE
filesystem.copy 

### ISSUE THREAD

**Issue by w-mcilhagga** [neutralinojs/neutralinojs#1227]
`Neutralino.filesystem.copy` fails when destination file already exists, because the only copy option in `fs.cpp` is `filesystem::copy_options::recursive`.

### Possible solutions:
It's not a huge problem, but could you either 

* allow the copy to succeed when the file exists (e.g. because you're overwriting an old file with a new one) by adding
  `filesystem::copy_options::overwrite_existing` to the fs.cpp code on line 627, or
* change the js api to allow copy options to be passed, or
* say in the docs that filesystem.copy will fail if the file already exists

**Comment by Sadaf-A** [comment]
> `Neutralino.filesystem.copy` fails when destination file already exists, because the only copy option in `fs.cpp` is `filesystem::copy_options::recursive`.
> ### Possible solutions:
> 
> It's not a huge problem, but could you either
> 
>     * allow the copy to succeed when the file exists (e.g. because you're overwriting an old file with a new one) by adding
>       `filesystem::copy_options::overwrite_existing` to the fs.cpp code on line 627, or
> 
>     * change the js api to allow copy options to be passed, or
> 
>     * say in the docs that filesystem.copy will fail if the file already exists

Hey, I have opened a PR which resolves this issue thank you for reporting this issue.

**Comment by Sadaf-A** [comment]
@w-mcilhagga you can also try the `writeFile()` method it will over write existing files

**Comment by w-mcilhagga** [comment]
I'm currently deleting the file before copying, if it already exists.
