### ISSUE TITLE
Feature Request: bind to random port

### ISSUE THREAD

**Issue by buckle2000** [neutralinojs/neutralinojs#123]
Can neutralinojs allow the app the bind to a random port every time? This can prevent port collision for small apps. Personally, I use port 8080 for web proxy.

Suggestion: when appport = 0, use random port.

```json
{
    "appname" : "app",
    "appport" : "0",
    "mode" : "desktop"
}
```

**Comment by shalithasuranga** [comment]
@buckle2000  Nice idea thanks..`0` or `random` for `appport` would be cool. We will be adding soon

**Comment by shalithasuranga** [comment]
Note: This will be added with the new version
