### ISSUE TITLE
Single page rewrite (for SPA)

### ISSUE THREAD

**Issue by JustPilz** [neutralinojs/neutralinojs#1230]
How to enable single page rewrite (for SPA) for the local server when the app is running?

I am using React with React-Router (BrowserRouter). 
If the app is launched from the base path ('/') it's fine, but if redirected to sub-route, for example from oauth callback_url to '/any-subroute' - 404 Not found. 

[One solution I have found](https://coderomayer.medium.com/solving-404-errors-on-sub-routes-in-react-vite-with-react-router-v6-d6a287b66178) is to switch from BrowserRouter to HashRouter but I don't want to use HashRouter cause there are other problems.

[Simple Web Server](https://simplewebserver.org/) has special option like `Single page rewrite (for SPAs): Automatically rewrite all paths that don't exist to a single page`. Is there something similar in Neutralino?

**Comment by shalithasuranga** [comment]
Hello @JustPilz, thanks for posting this feature request. Now, we can use the following configuration to activate SPA serving:
```json
"singlePageServe": true,
```
This feature will be released with the next version soon! :tada:
