### ISSUE TITLE
Extensions don't seem to work on Windows 11, maybe other?

### ISSUE THREAD

**Issue by AddictArts** [neutralinojs/neutralinojs#1234]
**Describe the bug**
I am trying to use extensions and have

`"commandWindows": "\"${NL_PATH}/extensions/rust/target/release/ext-rust.exe ${NL_PATH}\""`

With or without the additional quotes it never tries to launch the `ext-rust.exe`.

**To Reproduce**
1. Use Windows 11 and PowerShell 7
2. Create an extension in extensions/rust for example
3. Compile the release
4. Add the extensions stanza to the neutralino.config.js
5. `neu run`

**Expected behavior**
To see the process spawned

**Specifications**  
 - OS: Windows 11
 - Neutralinojs version: 5.1.0
 - Neutralinojs client library version:  5.1.0
 - Neutralinojs CLI version: 11.0.1

*Note: you can enter the `neu version` command to find these details*

**Additional context**

An example say in examples would be great to have if it doesn't alrady exist. Thanks

**Comment by hschneider** [comment]
Replace this in the `neutralino.config.json`:
```json
      "commandWindows": "${NL_PATH}\\extensions\\rust\\target\\release\\ext-rust.exe ${NL_PATH}"
  ```

**Comment by AddictArts** [comment]
Thanks @hschneider . That resolved the rust example. However, the node examples do not work. The one in this repo called sampleextension does not work and the log has no explanation. I can launch the sample from a powershell prompt like so:

````
C:\box\neu\neutralinojs\bin
❯ node .\extensions\sampleextension\main.js --windows
```

And it does not exit immediately, just waits.

**Comment by AddictArts** [comment]
Ok, I figured out the second issue or bug with the current sampleextension

neutralino.config.json

```
    "enableExtensions": true,

and this worked aften an npm install in sampleextensions

            "commandWindows": "node ${NL_PATH}\\extensions\\sampleextension\\main.js --windows"

```

**Comment by AddictArts** [comment]
While now working, the node process spun up becomes a zombie process. Maybe this is only dev mode and not a build. Thanks again for the help.

**Comment by hschneider** [comment]
Maybe this sample extension is outdated. The way extensions are initialized changed with Neutralino 5.

**Comment by AddictArts** [comment]
Yes, it is good to have it and would be great to have more. Maybe get the ones done called neutralino-ext-rust, neutralino-curl, neutralino-ext-bun and such in that github repo officially as examples. I can put links here, don't have it handy.

https://github.com/hschneider/neutralino-ext-rust  ....

Maybe they would be willing? are you willing to have more examples? Thanks again. Thiis can be closed.

**Comment by AddictArts** [comment]
This can be closed.
