### ISSUE TITLE
Timeout exceeded when launching neutralino react template

### ISSUE THREAD

**Issue by ChevalMonsieur** [neutralinojs/neutralinojs#1244]
**Describe the bug**

base port (3000) never sets up while running the neutralino react template for the first time so neutralino react app can't launch itself

**To Reproduce**

create a new neutralino app : ```neu create myappreact --template codezri/neutralinojs-react```
move to app folder : ```cd myappreact```
run application ```neu run```

**Expected behavior**

The application should launch normally

**Screenshots/Screen recordings**

![image](https://github.com/neutralinojs/neutralinojs/assets/126174925/380b7e02-b909-4e47-b648-b4fe99c0ab32)

**Specifications**  
 - OS: Windows 11
 - Neutralinojs version: v5.1.0
 - Neutralinojs client library version: i don't know
 - Neutralinojs CLI version: v11.0.1

**Additional context**

when changing the base port on the config file, it does change the name of the port on terminal but the error is the same

**Comment by hschneider** [comment]
I can confirm this bug on my system, too (macOS).

This one works out of the box:
https://github.com/JustPilz/neu-react-ts-vite-template

**Comment by ChevalMonsieur** [comment]
I tried it on a different OS (ubuntu) but it didn't work either

![image](https://github.com/neutralinojs/neutralinojs/assets/126174925/bdd26476-26d7-4d56-b26f-e98405d4caf8)

**Comment by ChevalMonsieur** [comment]
well now that I'm on ubuntu, the base react neutralino template end up working

**Comment by Sadaf-A** [comment]
> well now that I'm on ubuntu, the base react neutralino template end up working

It's working in linux mint also could it be possible that your port 3000 is already busy in that machine?

**Comment by ChevalMonsieur** [comment]
> > well now that I'm on ubuntu, the base react neutralino template end up working
> 
> 
> 
> It's working in linux mint also could it be possible that your port 3000 is already busy in that machine?
> 
> 

No, I've tried with multiple ports (including random numbers) so it can't be this

**Comment by ProbablyRaging** [comment]
To solve this issue, in `neutralino.config.json` change the following
```
- 32            "devCommand": "BROWSER=none npm start",
+ 32            "devCommand": "npm start",
```

**Comment by shalithasuranga** [comment]
Hello. thanks for discussing this issue. This issue won't appear in the latest React template (https://github.com/codezri/neutralinojs-react) and the neu CLI version :tada:
