### ISSUE TITLE
Configless usage

### ISSUE THREAD

**Issue by Aworldc** [neutralinojs/neutralinojs#1249]
**Is your feature request related to a problem? Please describe.**
For some scenarios involving webviews being opened as as child processes, it would be convenient if you didn't need a config file when you are using [internal cli arguments](https://neutralino.js.org/docs/cli/internal-cli-arguments/) to tell it what to load.

**Describe the solution you'd like**
The ability to just run `neutralino --url https://google.com/` for example, and have it load google.

**Describe alternatives you've considered**
electron can already do this. i can just run `electron https://google.com/` and it works.

**Additional context**
kinda inspired by #771, but still a bit different.

**Comment by shalithasuranga** [comment]
Hello @Aworldc, thanks for posting this feature request. This is now implemented and will be released with the next version :tada:

**Comment by Aworldc** [comment]
woo
