### ISSUE TITLE
Error when using build.sh

### ISSUE THREAD

**Issue by limenleap** [neutralinojs/neutralinojs#125]
**Expected Behavior**  
Was hoping to execute build.sh on Linux and get a fresh build of Neutralino
  
**Actual Behavior**  
Figured out that I needed Nodejs, npm and webpack. Installed all of these on a fresh Ubuntu 18x

**Steps to Reproduce the Problem**  
Start with a fresh install of Ubuntu 18x (Desktop) Install Node, webpack, npm

Run sudo sh build.sh

Here is the error

```
ERROR in neutralino.js from UglifyJs
Unexpected token: name (authbasic) [neutralino.js:93,5]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! neutralino-client-library@1.0.0 build: `webpack -p`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the neutralino-client-library@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sabufrancis/.npm/_logs/2018-12-01T08_36_07_796Z-debug.log

```

**Specifications**  
* NeutralinoJs Version: 1.0.7 Alpha
* Platform:  Ubuntu 18.x Desktop

**Comment by shalithasuranga** [comment]
What is your webpack version? Can you try removing `node_modules` and running `npm i`

**Comment by limenleap** [comment]
Webpack version is 3.5.6
How do I remove node_modules? Sorry I am new to Node so I dont know

**Comment by shalithasuranga** [comment]
You can do like following
```bash
cd neutralino.js
rm -rf node_modules
npm i
```

But before all get changes if there are, from remote repository
```
git pull origin master
```

**Comment by limenleap** [comment]
Got it to work. Thanks
