### ISSUE TITLE
Neutrolino.storage functions break macOS bundles

### ISSUE THREAD

**Issue by jeffwtm** [neutralinojs/neutralinojs#1252]
**Describe the bug**
Because the `Neutralino.storage` functions write to the application directory, using them in a macOS app bundle causes the bundle contents to be modified. This breaks code signing and notarization, preventing the app from running.

A previous workaround referenced in this issue no longer works: https://github.com/neutralinojs/neutralinojs/issues/1131

It seems that the `Resources` folder inside a bundle used to be considered writable, but current code-signing requires the entire bundle to be read-only: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html
> Making changes after you sign invalidates the signature. Consider a signed application bundle as a read-only entity.

The recommended way to handle this is to use `~/Library/Application Support/<bundle id>` as described here: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html#//apple_ref/doc/uid/TP40010672-CH10-SW1

**To Reproduce**
1. Create a Neutralino project and use the `storage` apis to store some data.
2. Build and bundle the project for macOS (using these build scripts simplifies this: https://github.com/hschneider/neutralino-build-scripts)
3. Sign and notarize the bundle (these scripts help: https://github.com/hschneider/macos-sign-notarize)
4. Run the app so that the `storage` functions are executed.
5. Close the app and attempt to run it a second time.
6. The app fails to run with a "app is damaged and cannot be opened" error because the bundle has been modified.

**Expected behavior**
The app bundle should not be modified. Either the `storage` functions could internally use the appropriate `~/Library/Application Support/<bundle id>` path on macOS, or they could provide a way to configure the directory they write to and leave it to the app developer to correctly set the folder.

**Specifications**  
 - OS: macOS
 - Neutralinojs version: 5.1.0
 - Neutralinojs client library version: 5.1.0
 - Neutralinojs CLI version: 11.0.1

**Comment by shalithasuranga** [comment]
Hello @jeffwtm, thanks so much for reporting this bug. The next version will use the `storageLocation` config option to use the system data dir for Neutralinojs app storage:

```json
"storageLocation": "system"
```

`"storageLocation": "app"` (default) will store storage files within the app bundle as usual. Thanks :tada:
