### ISSUE TITLE
"readDirectory" returned NE_RT_NATRTER error when reading directory with file with Unicode character

### ISSUE THREAD

**Issue by shan-developer** [neutralinojs/neutralinojs#1260]
**Describe the bug**
The "filesystem.readDirectory" function will return the following error:

_**code: 
"NE_RT_NATRTER"
message: 
"Native method execution error occurred. Make sure that you've provided required parameters properly."**_

when there is one or more files having unicode character in the file name.

**To Reproduce**
1. Create a folder with two files with the name as "abc.txt" and "实验.txt"
2. Use the function - "filesystem.readDirectory"  to read the above folder
3. The "NE_RT_NATRTER" error will appear

**Expected behavior**
The function should read the content of the folder with unicode encoding correctly.

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: v5.2.0
 - Neutralinojs client library version: v5.2.0
 - Neutralinojs CLI version: v11.2.0

**Additional context**
This seems to be a regression bug as there is no problem with v4.10 version of the library.
It may also be related to the bug - https://github.com/neutralinojs/neutralinojs/issues/1225

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue. Attaching a test case created by @Sadaf-A:

```js
// Failing on Windows, TODO: Add to the spec after fixing this issue on Windows
it('works with special characters', async () => {
     runner.run(`
         await Neutralino.filesystem.createDirectory(NL_PATH + '/.tmp/@#$%^&*☁☀☊☄');
         let entries = await Neutralino.filesystem.readDirectory(NL_PATH + '/.tmp');
         await __close(JSON.stringify(entries));
     `);
     console.log(runner.getOutput())
     const entries = JSON.parse(runner.getOutput());
     assert.ok(entries.find((entry) => entry.type == 'DIRECTORY' && entry.entry == '@#$%^&*☁☀☊☄'));
});
```

**Comment by shalithasuranga** [comment]
This issue was fixed and the above test case was re-added. Changes will be released with the next version. Thanks @shan-developer for reporting this bug :tada:
