### ISSUE TITLE
neutralino.config.schema.json is outdated or invalid

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [neutralinojs/neutralinojs#1264]
**Describe the bug**
Using `neutralino.config.schema.json` in `neutralino.config.json` results in warnings for every field:

![изображение](https://github.com/neutralinojs/neutralinojs/assets/3174357/7cc58e44-1aa2-460e-978e-0d33d6fa0fdf)

**To Reproduce**
1. `neu create myapp`
2. open `neutralino.config.json`
4. See errors

**Expected behavior**
The schema must provide correct type checks onto the file.

**Specifications**  
 - OS: Windows 11, irrelevant
 - Neutralinojs CLI version: v11.2.0 (latest)

**Comment by JamzOJamz** [comment]
@CosmoMyzrailGorynych, I was able to find a workaround for this by changing every occurrence of `additionalProperties` to `true` in the `neutralino.config.schema.json` file. You can replace the `$schema` property at the beginning of the file to instead point to `https://hst.sh/raw/hapovibiwu` if you want to give the modified file a try. Feel free to copy and host it anywhere you'd like. Again, this is only a temporary fix until the Neutralinojs developers finally decide to locate and address the underlying issue that is causing this problem. Best of luck.

![image](https://github.com/user-attachments/assets/1570e75b-ce0b-4548-bebd-c44413545bc4)

**Comment by thisjt** [comment]
Pushed a PR to fix this issue. In the meantime, if you need it fixed asap, you can also use the modified schema in my contribution repo.

```json
{
  "$schema": "https://raw.githubusercontent.com/thisjt/neutralinojs/refs/heads/update-schema/schemas/neutralino.config.schema.json"
}
```
