### ISSUE TITLE
`writeImage()` of the clipboard API does not work for windows

### ISSUE THREAD

**Issue by Sadaf-A** [neutralinojs/neutralinojs#1269]
**Describe the bug**
the testcase for `writeImage()` of the clipboard API is failing for windows

**Expected behavior**
`writeImage()` should write an image to the clipboard for windows just how it does for other platforms

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.

**Specifications**  
 - OS: Windows
 - Neutralinojs version: v5.2.0
 - Neutralinojs client library version: v5.2.0
 - Neutralinojs CLI version: v11.2.0

*Note: you can enter the `neu version` command to find these details*

**Additional context**

**Comment by CosmoMyzrailGorynych** [comment]
I assume the fix is in this PR: https://github.com/neutralinojs/neutralinojs/pull/1288

**Comment by shalithasuranga** [comment]
Closing the issue since #1288 is merged. Thanks so much for reporting this issue :tada:
