### ISSUE TITLE
Introduce build tool like electron-packager and nodebob

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#127]
There are packagers for electronjs(eg node-packager) and nwjs(eg nodebob). 
we need to build a cli tool or automated build script for making customized binary with icon (in windows)
and for linux we may introduce an option which will add entry to launcher.

This will make neutralino better

**Comment by masterjg** [comment]
I have created bootstrap which has sort of build step (window only though)
https://bitbucket.org/masterjguscius/neutralinojs-bootstrap

I'm using rcedit to set icon + some basic file info like copyright etc. But If anyone comes up with builder that packages everything into single binary (and hide sources) that would help out a lot.

**Comment by shalithasuranga** [comment]
Hello @masterjg Thanks. I checked your repo and it's really nice

Our idea is to embed this build plugin to existing neutralino binary so developers may enter 
`neutralino build` etc. Then app bundle makes everything in to `build` directory

Tools like https://github.com/electron/rcedit can be used. But still thinking how final application structure would be :)

**Comment by kasvith** [comment]
neutralino is too long for a command, i would go with something like `njs`

Basically we need a seperate repo for binary core and another one for JS Wrapper 

Since most developers are familiar with nodejs we can ship cli as a node package, and also the js wrapper.

**Comment by jetibest** [comment]
@kasvith "neutralino is too log for a command, i would go with something like `njs`": Please, don't kill readability. `njs` is way too generic, what would it mean, NodeJS? NeutralinoJS?

But I understand some may not be so lucky, perhaps you cannot type fast, suffer from dyslexia, or just don't have enough screen-space. Don't worry, because you could always:
 - Use auto-complete (e.g. type neu, and press TAB).
 - Use an alias (e.g. in Bash: `alias njs='neutralino'`, and put it in your profile).
 - Write a shell-function (e.g. in Bash: `njs() { neutralino "$@"; }`, and put it in your profile).

**Comment by kasvith** [comment]
@jetibest I was talking about the name, it's very easy to remember a shorter name. It's all about marketing. `njs` was a suggestion only at the end.

I don't need your guidance on writing a small shell command or auto-completion. Also, it seems you don't even get the point.

**Comment by kasvith** [comment]
@jetibest this was an open suggestion to use a simple name for the system, for marketing purposes. 

Thanks, I already know how to use TAB completions, Bash Aliases and Shell Functions.
But I appreciate your effort in writing those examples.

**Comment by lacymorrow** [comment]
It may be worth looking at how other alpha packages are able to compile for multiple platforms.

https://github.com/nodegui/packer works well and is relatively simple.

**Comment by kasvith** [comment]
@lacymorrow thanks, it seems useful, the implementation should be similar in our case also.
Thanks for the info

Once we merged all 3 codebases into a manageable single one, we should immediately solve this issue

**Comment by apollolux** [comment]
Hello! If a shorter name is really recommended, how about 'neu' ?

**Comment by shalithasuranga** [comment]
Hey. agree neu looks cool. @apollolux

**Comment by shalithasuranga** [comment]
Some initial drafts for the cli is here https://github.com/neutralinojs/neutralinojs-cli

**Comment by shalithasuranga** [comment]
Closed since the initial implementation done for neu cli. and feature requests and bug reports will be added there
