### ISSUE TITLE
`getEnv()` fails for unicode characters on Windows Platform

### ISSUE THREAD

**Issue by Sadaf-A** [neutralinojs/neutralinojs#1272]
**Describe the bug**
`getEnv()` is failing for unicode characters on Windows Platform

**To Reproduce**
1. try to retrieve unicode characters with `getEnv()`

**Expected behavior**
It should work fine with unicode characters

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.

**Specifications**  
 - OS: Windows
 - Neutralinojs version: [e.g. v4.3.0]
 - Neutralinojs client library version: [e.g. v3.3.0]
 - Neutralinojs CLI version: [e.g. v9.1.2]

*Note: you can enter the `neu version` command to find these details*

**Additional context**

**Comment by shalithasuranga** [comment]
This issue was fixed. Changes will be released with the next version. Thanks @Sadaf-A  for reporting this issue :tada:
