### ISSUE TITLE
Windows extensions do not start and give no errors.

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [neutralinojs/neutralinojs#1282]
**Describe the bug**
Extensions on windows do not start. This affects both dev and build config. This issue was also confirmed on the discord server by hschneider.

I have an extension that works on linux, and also works on windows when started manually with the command in neutralino config. 
When started the application gives no stdout output from the extension and no error messages.  The extension does not respond to events. 

The extension shows as loaded but not connected with extensions.getStats()

**To Reproduce**
1. clone https://github.com/hschneider/neutralino-ext-python or another extension and neu update
2. edit the commandWindows (or change it to just "echo HELLOWORLD")
3. neu run
4. The application should start but the extension will not respond and there will be no errors in the stdout

**Expected behavior**
The extension should start and behave a normally

**Specifications**  
 - OS: Windows 11
--- Global ---
neu CLI: v11.2.0 (latest)

--- Project: ext-python (com.marketmix.extPython) ---
Neutralinojs binaries: v5.2.0 (latest)
Neutralinojs client: v5.2.0 (latest)
Project version: v1.0.0

*Note: you can enter the `neu version` command to find these details*

**Additional context**

**Comment by hschneider** [comment]
@shalithasuranga How can I revert back to an older version of NeutralinoJS, to find out when this issue came up?

**Comment by Avaray** [comment]
> @shalithasuranga How can I revert back to an older version of NeutralinoJS, to find out when this issue came up?

In `neutralino.config.json` file set versions
```
cli.binaryVersion: X.X.X
cli.clientVersion: X.X.X
```
Then run `neu update`
I think in this way specific binaries will be downloaded.

**Comment by hschneider** [comment]
Thanks! 
This downloads the binaries, but the CLI needs to be downgraded too. 
Any hints?

**Comment by Avaray** [comment]
> Thanks! This downloads the binaries, but the CLI needs to be downgraded too. Any hints?

It depends on what you use. With [Bun.sh](https://bun.sh/) you can do something like:
`bunx @neutralinojs/neu@10.0.0 run`
With NPM
`npx @neutralinojs/neu@10.0.0 run`

You can specify versions like in example. But from what I just checked there are issues below version 10.
You can use other CLI commands than `run`, ofc.

**Comment by hschneider** [comment]
Thanks. I see this broken in version 4.15.0. 
I can swear it ran in the past with this version.
Either I mixed something up or something changed in Windows 11, which caused it to break.

@shalithasuranga : I can provide you access to a Win 11 VM, if you need a development environment. Just drop me a PM on discord.

**Comment by CosmoMyzrailGorynych** [comment]
This https://github.com/neutralinojs/neutralinojs/issues/1242 signifies that extensions were runnable in v5.1.0
But it doesn't now if I set CLI and client versions to 5.1.0. So this is probably something about Windows/Webview2.0 framework

**Comment by hschneider** [comment]
**Ext-Python:**
Please download the latest repo and make sure the following requirements are met:
- Upgrade to the Neutralino 5.3.0 with `neu update --latest` in your project folder and verify afterwards with `neu version`.
- Re-Install the websocket-client package in your Python interpreter. 
- Extensions must be allowed in the nativeAllowList of neutralino.config.json:

```
  "nativeAllowList": [
    "app.*",
    "os.*",
    "window.*",
    "events.*",
    "extensions.*",
    "debug.log"
  ],
  ```

**Ext-Bun:**
- Upgrade to the Neutralino 5.3.0 with `neu update --latest` in your project folder and verify afterwards with `neu version`.
- Download the latest repo. It contains a fixed extensions/bun/run.cmd
- Extensions must be allowed in the nativeAllowList of neutralino.config.json:

```
  "nativeAllowList": [
    "app.*",
    "os.*",
    "window.*",
    "events.*",
    "extensions.*",
    "debug.log"
  ],
  ```

All other extension also have been tested successfully with Windows 11 and Neutralino 5.3.0.

**Comment by CosmoMyzrailGorynych** [comment]
Confirmed that neutralino-ext-bun works on Windows 11 after pulling the repo and updating `neu`. Will try to incorporate the extension into my project.

Just in case, you can use a locally installed bun for development in this way:
```diff
 @echo off
-set BUN_INSTALL=%1\extensions\bun\_runtime
 
 if exist "%1\extensions\bun\main.js" (
-    "%BUN_INSTALL%\bin\bun.exe" run "%1\extensions\bun\main.js"
+    bun run "%1\extensions\bun\main.js"
 ) else (
     "%1\extensions\bun\main-app.exe"
 )
```

**Comment by hschneider** [comment]
Sure. You could also add another parameter to run.cmd, to switch between locally and bundled via neutralino.config.json.
