### ISSUE TITLE
Use `Neutralino.filesystem` for packaged resources

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [neutralinojs/neutralinojs#1290]
**Is your feature request related to a problem? Please describe.**
Right now you can use bundled resources (`resources.neu`) only through browser means – through the Fetch API and by straightly linking to a file in HTML/JS. But sometimes you need to get the list of bundled files to know what you can load. Plus an ability to use `Neutralino.filesystem` methods would simplify code a bit compared to using Fetch API + Neutralino.fs.

Examples in my app:

* Loading a list of bundled translation files;
* Discovering bundled game asset packs and assets inside them;
* Discovering bundled example projects.

**Describe the solution you'd like**
A way to use `Neutralino.filesystem` to work with bundled files, like a shortcut that leads to the static server's directory: `await Neutralino.filesystem.readDirectory('%NLResources%/i18n');`.

**Describe alternatives you've considered**
Bundling all these files alongside the built executables, outside of `resources.neu`.

**Additional context**
Woof 🐺

**Comment by shalithasuranga** [comment]
Thanks so much for posting this feature request. Now the framework offers `getFiles()`, `extractFile()`, `readFile()`, and `readBinaryFile()` functions via the `resources` module for this requirement. Please await for the next release :tada:
