### ISSUE TITLE
 Replace WinRT APIs for Windows 7 Compatibility

### ISSUE THREAD

**Issue by BhuvanAde** [neutralinojs/neutralinojs#1295]
problem? Please describe.
Our codebase currently uses several WinRT APIs that are not supported on Windows 7. To ensure compatibility with Windows 7, we need to find alternate APIs or solutions that provide similar functionality.

Describe the solution you'd like
Identify and use alternative APIs that are compatible with Windows 7.
Ensure the new implementation mimics the behaviour of the original code to maintain functionality across different Windows versions.
Implement the changes in a way that maintains backward compatibility with Windows 8 and above.

Describe alternatives you've considered
Research needed

**Comment by shalithasuranga** [comment]
Closing this as we are still discussing whether we need to implement support for older Windows versions or not based on the GSoC  research project findings. We can re-open this issue if needed in the future. Thanks for creating this issue :tada:
