### ISSUE TITLE
Setting for Spawned Process termination when app is closed

### ISSUE THREAD

**Issue by OreoCookieRustDev** [neutralinojs/neutralinojs#1299]
If one closes the app without using my "exit" button, all spawned tasks stay running.

I can see why in some situations this would be needed and in other situations why it might not be desirable. 

I am making a cryptocurrency wallet and the wallet spawns the mining unit in the background.

I would like it so if the user closes the app without clicking my "exit" button that the spawned mining unit also is closed.

So my feature request is a setting in the neutralino config to allow spawned tasks to be killed when the app closes.

Not sure how this could be handled on crashes but that would also be ideal.

This way the dev can opt to kill spawned tasks with the Neutralino app, or not.

**Comment by thisjt** [comment]
If you're using the [`modes.window.exitProcessOnClose: false`](https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean) config, the app dispatches a `windowClose` event. You can use that to terminate your spawned processes before closing the app.

Not sure how to handle crashed though, you could periodically keep checking the websocket server if it still responds or not and self-close the spawned process when the websocket server doesn't exist anymore.

**Comment by shalithasuranga** [comment]
Thanks so much for the detailed answer @thisjt. We can close this issue this it's already answered with the above comment :tada:

**Comment by rsxdalv** [comment]
This creates a bad situation where a spawned process keeps the old neutralino alive forever and prevents a new neutralino from being opened. Thus an user needs to restart their PC to be able to open the app again if there remains something, anything, that was spawned.
