### ISSUE TITLE
Neutralino binaries uses webkitgtk 4.0 instead of 4.1

### ISSUE THREAD

**Issue by GomezMig03** [neutralinojs/neutralinojs#1307]
**Describe the bug**
When running a neutralino app in Fedora 40, if you have just webkitgtk 4.1 installed and not webkitgtk 4.0 it will throw the following error:
```
bin/neutralino-linux_x64: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
neu: WARN neutralino-linux_x64 was stopped with error code 127
```

**To Reproduce**
1. Uninstall webkitgtk 4.1 if you already have it installed and ensure 4.0 is installed
2. Try to open a neutralino app, either in production or in development
3. App won't open and error appears in the command line

**Expected behavior**
I've been told in the discord that the correct behavior should be neutralino using webkitgtk 4.1 as default and, if it's missing, using 4.0, but this seems like the opposite.

**Screenshots/Screen recordings**
![imagen](https://github.com/user-attachments/assets/9f1e751b-a5ad-4a35-8323-6a479d3f27ff)

**Specifications**  
 - OS: Fedora 40 Cinnamon
 - Neutralinojs version: 5.3.0
 - Neutralinojs client library version: 5.3.0
 - Neutralinojs CLI version: v11.2.2

**Additional context**
This also happens on a friend's computer. He uses Bazzite KDE, and it seems that it only ships with version 4.1 by default, so he couldn't open the app until he installed version 4.0.

**Comment by Ioniser95** [comment]
I think it should be fixed by simply upgrading the webkit2gtk-4.0 to webkit2gtk-4.1 in build configuration its currently targeting webkit2gtk-4.0

**Comment by OpenReplicant** [comment]
Just hit this issue, first time working with Neutralino after watching for years. ironically i want to build a CLI and shouldn't even need webkit for this.

**Comment by mikson022** [comment]
Will it get merged and if not how do I compile this myself? Because  
```error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory```

**Comment by shalithasuranga** [comment]
Hello thanks for reporting this issue and starting a discussion. This problem was fixed by dynamically searching and loading webkit2gtk library functions. Now webkit2gtk is only needed to run Neutralinojs apps using the `window` mode.

This fix will be released with the next version soon :tada: Thanks :)
