### ISSUE TITLE
There is a problem with the --url option of the executable file. It seems that it does not support the = symbol in the url.

### ISSUE THREAD

**Issue by huanshiwushuang** [neutralinojs/neutralinojs#1308]
**Describe the bug**
There is a problem with the --url option of the executable file. It seems that it does not support the = symbol in the url.
When I use the same command with a different URL, it loads the unexpected URL.

**To Reproduce**
1. cd bin directory , then  execute 【neutralino-win_x64.exe --path=. --url=https://www.baidu.com】，it's nice
2. cd bin directory , then execute 【neutralino-win_x64.exe --path=. --url=https://www.baidu.com/s?wd=123】，it's bad

**Expected behavior**
it loads the expected URL

**Screenshots/Screen recordings**
https://drive.google.com/file/d/1lUDBW_yRxLhKqJGyyGio7xr6J3UZipfi/view?usp=sharing

**Specifications**  
 - OS: windows10 22H2（19045.4780）
 - Neutralinojs version: v5.3.0
 - Neutralinojs client library version: v5.3.0
 - Neutralinojs CLI version: v11.2.2

**Comment by shalithasuranga** [comment]
This issue was fixed and will be released with the next version. Thanks so much for reporting this bug @huanshiwushuang 

Thanks :tada:
