### ISSUE TITLE
Tray menu support

### ISSUE THREAD

**Issue by blurymind** [neutralinojs/neutralinojs#131]
I really want to use this instead of electron, but my app requires the ability to have a tray menu

Any hope to see this feature some day?

**Comment by shalithasuranga** [comment]
@blurymind  Thanks. yeah this can be added to Neutralino API. 

##For developers

seems These resources may be used

- https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html
- https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shell_notifyicona

**Comment by blurymind** [comment]
Well for my app I need to create an invisible active window and have all the interface in the tray menu.
For that I was wondering if you have something similar to electron's show:false window init parameter

**Comment by momozor** [comment]
Hi. Can I have an example on the tray menu? I kinda interested in realizing this feature

**Comment by apollolux** [comment]
Question: for macOS would a menu icon be the equivalent, or would it be something else entirely?

**Comment by JakobReiter** [comment]
+1 
... Menu item (os x) = tray icon (win/Linux) 
but OSX allows for a Menu Item Test next to the Icon that the other platforms don't support. 
Menu icon menu then looks like a drop down context menu. 

This is as super important Feature, since writing a tray icon only app in Electron is > 300 MB in size which is crazy. This could be perfect for NeutralinoJS

**Comment by JakobReiter** [comment]
![67124020-eef5a880-f1f1-11e9-908f-d06024a17580](https://user-images.githubusercontent.com/9266151/75392106-a65ea200-58eb-11ea-8e51-f73d89646510.png)

**Comment by blurymind** [comment]
Yes that is actually what led me to this project, only to find that it cant actually do tray menus :(

I would have added it myself if I knew any c++, but alas my experience is in other languages

**Comment by chief-nerd** [comment]
What is the status of this? How can we (community) help?

**Comment by konsumer** [comment]
I'm no C-expert, but I'm going to see if I can figure it out. If anyone else is working on it and wants to collab, lemme know.

**Comment by shalithasuranga** [comment]
Thanks all for willing to help. Looks like we can use https://github.com/zserge/tray header file like we used webview. We could try to introduce `Neutralino.os.setTrayMenu()` we will be able to create menu with icon. But we need a way to handle click etc. probably that needs some big change

**Comment by konsumer** [comment]
I'm trying to think through the config/usage before I implement anything, and work back.

I think we will need a way to optionally not have the initial window show, but still run it's content (in a hidden window). Maybe if the window had an option to do off-screen running, like `window.show: false` in settings.json? That way we could do the menu setup in the script in the initial window.

Another idea I had was to add the menu to the JSON. I was thinking that if it was a URL-map it would be easy to read, but this would also make dynamic menus impossible. Maybe we could combine these ideas:

```
{
    "appname": "myapp",
    "appport": "5006",
    "mode": "browser",
    "url": "/",
    "window": {
        "title": "My app",
        "width": "1000",
        "height": "700",
        "fullscreen": false,
        "alwaysontop": false,
        "iconfile": "neutralino.png",
        "enableinspector": false,
        "borderless": false,
        "show": false
    },
    "tray": {
      "iconfile": "neutralino.png",
      "title": "My Tray Icon",
      "menu": {
        "Home": "/",
        "About": "/about"
      }
    }
}
```

This has `window.show: false` and an initial tray-object. Later, if you needed a dynamic menu, you could do a `Neutralino.os.setTrayMenu()` with the same object format. I think using URLs for routing helps keep it it simple, and there are lots of builtins for handling different sorts of use-cases around URLs (like `window.onhashchange` for SPAs.)

So, I think this would cover it:

* add `window.show: false`
* add `Neutralino.os.windowHide()` and `Neutralino.os.windowShow()` to control the main window after initial load
* parse `menu` in settings.json as initial menu. If you need a menu, you need to at least set that
* add `Neutralino.os.setTrayMenu()`
* Users will need to respond to page-load/hash-change/etc to show the window. If they initially set  `window.show: false`, they will probably need `Neutralino.os.windowShow()` somewhere, but it also leaves the possibility of menu-items just triggering callback for responding to menu and not popping up a window.

Does this make sense?

**Comment by konsumer** [comment]
This would hit all my possible usecases, that I can think of:

### I want a simple menu with an initial window

* Set initial `tray.icon` to a branding-icon, with no `tray.title`
* Set `tray.menu` to an object with different URLs
* `window.onload = () => Neutralino.os.windowShow()` in all HTML files
* call `Neutralino.os.windowHide()` when I want to hide the main window

This brings up another thing, we probly need a way to not close app when the main window is closed. Maybe `window.stay: true`? This would also require a callback for "the user clicked the close button"


### I want a simple menu with no initial window

* Set initial `tray.icon` to a branding-icon, with no `tray.title`
* Set `tray.menu` to an object with different URLs
* set `window.show` to `false`
* `window.onload = () => Neutralino.os.windowShow()` in all HTML files


### I want just a tray-icon that changes based on something happening in background, with no menu or initial window

* Set initial `tray.icon` to a loading icon, with no `tray.title` and no `tray.menu`
* set `window.show` to `false`
* in my `url` javascript, wait for things and swap out the icon with `Neutralino.os.setTray({ title: '', icon: 'newicon.png' })`


### I want a tray-icon and title that changes based on something happening in background, with no menu or initial window

* Set initial `tray.icon` to a loading icon, with no `tray.title` and no `tray.menu`
* set `window.show` to `false`
* in my `url` javascript, wait for things and swap out the icon with `Neutralino.os.setTray({ title: 'New title', icon: 'neutralino.png' })`


### I want just an icon with a dynamic menu that changes based on something happening in background

* Set initial `tray.icon` to a branding-icon, with no `tray.title`
* set `window.show` to `false`
* `window.onload = () => Neutralino.os.windowShow()` in all HTML files
* in my `url` javascript, wait for things and swap out the menu with `Neutralino.os.setTray({ title: '', icon: 'neutralino.png', menu: { ... } })`

**Comment by konsumer** [comment]
Maybe all the custom function could be wrapped into settings, so it's a sort of object-graph of the current state, so instead of `setTray`, `windowShow`, `windowHide` it could all be through a single settings call:

```js
os.updateSettings(function success(settingsData), function error())
```

**Comment by konsumer** [comment]
Another use-case I didn't consider is the above example of custom content. This would maybe be a better first-pass implementation, as I can make a menu in HTML:

```json
{
    "appname": "myapp",
    "appport": "5006",
    "mode": "browser",
    "url": "/",
    "window": {
        "title": "My app",
        "width": "1000",
        "height": "700",
        "fullscreen": false,
        "alwaysontop": false,
        "iconfile": "neutralino.png",
        "enableinspector": false,
        "borderless": false,
        "show": false
    },
    "tray": {
      "iconfile": "neutralino.png",
      "title": "My Tray Icon",
      "url": "/tray.hmtl"
    }
}
```

**Comment by chief-nerd** [comment]
@konsumer I think you covered a lot of use cases here. Especially the render file one seems especially powerful. 
I also like the idea of the `os.updateSettings` to override since it makes bulk overrides very efficient.

What is now still missing?

**Comment by konsumer** [comment]
@chief-nerd I'm still not quite sure how to achieve all this. The library @shalithasuranga mentioned looks awesome & light, but doesn't seem to have a way to do an arbitrary web panel (it's just a menu.) Even icons is in their TODO, so it would be very basic text-menu support.

**Comment by konsumer** [comment]
I think another issue with this idea is that each OS generally has a way to make custom widgets in their tray-icons, that use the library directly, and web-based menus will probly have to be a bit hacky and not native-looking. This might be a good argument for simpler menus (just a list of items, with icon/text/link) TO prototype my experiments around this, I made a little demo in python for gnome/gtk:

```py
#!/usr/bin/env python3

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator

APPINDICATOR_ID = 'myappindicator'

def main():
  indicator = appindicator.Indicator.new(APPINDICATOR_ID, 'whatever', appindicator.IndicatorCategory.SYSTEM_SERVICES)
  indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
  
  menu = gtk.Menu()
  item_quit = gtk.MenuItem('Quit')
  item_quit.connect('activate', handle_quit)
  menu.append(item_quit)
  menu.show_all()
  
  indicator.set_menu(menu)
  gtk.main()
 
def handle_quit(source):
  gtk.main_quit()

if __name__ == "__main__":
  main()
```

![Screenshot from 2020-06-08 11-11-19](https://user-images.githubusercontent.com/83857/84065216-d866b200-a978-11ea-996a-66a0e70f34db.png)

**Comment by konsumer** [comment]
I think we will also need an API for notifications.

This code, again in python, for GTK make a nice notification:

```py
#!/usr/bin/env python3

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Notify as notify

APPINDICATOR_ID = 'myappindicator'

def main():
  indicator = appindicator.Indicator.new(APPINDICATOR_ID, gtk.STOCK_INFO, appindicator.IndicatorCategory.SYSTEM_SERVICES)
  indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
  
  menu = gtk.Menu()
  item_quit = gtk.MenuItem('Quit')
  item_quit.connect('activate', handle_quit)
  menu.append(item_quit)
  menu.show_all()
  
  indicator.set_menu(menu)
  notify.init(APPINDICATOR_ID)
  notify.Notification.new("Test", "Notifications seem to work.", None).show()
  gtk.main()
 
def handle_quit(source):
  gtk.main_quit()

if __name__ == "__main__":
  main()
```

![Screenshot from 2020-06-08 11-19-54](https://user-images.githubusercontent.com/83857/84065958-131d1a00-a97a-11ea-85e1-03d82120ce11.png)

**Comment by konsumer** [comment]
Another thought on config structure:

Maybe instead of `window.show`, there could just be a new `window.mode` like "hidden" that means "open the initial URL but don't show it's window". this might cover more use-cases and fit better with current config-shape. It would still require API for hide/show window and other things, but might make it all feel more cohesive.

If anyone else knows more about C & Gtk, they might be a better fit to actually implement these ideas. I played with it for a bit, but couldn't get it to work, and I'm not sure if I could without devoting more time than I have.

While I can't make go compile a binary quite as small (on linux, I got it down to 2.3M, not 1.1M, with a tester that does webgtk window + systray menu) I am more familiar, and the code is identical on different platforms which helps a lot for maintainability/readability. For my own stuff, I might just end up doing that, but I'd still be into helping other more experienced C/GTK dev, if I can.

**Comment by chief-nerd** [comment]
@apollolux, @momozor ... checking in on this ... do you have plans for this or should I stop bugging you :)

**Comment by apollolux** [comment]
I actually don't know why I'm being pinged about tray menus, I only asked what the Mac equivalent would be and AFAICT did not express interest in attempting to implement this myself.

**Comment by zaaack** [comment]
Any updates here?

**Comment by shalithasuranga** [comment]
Mm.. this one is closed after 2.5 years :smiley:  But finally it's done. I will make it available with the next release soon. This feature will work on all supported operating systems. The following sample is on Linux.

![image](https://user-images.githubusercontent.com/18402702/122951760-27706100-d39b-11eb-93e0-d0aa57bd89c0.png)

```
Click events available via `Neutralino.events.onTrayMenuItemClicked`
```

**Comment by chief-nerd** [comment]
AMAZING -- I was so waiting for this! This will be a game changer for slick/slim tray apps! .... bye bye electron craziness!

**Comment by konsumer** [comment]
This looks awesome!

**Comment by Joshua-0612** [comment]
Can we please get example code for tray menu app?

**Comment by shalithasuranga** [comment]
Hey. @Joshua-0612  I will make a tutorial for it soon, but you can check [official docs](https://neutralino.js.org/docs/api/os#ossettraytrayoptions)

**Comment by georgechitechi** [comment]
Thanks @shalithasuranga and team for this  great feature,
Is it possible to include this in the minimal template.

Am sure it'll benefit lot's of people.

**Comment by shalithasuranga** [comment]
@georgechitechi Yeah.. looks like a great idea

**Comment by georgechitechi** [comment]
> @georgechitechi Yeah.. looks like a great idea

@shalithasuranga any update on this

**Comment by shalithasuranga** [comment]
Hey @georgechitechi  it's added, hope you will check by creating a new app :)

**Comment by georgechitechi** [comment]
> Hey @georgechitechi it's added, hope you will check by creating a new app :)

Thanks, done

**Comment by Lucasmiguelmac** [comment]
Is there yet a way to have a tray-bar-only app? That is, to have a window open only from the tray bar.

**Comment by konsumer** [comment]
@Lucasmiguelmac you can do `window: hidden` See options, [here](https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowhidden-boolean).

**Comment by n1kk** [comment]
Is it only 1st level menus items? Are submenus an option?
