### ISSUE TITLE
IndexedDb data persistence on MacOS?

### ISSUE THREAD

**Issue by LetMyPeopleCode** [neutralinojs/neutralinojs#1314]
I've found various web pages discussing how Apple erases the storage of IndexedDb data in Safari for sites that haven't been visited in at least 7 days (unless you add the site to your desktop). They claim it's a privacy enhancement.

I'm working on an app in Neutralino. I want to use a JS database library like Pouch or Loki, which have IndexedDb adapters for persisting the data. But that creates the worry that using IndexedDb will create data loss for users who don't use it regularly.

If I can be sure the IndexedDb data would persist on Mac, I'd use it. It will save me the time of writing a device storage adapter using the Neutralino filesystem APIs. This is a semi-blocking issue. I intend to build in a "bring your own database" interface that can be used to create an adapter for any database, but that was intended as a V2 feature, not MVP.

Being able to use one of these databases without having to write that abstraction layer or a persistence adapter for one would help me get to MVP and start recruiting beta testers faster.

I just can't find any solid confirmation that Apple won't clobber the IndexedDb data in the MacOS webview Neutralino uses if the user doesn't boot the app at least once every 7 days.

**Comment by LetMyPeopleCode** [comment]
I've created a simple test that uses a timestamp as a key. The query gets all keys, does some Date() magic on them and prints the list as date and GMT time. I added a few items. Now it will sit unused and I'll run it again in 9 days. If no one's posted an answer, I *should* have the answer by then.

**Comment by LetMyPeopleCode** [comment]
Oops, accidentally closed.

**Comment by LetMyPeopleCode** [comment]
Accidentally closed this and I do not have the permissions to reopen. D'oh.

**Comment by shalithasuranga** [comment]
Reopened, thanks so much for posting this issue :tada:

**Comment by LetMyPeopleCode** [comment]
My experiment showed the data I'd saved a couple of weeks earlier got clobbered. I'm using LokiJS as my database and wrote a persistence adapter using the Neutralino.filesystem (to read/write) and Neutralino.os (to find where to create the data directory) APIs.

**Comment by LetMyPeopleCode** [comment]
My experiment showed the data I'd saved a couple of weeks earlier got clobbered. I'm using LokiJS as my database and wrote a persistence adapter using the Neutralino.filesystem (to read/write) and Neutralino.os (to find where to create the data directory) APIs.
