### ISSUE TITLE
Console gets flooded with `neu: INFO Global variables patch was reverted.` when using a dev server

### ISSUE THREAD

**Issue by thisjt** [neutralinojs/neutralinojs#1324]
**Describe the bug**
The console log gets flooded with the message:. This message shows up in the console every second.
![image](https://github.com/user-attachments/assets/bf36ea82-990a-48df-b7e8-50f4fcbc5b15)

Note: I am not importing the `neutralino.js` client-side script. I'm planning to control the neu using websocket and extensions.

**To Reproduce**
1. create a zero project `neu create neutralinojs/neutralinojs-zero`
2. change config from `"url": "/"` to `"url": "http://localhost:5173"`
3. add config for `cli.frontendLibrary`
```json
"cli": {
  "frontendLibrary": {
    "devUrl": "http://localhost:5173"
  }
}
```
5. run `neu run` in the console

**Expected behavior**
Info message only shows up once, or a few times, or maybe once every 30-60 seconds, or there should be a config to disable this particular message.

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: 5.4.0
 - Neutralinojs client library version: Installed from a package manager
 - Neutralinojs CLI version: 11.3.0

**Comment by thisjt** [comment]
I'm, gonna close this now. Seems like the issue can be remediated by just removing the `cli.frontendLibrary`.

**Comment by kindlychung** [comment]
Removing "cli.frontendLibrary" means not hot reload, right?

**Comment by thisjt** [comment]
> Removing "cli.frontendLibrary" means not hot reload, right?

Yes, but HMR will be handled by the dev server of your chosen front-end framework.
