### ISSUE TITLE
File pickers?

### ISSUE THREAD

**Issue by tonnerkiller** [neutralinojs/neutralinojs#133]
Just about to write an application that needs loading and saving of files.
As far as I see it, with the filesystem methods I need to know path and file name to open files and also to save files.
A file picker that returns me the paths+filename as sting would be really handy. Anything likely planned? Any ideas for a workaround? I tried with File API as an alternative, but this only allows loading and writing by means of download links is just clumsy...

**Comment by tonnerkiller** [comment]
Marvellous!

**Comment by shalithasuranga** [comment]
This is done. `Neutralino.os.dialogOpen` and `Neutralino.os.dialogClose` methods will be available with the next release

**Comment by jjgh** [comment]
Does njs support opening multiple files? I mean, the ability to select and open multiple files in the file open dialog?

**Comment by blockpit-einicher** [comment]
Was this feature removed? Why?
