### ISSUE TITLE
does Neutralinojs support/detect `webkit2gtk-4.1`?

### ISSUE THREAD

**Issue by leeoniya** [neutralinojs/neutralinojs#1335]
@shalithasuranga it seems to be expecting 4.0, but according to https://github.com/neutralinojs/neutralinojs-cli/issues/149#issuecomment-2095922967, i expected it to grab any latest available 4.x?

![image](https://github.com/user-attachments/assets/dc0cb4fc-354d-4f2b-810b-52a6af647e52)

**Comment by shalithasuranga** [comment]
Hello @leeoniya, thanks for reporting this issue. We already have a pull request, #1330 for this. But, I am researching about its effect on older Ubuntu users -- they won't be able to run the latest version without updating system sources/libraries. Perhaps, we'll have to start using 4.1 from next Neutralinojs version and ask older Ubuntu users to install it to run apps. We'll fix this soon :tada: with the next version.

**Comment by leeoniya** [comment]
> Another option is to dynamically load available webkit GTK libraries :)

i kinda figured that's the whole pitch of this project, how else can the binaries be so small? :sweat_smile:

**Comment by shalithasuranga** [comment]
> > Another option is to dynamically load available webkit GTK libraries :)
> 
> i kinda figured that's the whole pitch of this project, how else can the binaries be so small? 😅

Mmm. I meant we can dynamically load available webkit2gtk library during runtime :) I am implementing it now ;) I hope we can run the next Neutralinojs version on old and new Ubuntu versions without any issues :tada:

**Comment by shalithasuranga** [comment]
Fixed via #1307 (see the last comment for more info). Thanks so much for reporting this issue and starting a discussion :tada:

**Comment by leeoniya** [comment]
woohoo!
