### ISSUE TITLE
32bit windows version available

### ISSUE THREAD

**Issue by infantilo** [neutralinojs/neutralinojs#136]
Ist there an 32bit windows version, too??

**Comment by shalithasuranga** [comment]
Hi.. Thanks for posting an issue. We have included 64-bit versions only in our releases because many of users are not using 32-bit environments. We think its better to include 32-bit version as well.

We will update our latest release with 32-bit version as well soon

**Comment by meagerframework** [comment]
When can we expect windows 32 bit release ?

**Comment by dns** [comment]
Any update on 32-bit windows release?

**Comment by shalithasuranga** [comment]
Since this seems about just compiling and updating binaries will do it asap and do a quick release

**Comment by Markcial** [comment]
or you could add this information on the docs so we can make the build, thanks

**Comment by shalithasuranga** [comment]
@Markcial Hey.. Adding `-m32` flag to the g++ build command in .sh and .bat files will make 32bit binaries. As I remember I got several error messages. Need to check again

**Comment by shalithasuranga** [comment]
Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486  open until we apply a fix. Thanks
