### ISSUE TITLE
Using other JS frameworks inside Neutralino

### ISSUE THREAD

**Issue by paulocoghi** [neutralinojs/neutralinojs#137]
Sorry for the newbie question, but, is it possible to use websites created using other front-end / js frameworks inside Neutralino?

Thanks!

**Comment by shalithasuranga** [comment]
Yeah you can use your existing html/js stuff (using some other frameworks) inside Neutralino. Simply put your sources(final) to assets directory. Please check [ReactJs](https://github.com/neutralinojs/neutralinojs-reactjs-template) template for more info :)

**Comment by paulocoghi** [comment]
Thanks!
