### ISSUE TITLE
windows, 32/64 bit, inaccuracy in the specified compiler

### ISSUE THREAD

**Issue by niXman** [neutralinojs/neutralinojs#139]
When using the MinGW compiler specified by the `README`, it is impossible to build the 64-bit target, since `mingw.org` provides the compiler only for 32-bit. It is more correct to specify the `MinGW-W64`(mingw-w64.org), which supports both 32-bit and 64-bit.

**Comment by shalithasuranga** [comment]
Yeah you are correct. w64 is the right one. Can you please check ur pull request comment ;)

**Comment by shalithasuranga** [comment]
Hey, I am closing this since now the framework documentation (README) is updated.
