### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Peter2121** [neutralinojs/neutralinojs#141]
Please, add FreeBSD support.

**Comment by momozor** [comment]
Assuming you already installed `gnome3`, `xorg`, and `emulators/linux_base-c7`..and enabled the linux compatibility modules, you should be able to run the neutrolino-linux build. I did a test on this, but it returned this error `error while loading shared libraries: libwebkit2gtk-4.0.so.3: cannot open shared object file: No such file or directory`.

**Comment by Peter2121** [comment]
Hmm... Why do one need to install gnome3? Can you build it on Linux using recent clang? If not - probably installing gcc from package could improve your build on FreeBSD...

**Comment by momozor** [comment]
No you don't need gnome3 for that, indeed.

**Comment by momozor** [comment]
> I also tried to build the linux version on freebsd, but it failed and complained about 'incomplete types'

changing C++ standard to -std=c++17 should fix this error

**Comment by shalithasuranga** [comment]
Closing this because now FreeBSD support is added. Thanks @lhondareyte for the pull request.
