### ISSUE TITLE
ping stop working (connection refused after editing index.html)

### ISSUE THREAD

**Issue by danbulant** [neutralinojs/neutralinojs#144]
Hello. 
I tried neutralino with the default example and it worked. But when I edited the app, the ping stop working - it show connection refused. Why?

**Comment by shalithasuranga** [comment]
Hi.. 
Can you please post the content of `config.json` and modified `index.html`

**Comment by shalithasuranga** [comment]
Maybe the `script` tag of `app.js` is removed that has the init?.. I am closing this issue since this was not active so far.
