### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by kefniark** [neutralinojs/neutralinojs#145]
Thanks guys for this project, it's a really good idea and I hope it will provide us smaller and faster webapps.

## Description
I just got a bit confused because on windows 10, neutralinojs start using internet explorer 11 and not edge. This enforce usage of ES5 with bunch of polyfill/hack for modern framework, and sadly it leads to terrible performance with webgl.

## Expected Behavior
I would like to know if it could be possible to provide a default browser table in the documentation.

## Actual Behavior
The user has to manually test to see which browser shows up.

**Comment by shalithasuranga** [comment]
@kefniark  Thanks for your comments and the issue. Neutralinojs currently uses IE browser component for rendering web pages. and in Windows 10 it's going to use IE11 component which doesn't support latest features of Javascript.

We are using webview c++ header file to render html as a wrapper. webview uses IE plugin currently there are still looking a way to use EdgeHTML when it's available on the system

References : https://github.com/zserge/webview/issues/85

**Comment by kefniark** [comment]
Thanks for the answer, based on the recent work on the `webview-x` branch and the README, it looks like this webview should support `EdgeHTML` soon.
Sounds really promissing for neutralinojs performance wise (IE is a real issue)

**Comment by bjimdar** [comment]
Looks like something like this might work:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by shalithasuranga** [comment]
I am closing this because Neutralinojs v2 uses EdgeHTML/Chromium on Windows. :rocket:
