### ISSUE TITLE
Access native system API

### ISSUE THREAD

**Issue by sudhakar3697** [neutralinojs/neutralinojs#155]
How can I access native system APIs (like native node addons) ?.

Thank you.

**Comment by sudhakar3697** [comment]
In case of electron/NW.js, I write native node addon (node-addon-api) to access windows registry.

**Comment by shalithasuranga** [comment]
Neutralinojs API has most required native functions as explained in [docs](https://neutralino.js.org/docs/#/) If you like to suggest a new native function which can be introduced to Neutralino API please let us know via an issue.

If you can to run a custom native call. You can make a executable for the particular native call and place in to Neutralino app directory. Then you can use [`Neutralino.os.runCommand`](https://neutralino.js.org/docs/#/api/os?id=osruncommandstring-command-function-successdata-function-error)

**Comment by kasvith** [comment]
@sudhakar3697 to support an addon i think we would have to go in a long way

Ultimately it would be a dynamic lib you can call through the JS side(in this case you may need to provide C/C++ implementation and Glue JS code as you currently do with NodeJS)

It would take time but definitely worth it.

**Comment by shalithasuranga** [comment]
This issue is closed because of https://github.com/neutralinojs/neutralinojs/issues/459. 
Please check more about Neutralinojs API extensions.
