### ISSUE TITLE
Sample not working on Windows 10

### ISSUE THREAD

**Issue by Sensiblemnd** [neutralinojs/neutralinojs#157]
**Expected Behavior**  
When clicking on the   neutralino.exe in the sample folder the app should run.

**Actual Behavior**  
When clicking on the   neutralino.exe in the sample folder windows firewall asks permission to run and then an error shows up

![Capture](https://user-images.githubusercontent.com/940303/57584549-c16e3b80-74aa-11e9-96a3-d7d468fdbf27.PNG)
.

**Steps to Reproduce the Problem**  
 1. go to any sample folder once unzipped
 2. Click   neutralino.exe
 3. give permissions to execute the file
4. js error shows up.

**Specifications**  
* NeutralinoJs latest sample folder
* Platform: windows 10

**Comment by shalithasuranga** [comment]
Hello. Thanks for posting the issue. Can you let us know your Internet Explorer version? This will usually happen when latest js syntax is parsed by old IE (Neutralino currently uses IE in Windows)

**Comment by Sensiblemnd** [comment]
Latest Chrome

**Comment by Sensiblemnd** [comment]
Wait it uses IE?

**Comment by shalithasuranga** [comment]
Yeah... in windows it uses IE 😢  . We are trying to add Edge instead but seems it require some additional dev dependencies (Win 10 sdk etc for some c++ headers)

**Comment by gr1los** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/38035829/63231652-a849f900-c216-11e9-895a-e12c2de08462.png)

**Comment by kasvith** [comment]
Windows will ship a Chrome-based Edge version soon, once it is released we will be able to ship it by default

**Comment by acedigibits** [comment]
Any update on this issue? This one is total bummer.

**Comment by kasvith** [comment]
@acedigibits its not stable yet

**Comment by uchihafelip3** [comment]
Is there already a solution to the problem?

**Comment by shalithasuranga** [comment]
Hey.. I am closing this since now the latest Windows version is working fine. The issue was the IE doesn't support ES6. now neu-cli templates use ES5 as the target.
