### ISSUE TITLE
How do I install WebkitGTK+ on windows

### ISSUE THREAD

**Issue by genesy** [neutralinojs/neutralinojs#158]
It says on the documents that this is required, and i can't successfully run build in the core-windows version so i think i'm missing this. I'm just not sure how to install and apply the files from the webkitgtk site, they're tarballs.

**Comment by shalithasuranga** [comment]
Hey.. no need to install WebkitGTK on windows. It is required in Linux. Please setup g++ (from ming) and webpack. Windows build will work fine then :)

**Comment by kasvith** [comment]
We will soon support using Microsoft Visual C++ as well.
I think in the future we will skip MinGW and stick to MSVC for better optimizations
