### ISSUE TITLE
Windows App Title with Spaces

### ISSUE THREAD

**Issue by Prid13** [neutralinojs/neutralinojs#159]
The `<title>` tag is not working on Windows app title bar, as it only shows the value of `appname` in `settings.json`. No problem with that. However, as soon as I type in an appname with **spaces**, the Windows Neutralino.js app stops working and prompts a Save As dialog for a JSON file with the appname, and an error saying "Navigation to the website was canceled.".

![image](https://user-images.githubusercontent.com/27897747/59059680-dcf91600-889f-11e9-924f-382ae947ff46.png)

![image](https://user-images.githubusercontent.com/27897747/59059707-eaae9b80-889f-11e9-8400-4521b1103304.png)

**Comment by momozor** [comment]
On linux version, it behaves a bit weird 
![lop](https://user-images.githubusercontent.com/24475030/75299328-b9339100-586f-11ea-967c-e52f694bb6e5.png)

**Comment by ainar** [comment]
Same behavior as in Linux when opening in browser on Windows.

**Comment by shalithasuranga** [comment]
It was fixed in Windows via #257 . We need to add into other platforms as well

**Comment by shalithasuranga** [comment]
Now `window.title` can be used with spaces etc for the title. and appname should act as app id without space etc
