### ISSUE TITLE
Using way too much RAM than advertised (1GB)

### ISSUE THREAD

**Issue by Prid13** [neutralinojs/neutralinojs#160]
I had really high hopes for this as Electron.js is a RAM hog, and I thought this would actually be below 100MB for the most part for a fairly simple app.

I just imported Bootstrap and jQuery, and added 3 simple card with a Jumbotron like this:

![image](https://user-images.githubusercontent.com/27897747/59070214-340be480-88ba-11e9-8fce-79dad63db153.png)

However, the RAM just keeps on increasing to absurd numbers with zero interaction:

![image](https://user-images.githubusercontent.com/27897747/59070263-5ef63880-88ba-11e9-8229-c4f65839143a.png)

It reaches 1GB, and then goes back to 500MB, but keeps on increasing to 1GB. And then the app just suddenly closed :/

Either I'm doing something terribly wrong, or the promised low RAM consumption was only applicable for a simple Hello World app. Props for the effort though :)

**Comment by Prid13** [comment]
I ended up using [PHPDesktop](https://github.com/cztomczak/phpdesktop), which is only consuming 50MB of memory for the same app as in the screenshot above, and it suited my needs better as I'm a fan of PHP :)

I really appreciate the effort as there are too few lightweight, simple alternatives to monolithic mainstream frameworks and libraries, and I wish there were more. Maybe it's my laptop that's at fault, maybe I didn't do something right, or maybe Neutralino.js couldn't handle my app. Either way, I hope I can one day use this to make JS apps with super low footprint :)

**Comment by userabuser** [comment]
Do you have a link to your source?

I've ran the same test with Jumbotron and 3x cards, with images in excess of 5000px x 5000px (2MB) [from remote sources] and I clock around 14/15MB of memory usage.

Trying to load images from `app/assets/...` results in Neutralino crashing.

FWIW I've used PHPDesktop before and it's quite nice.

Any attempt at an alternative to Electron/NW is a good effort. Have a few projects in Electron so certainly not complaining at the choice and ease of developing for the desktop but hopefully we'll see light-weight efforts like this and others take formal shape.

**Comment by Prid13** [comment]
> Trying to load images from `app/assets/...` results in Neutralino crashing.
You're absolutely right, once I dropped the background image of my jumbotron, which was loaded locally from the assets folder, the app went down to 13MB of memory usage. I must be loading the assets wrongly, then, perhaps. Regardless, PHPDesktop works much better for me and is easier to work with because of PHP scripts having more control over your system :)

**Comment by userabuser** [comment]
Ah interesting... Yeah, obviously we are both encountering the same problem re: loading of local images at the very least. Might need to dig deeper on that. But yeah if you're looking to run PHP then PHPDesktop is the way to go. With that said you can easily spawn and run PHP from this lib or others such as Electron/NW too.

Also a little tip, for libs such as Neutralino, PHPDesktop or anything that is a thin-layer that excludes all or most of the Node API, you can still create Node applications (smaller modules) and pack them into an *.exe using `pkg` or `nexe` and bundle them Neutralino/PHPDesktop and invoke the executable from PHP or whatever API is made available to you depending on base library you are using.

This can afford you the ability to make use of Node APIs as well as ecosystem packages while reducing memory consumption.

I look forward to the next 12 months as project like this here and others are affording us a lot off-the-shelf cross-platform ability.

**Comment by kasvith** [comment]
As I suspect this seems a memory leak in the binary, need to take a look

**Comment by shalithasuranga** [comment]
@kasvith  yeah sounds there is a leak I also experienced in linux version too

**Comment by kasvith** [comment]
In linux its a problem with path resolvers. We should hold all until we merge all platforms into a single codebase

**Comment by kasvith** [comment]
@userabuser I see your problem, Neutralino does not support reading binary files. But we are working on rewriting the system from scratch and the issue will be addressed by then

**Comment by shalithasuranga** [comment]
I am closing this issue since the latest version has no issues like this.
