### ISSUE TITLE
Two commands to OS can not run simultaneously

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#162]
I wanted to run two powershell instances to act as a `NamedPipeServerStream` and `NamedPipeClientStream` (where server script is always running), but it doesn't work, because two commands can not run simultaneously. When the second command starts running, the first one immediately finishes with empty output. There's also a race condition of some sort.

**Code used**

```
    const command1 = `powershell 1`
    const command2 = `powershell 2`
    const run = function (command) {
        Neutralino.os.runCommand(command1, (result) => {
           console.log(result)
        })
    }
   run(command1)
   run(command2)
```

**Expected Output**  
    `{ stdout: "1↵"}`,
    `{ stdout: "2↵"}`
  
**Actual Behavior** 
    It's either
    `{ stdout: "↵"}`, // returns empty
    `{ stdout: "2↵"}`
    or
    `{ stdout: "↵"}`, // returns empty
    `{ stdout: "1↵"}` 

**Steps to Reproduce the Problem**  
 1. Run the code

**Specifications**  
* NeutralinoJs Version: 1.1.0
* Platform: Windows 10, x64

**Comment by shalithasuranga** [comment]
Please try with the latest version. This will work fine because we recently re-implemented os.exeCommand's core logic.
