### ISSUE TITLE
Service Worker support in Window mode

### ISSUE THREAD

**Issue by NilesshGaikwad** [neutralinojs/neutralinojs#163]
**Expected Behavior**  
Real time push notification not working in window mode.. 
but working in browser mode

**Comment by kasvith** [comment]
Yes we would have to implement that

**Comment by JoaquinDecima** [comment]
This error continues?

**Comment by shalithasuranga** [comment]
I am closing this because Neutralinojs supports native notifications (https://neutralino.js.org/docs/api/os#osshownotificationnotificationoptions).

**Comment by hrgdavor** [comment]
Title of this issue is maybe misleading. I see in comments the discussion is about notifications. But I have an issue where Service Worker when used freezes neutralino on linux. Are there known issues with ServiceWorker itself or limitations in it's use in neutralino.
