### ISSUE TITLE
set window size?

### ISSUE THREAD

**Issue by Vrx8** [neutralinojs/neutralinojs#165]
set fullscreen, window size, window position, window opacity at runtime, and window type, eg. borderless, there is also no official tutorial on creating executeable out of neutralino js.

**Comment by shalithasuranga** [comment]
Hi. Thanks for the ideas. fullscreen support is already added to Linux version but as you mentioned it is better to have runtime manipulation of window. We will add `Neutralino.app` for those

**Comment by genesy** [comment]
Also please add always on top mode for window manipulation.

**Comment by shalithasuranga** [comment]
Fullscreen and always on top mode were there already :). Added `Neutralino.window.setSize(options)` for changing size properties. Allowed options are `width`, `height`, `minWidth`, `minHeight`, `maxWidth`, `maxHeight`, and `resizable`. Added opacity and positioning features to the roadmap. I will release these new things with the next release.

**Comment by muditsaxena01** [comment]
Are we aware of any bugs related to setSize?
In borderless mode when I change the size (setSize) of the window, border appears after the change has been applied.
