### ISSUE TITLE
Implement log file support for existing logger module

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#167]
Now we have a logger module which is implemented by @philippludwig . It is better if we can asynchronously write what we get in terminal in to `neutralinojs.log` at root of the project.

**Comment by philippludwig** [comment]
I will look into it :)

**Comment by shalithasuranga** [comment]
Awesome.. Thanks 👍

**Comment by shalithasuranga** [comment]
Feature is merged in to master. Thanks @philippludwig
