### ISSUE TITLE
Can't double click to run neutralino in macOS?

### ISSUE THREAD

**Issue by jardenliu** [neutralinojs/neutralinojs#174]
I clone the repo and run the awesome program in my mac. Use terminal exec "./neutralino" to run the binary file, it work. However, it is not work when I double click to run it, as follow:
![image](https://user-images.githubusercontent.com/15191056/64517174-65190c80-d322-11e9-857b-1a542da50b45.png)

  I am so sorry about I just a web developer. Could you please tell me, can run it by double click?

**Comment by kasvith** [comment]
Thanks, this issue seems also on Linux systems. I will check this ASAP.

**Comment by kasvith** [comment]
Fix is on the way

**Comment by kasvith** [comment]
Hi @jardenliu can you please test #176 
You can find a sample application in `core-macos/example` directory

**Comment by jardenliu** [comment]
@kasvith test it and work, thanks for you work.

**Comment by kasvith** [comment]
Always a pleasure
