### ISSUE TITLE
MacOS Support 

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#18]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24200%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/neutralinojs/neutralinojs/issues/18)

Idea proposed by Reddit user 
Check the source [here](https://www.reddit.com/r/javascript/comments/907hym/why_we_built_neutralinojs_framework_medium/e2ofukh)

## TODO

- Write neutralino server implementation(We try the existing linux and do some modifications if needed) for MacOS in `core-macos`
- Executable will be placed in to `dist/neutralino.{extension}`

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)
### Submitted pull Requests
- [#170 MacOS support](https://issuehunt.io/r/neutralinojs/neutralinojs/pull/170)
- [#173 MacOSX Support](https://issuehunt.io/r/neutralinojs/neutralinojs/pull/173)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/neutralinojs/neutralinojs/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by noisiak** [comment]
Yes! It would be nice to try this on mac.

**Comment by calumk** [comment]
agreed

**Comment by xboston** [comment]
https://github.com/pojala/electrino ;-)
https://medium.com/dailyjs/put-your-electron-app-on-a-diet-with-electrino-c7ffdf1d6297

> I’ve just released the first version of a runtime named Electrino which does exactly this. Its goal is to be API-compatible with Electron (i.e. you can just copy your Electron-using JavaScript app’s files into the Electrino binary, and it will run).

**Comment by shalithasuranga** [comment]
@xboston  Electrino is a  nice project!. Neutralino is kind of different than Electrino. Neutralino is fully portable (One SDK for all supported platforms) and no dependencies(even no node, js libs etc) required

**Comment by davidbwaters** [comment]
Have you taken a look at [MacGap](http://macgapproject.github.io/)? This could be a possible alternative in the mean time or could help get this figured out.

**Comment by SirWindfield** [comment]
Is there a page where I can see all available protocol commands? 
And does the MacOS port has to be written using C/C++?

I would much prefer to write it in Rust. This would enable a potential port for later on, moving the whole code base into one single server binary that can be compiled for three platforms. 
Rust basically allows conditional compiling and since a lot of crates (Rust packages) already are multi-platform there would be minimal need to actually write custom parts for each OS.

**Comment by kasajian** [comment]
Does this mean at the present time no there's no plan to support this, and someone just needs to step in to do it?

**Comment by kasvith** [comment]
@kasajian its supported
