### ISSUE TITLE
Neutralino.filesystem.readFile infinite loop bug on non-existent file

### ISSUE THREAD

**Issue by jetibest** [neutralinojs/neutralinojs#181]
**Expected Behavior**  
When calling `Neutralino.filesystem.readFile` for a file that does not exist, it should call the error function immediately.
  
**Actual Behavior**  
The CPU goes to 100% for a while, and it seems to consume gigabytes of RAM, looking at `top`. When RAM is full, it crashes (in `browser` mode it already crashes after a few seconds, but in `window` mode it takes very long, consuming more and more RAM).

**Steps to Reproduce the Problem**  
 1. Download the example ready-to-run neutralino zip-file
 2. Modify app.js, and add for example: `Neutralino.filesystem.readFile('aeouaoe', alert, alert);`
 3. Run the neutralino-linux executable

**Specifications**  
* NeutralinoJs Version: v1.2.0
* Platform: Arch Linux (x64)

**Comment by kasvith** [comment]
This will be fixed in the next major release, we are working on a unified codebase and this will be addressed there.

The reason is a problem in exception handling, will be fixed soon

**Comment by haroflow** [comment]
I think this also happens when I run the linux binary from outside the folder:
```code
~/dev$ teste-neutralino/neutralino-linux
```
NeutralinoJs 1.2.0
Linux Mint 19.3 Cinnamon

**Comment by shalithasuranga** [comment]
For now it will send empty content with requested MIME type.. maybe it should generate some logs also.. Later when we add some promises support or when we improve error handling we could see file not found errors etc I guess
