### ISSUE TITLE
how to support armhf？

### ISSUE THREAD

**Issue by p0nley** [neutralinojs/neutralinojs#193]
I want run it on raspi bu it not works

**Comment by shalithasuranga** [comment]
Hi.. @p0nley  you tried on arm64?

**Comment by k1r0s** [comment]
It doesn't work on rasp. I've tried the hello world sample

Linux DietPi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

**Comment by shalithasuranga** [comment]
Hey.. Neutralinojs's next release will work on Raspberry PI 32-bit machines. We will add 64-bit arm support via https://github.com/neutralinojs/neutralinojs/issues/593 in a future release.
