### ISSUE TITLE
"Privileges" is misspelled across the codebase

### ISSUE THREAD

**Issue by hrn4n** [neutralinojs/neutralinojs#194]
Super minor stuff, a quick search https://github.com/neutralinojs/neutralinojs/search?q=previleges&unscoped_q=previleges reveals that the word "privileges" is consistently misspelled across the codebase.

This is something that can probably be fixed with a simple bash command, I could try and submit  a PR for this if you'd like :smile:

**Comment by shalithasuranga** [comment]
@hrn4n . Thanks for letting us know. Since you are interested to work on it, hope you will contribute to fix this :+1:

**Comment by hrn4n** [comment]
Opened a PR: #195 

Very simple changes, tested by re-compiling neutralino on Linux (Ubuntu 18.04)

**Comment by shalithasuranga** [comment]
Merged.. Thanks 👍
