### ISSUE TITLE
Introduce Neutralino.app.exit()

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#200]

**Comment by shalithasuranga** [comment]
Added to Linux

**Comment by shalithasuranga** [comment]
Added to Windows too only mac os is pending

**Comment by shalithasuranga** [comment]
@alphagamer7  Could you add for macos ?

**Comment by calumk** [comment]
Thanks for your work on this @shalithasuranga 

However I am unable to get it to work
Downloaded new binary, (and tried to build from source)
but **Neutralino.app.exit() ** - fails to terminate the running application.

**Comment by shalithasuranga** [comment]
@calumk  Could you check with the latest release. it worked for me

**Comment by calumk** [comment]
@shalithasuranga - great Working with 1.3.0 release
