### ISSUE TITLE
Debugging in window mode

### ISSUE THREAD

**Issue by exside** [neutralinojs/neutralinojs#208]
**Expected Behavior**  
We need a way of debugging the app in window mode.
  
**Actual Behavior**  
Couldn't find a way to debug the app in window mode (I basically need to open the inspector/dev tools within window mode), which is desperately needed as many features that are available in browser mode are not working in window mode, but I'm basically blind in regards of what's going wrong as I can't see the console errors.

**Steps to Reproduce the Problem**  
 1. For example, try to use HTML5 geoLocation API or Notifications API in your app
 2. Test it in browser mode, it works
 3. Switch to window mode, it doesn't work

**Specifications**  
* NeutralinoJs Version: latest (with mac-os build capability)
* Platform: OS X

**Comment by jjgh** [comment]
I'm in the same situation, I'm using some jquery functions which are not working in the window but are working in the browser.

**Comment by shalithasuranga** [comment]
Please check the latest version. You can use `enableInspector: true` to get devtools enabled in the window mode.
