### ISSUE TITLE
Image won't load.

### ISSUE THREAD

**Issue by Singha360** [neutralinojs/neutralinojs#212]
I made a simple app with an image embedded in the html file. The img src=""  line points to the path of the image file "/assets/imgs/filename.jpg". For some reason the image file won't show up. I've tried changing to browser in the settings.json but with no success. I know everything works because I've tried my app on a live server without Neutralino. 

Is images not supported yet?

**Specifications**  
* NeutralinoJs Version: [1.2.0]
* Platform: [Linux Ubuntu 19.10]

**Comment by shalithasuranga** [comment]
Currently neutralino will not support binary reads. So only text files (html, css etc) will work. There are issues referring this problem. But we always can use base64 version of the image as in neutralino vue template.

**Comment by shalithasuranga** [comment]
v1.4.0 supports images
