### ISSUE TITLE
[FEAT.REQ.] A plugin system, and how?

### ISSUE THREAD

**Issue by apollolux** [neutralinojs/neutralinojs#213]
Hello! I know there was a brief mention of an add-on system similar to Node being a good idea [in this issue](https://github.com/neutralinojs/neutralinojs/issues/155) . What would be more reasonable to expect if this were implemented, exposing some plugin API that encompasses "all possible cases" to the JS side or having plugin devs write DLLs/libs that would expose functionality to the JS side on a per-plugin basis? Or even better, if it ends up that Chromium becomes the default webview on all versions of Neutralino would Chromium extension APIs be available to us as well or is that limited to full-on direct implementations of Chromium?

I know that while Neutralino using other webviews on Windows is still being worked out that Windows users like myself have to settle with IE11 webview + polyfills if we use binary releases like v1.2.0, which also means that the more mature implementations of some newer web APIs like Web Audio might not be fully available to use natively. Exposing more system I/O like audio and probably using (sandboxed, probably) plugins would be groovy.

**Comment by kasvith** [comment]
Our initial plan was to introduce `LibUV` which is the core of NodeJS to the neutralino. This allow us to load libraries in a generic way. To bind it with JS we can provide some glue code to the webview since we don't manage a JS runtime like Node

Shipping chrome is a good idea though, it allow us to use cutting edge web technologies. But that will increase the size of the binary around by 40~90MB

**Comment by apollolux** [comment]
I'm not necessarily advocating for including full-on Chrome/Chromium; Electron and a couple of others already do that and part of why I like Neutralino is how small its final package can be. I was more curious as to how to force using EdgeHTML or Edge Chromium-based webviews on Windows that have them, or if packaging CEF rather than Chromium might be an acceptable trade-off of size vs functionality.

I'd much rather see LibUV, though, to add the potential of Node module integration somehow.

**Comment by kasvith** [comment]
we can go for EdgeHTML on `webview-x` release. But AFAIK it will be still limited IMHO, CEP has more potential over IPC and we will still have to find a way to do system calls that take a long time to complete. Maybe using WebSockets or a similar thing

**Comment by apollolux** [comment]
I like the idea of WebSockets for system calls, but ideally it would also provide some sort of progress indicator or readystate listening or something like that for calls that take time but don't necessarily return anything until the end.

**Comment by kasvith** [comment]
I think it could be done similar to Electron IPC

**Comment by shalithasuranga** [comment]
Thank all for the awesome ideas.. This issue is closed because of https://github.com/neutralinojs/neutralinojs/issues/459
Please check more about API extensions: https://github.com/neutralinojs/proposals
