### ISSUE TITLE
MS Edge WebView2 (developer preview)

### ISSUE THREAD

**Issue by trinione** [neutralinojs/neutralinojs#220]
Good day,
Saw your comment on your GSOC page about Project Idea neutralinojs/neutralinojs.github.io#2. Microsoft Edge integration, and thought this page that I came across sometime ago would be helpful.

https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2

Microsoft Edge WebView2 (developer preview)   
The Microsoft Edge WebView2 control enables you to host web content in your application using Microsoft Edge (Chromium) as the rendering engine.

**Comment by ghaspias** [comment]
WebviewJar,the java wrapper for webview, is alreading using Edge, but it seems to have some issues. But if Edge is not working, I'd rather have WebkitGTK on windows than IE...

**Comment by dvergeylen** [comment]
> Hey.. Thanks for the finding. We are currently using https://github.com/zserge/webview for rendering across platforms it looks like they have added edge support. Sounds cool if we can use MSHTML for older windows, and Edge/Chromium if conditionally for latest windows

I'm afraid the plan is to drop MSHTML support, although there is a discussion ongoing: https://github.com/webview/webview/issues/305

**Comment by shalithasuranga** [comment]
Closing this because the latest version already uses EdgeChromium/HTML on Windows. MSHTML is no longer supported.
