### ISSUE TITLE
Support for Serial Port? (feature-request)

### ISSUE THREAD

**Issue by AfdhalAtiffTan** [neutralinojs/neutralinojs#221]
Is native Serial Port access possible in Neutralinojs? If not, is there any workaround?

**Comment by shalithasuranga** [comment]
Hey.. I am closing this because this can be done with a Neutralinojs extension (can be written with any language). Please check https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension for an example. Thanks for reporting the issue
