### ISSUE TITLE
Starter project for Kotlin

### ISSUE THREAD

**Issue by androidovshchik** [neutralinojs/neutralinojs#225]
Hello
I wrote a starter for Kotlin
If you want, you can add to your project
I think it's good to support such a language too
https://github.com/androidovshchik/neutralinojs-kotlin

**Comment by shalithasuranga** [comment]
@androidovshchik  Awesome work. I tried it and worked nicely. Could you please make a PR to https://github.com/neutralinojs/neutralinojs-kotlin
Then I will check how we could add this to neu cli

**Comment by androidovshchik** [comment]
@shalithasuranga Thanks. What about the fork?

**Comment by shalithasuranga** [comment]
Thanks it's imported now.. I will check and update cli accordingly
