### ISSUE TITLE
Discussion: accessing detached UI thread object from javascript API 

### ISSUE THREAD

**Issue by momozor** [neutralinojs/neutralinojs#231]
**Expected Behavior**  
Description about what should be the expected behavior of the framework.

Currently, I see there is no way to access the running UI thread data from the core/ api. Making this a possibility will enable ways for the framework users to manipulate the UI (minimise, changing size, transparency, theming, web inspector, etc) at runtime via the JS api.

At this point, issues like #142, #218, #165, #131 cannot be resolved yet because of this.

Declaring globals or creating a singleton access point might work, but I'm not sure how exactly this gonna turn out to be. Do you guys already have any strategy on approaching this issue?

This is my experimentation on Linux (which doesn't work, but hopefully makes sense for others to know what I'm trying to do here)

### View.h (non thread-safe singleton global accesspoint)
```c++
// View.h
#include "webview.h"

class View
{
protected:
	struct webview _webview;
public:
	static View* getInstance();
	struct webview get_webview() { return _webview; }
	
private:
	View(){};
	View(View const&){};
	View& operator=(View const&){};
	static View* p_instance;
	
};

View* View::p_instance = nullptr;

View* View::getInstance()
{
	if (!View::p_instance)
		View::p_instance = new View;
	
	return View::p_instance;
}

```

### main.cpp
```c++
// main.cpp
// ..
#include "View.h"

void uiThread(std::string appname, int port, int width, int height,
              int fullscreen, bool always_on_top, std::string iconfile,
              int debug) {
// ...
// ..
        string url = ("http://localhost:" + std::to_string(port) + "/" + appname);

        // using the global singleton
        struct webview webview = View::getInstance()->get_webview();

        memset(&webview, 0, sizeof(webview));
        webview.title = appname.c_str();
        webview.url = url.c_str();
        webview.width = width;
        webview.height = height;
       //..
}
```

### core/app/app.h (webview window minimization implementation as an example)
> Note, that I already implemented the Javascript minimise api in Neutralino.js codebase but I won't share it here because they are working fine however, irrelevant to this issue.
```c++

//..

namespace app {

    string exit(string jso); 
    string minimise(string jso);

    typedef string (*pfunc)(string);

    map <string, pfunc> funcmap = {
        {"app.exit", app::exit},
	{"app.minimise", app::minimise}
    };
}


```

### core/app/app.cpp
```c++
#include "View.h"

        //..
        //..
	string minimise(string jso)
	{       
		json input;
		json output;
		
		try {
			input = json::parse(jso);
		}
		catch(exception e){
			output["error"] = "JSON parse error is occurred!";
			return output.dump();
		}
                
                // doesn't work
                // this return a new webview object
                // instead of using the same webview object returned in main.cpp
		struct webview win = View::getInstance()->get_webview();

                // got warning where win.priv.window is not GTK_WINDOW type
                // at runtime
		gtk_window_iconify(GTK_WINDOW(win.priv.window));
		
               // actually returns 0
		output["value"] = std::to_string(win.width);
		
		return output.dump();
	}
```

**Specifications**  
* NeutralinoJs Version: 1.3.x
* Platform: Linux, MacOS, maybe Windows too

**Comment by shalithasuranga** [comment]
Thanks for experimenting with a nice implementation. Please check the `api/window/window.cpp` file's `setTitle` method. But it will not support multiple instances and we don't support multiple windows yet.
