### ISSUE TITLE
Is there any way to run external EXE file?

### ISSUE THREAD

**Issue by dehghani-mehdi** [neutralinojs/neutralinojs#234]
I know there is no node runtime available, but I'm wondering is there any way to run external exe file?

**Comment by shalithasuranga** [comment]
Yeah you could use `os.runCommand` https://neutralino.js.org/docs/#/api/os?id=osruncommandstring-command-function-successdata-function-error

**Comment by dehghani-mehdi** [comment]
Interesting.

Another question, when `mode: "window"`, Is there any way to run the app using Firefox, then Chrome and the the best browser of all time, Edge?

**Comment by momozor** [comment]
@dehghani-mehdi Does it (the neutralino program) shows any error when you tried to execute an exe file?

**Comment by dehghani-mehdi** [comment]
@momozor no. it doesn't do anything. I added a log to the first callback of `runCommand` method and it print nothing.

**Comment by patarapolw** [comment]
I tried running `pwd`, and it seems that I get `$HOME`. I cannot find a way to get the app server path.

**Comment by sinedie** [comment]
Hey there. It worked for me in windows. The thing is getting the path, maybe running "CD" or opening a dialogBox... hope it help you.
```
function executeExe() {
    Neutralino.os.runCommand("start C:/Users/XXXX/Downloads/test.exe", 
        function (data) {
            console.log(data);
        },
        function () {
            console.error('error');
        }
    );
}
```

**Comment by masoudahmadvand** [comment]
make a new text file in the app server path .
---------------- copy this text in the text file----------------------
@ECHO OFF 

:: get current ip 
Title Get IP and MAC Address
@for /f "delims=[] tokens=2" %%a in ('ping -4 -n 1 %ComputerName% ^| findstr [') do (
    set "MY_IP=%%a"
)
:: get current mac
@For /f %%a in ('getmac /NH /FO Table') do  (
    @For /f %%b in ('echo %%a') do (
        If /I NOT "%%b"=="N/A" (
            Set "MY_MAC=%%b"
        )
    )
)

:: get current path
SET "APPpath=%~dp0"

:: get current getway
set "getway="
for /f "tokens=1-2 delims=:" %%a in ('ipconfig^|find "Default"') do if not defined ip set getway=%%b

:: get operation system
SET "OS="
FOR /F "skip=1 tokens=*" %%a IN ('WMIC OS GET CAPTION') DO IF NOT DEFINED OS SET OS=%%a

:: get drive liast
set "drives=["
For /F "Skip=1 Delims=:" %%A In ('WMIC LogicalDisk Get Caption') Do call set "drives=%%drives%%"%%A","  


:: make info file
echo {"path":"%APPpath:\=/%","ip":"%MY_IP%","mac":"%MY_MAC%","getway":"%getway: =%","os":"%OS:  =%","localDisk":%drives:,"",=%]} >  info.json


START %APPpath%neutralino-win.exe

EXIT

-----------------------------------------------------------

change the text file suffix to .bat .
run the bat file .
now you have a info.json file in the server folder .
read the file with -> Neutralino.filesystem.readFile('info.json',
  function (data) {
    console.log(JSON.parse(data.content));
  },
  function () {
    console.error('error');
  }
);
in the file there is the path of your app .its mean you can have your exe file path in your app
put your exe file in your application folder and call it with os.runCommand();

**Comment by shalithasuranga** [comment]
Closing this since os.runCommand can be used to execute any executable. As @patarapolw  mentioned `NL_CWD` looks nice to me too.. We can add it to all platforms
