### ISSUE TITLE
Webfont and Image Serve Support

### ISSUE THREAD

**Issue by cagrig** [neutralinojs/neutralinojs#239]
## Description
Binary file serving capability has been added to neutralinojs. Some mime types are added router in order to make neutralinojs to handle with related types of requests. A PR created for this improvement. If it is approved; you can use webfont, jpg/jpeg, png, gif, svg and ico files in your project hereafter.

## Changes proposed
 - woff2 file extension (mime type: font/woff2) added (webfonts support)
 - jpeg/jpg  file extensions (mime type: image/jpeg) added (image support)
 - png  file extension (mime type: image/png) added (image/favicon support)
 - svg  file extensions (mime type: image/svg+xml) added (webfont, vector graphics support)
 - gif file extensions (mime type: image/gif) added (image support)
 - ico  file extensions (mime type: image/icon) added (image/favicon support)

`getFileContentBinary` function has been added to "settings.cpp". The function reads binary file and returns its content.

## How to test it
 - Binary file streaming has been tested on both Windows & Linux
 - Currently, it cannot be tested on MacOS.
 - To test how the things are shown, following changes are made in _index.html_

1. Following line is added to head. (favicon test)
`<link rel="icon" href="/assets/favicon.ico" type="image/x-icon">`

2. Following lines are added to body. (image types test)

> `<img src="/assets/ex.jpg"/>
>  <img src="/assets/ex.png"/>
>  <img src="/assets/ex.gif"/>
>  <img src="/assets/ex.svg"/>`

3. woff2 font type is added to css via "@font-face".

## Next steps
Various mime types/file extensions (ttf, eot, woff, xls, etc.) can be added in similar way when required.

## Notes
 - MacOS support could not be done. Binary file reader function was remained as empty string return. MacOS experienced developers can easily adapt codes from linux/windows versions, and test the code.

**Comment by shalithasuranga** [comment]
Added for macos as well
