### ISSUE TITLE
Test neutralino on several os versions

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#24]
Neuralino needs to be tested in several versions of os

eg : Windows 7, Vista, 8, 8.1  and Ubuntu old versions , and the latest version.

**Comment by shalithasuranga** [comment]
Since there are lot of os needs to be tested we wait for users and also we open a thread in forum

**Comment by Deilan** [comment]
So does it work on Windows 7, Windows 8, Windows 8.1?

**Comment by amitgithub1** [comment]
does not work on windows 8.1
setprocessdpiawarenesscontext not found in user32, which is only in windows 10

**Comment by shalithasuranga** [comment]
Hm yeah.. there are some issues with Windows 8.1 and lower versions. We need to support Windows 7 too. We've created this issue https://github.com/neutralinojs/neutralinojs/issues/486 to solve these problems. Thanks for checking :+1:

**Comment by aianshume** [comment]
hi, its works on ubuntu 16.04 32bit and 64bit systems

**Comment by shalithasuranga** [comment]
Hey.. great.. Thanks for checking @aianshume
