### ISSUE TITLE
[1.3] dyld: Symbol not found error on macOS

### ISSUE THREAD

**Issue by vladshcherbin** [neutralinojs/neutralinojs#245]
**Expected Behavior**  
Start app without errors.
  
**Actual Behavior**
Simple app from tutorial gives an error after `neutralino-mac` execution from SDK archive:

![image](https://user-images.githubusercontent.com/6711845/76660865-f9db1c00-658a-11ea-98a8-7095d352bc5d.png)

Happens with 1.3 version. I've also tested 1.2 and the app starts without errors. I can create a reproduction repo if needed.

**Steps to Reproduce the Problem**  
 1. Setup project from tutorial
 2. Execute neutralino-mac 1.3 from SDK on mac os 10.14.6

**Specifications**  
* NeutralinoJs Version: 1.3
* Platform: macOS Mojave 10.14.6

**Comment by momozor** [comment]
probably something to do with the experimental filesystem feature

**Comment by momozor** [comment]
Try this patch 

```
--- CMakeLists.txt      2020-03-14 07:26:12.260006232 +0800
+++ CMakeLists.txt.new  2020-03-14 07:26:46.408006538 +0800
@@ -23,6 +23,7 @@
add_subdirectory(src/cloud)
add_subdirectory(src/platform/fd)

+target_link_libraries(neutralino stdc++fs)
target_link_libraries(neutralino core)
target_link_libraries(neutralino auth)
target_link_libraries(neutralino ping)
```

PS:  Just patch the `neutralinojs/core-macos/CMakeLists.txt` file with attached patch below.

[CMakeLists.txt.patch.txt](https://github.com/neutralinojs/neutralinojs/files/4331963/CMakeLists.txt.patch.txt)

**Comment by vladshcherbin** [comment]
@momozor I've tried to rebuild using `bash build.sh macos` before and after patch, it gives me this error all the time:

![image](https://user-images.githubusercontent.com/6711845/76677892-69312a00-65e4-11ea-9df5-cfceb490408c.png)

**Comment by momozor** [comment]
Hmm. May I know the compiler and version of the compiler you are using?

**Comment by vladshcherbin** [comment]
@momozor sure, I believe it's this one:

![image](https://user-images.githubusercontent.com/6711845/76688573-0faa1900-663f-11ea-8482-387e3ff551f8.png)

I also found someone else had this error in [hacker news post](https://news.ycombinator.com/item?id=22424346).

**Comment by momozor** [comment]
Ah. Clang 10. I'm not sure if Clang 10 on Mac comes with filesystem feature just yet. Anyway, using xcode compiler as specified in the requirement section in the project README should fix the problem for now (hopefully).

But you gotta build it manually.
PS: change the path compiler to your actual xcode compiler

```sh
cd neutralinojs/core-macos; rm -rf build; cd build; cmake -DCMAKE_C_COMPILER=/path/to/xcode-compiler -DCMAKE_CXX_COMPILER=/path/to/xcode-compiler ..; make
```

If above works, then I'll send a new PR to use xcode compiler by default on macos (or you could do that too, if you want).

**Comment by momozor** [comment]
@shalithasuranga Since some of these platforms still labeling filesystem as an experimental (or don't come with it at all) feature, I think implementing a fallback is a good idea to maximize portability.

https://github.com/gulrak/filesystem

**Comment by shalithasuranga** [comment]
@momozor  Do you think it's up to them to use latest compiler ?

**Comment by momozor** [comment]
@shalithasuranga I'm not sure.

**Comment by shalithasuranga** [comment]
@vladshcherbin  Could you please post output of `gcc --version`

**Comment by vladshcherbin** [comment]
@shalithasuranga sure:

![image](https://user-images.githubusercontent.com/6711845/76729195-99560580-6769-11ea-930c-79a338737987.png)

**Comment by prathyvsh** [comment]
Bumped into the same error on Mac 10.13. Tried updating gcc and clang and still gets that symbol error after compilation asking for upgrade to 10.15

**Comment by shalithasuranga** [comment]
Closing this since now the latest version's compilation process uses an earlier minimum OS version via `MACOSX_DEPLOYMENT_TARGET=10.7` Thanks :tada:
