### ISSUE TITLE
Add borderless mode to Windows version

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#248]

**Comment by apollolux** [comment]
A reminder that if borderless successfully hits the Windows version that we'd need to confirm that whatever engine webview decides to use supports setting elements as draggable (to move & resize the window), the basic titlebar functions can be called programmatically (to attach to custom buttons and such), and the borderless window can still somehow be resized/resizable. Most Chromium-based programs seem to set the CSS property `-webkit-app-region` to accomplish window move, but I don't think MSHTML-IE has an `-ms-` equivalent in CSS at least.

**Comment by ainar** [comment]
> 
> 
> A reminder that if borderless successfully hits the Windows version that we'd need to confirm that whatever engine webview decides to use supports setting elements as draggable (to move & resize the window), the basic titlebar functions can be called programmatically (to attach to custom buttons and such), and the borderless window can still somehow be resized/resizable. Most Chromium-based programs seem to set the CSS property `-webkit-app-region` to accomplish window move, but I don't think MSHTML-IE has an `-ms-` equivalent in CSS at least.

It seems that -webkit-app-region is implemented in Electron and not Chromium. So we should implement it along WINAPI, and it should be possible. https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest
Otherwise we could implement it in Javascript, in app.

**Comment by shalithasuranga** [comment]
borderless mode is added but I guess we can think about moving window a bit later
