### ISSUE TITLE
support multiple window?

### ISSUE THREAD

**Issue by dingchaoyan1983** [neutralinojs/neutralinojs#249]
**Expected Behavior**  
Description about what should be the expected behavior of the framework.
  
**Actual Behavior**  
Description about how the framework is actually behaving and deviating from the expected behavior. 

**Steps to Reproduce the Problem**  
 1. List the steps to reproduce the problem
 2. Step 2
 3. Step 3

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework]
* Platform: [Platform specifications]

**Comment by holmesadrianh** [comment]
I assume the description was not updated. However, the title is still relevant to me. Does Neutralino support multiple windows? This is a deciding factor for me. If it does them I would really be keen to port my existing Vue based Electron app to Neutralino. I would really like to make the app more compact and so far Neutralino seems to be promising.

**Comment by jaswafford1211** [comment]
> I assume the description was not updated. However, the title is still relevant to me. Does Neutralino support multiple windows? This is a deciding factor for me. If it does them I would really be keen to port my existing Vue based Electron app to Neutralino. I would really like to make the app more compact and so far Neutralino seems to be promising.

I can tell you it may be worth moving because of the bloat Electron has. Electron needs a couple of thousand dependency packages while NeutralinoJs needs like 8.

Not to mention, making executables is easy with only one command. Electron required you to pick only one OS per build command.

**Comment by rastographics** [comment]
@shalithasuranga excited to see multi-window support....will you also be able to add some function to the window namespace that will allow programmatically moving windows to different displays (in multi-monitor scenario?)

**Comment by shalithasuranga** [comment]
This is implemented on all supported platforms but will be released with the next version. Now we can create new windows from a Neutralinojs app via `Neutralino.window.create`, as shown in the following example.

```js
Neutralino.window.create("/resources/aboutScreen.html", {
   title: "About my awesome app",
   alwaysOnTop: true,
   width: 500,
   height: 300,
  ...
 ...
 ....
  processArgs: "--window-id=ABOUT"
})
```

**Comment by extorc** [comment]
> This is implemented on all supported platforms but will be released with the next version. Now we can create new windows > 
 from a Neutralinojs app via `Neutralino.window.create`

Is this already implemented? @shalithasuranga

**Comment by shalithasuranga** [comment]
Hey.. @extorc  yeah.. you can check Docs here: https://neutralino.js.org/docs/api/window#windowcreateurl-windowoptions :)
