### ISSUE TITLE
No Iframe Support

### ISSUE THREAD

**Issue by LiveUser** [neutralinojs/neutralinojs#250]
## Problem
App fails to load when I add an Iframe to the html.
--------------------------------------------------------------------------------------------------
## Feature Request
Also it would be nice to have access to neutralino functions from the iframe

**Comment by shalithasuranga** [comment]
Hey.. Please try the latest version. it works.

I did small experiment, as shown below.

app.html
```html
<button onclick="(async () => {console.log((await window.parent.Neutralino.app.getConfig()).config);})()">test</button>
```

index.html
```
<iframe src="app.html"></iframe>
```

Make sure to call `Neutralino` as `window.parent.Neutralino` from iframe's html.
