### ISSUE TITLE
Neutralinojs v1.3.0 doesn't work on the browser

### ISSUE THREAD

**Issue by leliamesteban** [neutralinojs/neutralinojs#251]
**Expected Behavior** 
Installing the latest release of neutralino and changing the mode in settings.json to browser according to the documentation should output something on the console and respond to requests at the port specified.
  
**Actual Behavior**  
Nothing appears on the console when I run `./neutralino-linux`. `curl localhost:8080`
(the port specified in `settings-browser.json`) returns `curl: (7) Failed to connect to localhost port 8080: Connection refused`. Loading localhost:8080 on a web browser says Unable to connect. Pressing C-c once doesn't kill the app. Pressing it twice does

It works fine if the mode is window.

**Steps to Reproduce the Problem**  
 1. wget https://sourceforge.net/projects/neutralinojs/files/v1.3.0/neutralinojs-v1.3.0.zip/download
 2. unzip download
 3. edit app/settings.json to change mode to browser
 4. ./neutralino-linux

**Specifications**  
* NeutralinoJs Version: 1.3.0
* Platform: Bedrock linux

**Comment by leliamesteban** [comment]
The same happens with version 1.2.0

**Comment by shalithasuranga** [comment]
Closed since there is no issue with the latest version.
