### ISSUE TITLE
 Can you import libraries (js, css) from the system to share between different apps?

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#252]
**Expected Behavior**  

The idea would be to install, for example bootstrap, and that all my apps consume the same instance, or even generate themes so that all apps change depending on what is chosen.

**Specifications**  

* NeutralinoJs Version: 1.0.8
* Platform: Linux

**Comment by shalithasuranga** [comment]
Hey @JoaquinDecima  sorry for the late reply. Thanks for trying Neutralinojs. Regarding your question, we would like to isolate each Neutralinojs app as much as possible to avoid security issues. For example, each app makes native requests to the server using a unique `NL_TOKEN`. Therefore, for security, we would recommend keeping all app resources isolated. 

However, if you need to have a shared template or library like thing, you can create an npm package for it :)
