### ISSUE TITLE
Open Dialog: Possible memory leak on cancel (Windows)

### ISSUE THREAD

**Issue by sinedie** [neutralinojs/neutralinojs#253]
Hey, I'm in the middle of develop an app where the progress in saved into .json files. I really want to migrate from electron for the memory usage and size that Neutralinojs provides.

For opening the project i'm using open dialog and saving the object of the .json file to the RAM. But when i cancel the open dialog memory usage goes from 15Mb to 1GB+. Any help?

```
function createNewProject() {
    Neutralino.os.dialogOpen("Select project...",
        function(data) { loadProject(data.file) },
        function() { console.error("Error on load"); }
    );
}
```

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting the issue. This will happen with window mode or browser mode? and this issue will come out always ?

**Comment by sinedie** [comment]
Both. But I manage to fix it.

When hit cancel in `dialogOpen`, `data.file` is an empty string and seems like the function to load the proyect (that calls `Neutralino.filesystem.readFile()`) keeps running and create a memory leak. Not sure why yet.

Here is the _solution_
 
```
function createNewProject() {
    Neutralino.os.dialogOpen("Select project...",
        function(data) { if (data.file.length) { loadProject(data.file) } },
        function() { console.error("Error on load"); }
    );
}
```
