### ISSUE TITLE
Working Directory of Server

### ISSUE THREAD

**Issue by DSanborn** [neutralinojs/neutralinojs#258]
Not sure if this is a bug or user error, but the working directory of the server is the working directory of the shell, not where the executable is located. Rather frustrating that there is no cli help functions and didn't see this in the documentation, spent countless hours on this. Take for instance my launch.json from VS Code:
```
    "debug": "webpack -d --config webpack.config.js && ./dist/neutralino-linux", // DOES NOT WORK
    "debug": "webpack -d --config webpack.config.js && cd ./dist && ./neutralino-linux", // WORKS
```
Or shell commands:

```
[user@myapp]$ ./dist/neutralino-linux", // DOES NOT WORK
[user@dist]$ ./neutralino-linux", // WORKS
```

**Comment by shalithasuranga** [comment]
Please check the latest version. Now Neutralinojs can be launched from any directory.
