### ISSUE TITLE
Path Resolution for neutralino.js is confusing

### ISSUE THREAD

**Issue by DSanborn** [neutralinojs/neutralinojs#259]
The obfuscation of neutralino.js's filepath in index.html is extremely confusing to understand when learning this framework. It's initially unclear why the developers chose to omit the the `asset/` directory when loading this script, but did the opposite for `assets/app.css` and `assets/app.js` for their templates and examples.

```
    <link rel="stylesheet" href="/assets/app.css">
    <script src="/neutralino.js"></script>
    <script src="/assets/app.js"></script>
```
https://github.com/neutralinojs/neutralinojs-typescript/blob/master/app/index.html

The only reason that I could think of was that the relative path was hardcoded, and indeed it is.

```
namespace routes {

    string getClientJs() {
        return settings::getFileContent("app/assets/neutralino.js");
    }
}
```
https://github.com/neutralinojs/neutralinojs/blob/master/core-linux/src/router.cpp

Despite the documentation regarding the file structure, I found that the obfuscation muddied the waters when it came time to configure webpack, ts-loader, and VS Code. From my experience the following two things can be done to make this easier on newbies:
**1) Keep your path resolution logic harmonious, don't have a one-off logic flow just for discovering neutralino.js.**
2) In the documentation, note what files must be static versus what can be modified. For instance, it's my understanding that I can change the names of app.css and app.js and still have a working application (given that I update my references).

```
├── app
|  ├── assets
|  |  ├── app.css
|  |  ├── app.js
|  |  └── neutralino.js
|  ├── index.html
|  └── settings.json
└── neutralino-win.exe
└── neutralino-linux
└── neutralino-mac
└── storage
```

https://neutralino.js.org/docs/#/gettingstarted/quickstart

**Comment by patarapolw** [comment]
As far as I understand, `assets` folder cannot be renamed as well.

I think here is typo? https://neutralino.js.org/docs/#/gettingstarted/firstapp?id=step-3-develop-app-functions

**Comment by dvergeylen** [comment]
Hardcoding relative paths (e.g in `src/settings.cpp`) makes it also impossible for `neutralino` to be called from an arbitrary location.

We'd need an `NL_BINPATH` (path of called executable) or something to open files relatively from. There seems to be [no cross platform way](https://stackoverflow.com/q/1528298) to do so, though.

**Comment by dvergeylen** [comment]
Since the project [is compiled against `-std=c++17`](https://github.com/neutralinojs/neutralinojs/blob/2cac11cb131a397cdcd93c75f57eb57db61b06ba/core-linux/build.sh#L29), there is actually an easy way to do it, with `<filesystem>`:.

##### On Linux (tested against g++ (Debian 10.2.1-3) 10.2.1):
Using `std::filesystem::canonical("my_path")`.
```cpp
#include <iostream>
#include <filesystem>

int main(int /*argc*/, char** /*argv*/) {
  const std::string linux_binpath = "/proc/self/exe";

  if (std::filesystem::exists(linux_binpath)) {
    std::cout << std::filesystem::canonical(linux_binpath) << std::endl;
  }
  return 0;
}
```

```bash
# Testing
g++ -Wall -Werror -Wextra --std=c++17 main.cpp
./a.out
# Outputs: "/tmp/a.out"
```

##### On Windows (I can't test):
I would call [`getModuleFilenameA()`](https://docs.microsoft.com/fr-be/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea) and use its returned string as `std::filesystem::path`'s constructor input (`const std::filesystem::path windows_binpath(/* result of getModuleFilenameA() */);`). I would then call `windows_binpath.parent_path()` or something 🤔.

**Comment by shalithasuranga** [comment]
Hey all.. Please check the [v2 documentation](https://neutralino.js.org/docs/developer-environment/project-structure).
Now Neutralinojs server behaves like any other static file server. There are no fixed and hardcoded paths anymore.
