### ISSUE TITLE
Unable to create directory

### ISSUE THREAD

**Issue by ledavid993** [neutralinojs/neutralinojs#260]
**Expected Behavior**  
Create a directory 'abcd' in project root
  
**Actual Behavior**  
Multiple errors shown in chrome console

```
error @ app.js
Failed to load resource: net::ERR_EMPTY_RESPONSE
Failed to load resource: net::ERR_CONNTECTION_RESET
GET http://localhost:5006/ping net::ERR_CONNECTION_REFUSED
```

**Steps to Reproduce the Problem**  
 1. neu create myapp --template ts
 2. in src/app-core/app-core/lib and call it

```
export class AppLib {
  public createDirectory(): void {
    Neutralino.filesystem.createDirectory(
      "abcd",
      function (data: any) {
        console.log(data);
      },
      function () {
        console.error("error");
      }
    );
  }
}
```
**Specifications**  
* NeutralinoJs Version: 1.3.0
* Platform: Ubuntu 18.04

**Comment by shalithasuranga** [comment]
@ledavid993  I guess you ran `neu build` after modification of code?

**Comment by shalithasuranga** [comment]
Closing this since looks neutralino process looks stopped
