### ISSUE TITLE
Slack Invite is no longer active

### ISSUE THREAD

**Issue by Zenahr** [neutralinojs/neutralinojs#263]
Hey guys, the slack link is broken. Is that intended?

https://github.com/neutralinojs/neutralinojs#realtime-chat-room---slack

**Comment by shalithasuranga** [comment]
Thanks for reporting.. Updated with the latest link https://join.slack.com/t/neutralinojs/shared_invite/zt-b7mbivj5-pKpO6U5drmeT68vKD_pc6w
