### ISSUE TITLE
HELP ME IM BEGINNER

### ISSUE THREAD

**Issue by GetRektBoy724** [neutralinojs/neutralinojs#264]
How to make a html that contain neutralinojs script that execute command on client browser...sorry im beginner to javascript...if it use neutralino.os.runcommand() , pls give me example of the code

**Comment by input-variable** [comment]
What do you mean by "executing a command on the client's browser"?

**Comment by GetRektBoy724** [comment]
I mean executing command on the client's computer

**Comment by Dugnist** [comment]
https://github.com/Dugnist/Platform
Maybe try my example. But I use Svelte.js as a framework. It easy to learn.

**Comment by input-variable** [comment]
I think you mean on the client's PC under the NJS App and not their browser. 
Try this from the docs:
```
Neutralino.os.runCommand('help', 
  function (data) {
    console.log(data);
  },
  function () {
    console.error('error');
  }
);
```

**Comment by GetRektBoy724** [comment]
ohh ok thx

**Comment by GetRektBoy724** [comment]
y'know...im really a beginner

**Comment by shalithasuranga** [comment]
Hey.. I am closing this since the question has been answered already.
