### ISSUE TITLE
Multiple windows and Angular template

### ISSUE THREAD

**Issue by parliament718** [neutralinojs/neutralinojs#266]
This looks like a great project!

Im looking for an alternative for my Electron app that will be more lightweight/faster.

My app needs to spawn a window in a separate process and communicate with it. 
Is this possible? The only relevant thing I see in the docs is openDialog but it's not clear what it does.

Also, when will the Angular (not AngularJS) template be available?

Thanks

**Comment by holmesadrianh** [comment]
I would like to know as well, does Neutralino support multiple windows?

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this issue. Please check https://www.youtube.com/watch?v=TreJXBarK6k for making Angular-based Neutralino apps. And I will close this one since we will add multi-window support soon via one of previous issue https://github.com/neutralinojs/neutralinojs/issues/249
