### ISSUE TITLE
[Question] WebRTC support & underlying rendering engine

### ISSUE THREAD

**Issue by innerop** [neutralinojs/neutralinojs#270]
WebRTC requires HTTPS or use of "localhost" serving URL.  

I don't know much about Neutralino so my question is does it support Web Platform APIs that require HTTPS in Chrome?

A related question is what is the underlying rendering engine? Is it the same across all platforms?

**Comment by Berkmann18** [comment]
I second the question on the rendering engine.
AFAIK it uses Chrakra for Windows (given the fact that the [Windows build apparently uses IE's rendering engine](https://github.com/neutralinojs/evaluation#5-conclusion)) no idea for GNU/Linux or MacOS.
I would guess WebKit tho.

**Comment by innerop** [comment]
Chakra is a JS engine. Webkit is a rendering engine, so are Blink and Gecko. 

So maybe V8 or Servo on Mac and Linux and Chakra on Windows for JS engine, and Webkit everywhere for rendering?

If so, my question about HTTPS-only APIs remains: does the security model allow use of HTTPS-only APIs? I guess Electron supports HTTPS-only API so I expect Neuralino to support them as well, but I'm asking to be sure.

Thank you in advance 

Cc: @shalithasuranga

**Comment by shalithasuranga** [comment]
Hello, Neutralinojs uses a modified version ([source](https://github.com/neutralinojs/webview)) of [C++ webview](https://github.com/webview/webview) which uses the following platform-specific rendering engines:

- GNU/Linux: WebKitGTK
- macOS: WkWebView
- Windows: WebView2 

Please kindly check each component's documentation for web API support. Thanks :tada:
