### ISSUE TITLE
Appname not showing on Ubuntu 18.04

### ISSUE THREAD

**Issue by aiibe** [neutralinojs/neutralinojs#271]
**Expected Behavior**  
Display `appname` from `settings.json` on window title/bar
  
**Actual Behavior**  
It displays `Neutralino window`

**Specifications**  
* NeutralinoJs Version: 1.5.4
* Platform: Ubuntu 18.08

**Comment by shalithasuranga** [comment]
Appname as the title is deprecated in v1.4.0 and please use `window.title` to set the window title,

See this config as an example

```json
{
    "appname" : "myapp",
    "appport" : "5006",
    "mode" : "window",
    "window" : {
        "title": "My app",
        "width" : "1000",
        "height" : "700",
        "fullscreen" : false,
        "alwaysontop": true,
        "borderless": false,
        "iconfile": "neutralino.png"
    }
}
```

We are in progress of updating the documentation. until please check changelog from https://github.com/neutralinojs/neutralinojs/releases/tag/v1.4.0
