### ISSUE TITLE
Application not opening on windows

### ISSUE THREAD

**Issue by Chiyoku** [neutralinojs/neutralinojs#272]
**Actual Behavior**  
Application not opening on windows 10, but task manager shows a process using 0% of CPU and 0.9MB of RAM called test-win

**Steps to Reproduce the Problem**
1.  Create a template called Test with the command `neu create test --template js`
2.  use `cd test` and `neu build` and then run the aplication in the file manager.

**Log**
ERROR [src/Socket.cpp:Bind] Socket::bind error: Address already in use

**Error ( sometimes happen )**
terminate called after throwing an instance of 'SocketBindingException'
  what():  bind() failed with error: 0

**Specifications**  
* NeutralinoJs Version: 1.4.0
* Neu-Cli: 1.5.4
* Platform: Windows 10 Home

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting. it was using port number `5006` now I set it to random. Could you please check again and let us know status.

**Comment by Chiyoku** [comment]
**Command**
`neu create test --template js`

**Error**
```
Error: ENOENT: no such file or directory, rename 'test/neutralino-win.exe' -> 'test/test-win.exe'    
    at Object.renameSync (fs.js:756:3)
    at User\AppData\Roaming\npm\node_modules\@neutralinojs\neu\src\commands\create.js:23:32
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  errno: -4058,
  syscall: 'rename',
  code: 'ENOENT',
  path: 'test/neutralino-win.exe',
  dest: 'test/test-win.exe'
}
```

**Comment by Chiyoku** [comment]
Not opening...

**Comment by shalithasuranga** [comment]
Hey.. now it should work. I did small fix in js template to match with latest neutralino version
