### ISSUE TITLE
Rebrand to Neujs?

### ISSUE THREAD

**Issue by aiibe** [neutralinojs/neutralinojs#273]
Because the CLI is called `neu`. IMO `new` sounds good too.

Available domains :
`neujs.io`
 `neujs.dev` 
`neujs.org`

What do you think ?

**Comment by shalithasuranga** [comment]
Thanks for the suggestion. Neutralino name doesn't look familiar for most of people it seems.In some youtube videos they pronounce it in a different way than I thought. Since this is still in development stage(I mean it's not mature yet) we would like to go ahead with current name.
