### ISSUE TITLE
[QUESTION] Nativefier Equivalent

### ISSUE THREAD

**Issue by SantoshSrinivas79** [neutralinojs/neutralinojs#275]
Hope a question is allowed here. Please let me know the protocol otherwise.

I am wondering if it is possible to create an equivalent of [jiahaog/nativefier: Make any web page a desktop application](https://github.com/jiahaog/nativefier)

Primarily just to for some light-weight alternative for browsing some very commonly used websites.

**Comment by input-variable** [comment]
If you modify the source to allow for it, I don't see why not.

**Comment by shalithasuranga** [comment]
Yeah sure we can. Nativefier uses electron template, Then your idea is already added to https://github.com/neutralinojs/neutralinojs-cli-appify :+1: I am closing this issue since we have a new repo for it.
