### ISSUE TITLE
Question: How to communicate with a native process?

### ISSUE THREAD

**Issue by nicholashaydensmith** [neutralinojs/neutralinojs#278]
I'm curious as to what is the best way to communicate with a native process.  I can see a few possibilities for how this might work, but I'm not familiar with neutralino (nor native web-tech in general) enough to know the best way to do this.

  - There are custom native hooks, where js can call directly into some C library via FFI.
  - Spawn a new process and communicate via stdin/stdout, popen style.
  - Spawn a new process and communicate via socket/port.

Are any of these options viable today?  My goal is to use neutralino as a GUI front-end that communicates with a C library that does more computationally intensive tasks and is the backend of my app.

**Comment by JoaquinDecima** [comment]
Hi, Currently we are working on incorporating the possibility of adding functions in languages such as C ++, Python, etc.

However, at present it is not available yet, however the techniques you mention are interesting, from my opinion (I am not a Neutralino developer) I would say that the best implementation, maintaining good practices would be:

* Spawn a new process and communicate via socket/port.

I hope this is useful to you and any questions we are at your disposal.

**Comment by shalithasuranga** [comment]
Hey.. I am closing this because this can be done with a Neutralinojs extension (can be written with any language). Please check https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension for an example.
I think you can initiate your C-based backend as a Neutralino extension.

Thanks for reporting the issue

**Comment by nicholashaydensmith** [comment]
How do the extensions work?  Is there a browser API that let's run JS on the host?

Or do you mean extensions that compile to wasm and run in browser?

**Comment by shalithasuranga** [comment]
Hey.. we can provide an extension Id and startup command in the app config file as shown in https://github.com/neutralinojs/neutralinojs/blob/b5679f98db6b9bfefff1e7773da43bbdf2a1e379/bin/neutralino.config.json#L49

Neutralinojs process will spawn child processes based on the startup command. Also, the main process provides required details for child processes to start a WebSocket communication with the main native API. We can use `extensions.dispatch` from the app to send a message to the extension. On the other hand,  the extension can send a message to the app with `app.broadcast`.

I will add more details to the documentation once after releasing this feature. Thanks
