### ISSUE TITLE
How to Maximize (not Fullscreen)

### ISSUE THREAD

**Issue by patarapolw** [neutralinojs/neutralinojs#279]
**Actual Behavior**  
`"fullscreen" : true` cause windowed app to go fullscreen on MacOS, not maximize.

**Specifications**  
* NeutralinoJs Version: v1.4.0
* Platform: macOS Catalina

---

You might also checkout my self solution in Kotlin,

https://github.com/patarapolw/k-neu

**Comment by jpguzman** [comment]
I second this. I would love a maximized window option.

**Comment by shalithasuranga** [comment]
Added to Linux.. needs to be added to Windows and macOS @alphagamer7  Could you check macOs verion?

**Comment by patarapolw** [comment]
As a matter of fact, I already find ways in CGO (for Lorca / Webview); but it may be able to be applied to C++ in Neutralino.

[See my previous commits of webview-server](https://github.com/patarapolw/webview-server/commits/master).

**Comment by shalithasuranga** [comment]
Closed and added to https://github.com/neutralinojs/neutralinojs/issues/310
