### ISSUE TITLE
Shared library support - experimental 

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#283]
- Mac - .dylib
- Linux - .so
- Windows .dll

Developer will be able to add shared library names and function mapping to `neutralino.config.json` thereafter functions will be available with `Neutralino.shared.<filename>.<method>`

**Comment by konsumer** [comment]
I don't know if this is the place to discuss it, but wasm (with wasi) support would also be rad. That way you could write your efficient compiled plug-in in any language, compile once, and use it on any platform.

**Comment by shalithasuranga** [comment]
This idea is replaced with https://github.com/neutralinojs/proposals's API extensions Golang seems a better way to make a custom backend for Neutralinojs
