### ISSUE TITLE
can i load some page from internet and apply own logic?

### ISSUE THREAD

**Issue by whateveruse** [neutralinojs/neutralinojs#285]
i need to customize some cloud app in internets

can i load pages  https://somepage.com/super-external-app/

and apply js from this local neutralinojs i other word i need to injecting some my code when some external page was loaded

now i  can do this with  browser extension - but is too hard to write and publish extension

**Comment by shalithasuranga** [comment]
Hey.. it will be possible with next version using `url` in `settings.json`. But it can be used with your own web app and here are the steps

- Set url to remote page
- In that remote page load neutralinojs client js using `script` tag
- Also add another script tag to load local code which has some application logic

**Comment by 6umpukc-uHKBu3umop** [comment]
can you provide some example?

**Comment by cope** [comment]
@shalithasuranga an example of loading the neutralinojs client and custom logic would be helpful...

**Comment by dpaluchowski** [comment]
Has anyone already solved the problem with including their own script? 😢

**Comment by shalithasuranga** [comment]
Hey.. all please note that even though my previous comment said it's possible with some tweaks, the current Neutralinojs mode/design doesn't directly support calling Neutralinojs API from remote URLs or injecting Neutralinojs client for websites loaded over the network. But, as you already noticed Neutralinojs allows developers to set remote URLs. However, it's for the following scenarios.
- Displaying a PDF from the internet.
- Displaying a quick signup/registration form or any other forms like feedback forms etc.
- Wrapping web apps to desktop apps via https://github.com/neutralinojs/neutralinojs-cli-appify (API is not enabled)

But, we would like to discuss this - maybe we can make a feature. Could you let me know for what kind of scenario, the injecting Neutralinojs client is required?

**Comment by shalithasuranga** [comment]
Hey.. for this one we need to inject our Js library to webview. Also, we need to do it by disabling web security. I am closing this and we will look at this case with https://github.com/neutralinojs/neutralinojs/issues/586 for sure ;)

**Comment by s1nistr4** [comment]
Man, still an issue in 2023
