### ISSUE TITLE
Neutralino does not compile easily in VS-based toolchain on Windows

### ISSUE THREAD

**Issue by apollolux** [neutralinojs/neutralinojs#287]
**Expected Behavior**  
Neutralino source should come with a VS-friendly build.bat, either separate from the gcc-based build.bat or as a command line arg to use msbuild or cl instead of g++

**Actual Behavior**  
Neutralino source only comes with a gcc-based build.bat

**Steps to Reproduce the Problem**  
 1. Get the source onto Windows
 2. Only have VS2017 or VS2019 installed and realize build.bat only calls g++ rather than msbuild or cl
 3. Lament about having to find a reliable pre-built package of a modern version of mingw64+msys/msys2

**Specifications**  
* NeutralinoJs Version: 1.4.0
* NeutralinoJs CLI version: n/a
* Platform: Win10 Pro 1909/18363.836

Some of the platform-specific source files having all the source for the other platforms (e.g. the Windows webview.h having a copy of *all* the webview.h code for mac and linux) certainly doesn't help matters.

**Comment by shalithasuranga** [comment]
I am closing this because now the source code is already refactored better and also it uses MSVC on Windows.
