### ISSUE TITLE
Live/Hot reload for Neutralino applications

### ISSUE THREAD

**Issue by saaymeen** [neutralinojs/neutralinojs#288]
Hi, just discovered Neutralino. Is it possible to develop a React app with neutralino using the benefits of hot module replacement or live reload? It's a bit cumbersome to rebuild the whole app everytime I change a div or test some styles. Please excuse me if I oversee anything from the docs.
Cheers!

**Comment by shalithasuranga** [comment]
Thanks for reporting the issue. This feature request is already there in CLI https://github.com/neutralinojs/neutralinojs-cli/issues/7

This will be added soon

**Comment by saaymeen** [comment]
Perfect, thanks for the response on this one! Maybe it's a good idea to allow the Github discussions for this repository so that the issues don't get polluted with such kind of questions.

**Comment by EriKWDev** [comment]
Currently I use `nodemon` with the command `nodemon -x "neu build && neu run" -w src/*`
This will listen to changes in the `src` directory and execute build and run.

It's rather slow compared to something like Flutter's Hot Reload or even Webpack since it rebuilds everytime, but it works and at least I dont't have to manually type the commands... xP

**Comment by raffaelj** [comment]
I use a simple workaround to refresh the window. It works in browser and window mode. For simplicity I just used [Mousetrap][1], but you could add your own event listeners.

Download `mousetrap.min.js` and add it with a key binding to `index.html` with

```html
<script src="/assets/lib/mousetrap.min.js"></script>
<script>
// bind F5 key to page reload
Mousetrap.bind('f5', function() {window.location.reload();});
</script>
```

You can also run the refresh in a loop or/and bind an onclick event to a button.

[1]: https://github.com/ccampbell/mousetrap

**Comment by shalithasuranga** [comment]
Hey @raffaelj  Nice idea.. I will try to add `neu listen` asap

**Comment by shalithasuranga** [comment]
Hey.. I closed this since `neu listen` was released.

**Comment by jwhijazi** [comment]
`neu listen` is no longer available in version 4. What are the alternatives?

**Comment by jwhijazi** [comment]
> Hey.. @jwhijazi you can use `neu run --frontend-lib-dev` and read more details from here: https://neutralino.js.org/docs/how-to/use-a-frontend-library

Thanks for the info.
I don't know if I can ask another question in this issue, but I'm asking for an API to get PC network information such as IP address and MAC address.

**Comment by jwhijazi** [comment]
> Hey.. @jwhijazi you can use `neu run --frontend-lib-dev` and read more details from here: https://neutralino.js.org/docs/how-to/use-a-frontend-library

Thanks for the info.
I don't know if I can ask another question in this issue, but I'm asking for an API to get PC network information such as IP address and MAC address.

**Comment by jwhijazi** [comment]
> Hey.. @jwhijazi you can use `neu run --frontend-lib-dev` and read more details from here: https://neutralino.js.org/docs/how-to/use-a-frontend-library

Thanks for the info.
I don't know if I can ask another question in this issue, but I'm asking for an API to get PC network information such as IP address and MAC address.

**Comment by shalithasuranga** [comment]
Hey.. Sure you can ask more questions. Also, you can discuss your ideas/questions with the entire community via Discord too.
Neutralinojs doesn't offer an API for network information, I think it's not a too generic API to be added into the official API. But there are several approaches to do this. You can create an extension using any favorite language and obtain network details via that specific extension instance. Please check more details about extensions from here: https://neutralino.js.org/docs/how-to/extensions-overview

**Comment by thehackingknight** [comment]
@shalithasuranga the filesystem does not work with react when using `neu run --frontend-lib-dev`

**Comment by shalithasuranga** [comment]
Hey.. @thehackingknight Are you using the latest version and did you follow [this tutorial](https://neutralino.js.org/docs/getting-started/using-frontend-libraries) to enable hot reloading?
