### ISSUE TITLE
Is there any way to play local audio files?

### ISSUE THREAD

**Issue by Kicshikxo** [neutralinojs/neutralinojs#289]
I have encountered a problem with audio playback.

I created three buttons on the page and put a playback event on each of them. The first button played the audio from the site, the second from the folder where was located index.html, and the third button played the audio from from the assets folder.

The code looked like this:
`<button onclick = 'new Audio("https://soundslibmp3.ru/sounds/1575205539_flowers-11.mp3").play()'>Cloud</button>
    <button onclick = 'new Audio("1575205539_flowers-11.mp3").play()'>Local</button>
    <button onclick = 'new Audio("/assets/1575205539_flowers-11.mp3").play()'>Local /assets</button>`

The first button played the sound, but with a delay due to the download from the site.
When I pressed the second button nothing happened.
But when I clicked on the third one my app closed with a segmentation error.

I tried to run the audio via web inspector, but I got an error...

I understood that neutralino blocks audio playback on the page, but I managed to launch audio from a third-party site. Maybe there is some way to start the audio? For example connect to it via a local server?

**Comment by shalithasuranga** [comment]
Thanks for reporting the issue. there was support for some general files like js, html, css, png etc.. now mp3 also added and will work. will be released with the next version

**Comment by Kicshikxo** [comment]
I really hope that the next version will be released in less than six months... :)

**Comment by shalithasuranga** [comment]
@Kicshikxo haha.. going to do a release now.. mp3 files will be served on all platforms
