### ISSUE TITLE
borderlesswindow setting does not hide the border in KDE

### ISSUE THREAD

**Issue by Kicshikxo** [neutralinojs/neutralinojs#291]
I found that the borderlesswindow option does not hide borders in KDE, although it is written that it works on all platforms.

What it looks like for me:
![window screenshot](https://dl.dropbox.com/s/i8o2b2a31vxavh7/Screenshot_05.06.2020_19.11.21.png?raw=1)

I'm also interested in how to implement the drag area of the window and the collapse button in the tray. Electron uses the CSS style: "-webkit-app-region: drag" to create a move area. How to implement this in neutralino? I didn't find anything about it in the documentation. The same question applies to the collapse button for the app.
It's just important for me to create my own top app panel...

**Specifications**  
* NeutralinoJs Version: 1.4.0
* NeutralinoJs CLI version: 1.5.4
* Platform: Manjaro Linux with KDE (64 bit)

**Comment by Kicshikxo** [comment]
The same with windows, maybe I didn't quite understand how borderlesswindow works? I just thought it worked like "frame: false" in electron.

**Comment by jpguzman** [comment]
I thought the same. I would love to be able to go frameless and do a custom taskbar with HTML/CSS like in Electron.

**Comment by originecode** [comment]
Same here. macOS (Catalina 10.15.5).

**Comment by kde3kko** [comment]
I can confirm the option is not working on macOS (Catalina 10.15.4)

**Comment by kde3kko** [comment]
My bad, the docs [here](https://neutralino.js.org/docs/#/configuration/settings.json) needs to be updated, I found the useful infos inside the 1.4.0 release notes:
https://github.com/neutralinojs/neutralinojs/releases/tag/v1.4.0

**Comment by shalithasuranga** [comment]
@kde3kko Thanks nice finding.. I updated the documentation 
https://neutralino.js.org/docs/#/configuration/settings.json?id=windowborderless
