### ISSUE TITLE
Question: Is the exe (for windows) in dist folder a standalone executable?

### ISSUE THREAD

**Issue by timlorepublic** [neutralinojs/neutralinojs#292]
Question:

Hello, I followed the guide here: https://neutralino.js.org/docs/#/tools/cli
and I use the template for js

**Expected Behavior**  
Standalone exe inside dist folder shows the window frame
  
**Actual Behavior**  
Nothing shown, only exe running shown in Windows Task Manager

**Steps to Reproduce the Problem**  
 1. run neu build
 2. run neu release
 3. go to dist folder and double click on the exe (for windows)

**Specifications**  
* NeutralinoJs Version: [1.4.0]
* NeutralinoJs CLI version: [1.5.4]
* Platform: [Win 10]

**Comment by jpguzman** [comment]
The bug is happening for me too. I am also on Windows.
If there's a way to compile the app into a single binary file - so that other users can't see & modify the html/js files that would be great.

**Comment by David263** [comment]
Is this product supported?

**Comment by GlennVialli** [comment]
the file "neutralino.png" is missed.... try to add it manually

**Comment by shalithasuranga** [comment]
Please try the latest version. These issues are not there. :) https://neutralino.js.org/
