### ISSUE TITLE
Can I use my own fonts?

### ISSUE THREAD

**Issue by Kicshikxo** [neutralinojs/neutralinojs#296]
I ran into the problem that I can't use my ttf fonts. I understand that font files are not currently supported, as they were with mp3. Are there plans to support font files?

**Comment by AntonioDePau** [comment]
Have you had a look at this issue: (238)[https://github.com/neutralinojs/neutralinojs/pull/238]

Says you should be able to load fonts (woff2 format at least) if you try with @font-face in css.

**Comment by Kicshikxo** [comment]
Thank you, this solves my problem.
