### ISSUE TITLE
Can't find variable: NL_TOKEN

### ISSUE THREAD

**Issue by Dugnist** [neutralinojs/neutralinojs#297]
**Expected Behavior**  
Neutralino.os.runCommand "help" work.
  
**Actual Behavior**  
Message: Can't find variable: NL_TOKEN. 

**Steps to Reproduce the Problem**  
 1. Try to run command "help" 

```
const exec = () =>
    new Promise((res, rej) => {
      try {
        Neutralino.os.runCommand(
          'help',
          (data) => {
            res(data);
          },
          () => {
            rej('error');
          }
        );
      } catch (error) {
        console.log(error.message);
        rej(error.message);
      }
    });
```

 2. Catch error "Can't find variable: NL_TOKEN".

**Specifications**  
* NeutralinoJs Version: neu update and neu run
* NeutralinoJs CLI version: 1.5.4
* Platform: Linux Ubuntu 19.10

https://www.loom.com/share/21de1ec1e3c541c785769006fe419fd7

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting the issue. could you set mode to browser in settings.json and copy paste following code into console and see whether it works or not

```js
Neutralino.os.runCommand("help", (out) => {console.log(out)}, (err) => {console.error(err)}); console.log(NL_TOKEN)
```

**Comment by Dugnist** [comment]
![image](https://user-images.githubusercontent.com/6489460/85371978-d1739e00-b539-11ea-835d-db6fdf2fea11.png)


https://www.loom.com/share/ebb3ba42b1b345d2bb26092357a083a5

**Comment by Dugnist** [comment]
@shalithasuranga, hello, any updates? What's my mistake?

**Comment by shalithasuranga** [comment]
Hey @Dugnist  I tried to reproduce this issue but it is working fine for me. Internally when request for `neutralino.js` js file server will read the file from disk and append global variables including `NL_TOKEN`. If possible could you share the source files ? Then we can easily fix it :)

**Comment by Dugnist** [comment]
@shalithasuranga https://github.com/Dugnist/Platform

**Comment by Dugnist** [comment]
https://www.loom.com/share/b1836a3626e84fb6a92223b5669aeba3

The problem arises because for correct operation the link from HTML to the /neutralino.js should point to the "app" folder, but neutralino.js file itself is in the assets folder and gives a 404 error when the application starts in the browser because the path from HTML does not work correctly.

**Comment by Dugnist** [comment]
Reference to: https://github.com/neutralinojs/neutralinojs/issues/259

@shalithasuranga

**Comment by shalithasuranga** [comment]
Nice you found the issue :D
