### ISSUE TITLE
Add "onblur" and "focus" event handlers

### ISSUE THREAD

**Issue by pmjohann** [neutralinojs/neutralinojs#299]
**Expected Behavior**  
Implement / Document "onblur" and "focus" events.
  
**Actual Behavior**  
I found no implementation of the "onblur" or "focus" events so far.

**Benefits**  
Currently I am using DeskGap which [has this](https://deskgap.com/api/#instance-events), and I would like to migrate to Neutralino, but a crucial part is missing for me, that is the "onblur" event.

Electron [has it](https://deskgap.com/api/#instance-events) as well.

This way I can detect that the window is out of focus (blurred), so I can pause (an expensive) backend service, and resume it as soon as the window gets focused again.

This is extremely important especially when running on battery power.

**Comment by shalithasuranga** [comment]
Thanks for sending this feature request. Now we have `windowFocus` and `windowBlur` events via `Neutralino.on()`. We will release these features with the next version :tada:
