### ISSUE TITLE
Can't get the url: <path> to work in settings.json.

### ISSUE THREAD

**Issue by DanielMontilla** [neutralinojs/neutralinojs#304]
My index.html file is outside the app folder elsewhere. How would I go about indicating where it is inside the settings.json file?

Lets say my entry point is somewhere like this:
Project Folder
└ App Folder
--└ settings.json
└ other Forlder
--└ index.html

Ideally I would indicate the location of the file with a relative path right? Sorry for the inconvenience

**Comment by DanielMontilla** [comment]
Not sure how to tag the issue as a question sorry

**Comment by BenStigsen** [comment]
`"url": "/"` is the same directory as the `settings.json` file. To go outside of the folder you use `../`. So you would have to do `../Other Folder/`

**Comment by shalithasuranga** [comment]
Please try the latest version: https://neutralino.js.org/docs/
Now the project structure is very flexible for developers.
