### ISSUE TITLE
API to toggle fullscreen

### ISSUE THREAD

**Issue by andybalaam** [neutralinojs/neutralinojs#305]
There is an option in settings.json to start the program in fullscreen mode, but is there an API to change in and out of fullscreen mode after the program is started?

Awesome project!

**Comment by shalithasuranga** [comment]
Thanks for the suggestions. This seems to be related with #231 . Sounds we need to work on #231 thereafter we will be able to easily implement this.

**Comment by andybalaam** [comment]
Sounds right, thanks for commenting.

**Comment by shalithasuranga** [comment]
Thanks for reporting this. This is done via https://github.com/neutralinojs/neutralinojs/issues/516 I will release with the next version
