### ISSUE TITLE
Borderless windows should not have a title bar

### ISSUE THREAD

**Issue by David263** [neutralinojs/neutralinojs#306]
**Expected Behavior**  
A borderless window should not have a title bar (my application will be a digital clock). 
  
**Actual Behavior**  
When I run neutralino-win.exe I see a borderless window that has a title bar.

**Steps to Reproduce the Problem**  
 1. Download the Zip file (I forget how to do this)
 2. Edit 'settings.json' to add ' "borderlesswindow": true '
 3. run neutralino-win.exe

**Specifications**  
* NeutralinoJs Version: neutralinojs-v1.5.0
* NeutralinoJs CLI version: [neu-cli version] NOT USED
* Platform: Windows 10 Home 

**Comment**
[x] I suspect you will have a lot of trouble eliminating the title bar. I can't figure out how to do it.
**Note: Electron creates borderless windows perfectly.**

**Comment by shalithasuranga** [comment]
Please try the latest version: https://neutralino.js.org/

**Comment by David263** [comment]
I don't really have time to "try" a version. I'm busy making software. Can't you just tell me whether neutralino can create a simple borderless window or not? I want to do a tiny project to create a tiny customizable digital clock for Windows desktops.

I think Electron can do it, but Electron is massive, even for a tiny app.

David Spector
