### ISSUE TITLE
Any ping response 'missed' results in server shut down and ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Skarnivorous** [neutralinojs/neutralinojs#307]
**Expected Behavior**  
Any blocking operation which is occuring during a ping event should not result in server shut down.
  
**Actual Behavior**  
Numerous situations where a Javascript error or debugging operation or blocking code occurs a ping back may result in:
GET http://localhost:8080/ping net::ERR_CONNECTION_REFUSED
shortly afterwards indicating the server (executable) has shut down.

**Steps to Reproduce the Problem**  
 1. Run an app page in browser mode
 2. Enter debugger tools and find a point in code for a breakpoint
 3. Trigger breakpoint and just wait, maybe 30 seconds.
 4. Resume code playback
 5. Wait and observe the pinback error and note that the server executable has shut down (no longer in task manager as running process)

This may also randomly happen in other situations too, but the above does seem to reproduce the scenario.
Browser running app window is Chrome.

**Specifications**  
* NeutralinoJs Version: 1.5.0
* NeutralinoJs CLI version: ? 1.5.0?
* Platform: Windows 10 x64 - browser mode - chrome client.

**Comment by shalithasuranga** [comment]
Hey. thanks for reporting this .. This issue is fixed and will be released with the next version
