### ISSUE TITLE
Assets images with spaces do not load

### ISSUE THREAD

**Issue by Skarnivorous** [neutralinojs/neutralinojs#309]
**Expected Behavior**  
`<img src="/assets/test 1.png"/>` should show image "test 1.png"
  
**Actual Behavior**  
`<img/>` shows 'empty image' placeholder instead of image.

**Steps to Reproduce the Problem**  
 1. Put 2 images in assets folder - one with a space in the filename
 2. Put 2 `<img>` tags on a page to each image
 3. View page through framework.

**Specifications**  
* NeutralinoJs Version: 1.5.0
* Platform: Windows 10 x64

**Comment by shalithasuranga** [comment]
looks like url encoding is not happening.. properly will check it

**Comment by shalithasuranga** [comment]
Added to Linux version and other platforms need to be updated

**Comment by shalithasuranga** [comment]
Closed and added to https://github.com/neutralinojs/neutralinojs/issues/310
