### ISSUE TITLE
Add continuous integration 

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#31]

**Comment by shalithasuranga** [comment]
@RavinduHasithanjana  Can we try Travis CI first

**Comment by RavinduHasithanjana** [comment]
sure

**Comment by theharshitgarg** [comment]
@shalithasuranga Can I work on this?

**Comment by shalithasuranga** [comment]
@RavinduHasithanjana  is currently working with this I guess. Better to wait for his response I think

**Comment by shalithasuranga** [comment]
Done with Github Actions. macOs build script to be added
