### ISSUE TITLE
[Help wanted] - Implementing missing features in macOS version

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#310]
There are some features that are present in Linux and Windows but not yet implemented (I don't have a mac device with me right now) in the macOS version of Neutralinojs. Contributors are welcome. 

Here is the list of features that need to be added to the macOS version

https://github.com/neutralinojs/neutralinojs/issues/309
https://github.com/neutralinojs/neutralinojs/issues/303
https://github.com/neutralinojs/neutralinojs/issues/279
https://github.com/neutralinojs/neutralinojs/issues/269
https://github.com/neutralinojs/neutralinojs/issues/331
https://github.com/neutralinojs/neutralinojs/issues/340
https://github.com/neutralinojs/neutralinojs/issues/352
https://github.com/neutralinojs/neutralinojs/issues/342
https://github.com/neutralinojs/neutralinojs/issues/349
https://github.com/neutralinojs/neutralinojs/issues/357
https://github.com/neutralinojs/neutralinojs/issues/362
https://github.com/neutralinojs/neutralinojs/issues/357
https://github.com/neutralinojs/neutralinojs/issues/368
https://github.com/neutralinojs/neutralinojs/issues/372
https://github.com/neutralinojs/neutralinojs/issues/368
https://github.com/neutralinojs/neutralinojs/issues/372
https://github.com/neutralinojs/neutralinojs/issues/149
https://github.com/neutralinojs/neutralinojs/issues/363
https://github.com/neutralinojs/neutralinojs/issues/346
https://github.com/neutralinojs/neutralinojs/issues/367

**Comment by terrabythia** [comment]
I'd like to contribute to this project if I can! Can you please specify further what the differences between Windows/Linux and MacOS are right now?

**Comment by shalithasuranga** [comment]
Thanks @terrabythia . Those codebases are almost synced if we compare with features. But there are some issues on Github like https://github.com/neutralinojs/neutralinojs/issues/309 which contains comments like "feature needs to be added into macos version" etc. Basically some features are missing in macos but those features are already implemented in other platforms.

Also it will be great if you could help to resolve macos only issues such as https://github.com/neutralinojs/neutralinojs/issues/219

**Comment by shalithasuranga** [comment]
Hey.. all I've just updated the description with some tasks that need to be added to macOS version but present in other platforms. I am planning to release v1.6.0 without updating macOS version but with [these](https://github.com/neutralinojs/neutralinojs/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.6.0) features in all other platforms

**Comment by shalithasuranga** [comment]
I think we don't need to look at each issue and implement it in the mac version. I will create another issue to sync the code
