### ISSUE TITLE
Capture and prevent window close events (via beforeunload or other mechanism)

### ISSUE THREAD

**Issue by psiservices-justin-sullard** [neutralinojs/neutralinojs#313]
**Expected Behavior**
For a number of applications there may be concern over unsaved changes or other scenarios in which an application written with Neutralinojs would want to prompt the user to confirm that they really want to quit.

In Electron, and most other browser, this can be accomplished by adding a handler for the `beforeunload` event such as:
```javascript
window.addEventListener('beforeunload', (e) => {
  const answer = confirm('Are you sure you want to quit?');
  e.returnValue = answer;
});
```
**Actual Behavior**  
While this event is triggered when performing a `window.location.reload()` call, this event is not triggered for the closing of the application window from NeutralinoJS, and I have not found any documented method of preventing the closing of an application window, if only conditionally.

**Steps to Reproduce the Problem**  
 1. Add the event handler described above.
 2. Run application and attempt to close the window (closes without prompt).
 3. Using the developer console (via `enableinspector` in settings) execute `window.location.reload()` (prompt triggered).

**Specifications**  
* NeutralinoJs Version: 1.5.0
* NeutralinoJs CLI version: 1.7.0
* Platform: Linux 5.3.0-7648-generic x86_64

**Comment by jaronwanderley** [comment]
A good use for this would be in conjunction with the tray icon, avoiding closing the application and hiding it instead of closing it.
There is another way of hiding application on close click?

**Comment by shalithasuranga** [comment]
Hey..  This feature needs to be added, and already planned to add `onWindowClose` event as show in https://github.com/neutralinojs/roadmap#events 
So Neutralino will call `onWindowClose` when the user closes the window. Then the developer may call `app.exit()` or `window.hide()` as they wish. I will let you know once it's added soon.

**Comment by shalithasuranga** [comment]
Hey.. now `windowClose` event will be called when the user closes the window. Please check the example below,

```js
await Neutralino.events.on(`windowClose`, () => {
  // Do something like showing a message box?
  // Or call Neutralino.app.exit() to exit
});
```

I will release this feature with the next release.
