### ISSUE TITLE
Can you please add new section in your website to showcase user developed apps using NeutralinoJs

### ISSUE THREAD

**Issue by JigneshRaval** [neutralinojs/neutralinojs#314]
Hi @neutralinojs Team

Can you please add new section in your website to showcase user developed apps built using NeutralinoJs similar to following URL

 @https://www.electronjs.org/apps

This will be very helpful to all the developers and new comers who wants to develop apps using this framework.

**Comment by shalithasuranga** [comment]
Please check https://neutralino.js.org/apps/
