### ISSUE TITLE
Feature request : Add APIs for interprocess communication

### ISSUE THREAD

**Issue by kousiksatish** [neutralinojs/neutralinojs#316]
**Expected Behavior**  
I want to launch neutralino js application along side our current application as a child process. To communicate from my main process to neutralino js application, we need IPC capabilities. 

My suggestion for IPC is to enable APIs to create a TCP server on some free port in the PC. Other applications can connect to this port and send/receive messages. APIs similar to net module of nodejs should be good for this.

This will enable people like me who wish to launch neutralinojs app as a addon to their existing app.
  
**Actual Behavior**  
No way to establish IPC currently. Can work only as a standalone application and cannot coexist with other desktop app.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this. This missing feature you've mentioned is recently solved by API extensions implementation. You can check some intro here: https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#core-community-driver-processes . We'll add more details soon to documentation after the next release.

**Comment by serg06** [comment]
@shalithasuranga Can you please clarify how the client can receive data back from an extension?
