### ISSUE TITLE
Borderless windows don't work

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#317]
**Expected Behavior**  
A borderless window should not have a borders
  
**Actual Behavior**  
When I run neutralino-linux, I see a window that has a borders

**Steps to Reproduce the Problem**  
 1. Create projet whit neu v1.7.0
 2. Edit 'settings.json' to add ``` "borderlesswindow": true ```
 3. run neutralino-linux

**Specifications**  
* NeutralinoJs Version: 1.5.0
* NeutralinoJs CLI version: 1.7.0
* Platform: Linux Mint 20

**Comment by JigneshRaval** [comment]
Hi @JoaquinDecima ,

I think the property name has been changed from `borderlesswindow` to `"borderless": false`.

Can you please try that. I hope that will work.

Thanks,
Jignesh

**Comment by JoaquinDecima** [comment]
Sorry I didn't see it, it works properly! 

Thank you very much!
