### ISSUE TITLE
NL_CWD doesn't include slash after drive name, making path name invalid

### ISSUE THREAD

**Issue by joshpowlison** [neutralinojs/neutralinojs#321]
As the title says.

So if I use NL_CWD, I get a result like this:
![image](https://user-images.githubusercontent.com/18360475/95343298-5cc53500-0886-11eb-8990-33381bf39f32.png)

I need a slash after "D:", like "D:/" for the path to work in commands like `Neutralino.filesystem.readDirectory()`.

Easy to work around for now, in case anyone else needs this: `const PATH = NL_CWD.replace(/^([A-Z]):/i,'$1:/');`

**Comment by shalithasuranga** [comment]
Hey.. I just checked with the latest version. `Neutralino.filesystem.readDirectory(NL_CWD)` worked fine. Please let us know if there is an issue. Thanks for reporting this
