### ISSUE TITLE
Debug.log file is generating when we open any PDF or HTML file which is related to Chrome

### ISSUE THREAD

**Issue by JigneshRaval** [neutralinojs/neutralinojs#326]
**Expected Behavior**  
It should not generate debug.log file on opening any file into Google Chrome
  
**Actual Behavior**  
It is generating debug.log file with the following data, while we open any PDF, HTML, WebP or those files which is opening in Google Chrome

`[1015/195707.967:ERROR:registration_protocol_win.cc(131)] TransactNamedPipe: The pipe has been ended. (0x6D)`

**Steps to Reproduce the Problem**  
Open any PDF, html or .webp file in chrome

**Specifications**  
* NeutralinoJs Version: [1.5]
* NeutralinoJs CLI version: [1.7.0]
* Platform: [Windows 7 64bit]

**Comment by shalithasuranga** [comment]
Hey.. currently Neutralinojs faces some issues with Windows 7. We are planning to fix all via https://github.com/neutralinojs/neutralinojs/issues/486. I am closing this by keeping the other issue open. Thanks for reporting :)
