### ISSUE TITLE
[request] an empty install with cli

### ISSUE THREAD

**Issue by MatthijsKamstra** [neutralinojs/neutralinojs#327]
I work a lot with a programming language called Haxe.

To create a project with Haxe I use NPM to generate the `.js` (via Haxe) and `.css` (via sass).

That works fine (https://github.com/MatthijsKamstra/hx-neutralino-lite) but I think it would be helpfull to have an "empty" cli command as well.

`neu create myapp --template basic` or `neu create myapp --template empty`

This way people can use the commands like you normally do, but use their own system to build the source files.

btw: awesome project: love it! ♥️

**Comment by shalithasuranga** [comment]
Thank you very much for the ideas. Now we only use a minimal template. Please check the documentation here: https://neutralino.js.org/docs/developer-environment/project-structure
