### ISSUE TITLE
weird path in logging on osx

### ISSUE THREAD

**Issue by MatthijsKamstra** [neutralinojs/neutralinojs#328]
**Expected Behavior**  

Not sure what the expected behaviour should be, but I don't expect a reference to a path that is not on my computer : 
"/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/core/debug.cpp:log"
  
**Actual Behavior**  

It shows a path that is not on my computer : 

"/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/core/debug.cpp:log"

besides that its not my computer, its also not useful ... so I suggest that it is removed

**Steps to Reproduce the Problem**  

use example code
```
Neutralino.debug.log('INFO', str, function(data) {
				console.log(data);
				
			}, function() {
				console.error('error');
			});
```

**Specifications**  
* NeutralinoJs Version: 1.7.0
* NeutralinoJs CLI version: 1.7.0
* Platform: osx

```
INFO [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/core/debug.cpp:log] src/Main.hx:98: matthijskamstra
```

**Comment by shalithasuranga** [comment]
This is fixed.. Please check when the macOS version is available (I will release it soon)
