### ISSUE TITLE
documentation incorrect about storage

### ISSUE THREAD

**Issue by MatthijsKamstra** [neutralinojs/neutralinojs#329]
**Expected Behavior**  

https://neutralino.js.org/docs/#/api/storage?id=storageputdataobject-data-function-success-function-error

example code of the documentation:
```
let data = { 
    bucket : 'test', 
    content : { 
            item : 10 
    } 
}
```

  
**Actual Behavior**  

use typescript it suggests: `StoragePutData` which forces a `key` and `content`

```
		var data = {
			key: 'test',
			content: {
				item: 10
			}
		}

```

**Steps to Reproduce the Problem**  

 see above

**Specifications**  
* NeutralinoJs Version: [1.7.0
* NeutralinoJs CLI version: 1.7.0
* Platform: osx

**Comment by MatthijsKamstra** [comment]
It should be bucket, otherwise the app will crash

so not the documentation is incorrect, the ts files are incorrect

https://github.com/neutralinojs/neutralinojs-typescript/blob/4e8893c358816ffd7f0f73ee96497bd5ee1390a0/src/index.d.ts#L43

`key` should be `bucket`

**Comment by shalithasuranga** [comment]
Please check the latest documentation: https://neutralino.js.org/docs/.
Thanks for reporting the issue.
