### ISSUE TITLE
Generated settings are not in the same way describe in documentation

### ISSUE THREAD

**Issue by MatthijsKamstra** [neutralinojs/neutralinojs#330]
**Expected Behavior**  

https://neutralino.js.org/docs/#/configuration/settings.json?id=window

```
{
    "appname" : "myapp",
    "appport" : "5006",
    "mode" : "window",
    "window" : {
        "title": "My app",
        "width" : "1000",
        "height" : "700",
        "fullscreen" : false,
        "alwaysontop" : false,
        "iconfile" : "neutralino.png",
        "enableinspector" : false,
        "borderlesswindow" : false
    }
}
```

notice the `iconfile` in `window`
  
**Actual Behavior**  

```
{
  "appname": "myapp-ts",
  "appport": "5006",
  "mode": "window",
  "iconfile": "neutralino.png",
  "window": {
    "width": "1000",
    "height": "700",
    "fullscreen": false
  }
}
```
notice the `iconfile` **outside** `window`

**Steps to Reproduce the Problem**  

- create with ts

**Specifications**  
* NeutralinoJs Version: 1.7.0
* NeutralinoJs CLI version: 1.7.0
* Platform: osx

**Comment by shalithasuranga** [comment]
Please check the latest documentation: https://neutralino.js.org/docs/
