### ISSUE TITLE
Opening directory using os.dialogOpen()

### ISSUE THREAD

**Issue by kalucky0** [neutralinojs/neutralinojs#331]
**Expected Behavior**  
`os.dialogOpen(string title, function success(data), function error)` should allow opening not only files but also whole directories.
  
**Actual Behavior**  
Only allows to open a file

**Specifications**  
* NeutralinoJs Version: v1.5.0
* NeutralinoJs CLI version: v.1.7.0
* Platform: Windows

**Comment by shalithasuranga** [comment]
Yeah looks like we can add an option to say whether file-type open dialog or folder-type. :+1:

**Comment by shalithasuranga** [comment]
Added to Linux version and Windows version. Also, added to macOS main issue
