### ISSUE TITLE
Creating image with filesystem

### ISSUE THREAD

**Issue by Jo-Sword** [neutralinojs/neutralinojs#332]
Good morning, I have tried creating an image with the *filesystem.writeFile*.

What I want to do is the following, I have neutralino with Svelte and websockets. The server will send images either in an Image File or base64.

I receive them in Svelte and add the new file in a folder called "uploads".
I was trying in a simple way with an ``<input type="file" on:change={ newFile }>``
```javascript
const newFile = async e => {
    const file = e.target.files[0]

    let image_url = ''

    const reader = new FileReader()
    reader.addEventListener('load', async (e) => {
      image_url = e.target.result

      Neutralino.filesystem.writeFile('image.png', image_url,
        data => {
          console.log(data)
        },
        () => console.error('error.')
      )
    })
    reader.readAsDataURL(file)
}
```
Create the file successfully, but it is corrupted and does not display any images.

Am I doing something wrong or is the njs filesystem still in need of improvement? (I already tried converting base64 to Buffer)
Could anyone please guide me on how to create images this way?

**Specifications**  
* NeutralinoJs Version: 1.5.0
* NeutralinoJs CLI version: 1.7.0
* Platform: Linux

**Comment by shalithasuranga** [comment]
Hey.. writeFile method currently only supports text data not binary.. looks like we can add an option to the method like `isBinary`

**Comment by Jo-Sword** [comment]
> Hey.. Good morning..


Oh now I see. Thank you very much for the reply.
I know they don't use server-side but is there a way to set up an express server with Neutralino? This to be able to use multer and receive files by POST.

**Comment by shalithasuranga** [comment]
`Neutralino.filesystem.writeBinaryFile` and `Neutralinojs.filesystem.readBinaryFile` will be available with the next release. I think you can use Blob types and get form data working with these methods since they accept/return ArrayBuffers. Using expressjs is also possible you can start your express server with `Neutralino.os.execCommand`
