### ISSUE TITLE
JSON push data

### ISSUE THREAD

**Issue by anteolic** [neutralinojs/neutralinojs#333]
I am interested in this framework but I am beginner in programming. Can somebody make simplest table crud app and/or explain me how to add data into JSON file without losing previously added data
Tnx.

**Comment by shalithasuranga** [comment]
Hey.. I think you will be able to load the existing JSON bucket content into a variable then modify it as you want. Eventually, you can save the whole object back to the same bucket. Therefore, you have old data + new content.
