### ISSUE TITLE
Neutralino JS on raspberry pi

### ISSUE THREAD

**Issue by jordan-lumley** [neutralinojs/neutralinojs#334]
Hi all, 

This is more of a feature-request if it isnt already supported but wanted to know if neutralino supports bundling/compiling down to a linux arm desktop binary, primarily the raspberry pi.

**Comment by rocarlopez** [comment]
I support this request, I think neutralinojs has a lot of advantages on embedded devices, specially when there are limited performance specs

**Comment by jordan-lumley** [comment]
@rocarlopez I liked the original idea of neutralino, however, couldn’t really wait around for a response so I decided to go with Lorca. I tried to get a hold of them on slack and GitHub and no luck yet.

Lorca is pretty awesome, especially if you want to play around with Golang. Will continue following this however because it seems pretty ideal for small resource based systems.

**Comment by rocarlopez** [comment]
Thanks for the suggestion, I'll check Lorca too!

**Comment by shalithasuranga** [comment]
Hey.. Btw I thought njs will work on rbpy too because people run Linux on it. Can you guys let me know what kind of problems you had while running the binary ?

**Comment by jordan-lumley** [comment]
> Hey.. Btw I thought njs will work on rbpy too because people run Linux on it. Can you guys let me know what kind of problems you had while running the binary ?

I started down the route of nw.js but it didn’t appear to be really supported within nwjs. There were a couple of side projects and repos to make it run on ARM desktop but I was a little hesitant. So I didn’t go down that route as it didn’t appear to be very up to date

**Comment by tuckerchapin** [comment]
Just wanted to bump this too. 32-bit ARM support would be huge. Kinda seems like what's the point of being lightweight if not to support lightweight targets.

**Comment by Gowtham2003** [comment]
Any Update On This ?

**Comment by shalithasuranga** [comment]
Hey.. Neutralinojs's next release will work on Raspberry PI 32-bit machines. We will add 64-bit arm support via https://github.com/neutralinojs/neutralinojs/issues/593 in a future release.

**Comment by williamrijksen** [comment]
Hi,

How could I run my neutralino project on my raspberry pi 4 2GB? 
`dpkg --print-architecture` gives me a `arm64`. 

Running my project returns the following error 
```npx @neutralinojs/neu run --arch arm64
ERROR Unsupported platform or CPU architecture: linux_arm64```

**Comment by gvorster** [comment]
Any news on this. I just trtief it on Raspberry Pi 4b. "unsupported platform or CPU architecture: linux arm"
