### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by dvergeylen** [neutralinojs/neutralinojs#340]
**Expected Behavior**  
It would be cool if we could append some args when calling neutralino exec.
  
**Actual Behavior**  
I couldn't find a way to parse command line arguments and having them available on the JavaScript side.

**Steps to Reproduce the Problem**  
Not really a problem as it is more of a feature request but being able to have a flow like this would be cool:
1. `./neutralino-linux path/to/my/file`
2. Arguments become available on the client side, to call `os.filesystem.readFile(path/to/my/file, ...)` appropriately.
3. This would allow adding neutralino based programs to context menus (right click → "Open with") as this appends a filename to the called program (see [here](https://unix.stackexchange.com/a/547873)).

Plenty of other use cases could be possible.

**Specifications**  
* NeutralinoJs Version: **1.6.0** (commit `638280af`)
* NeutralinoJs CLI version: **1.8.1**
* Platform: **Linux (Debian)**

**Comment by Kerenok** [comment]
A possible solution is to encapsulate the Neutralino executable in a shell script that injects the command line arguments list as an attribute "args" of "settings.json" that will be then available to the Javascript part of the app.

**Comment by dvergeylen** [comment]
> A possible solution is to encapsulate the Neutralino executable in a shell script that injects the command line arguments list as an attribute "args" in the "globals" section of "settings.json" that will be then available to the Javascript part of the app.

Err.. No 🤨
Of course workarounds are always possible but this will always be a clunky solution not working 100% of the time (think of settings.json being read-only or the necessity to write json right without third-party libraries).

Having the ability to pour some command line arguments or even some command line options (overriding the ones from settings.json) would make `neutralino` more robust and would allow more use cases. 🙂

**Comment by shalithasuranga** [comment]
Hey.. nice to have command-line arguments. I think we can have them in Neutralino.init method like any other c, java code's main method. I think first we can add like that then we can look into overriding settings. what do you think?

**Comment by shalithasuranga** [comment]
Added NL_ARGS for Linux version.. will add to Windows 
![image](https://user-images.githubusercontent.com/18402702/103411178-a5923e80-4b94-11eb-8481-b317f984f9fe.png)

**Comment by dvergeylen** [comment]
That is AWESOME! 🎉

**Comment by shalithasuranga** [comment]
Added to Windows version as well, closed this and added to #310
