### ISSUE TITLE
Projects made with NeutralinoJS

### ISSUE THREAD

**Issue by JerryGreen** [neutralinojs/neutralinojs#344]
I just came here, and I like the idea behind the project, - to make Electron-like applications, except it's not just web apps that are able to run as desktop applications, but in addition it has the least possible size of the executable (unlike Electron apps, which don't care about that too much). Cool!

But I don't see any featured projects that are made with NeutralinoJS, and honestly that makes me very sceptic toward this project. So please share your projects you made with NeutralinoJS here in this issue!

**Comment by shalithasuranga** [comment]
Yeah agree [these](https://github.com/neutralinojs/neutralinojs-desktop-samples) are too old examples, maybe we can collect examples that use newer versions of njs.

**Comment by apollolux** [comment]
I would love to finish making a proper njs version of gtk-widget-factory but at this point need newer HTML+JS+CSS support to fine tune it.

**Comment by shalithasuranga** [comment]
Please check https://neutralino.js.org/apps/
