### ISSUE TITLE
Using multitple pipes returns empty stdout

### ISSUE THREAD

**Issue by lalilaloe** [neutralinojs/neutralinojs#345]
**Expected Behavior**  
![image](https://user-images.githubusercontent.com/9057622/102779979-72320180-4395-11eb-88ad-b26966859d51.png)
  
**Actual Behavior**  
```
        Neutralino.os.runCommand(
            'echo | set /p="Hello" | openssl base64',
            function (data) {
                console.log(data);
            },
            function (err) {
                console.error("error", err);
            }
        );
```

ouptut:
```
{
  "stdout": "\n"
}
```

I'm actually trying to use a series of commands converting an image from a package to base64 to view it inside the app. 
This is the command i use ```7z x package.zip img/test.dds -so | magick convert dds:- jpg:- | openssl base64``` The above example i simplified the issue to reproduce the same bug ```echo | set /p="Hello" | openssl base64```

I already found that using one pipe ```7z x package.zip img/image.jpg -so | openssl base64``` does not output the command, by adding ```2>&1``` i found that it did return the result ```7z x package.zip img/image.jpg -so | openssl base64 2>&1```. So clearly something is preventing it from reading the output correctly. 

In de code i see a temp file is used, https://github.com/neutralinojs/neutralinojs/blob/262283e3ba644d0a398b8638a60f704ea8c3a3fc/core-windows/src/functions.cpp#L67-L68

But if i replicate this by writing the command  output to a file usint > output.txt it does contain the commands output.

The commands work perfectly in the cmd, and also with the cmd /c command.

**Steps to Reproduce the Problem**  
 1. neu create myapp
 2. neu build
 3. neu run

**Specifications**  
* NeutralinoJs Version: 1.5
* NeutralinoJs CLI version: 1.8.1
* Platform: Windows 10

**Comment by lalilaloe** [comment]
I used a workarount, putting the command in a batch file. Then calling the batch file from the code.

`        Neutralino.os.runCommand(
            "convert.bat image",
            function (data) {
                console.log(data);
                image = "data:image/png;base64," + data.stdout;
            },
            function (err) {
                console.error("error", err);
            }
        );`

and convert.bat 
`@ECHO OFF
cmd /c 7z x %1.zip img/%1.dds -so | magick convert dds:- jpg:- | openssl base64`

**Comment by shalithasuranga** [comment]
Could you guys please check again with `neu update`. Multiple pipes should work fine. I just used multiple pipes in https://github.com/shalithasuranga/litepy
