### ISSUE TITLE
Launch error: This application has requested the Runtime to terminate it in an unusual way.

### ISSUE THREAD

**Issue by MagicalDrizzle** [neutralinojs/neutralinojs#348]
**Expected Behavior**  
The framework should launch normally.
  
**Actual Behavior**  
The program terminated with the message mentioned in the title, and then a few seconds later a window appears saying the application has stopped working.

**Steps to Reproduce the Problem**  
 1. Launch neutralio-win.exe

**Specifications**  
* NeutralinoJs Version: 1.6.0
* Platform: Windows 7 SP1

**Comment by JoaquinDecima** [comment]
Hello, I would ask you to try again with the current version and if possible use neu run to see what the console returns.

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue. We need to add support for older versions of Windows. I will close this since there is a specific issue to track it #486
