### ISSUE TITLE
xdg-open fails if appname contains whitespace - linux/browser mode

### ISSUE THREAD

**Issue by raffaelj** [neutralinojs/neutralinojs#349]
I just downloaded the latest release, tried the quick start tutorial and changed some settings in `settings.json`. When I set `"appname": "test app"`, I can run it in window mode, but in browser mode I get the error `xdg-open: unexpected argument 'app'` and the browser window doesn't open automatically. Besides the error message, I can still open the page at `http://localhost:5006/test%20app`.

**Expected Behavior**

Either a note in the docs and an internal check, that whitespaces are not allowed **or** proper escaping of the appname argument for xdg-open.

**Specifications**

* NeutralinoJs Version: 1.6.0
* Platform: OpenSUSE Tumbleweed/KDE

**Comment by shalithasuranga** [comment]
Hey.. appname is like app id. so no spaces expected. I noticed that spaces were working fine in the Windows version. So I just added to Linux too.. Thanks for reporting
Ref: https://neutralino.js.org/docs/#/configuration/settings.json?id=appname
