### ISSUE TITLE
storage - create subfolders on the fly and prevent writing to parent folders

### ISSUE THREAD

**Issue by raffaelj** [neutralinojs/neutralinojs#350]
Today I tried the storage api with sub and parent folders. I added notes about the behavior to the snippet below.

**Expected Behavior**

Subfolders should be created on the fly.

The storage driver shouldn't allow writing to parent folders.

**Actual Behavior**

Subfolders aren't created on the fly. If I want to store data, I have to create them manually before I can save in there.

The app can create and manipulate files above the storage folder.

**Steps to Reproduce the Problem**

1. Download latest release (1.6.0)
2. Add snippet to `app/assets/app.js`
3. Run app

```js
var data = {
    bucket: 'test',            // --> success:  storage/test.json
//     bucket: 'new/test',     // subfolder and file not created, but success message
//     bucket: 'exists/test',  // subfolder exists already --> success: storage/exists/test.json
//     bucket: '../test',      //  --> success: test.json is created in parent folder --> security issue

    content: {}
};

Neutralino.storage.putData(data, function () {
    console.log('Data saved to storage/'+data.bucket+'.json');
}, function () {
    console.log('An error occured while saving the data');
});
```

**Specifications**

* NeutralinoJs Version: 1.6.0
* Platform: OpenSUSE Tumbleweed/KDE Plasma5

**Comment by raffaelj** [comment]
> The app can create and manipulate files above the storage folder.

A simple woraround while using the current state would be sandboxing. I wrote a quick guide here with firejail:
https://github.com/neutralinojs/neutralinojs/issues/351#issuecomment-761211046

**Comment by shalithasuranga** [comment]
Hey.. Nice findings. Thank you. I will add a regex to validate file name.

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue. Applied a fix by adding validation for keys.
![image](https://user-images.githubusercontent.com/18402702/124284728-d61a5b80-db6a-11eb-9e58-a17638623161.png)

I think we could skip the subfolder support now because the storage API offers a very simple key-value storage.
