### ISSUE TITLE
Neutralino.os.runCommand doesn't work

### ISSUE THREAD

**Issue by PolluxFR76** [neutralinojs/neutralinojs#353]
**Expected Behavior**  
Neutralino.os.runCommand doesn't work 
  
**Actual Behavior** 
in Brower mode, I actually get the following error :
message: "An error occured while connecting with Neutralino server!"
Failed to load resource: net::ERR_CONNECTION_RESET  os/runCommand:1

**Steps to Reproduce the Problem**  

Neutralino.os.runCommand('help', 
	function (data) {
console.log(data);
	},
	function (error) {
console.error(error);
	}
);

**Specifications**  
* NeutralinoJs Version: 1.5, 1.6, 1.7
* NeutralinoJs CLI version: [neu-cli version]
* Platform: Windows 10 x64 & default browser Google Chrome

**Comment by shalithasuranga** [comment]
Hey.. could you share your code of your project. Then we will be able to look more into it :)

**Comment by PolluxFR76** [comment]
//app.js


let myapp = {
    myfunction : function () { 
	
		Neutralino.os.runCommand('ipconfig', 
		  function (data) {
			console.log(data);
		  },
		  function (error) {
			console.error(error);
		  }
		);
	
	}
};
    

Neutralino.init({
    load: function() {
        myapp.myfunction();
    },
    pingSuccessCallback : function() {

    },
    pingFailCallback : function() {

    }
});

**Comment by shalithasuranga** [comment]
Please try the latest version.
