### ISSUE TITLE
ubuntu 20.04 ppa:webkit-team/ppa 404  Not Found

### ISSUE THREAD

**Issue by webghostx** [neutralinojs/neutralinojs#356]
is this the right repository? ppa:webkit-team/ppa

in ubuntu 20.04 I get an error message. Possibly because 20.04 is not supported?
I see the most recently added distribution is Xenial at 2017

```
Ign:8 http://ppa.launchpad.net/webkit-team/ppa/ubuntu focal InRelease                 
Fehl:9 http://ppa.launchpad.net/webkit-team/ppa/ubuntu focal Release                  
  404  Not Found [IP: 91.189.95.85 80]
...
E: The repository "http://ppa.launchpad.net/webkit-team/ppa/ubuntu focal release" does not contain a release file.
N: Updating from such a repository cannot be done in a safe way, so it is disabled by default.
N: Further details on the creation of package repositories and their user configuration can be found in the manual page apt-secure (8).
```

**Comment by shalithasuranga** [comment]
Hey.. looks like GTK3 is included by default. I think Neutralinojs will be compiled without any libraries further.

**Comment by shalithasuranga** [comment]
Could you try `sudo apt install libwebkit2gtk-4.0-dev` I think even gtk is there we need to install web engine.

**Comment by webghostx** [comment]
Yes, I see now, libwebkit2gtk-4.0-dev is already the newest version (2.30.3-0ubuntu0.20.04.1).

But that's not only necessary for development, but also to be able to run the apps, right?
What are the minimum requirements for operating systems in order to run a finished app? Is there already an overview for the various OS that the corresponding libraries provide?

**Comment by shalithasuranga** [comment]
Hey.. Thanks for checking. those GTK related development libraries are needed if you need to compile the Neutralinojs framework. But for app developers and users, don't need any c++ dev libraries.

I've just updated the title of the documentation: https://github.com/neutralinojs/neutralinojs#framework-developer-guide and added some info about this problem.
