### ISSUE TITLE
Provide filesystem stream based

### ISSUE THREAD

**Issue by danielo515** [neutralinojs/neutralinojs#360]
Hello.
I want to build an app that requires streams because files will be large and some of them will be zipped, so I need to read them in chunks and process them.
However, seems the only API available is just reading the entire file into memory and providing its contents.

**Comment by shalithasuranga** [comment]
Hello.. thanks for reporting this issue. We'll release the file stream API with v4.9.0. Please check the changelog file for more details: https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#api-file-streams

Thanks :tada:
