### ISSUE TITLE
Nothing rendered but two dots

### ISSUE THREAD

**Issue by crazafimahatratra** [neutralinojs/neutralinojs#370]
I installed using neu `create myapp --template react`
When I run myapp, just two dots are displayed.

It seems like react components are not rendered.

![Screen Shot 2021-02-10 at 14 10 41](https://user-images.githubusercontent.com/4974131/107502780-30aa1f80-6baa-11eb-9431-891e340d7618.png)

**Comment by shalithasuranga** [comment]
Hey.. just checked for the existence of NL_ARGS and updated the release. now it will work with the latest version of CLI

**Comment by alphagamer7** [comment]
![image](https://user-images.githubusercontent.com/17358908/108075907-e71d7100-7090-11eb-8763-14c9af0c675b.png)
Works with latest @crazafimahatratra  
`neu --version
2.3.0
 `

**Comment by crazafimahatratra** [comment]
Heyyy, same here @alphagamer7 
Thanks @shalithasuranga 

![Screen Shot 2021-02-16 at 17 35 28](https://user-images.githubusercontent.com/4974131/108077348-7a4cab80-707d-11eb-842c-aeea76320f81.png)
