### ISSUE TITLE
Icon is not displayed in Windows

### ISSUE THREAD

**Issue by lexesv** [neutralinojs/neutralinojs#374]
Icon is not displayed in Windows

![photo_2021-02-18_15-35-49](https://user-images.githubusercontent.com/15149258/108364670-02a68a00-71ff-11eb-8116-7a99b45e236a.jpg)

**Comment by shalithasuranga** [comment]
Hey.. Could you please share settings.json file content.

**Comment by lexesv** [comment]
settings.json file from the archive neutralinojs-v1.8.0.zip

**Comment by shalithasuranga** [comment]
Ah okay. the reason is that the "iconfile" path is not correct with the `res.neu` archive (we will fix it in the next release). But that's just a sample app. The recommended way is to start developing via the CLI. Could you please try via CLI.

**Comment by lexesv** [comment]
Without res.neu, the icon is also not displayed.
 
![image_2021-02-21_12-34-46](https://user-images.githubusercontent.com/15149258/108622404-3d980000-7441-11eb-9e18-78d1fd56d36c.png)

**Comment by shalithasuranga** [comment]
Hey.. Please try the latest version. It should work
