### ISSUE TITLE
Error in Lunix: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ibrahemesam** [neutralinojs/neutralinojs#378]
when I run the app, it crashes
when checking it in the terminal, I get: "Segmentation fault (core dumped)"
here is my app: 
[ Chaty.tar.gz](https://github.com/neutralinojs/neutralinojs/files/6028230/Chaty.tar.gz)

**Comment by shalithasuranga** [comment]
Hey.. looks like your `app` folder is empty..

**Comment by ibrahemesam** [comment]
> Hey.. looks like your `app` folder is empty..

no, 
my app is the same of neutralinojs 1.7.0 release , but the difference is :
app/index.html:
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>NeutralinoJs</title>
    <link rel="stylesheet" href="/assets/app.css">
  </head>
  <body style="margin:0px;padding:0px;overflow:hidden">

    <script src="/neutralino.js"></script>


    <iframe src="../redist/index.html" frameborder="0" style="overflow:hidden;overflow-x:hidden;overflow-y:hidden;height:100%;width:100%;position:absolute;top:0px;left:0px;right:0px;bottom:0px" height="100%" width="100%"></iframe>

  </body>
</html>
`
and here is the "redist" folder: 
[redist.tar.gz](https://github.com/neutralinojs/neutralinojs/files/6032033/redist.tar.gz)
========================
when I simply open that index.html in the browser, it open normally with no error or warning
,but when I run "neutralino-linux" in terminal, It crashe with error: "Segmentation fault (core dumped)"

**Comment by Kerenok** [comment]
Neutralinojs server can't serve files that are outside the "app/assets" folder. Move "redist" there and use src="/assets/redist/index.html" for your iframe in the main index.html

**Comment by ibrahemesam** [comment]
@Kerenok thanks.. that fixed the problem ^_^
