### ISSUE TITLE
[HELP] Use of href new window

### ISSUE THREAD

**Issue by didiatworkz** [neutralinojs/neutralinojs#379]
**Expected Behavior**  
Click on a href link and open a new window or open the default browser 
I would prefer the default browser, if possible.
  
**Actual Behavior**  
Nothing happend :(

**Steps to Reproduce the Problem**  
 1. Click on a href link
![image](https://user-images.githubusercontent.com/18490798/109055568-a43a4980-76df-11eb-8b58-d4eef36e9554.png)

**Specifications**  
* NeutralinoJs Version: 1.8.0
* NeutralinoJs CLI version: 2.3.3
* Platform: Ubuntu 20.04 LTS

Sry, I'm new in this topic - I tried first electron with no success and I understand neutralinojs more.
But the whole topic nodejs is a little difficult for me.

**Comment by shalithasuranga** [comment]
Hello.. Please use [`Neutralino.os.open()`](https://neutralino.js.org/docs/api/app#appopenopenactionoptions)
