### ISSUE TITLE
storage API not work with released app

### ISSUE THREAD

**Issue by didiatworkz** [neutralinojs/neutralinojs#381]
**Expected Behavior**  
1. Start released app (linux)
2. Script loading external web resource and save it into storage (storage.putData)
3. Later another function will load the data (storage.getData)
4. Script can work 
  
**Actual Behavior**  
1. Start released app
2. Script loading external web resource and save it into storage (storage.putData)
3. Later another function will load the data (storage.getData)
-> SyntaxError: JSON Parse error: Unexpected EOF

![image](https://user-images.githubusercontent.com/18490798/109134003-dedec900-7755-11eb-9641-3a8042dd9527.png)

**Steps to Reproduce the Problem**  
write function
```javascript 
function writeData(dataString){
  let data = {
      bucket: 'printer',
      content: dataString
  }
  Neutralino.storage.putData(data,
      function () {
          console.log('Printer data refreshed');
          console.log(data);
      },
    
      function () {
          console.log('Cant update printer data');
      }
  );
}
```
loading function
```javascript
function loadPrinterList(){
  Neutralino.storage.getData('printer', //<-- Error
    function (content) {
      console.log('Loading local printer data');
      console.log(content);
...
```

**Specifications**  
* NeutralinoJs Version: 1.8.0
* NeutralinoJs CLI version: 2.3.3
* Platform: Ubuntu 20.04. LTS

I think that isn't possible to use the storage with the released version.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting .. yeah it's broken with the res.neu resource file usage implementation.. will be fixed in v1.9.0
