### ISSUE TITLE
neu run on windows gives a  'nlohmann::detail::type_error'

### ISSUE THREAD

**Issue by limenleap** [neutralinojs/neutralinojs#385]
**Expected Behavior**  
It is supposed to work :-)
  
**Actual Behavior**  
E:\apps\neutralino\unboxmail>neu run
ERROR [../core-shared/settings.cpp:getSettings] std::exception
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null

**Steps to Reproduce the Problem**  
Just do everything as per the documentation. 
the final step is 
neu run 
executed in the correct folder

**Specifications**  
* NeutralinoJs Version: 1.9
* NeutralinoJs CLI version: 2.4.0
* Platform: [Platform specifications] 
Windows 10 Home

**Comment by ppritesh** [comment]
same issue with me

**Comment by shalithasuranga** [comment]
Hey.. Could you guys try `neu update` and `neu run`. I've updated the latest version with the fix

**Comment by limenleap** [comment]
Sorry, it still does not work. Now I get a nice popup stating that Neutralino has started buy I cant connect to that port 5000 

![image](https://user-images.githubusercontent.com/20351066/110203286-5ec20d00-7e93-11eb-96ab-791f3f617756.png)

**Comment by shalithasuranga** [comment]
Hey.. that nice popup is the application :smile: .. Btw not sure why it fails on Chrome.. `http://localhost:5000/unboxmail` also failts.. maybe you could also try to set `appport` to `0`.. Then a random port will be used.

**Comment by ppritesh** [comment]
@shalithasuranga  Thanks! Now, it is working..

**Comment by limenleap** [comment]
Sorry, still does not work. I tried using Telnet to see if anything is going on; but Telnet does not respond 
https://www.the-art-of-web.com/system/telnet-http11/

No idea what to try next

**Comment by shalithasuranga** [comment]
@limenleap  Please download the v2 version. We tested with different computers. you can update binaries with `neu update`
