### ISSUE TITLE
ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.

### ISSUE THREAD

**Issue by acidtumbleweed** [neutralinojs/neutralinojs#386]
**Expected Behavior**  
Attempting to run & build an app newly created via "neu create" should work and result in a default neutralinojs application instance.
  
**Actual Behavior**  
"neu run" & "build" commands results in errors, here is what the the log yields:

ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.
ERROR [src/settings.cpp:getSettings] std::exception

**Steps to Reproduce the Problem**  
 1. Fresh Windows 10 Home Install
 2. Fresh neutralinojs install
 3. Create a new app with neutralino via the command: "neu create myapp --template js"
 4. Build the app with "neu build", the log will display errors
 5. If you instead do "neu run", the CMD prompt displays the res.neu error, a black window pops up but the application is not rendered or responsive.

**Specifications**  
* NeutralinoJs Version: 2.3.3
* NeutralinoJs CLI version: Not sure how to check
* Platform: Windows 10 Home x64, Intel Based

**Comment by shalithasuranga** [comment]
Hey.. Could you please try "neu update" and "neu run".. I've just updated the release

**Comment by acidtumbleweed** [comment]
Hey Shalitha,

Thanks for the response! Unfortunately after trying the steps you mentioned, I am still seeing these errors when attempting to run the compiled executable:

ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.
ERROR [src/settings.cpp:getSettings] std::exception

I might try completely removing neu and re-installing from scratch.

**Comment by QWART** [comment]
**acidtumbleweed**, 
After "neu create", run "neu release". The directory "dist" will be created in the working directory. Inside there will be a directory with a release, in which there will be a file "res.neu".

**Comment by acidtumbleweed** [comment]
> **acidtumbleweed**,
> After "neu create", run "neu release". The directory "dist" will be created in the working directory. Inside there will be a directory with a release, in which there will be a file "res.neu".

This did it, thank you!
