### ISSUE TITLE
User-agent

### ISSUE THREAD

**Issue by enriicsolaa** [neutralinojs/neutralinojs#396]
Anyway to set user-agent of the program? Thanks

**Comment by shalithasuranga** [comment]
Hey.. Could you please explain a bit further. Do you mean the user-agent header value is not set?

**Comment by Soliikaa** [comment]
I am looking for a way to change user-agent header value, and costumize it with code. It is not implemented yet in neutralino?

**Comment by startupgurukul** [comment]
Before load of web view  if you can inject js, you can try this,

https://gist.github.com/thorsten/148812e9cc4fb6a19215ce22afd4e5a8
