### ISSUE TITLE
Request to run as administrator

### ISSUE THREAD

**Issue by nguyentienlinh2611** [neutralinojs/neutralinojs#397]
How can I make request to run app as administrator?

**Comment by shalithasuranga** [comment]
Hey.. as usual, `sudo ./yourappname` works. If you are on Windows, you could right-click and choose run as admin. Then `os.execCommand` can run super user commands.
Eg: `sudo apt-get check`

**Comment by DevEarley** [comment]
Using Resource Hacker, you can add the following to the app.manifest file
``` xml
  <trustInfo>
   <security>
    <requestedPrivileges>
     <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
    </requestedPrivileges>
   </security>
  </trustInfo>
```

**Comment by shalithasuranga** [comment]
Closing this since the question has beed answered already. Thanks for discussing this :tada:
