### ISSUE TITLE
 Build location into existing svelte project

### ISSUE THREAD

**Issue by rchavezj** [neutralinojs/neutralinojs#398]
This is a follow up from neutralinojs-svelte
https://github.com/neutralinojs/neutralinojs-svelte/issues/7

I want to include neutralinojs into an existing svelte project

After building neutralinojs-svelte from executing 'npm run build', do we place the build folder/file inside our node_modules or root into a new svelte project?

**Comment by shalithasuranga** [comment]
Please notice that now there are no pre-built templates for Neutralinojs. But you can easily integrate Svelte with Neutralinojs. You can check Reactjs + Neutralinojs example from [here](https://github.com/shalithasuranga/litepy). Svelte also similarly can be integrated.
