### ISSUE TITLE
Starting problems, feedback, suggestion

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#399]
In the docs at https://neutralino.js.org/docs/#/gettingstarted/firstapp it is sugessted to do `neu create --template hello-world`.

This causes error `error: missing required argument 'name'`

When i add a name like `neu create --template hello-world helloworld` it causes error `Unable to find template hello-world`.

This happens on linux and windows.

When i do just `tns create helloworld` everything is created fine. Just on windows the app/assets/app.js file is minified, which is pretty bad for a start.

Also: do i have to enable hardware accelaration or something on linux? Cause when i run an editor script of mine in firefox or chrome on linux its very smooth, but when i open it in neutralino it starts to eat up the cpu.

i also suggest on the readme.md you add the `neu run` and `neu release` commands as short description for very quick starters.

**Comment by shalithasuranga** [comment]
Hello.. Thanks for your suggestions and feedback. The correct command is `neu create hello-world` and I've updated the documentation. Also we can use pre-built templates too. For example, `neu create hello-world --template react`

Please check following answers for your questions/

1. Regarding `app/assets/app.js`

In neutralinojs v1,x, `app/assets` is fixed for resources. On the other hand, v2 supports loading resources from any folder inside the project. Also, In the JavaScript template, `src` will contain the un-minified source and `app/assets/app.js`  will contain the minified code (That will be loaded to the app). In v2. templates may use maybe `./dist` for minified files. That will less confusing I think.

2. Regarding memory

On Windows? Windows version of Neutralino v1.x uses IE browser component, not Edge. Maybe that's the problem. I tried to integrate Edge. It was successful, But there is a security issue. Maybe you can check https://github.com/neutralinojs/neutralinojs/issues/147 's last comment. 

3. The CLI's documentation is [here](https://neutralino.js.org/docs/#/tools/cli) :)

**Comment by einicher** [comment]
2. No memory problem is on linux, on windows i did not yet get that far. I made an editor with ace editor and when i scroll it lag and cpu goes haywire.

3. I ment here on github in the main readme, i think its best to put all commands there someone needs who is fast checking if neutralino is running in his prefered environment. From what i understood so far it would be something like:

```
# npm i -g @neutralinojs/neu
$ neu create hello-world
$ cd hello-world
$ neu run
```
And maybe a picture of the to be expected first result.

Btw: when i do this my result looks like this with an alert:
![grafik](https://user-images.githubusercontent.com/948188/112845104-c8a19100-90a4-11eb-8577-539fb6353574.png)

Not very appealing for a first run, but ok. I would expect there an "It works!" or "Hello World!" with the neutralino logo or something. Looks a little like an error message this way. Its not important, just giving feedback.

**Comment by einicher** [comment]
@shalithasuranga other question: why Internet explorer or edge at all?
On linux you use webkit, isnt that available for windows too?

**Comment by shalithasuranga** [comment]
Hey.. Regarding the latest question. v2 (new version) uses Edge or Chromium on Windows depending on the available one. Neutralino will use the existing browser library, if we ship a browser (let's say gtk), again it becomes electron-like. :)

**Comment by einicher** [comment]
how do i get `neu create` to create a v2 project?
do i need to install another npm package?

**Comment by shalithasuranga** [comment]
Hey, @einicher  Now you can use the latest cli version to try v2.  Please check https://github.com/neutralinojs/neutralinojs-cli

**Comment by einicher** [comment]
@shalithasuranga Thanks, but i only get a white window:

![grafik](https://user-images.githubusercontent.com/948188/113402702-bde94380-93a5-11eb-904f-a546777e979e.png)

No error, empty log. Just a white window.

**Comment by shalithasuranga** [comment]
Hmm. yeah, that's expected because localhost is now allowed by default for UWP apps (I think this will be changed in the future). Could you run the command in https://github.com/neutralinojs/v2-specification/blob/main/webview.md

**Comment by einicher** [comment]
Yes, after running this command as administrator it works now.

`inspector: true` seems to be ignored though.

**Comment by shalithasuranga** [comment]
ah you mean enabling dev tools? I thought you already had webview2 runtime.. If you are not having webview2 runtime, Neutralino will use EdgeHTML (I think devtools support not yet added for this one . I need to check). 

Maybe you can install webview2 runtime :) https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by NemoStein** [comment]
> No error, empty log. Just a white window.
Just found Neutralinojs while searching for an alternative to Electron and got the same blank window on Windows.

> Could you run the command in https://github.com/neutralinojs/v2-specification/blob/main/webview.md
After running the command it works, but I don't expect that people will run this to execute my app.
Am I missing something?

**Comment by maxruby** [comment]
**Why I am reporting this here**
I am probably just encountering the same issue raised above and by others. However, I am hoping that we can find a way to resolve the issue of a "blank" screen on Windows 10 when starting a neutralino app win64 binary.  In my view, neutralinojs is  a welcomed alternative to electron, and I can see tremendous potential in this project if we could achieve stable results for Windows binaries :)

I built my dist binaries on my work Ubuntu 20.04 laptop and everything worked well on that platform.
I could run both the dist  `linux_x64`  binary on Ubuntu and  the `mac_x64` binary on my MacBook Pro., which  is great news.

However, when running the `win_x64` binary on my Windows laptop,  I see the same kind of empty screen shown in https://github.com/neutralinojs/neutralinojs/issues/399#issuecomment-812449540.

Here are the specs of the laptop:
- HP Intel i5
- Windows 10 Home
-  4GB RAM

An error  trace is logged in the Windows Event viewer when the .exe fails to run properly (white screen):

```
      Win32WebViewHost.exe
      10.0.17134.1
      ed1839dd
      CoreUIComponents.dll
      10.0.17134.376
      68dfa668
      c0000005
      0000000000083d22
      2790
      01d79dd2ed95c63b
      C:\Windows\SystemApps\Microsoft.Win32WebViewHost_cw5n1h2txyewy\Win32WebViewHost.exe
      C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
      820613ed-c888-4a4a-a665-721c3dba5f0a
      Microsoft.Win32WebViewHost_10.0.17134.1_neutral_neutral_cw5n1h2txyewy
      Win32WebViewHost
```

**What I tried already and did not help**
-  I ran the following in the Windows Shell with admin rights 
```
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
```

**My questions**
-  How can I further debug this?  
- What else should /could I could I try to get this to work?

**Comment by shalithasuranga** [comment]
Hey.. thanks for all suggestions and ideas. I am closing this issue since the original case mentioned by this issue is resolved and some things are no longer valid with the latest version of Neutralinojs. Feel free to open an issue for other problems/ideas. :)
