### ISSUE TITLE
Does the v2 support win7?

### ISSUE THREAD

**Issue by yoki0805** [neutralinojs/neutralinojs#403]
I try to launch the exe, it gives an error:
The procedure entry point SetProcessDpiAwarenessContext could not be located in the dynamic link library USER32.dll.

And I search this method on MSDN:
Minimum supported client : Windows 10, version 1703 [desktop apps only]
Minimum supported server : Windows Server 2016 [desktop apps only]

Is it possible to avoid using this method? There are still many users using win7 today.

**Comment by shalithasuranga** [comment]
Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486  open until we apply a fix. Thanks
