### ISSUE TITLE
os.runCommand is not implemented in the Neutralinojs server (v2) - With Fix(?)

### ISSUE THREAD

**Issue by Farmers-Tyler-Dougherty** [neutralinojs/neutralinojs#406]
**Expected Behavior**  
When using Neutralino.os.execCommand() I expect to get a valid return
  
**Actual Behavior**  
When using Neutralino.os.execCommand() I receive error "os.runCommand is not implemented in the Neutralinojs server".  Looking into the neutralino.js file I noticed that the code for "execCommand" references the url "runCommand" which appears to be invalid.  Upon changing it to "execCommand" the code runs successfully.

**Steps to Reproduce the Problem**  
 1.  Install with: npm i -g @neutralinojs/neu
 2. Create proj with: neu create hello-world
 3. Use execCommand and listen on onError callback
 ``` JavaScript
 Neutralino.os.execCommand({
    command: cmd, 
    onSuccess: (data) => {
        console.log(data);
    },
    onError: (error) => {
        console.log(error|'error');
    }
});
 ```

**Specifications**  
* NeutralinoJs Version: v2.0.0
* NeutralinoJs CLI version: 3.0.2
* Platform: [Platform specifications] Windows 10 64-bit

**Comment by shalithasuranga** [comment]
Ah looks like the released client source having some old stuff. I will update it. Thank you very much for reporting the bug.

**Comment by shalithasuranga** [comment]
Now it should work.. with `neu create`
