### ISSUE TITLE
debug.Log() missing message text (v2)

### ISSUE THREAD

**Issue by Farmers-Tyler-Dougherty** [neutralinojs/neutralinojs#407]
**Expected Behavior**  
When calling Neutralino.debug.log() and passing `{type: 'INFO', message: 'Log file test'}` I expect the log to contain the message text
  
**Actual Behavior**  
Log file does create entry containing the 'type' but is missing message text `INFO [src/api/debug/debug.cpp:log] `

**Steps to Reproduce the Problem**  
 1. Use function
 2. Examine log file `neutralinojs.log`

**Specifications**  
* NeutralinoJs Version: v2
* NeutralinoJs CLI version: v3.0.2
* Platform: Win10 64-bit

**Comment by shalithasuranga** [comment]
Thanks for checking the issue further. on Linux, seems like it's working fine, as shown below.
![image](https://user-images.githubusercontent.com/18402702/114259002-6f145d00-99e8-11eb-9a01-a64449ad0acd.png)

Windows reuses the same logging library. I will check further this issue on Windows with your above question :)

**Comment by Farmers-Tyler-Dougherty** [comment]
Hmm, does your local log file look correct as well? I'll test my edit in your lib on Monday to see if it exports in the console like your screenshot.

**Comment by Farmers-Tyler-Dougherty** [comment]
@shalithasuranga Do you know the location of the backend server code on the local machine?  I'm attempting to modify the logging code, but I'm not finding the source files it's using.

**Comment by shalithasuranga** [comment]
Hey.. I decided to integrate a logging library (https://github.com/neutralinojs/neutralinojs/issues/437). Hopefully, this issue can be resolved soon.

**Comment by shalithasuranga** [comment]
Hey.. everyone.. Please update your neu CLI and use `neu update`. Now we have a new logging library. working fine seems on Windows too. Closing the issue.
