### ISSUE TITLE
Run As Administrator causes failure to load (v2)

### ISSUE THREAD

**Issue by Farmers-Tyler-Dougherty** [neutralinojs/neutralinojs#408]
**Expected Behavior**  
Right-click > run as administrator should launch the app successfully.
  
**Actual Behavior**  
Right-click > run as administrator option on win.exe causes the application to not load.  This behavior is noticed in both my custom test app and the default template (neu create [name]).
![proof](https://user-images.githubusercontent.com/82057181/114102417-e3d28480-988c-11eb-8329-426ed7b82da1.png)

**Steps to Reproduce the Problem**  
 1. `neu create *name*`
 2. cd into app and run `neu build`
 3. navigate to dist folder and right-click > run as admin on the newly created .exe file

**Specifications**  
* NeutralinoJs Version: 2.0.0
* NeutralinoJs CLI version: 3.0.2
* Platform: Win 10 64-bit

**Comment by shalithasuranga** [comment]
Without admin mode, it's working?

**Comment by Farmers-Tyler-Dougherty** [comment]
> Without admin mode, it's working?

Correct, the application runs just fine w/o admin mode.  I require admin mode due to certain shell commands I'm running.

**Comment by Farmers-Tyler-Dougherty** [comment]
It seems somewhat similar to what happens prior to running the command: 
`CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"`

**Comment by shalithasuranga** [comment]
Hmm yeah.. that's required for the users too I think projects that use webview2 runtime, surely run this code during the installation otherwise those apps also won't work. Probably, this will change with the newest windows updates. The reason is that the neutralino server will run in the background to serve resources and perform native operations. It's somewhat like a lightweight Apache server.

**Comment by Farmers-Tyler-Dougherty** [comment]
Yeah that makes sense. I attempted running the command in an elevated (run as admin) cmd shell, but I'm still unable to get it to render properly.  The window size is not correct when using run as, so I assume this means the browser is not able to read in the config file.  

Is there some other way I should run the command so it will work with run as admin?

**Comment by Farmers-Tyler-Dougherty** [comment]
@shalithasuranga I just tested Tauri and I'm having the same issue with it as well.  Seems like we might have a root cause of WebView2 not working correctly when Run As Admin.

**Comment by Farmers-Tyler-Dougherty** [comment]
@shalithasuranga Well, good news / bad news. I was able to fix the issue by installing the[ Evergreen Runtime for WebVew2](https://go.microsoft.com/fwlink/p/?LinkId=2124703).  This is obviously not idea, but I think it suggest the issue is with the current stable version of Edge.

**Comment by Farmers-Tyler-Dougherty** [comment]
@shalithasuranga Ok... last note on this I think. I've installed the Edge Beta (90.0.818.27) and run as admin is working in that too.  I feel as though we'll just have to wait for release on this issue, or I'll need to package an installer for WebVew2 v90 into my project.  On the bright side it doesn't appear to be your stuff.

Really enjoying Neutralino, keep up the good work.

**Comment by shalithasuranga** [comment]
Thank you very much I will definitely include these findings to the new documentation. The current documentation is outdated.
