### ISSUE TITLE
Ask: Set Minimum or Maximum Window size?

### ISSUE THREAD

**Issue by nekkiichi** [neutralinojs/neutralinojs#415]
I wanted to prevent the program from shrinking and enlarging too much when resizing by giving parameters like _minWidth_ or _maxWidth_, but it doesn't seem to work. I didn't find it in the official documentation either. has the minimum and maximum configuration window size been implemented?

**Comment by shalithasuranga** [comment]
Hey. Thanks for reporting the issue. This one looks like a new feature because currently we only have `width` and `height` attributes regarding resizing a window.

**Comment by tizi24** [comment]
Hi, add these features, they would be very useful to port my app to neutralinoJs. resizable, maximizable, minWidth, minHeight, maxWidth, maxHeight

**Comment by apollolux** [comment]
A note of consideration: assuming any or all of these proposed properties are implemented in Neutralino proper, in whatever docs are written for them in the future we'd need to make sure that devs who use them make sure that their apps are still designed to be just as usable on 100% scale as on non-100% scale. Mac users with Retina scaling turned on and Windows 10 users with the equivalent (it's in Settings - Ease of Access, I forget the proper name for it) will 100% notice if an app doesn't support OS-level display scaling.

**Comment by shalithasuranga** [comment]
Hey.. all thanks for the suggestions and ideas v2.3.0 has `minWidth`, `minHeight`, `maxWidth`, `maxHeight`, and `resizable`. 
I noticed `maximizable` as the same as `resizable: true`. If it is needed we can try to add with the next version.
