### ISSUE TITLE
Neutralinojs + React ?

### ISSUE THREAD

**Issue by nayots** [neutralinojs/neutralinojs#417]
Is there an official guide on how to use react with neutralinojs
I saw some roadmap post about using the cli but found nothing in the documentation.
https://neutralino.js.org/docs/developer-environment/cli

How can we create and use the latest version of neutralino with react ?

**Comment by Efrainq07** [comment]
I tried to follow the steps mentioned [here](https://www.youtube.com/watch?v=TreJXBarK6k) for AngularJS (adapted to work with ReactJS). I wrote the steps on issue #428 but they did not work. It'd be nice to get some support on this.
I'd be happy to help making a boilerplate template for reactjs

**Comment by shalithasuranga** [comment]
Please check this YouTube playlist: https://www.youtube.com/watch?v=txDlNNsgSh8&list=PLvTbqpiPhQRb2xNQlwMs0uVV0IN8N-pKj&ab_channel=CodeZri
