### ISSUE TITLE
window.fetch not working

### ISSUE THREAD

**Issue by hpgiorgio** [neutralinojs/neutralinojs#419]
**Expected Behavior**  
window.fetch({
                url: "https://www.....",
                data: {
                    headers: new Headers({ "Content-Type": "application/json"}),
                    body: JSON.stringify({}),
                    method: "POST",
                    mode: 'cors',
                    cache: 'no-cache',
                    credentials: 'omit',
                    redirect: 'follow',
                    referrerPolicy: 'no-referrer'
                }
            });
  
**Actual Behavior**  
Neutralino js makes a call to localhost.

**Comment by shalithasuranga** [comment]
This is probably due to the missing CORS headers. If you can update headers please try to update headers. Otherwise, we need to wait for https://github.com/neutralinojs/neutralinojs/issues/586 (closing as a duplicate issue). Thanks for reporting this issue :)
