### ISSUE TITLE
[v2.0.0-pre, Win] Unpackaged resource updates not respected

### ISSUE THREAD

**Issue by apollolux** [neutralinojs/neutralinojs#420]
**Expected Behavior**  
Changes to the directory structure and/or its files should be reflected upon next run of neutralino-win.exe app.
  
**Actual Behavior**  
The app remains with default content.

**Steps to Reproduce the Problem**  
 1. Download the v2.0.0 tagged pre-release version. I had downloaded a copy on April 3 which was a larger zip (1,434,438 bytes) than one I downloaded April 16 (1,395,219 bytes). The older one had res.neu, a default config file, and a default resources folder that the newer zip lacks.
 2. Modify any of the resource files and/or the config, like change the title.
 3. The window content remains the default HTML/CSS/JS without reflecting any changes in any files.

**Specifications**  
* NeutralinoJs Version: 2.0.0-pre (both from Apr 3 and Apr 16)
* NeutralinoJs CLI version: none
* Platform: Windows 10, one 20H2/19042 with Edge Chromium and one 1903/18362 with pre-Chromium Edge

**Notes**
I haven't yet familiarized myself with the new neu CLI-based method of developing a neutralino app, and am intentionally doing everything manually by copying the neutralino-win binary, config file, and resources into a folder without running any neu CLI functions. I opened res.neu in a hex editor and with slight edits confirmed that the content embedded is indeed what is being read by neutralino-win.exe when running, and all of the edits to the local files in the same directory are being ignored. Removing/renaming res.neu results in neutralino-win not opening anything.

The 20H2 machine has Node.js but I haven't yet installed the latest neu CLI package. The 1903 machine is a tablet, does not have Node.js, and I intend to keep it that way. I haven't yet had the opportunity to go through the latest updates to the neu CLI code or to the binaries, but so far it looks like there's an arg `--load-dir-res` that has to explicitly be passed to neutralino-win in order to run without res.neu. This seems to be what I'm looking for, but I have issues with this approach:

1. The neutralino-win binary expects res.neu to exist by default
2. If res.neu is absent and neutralino-win is opened without the `--load-dir-res` argument then simply nothing runs rather than trying to run as if the argument was passed
3. There is no obvious feedback/indication of what goes wrong in any of these scenarios

If res.neu is absent then I vote that neutralino-win's default behavior be to run as if `--load-dir-res` was passed. If neither res.neu nor a valid config are found by neutralino-win regardless of `--load-dir-res` then there should be a clear system error dialog saying something like "No valid application data nor config found" or something to that effect, and may need to be language localizable. If both res.neu and a valid config are found then begrudgingly I'd have to vote for res.neu taking priority if `--load-dir-res` isn't used.

For reference, I understand now that res.neu is packaged by asar during build, limiting the ability to create it manually and forcing the neu CLI or other similar asar-based packager into the development workflow. I can see the pros and cons of this decision, but it hampers developing on a machine that doesn't have Node.js if `--load-dir-res` isn't the binary's behavior when res.neu is absent.

**Comment by shalithasuranga** [comment]
Hey.. @apollolux  Thanks for trying Neutralinojs again. This is indeed a great idea. Right now, if the `res.neu` is missing and the process is started with a double click, it's hard for users to identify the real problem. We can conditionally load resources depending on the existence of `res.neu` as you mentioned.

**Comment by shalithasuranga** [comment]
A new error message added. It will be displayed when Neutralino cannot load config from either res.neu or directory. Also, if use double-clicked on the binary when there is no res.neu, Neutralino automatically adds `--load-dir-res`

Thanks @apollolux This is a great idea.
