### ISSUE TITLE
[v2.0.0-pre, Win] Borderless app doesn't support -webkit-app-region

### ISSUE THREAD

**Issue by apollolux** [neutralinojs/neutralinojs#421]
**Expected Behavior**  
The `-webkit-app-region` CSS property supported by Chromium/CEF apps like Electron should theoretically be supported in the Chromium-based WebView2, both `drag` and `no-drag` values.
  
**Actual Behavior**  
Setting `-webkit-app-region: drag` on a borderless Neutralino app has no effect and does not allow dragging the window. 

**Steps to Reproduce the Problem**  
 1. Set some element's CSS to include `-webkit-app-region: drag;` `body` or a top-level `header` are good candidates for such
 2. Set the borderless config to true
 3. Run the app and try to drag the window around by the element(s) set in step 1.

**Specifications**  
* NeutralinoJs Version: v2.0.0-pre
* NeutralinoJs CLI version: none
* Platform: Windows 10

**Notes**
Now that the Windows version can use WebView2, unless otherwise noted by Microsoft I assume the system Chromium that Edge/WebView2 uses is fully featured and has support for the relevant `-webkit-app-region` property. It'd be pretty pointless to implement borderless/frameless without the ability to add an alternative method to drag the window like Electron can.

**Comment by r0hin** [comment]
Any word on this?

**Comment by shalithasuranga** [comment]
Hey.. @r0hin I will check this one after https://github.com/neutralinojs/neutralinojs/issues/516

**Comment by shalithasuranga** [comment]
Hey.. this is implemented but in a bit different way than Electron. The following method will make any DOM element a draggable region.

```js
await Neutralino.window.setDraggableRegion("yourDomId");
```

**Comment by extorc** [comment]
@shalithasuranga when I write this line in the `main.js` , the element doesn't become draggable , but a block sign appears whenever I try to move the window from that element
