### ISSUE TITLE
Using 'Require' in javascript?

### ISSUE THREAD

**Issue by bmcgonag** [neutralinojs/neutralinojs#425]
This is just a question: I saw a previous question about the older version not supporting 'require' and it was stated that because it doesn't use NodeJS it didn't support 'require' at the time. 

Can you please let me know if this is still true? 

Seems like loading it with NPM means it's node capable now, but I still get an error when trying to use 'require'.

Thanks,

**Comment by shalithasuranga** [comment]
Hey @bmcgonag  sorry for the delayed response. `require` is not a standard module loader method in JavaScript. It belongs to Nodejs and Neutralinojs doesn't use a Nodejs instance for its applications. Therefore, developers can't use either Nodejs libraries or `require`. But it's possible to use `import` even if you not using a frontend framework to build Neutralinojs apps.

Check the following example

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>NeutralinoJs</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <script src="js/neutralino.js"></script>
    <script type="module" src="js/main.js"></script>
  </body>
</html>
```

**js/main.js**
```js
import {add} from "./testimport.js";

Neutralino.init();
console.log(add(5,7));
```

**js/testimport.js**
```js
export function add(a, b) {
    return a + b;
};
```

You can import npm modules using the same approach. In other words, Neutralino can run npm modules with `import` but not with `require`.
