### ISSUE TITLE
Not getting any data for response.stdout with Neutralino.os.execCommand

### ISSUE THREAD

**Issue by bmcgonag** [neutralinojs/neutralinojs#426]
**Expected Behavior**  
Running from API example with Neutralino.os.execCommand I expect the command provided to return result in the object to be accessible. 
  
**Actual Behavior**  
I can see the response object has layers as: 
    promise
      results:
        {
          stdout: "some information",
          process: "200 OK"
        }
    ...

**Steps to Reproduce the Problem**  
 I cannot get the response.stdout to give the proper information using Linux 20.04 (Ubuntu).

Am I addressing the object incorrectly?  I'm using the same object as in the example for the API.

**Comment by renton16** [comment]
Something happened to me. I only got _[object Promise]_,  it just that I didn't put the code in an **_Async_** function and the command in _**await**_ state.

**Comment by shalithasuranga** [comment]
Hey.. Could you please try with neu update. Now it's `output` (not `stdout`). output = stdout + stderr

**Comment by bmcgonag** [comment]
hello, did 
    npm install -g @neutralinojs/neu

this morning to update, then changed my code to have response.output instead of response.stdout.

When I run it, i still get "Undefined". 

Here's my code. 

```
window.myApp = {
    showInfo() {
        let response = Neutralino.os.execCommand({
            command: 'dig +short myip.opendns.com @resolver1.opendns.com'
        });

        console.dir(response);
        console.log(`Your IP is:  ${response.output}`);
        document.getElementById('info').innerHTML = "<span>" + response.output + "</span>";
    },
};

Neutralino.init();
window.myApp.showInfo();

````
and here is the output in the console:

```
Promise
    result: {stdout: "68.206.155.103↵", success: true}
    status: "resolved"

Promise Prototype                                                                                    showInfo — main.js:8
Your IP is:  undefined
```

Any help is greatly appreciated.

**Comment by shalithasuranga** [comment]
Hey could you please try using await as in the documentation

**Comment by Blatman** [comment]
Probably too late but chances are that the above example may work OK using .then - I had a similar issue and the result was undefined because it was being run before the completion of the Promise. In my case I was wanting to kill a server process that had been started previously for an Express server -

                let checkPid = Neutralino.os.execCommand({
                    command: 'lsof -t -i tcp:5000'  // -t is Terse result giving PID of Express server only
                }).then(function(checkPid) {
                    var servPid = checkPid.output  // eg:  5729
                    Neutralino.os.execCommand({
                        command: 'kill -9 ' + servPid   // eg: 'kill -9 5729'
                    });

                    setTimeout(function() {
                        Neutralino.app.exit();
                    }, 200);

                });
 I used this rather than await which would require the use of a wrapping async function.

Cheers.
