### ISSUE TITLE
Is there a recommended way to run a ReactJS frontend with the template neutralinojs?

### ISSUE THREAD

**Issue by Efrainq07** [neutralinojs/neutralinojs#428]
**Expected Behavior**  
After creating a react app with the template page and adapting the modifications made for angular in this [video](https://www.youtube.com/watch?v=TreJXBarK6k) the template react page should be shown.

**Actual Behavior**  
A blank page is shown.
![image](https://user-images.githubusercontent.com/33973526/115763003-aaf4de00-a369-11eb-877d-36d708080096.png)

**Steps to Reproduce the Problem**  
I tried the following:

- Creating a react project inside the `neutralinojs-minimal` folder. 
- Then adding the `neutralinojs` script to the `index.html` created inside the react project. 
- After that I changed the `url` and `resourcesPath` inside the `neutralino.config.json` file so that they now redirect to the `public` folder of the react project.
- FInally I ran `neu run` on the root of the project.
This only leads to a window opening with a blank page. How can I use ReactJS with this new version of neutralino? 

**Specifications**  
* NeutralinoJs Version: 3.0.3
* NeutralinoJs CLI version: [neu-cli version]
* Platform: Linux Ubuntu 16.04

**Comment by shalithasuranga** [comment]
Please check: https://youtu.be/4WAur8r7Jhk
