### ISSUE TITLE
Neutralino.app.exit() doesn't close the app. Ubuntu 20.04.

### ISSUE THREAD

**Issue by MindSetFPS** [neutralinojs/neutralinojs#434]
**Expected Behavior**  
The application should be terminated.
  
**Actual Behavior**  
The application keeps open, but using the GTK buttons works fine.

**Steps to Reproduce the Problem**  

`let killApp = async () => {
    try {
        console.log('closing')
        await Neutralino.app.exit()
    }
    catch (e) {
        console.log(e)
    }
}`

**Specifications**  
* NeutralinoJs Version: [2.0]
* NeutralinoJs CLI version: [3.0.3]
* Platform: [Ubuntu 20.04]

**Comment by shalithasuranga** [comment]
Thanks for reporting. I will check this asap.

**Comment by shalithasuranga** [comment]
There was an issue with the client source..  Now it has been fixed. Please try with `neu create` or simply updating `neutralino.js` file from https://github.com/neutralinojs/neutralinojs-minimal
