### ISSUE TITLE
ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal

### ISSUE THREAD

**Issue by huqings** [neutralinojs/neutralinojs#435]
ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal

**Comment by JoaquinDecima** [comment]
I have this error too

**Comment by 25juan** [comment]
I have this error too (+1)

**Comment by shalithasuranga** [comment]
Hey.. The macOS version is not working with v2 implementation. Please check https://github.com/neutralinojs/neutralinojs/issues/395

**Comment by JoaquinDecima** [comment]
The error I have in Linux

**Comment by shalithasuranga** [comment]
@JoaquinDecima Oops that's a bit strange. Are you trying with the latest neu CLI and with `neu run` ?

**Comment by JoaquinDecima** [comment]
I compile the master branch, I don't use neu cli because I need to add some functionalities (and I only need for linux)

**Comment by ibandominguez** [comment]
Same issue here too! running on macos!

**Comment by DavidLibeau** [comment]
Same here with the basic example on MacOS using the neu cli!

**Comment by myluna08** [comment]
Same issue on macOS 11.3.1 (20E241)

ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
libc++abi: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null

Application was terminated.

**Comment by myluna08** [comment]
> Same issue on macOS 11.3.1 (20E241), nom 7.13.0, neu 3.0.5
> 
> ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
> libc++abi: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null
> 
> Application was terminated.

For everybody in MAC a solution is to use 2.0 framework, just do the following
npm install -g @neutralinojs/neu@2.0

that was commented in #442

**Comment by shalithasuranga** [comment]
Please try with the latest CLI. macOS v2 version is ready :)
