### ISSUE TITLE
App does not run on windows 8, shows missing dll.

### ISSUE THREAD

**Issue by hemroy21** [neutralinojs/neutralinojs#436]
**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework]1.9.0
* NeutralinoJs CLI version: [neu-cli version] 3.0.4
* Platform: [Platform specifications] Windows 8 x64

>> Neutralinojs app not start on windows 8, shows missing dll error.
The following dll's required,
1. api-ms-win-core-file-l1-2-2.dll
2. api-ms-win-core-file-l1-1-0.dll
3. api-ms-win-core-libraryloader-l1-2-0.dll
4. api-ms-win-core-libraryloader-l1-2-2.dll
5. api-ms-win-core-winrt-error-l1-1-1.dll

But then after collecting all dlls and pasting inside application folder(temporary setup) the following message appeared about DPI awareness context error.

Is the built only for windows 10 or for other previous version like windows 7?

Here is the screenshot, of the error message.
![Screenshot (299)](https://user-images.githubusercontent.com/83438329/116872296-41ab7f80-ac33-11eb-8996-7c64cc7374ec.png)

**Comment by shalithasuranga** [comment]
Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486  open until we apply a fix. Thanks
