### ISSUE TITLE
Window mode does not work

### ISSUE THREAD

**Issue by CitizenFoffie** [neutralinojs/neutralinojs#439]
**Expected Behavior**  
Shows the code in the application, it works if I do browser mode but no window  
**Actual Behavior**  
Blank Screen

**Specifications**  
* NeutralinoJs Version: Newest
* NeutralinoJs Newest
* Platform: Windows 10

**Comment by renton16** [comment]
Try to run this code on CMD, from https://github.com/neutralinojs/neutralinojs/issues/408#issuecomment-816775271 

`CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"`

**Comment by shalithasuranga** [comment]
Yeah @renton16 .. 
@CitizenFoffie  Please check https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app
