### ISSUE TITLE
Chinese garbled window title

### ISSUE THREAD

**Issue by 25juan** [neutralinojs/neutralinojs#440]
**Expected Behavior**  
show Chinese  title.
  
**Actual Behavior**  
Chinese  garbled

**Steps to Reproduce the Problem**  
![E5HD~2{L9Q2VC)IU_%%FG29](https://user-images.githubusercontent.com/14308183/117087516-46cb1480-ad82-11eb-95a7-9feff6078246.png)
![image](https://user-images.githubusercontent.com/14308183/117088326-c528b600-ad84-11eb-9e73-fe954e3177c1.png)

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework]
v2.0.0
* NeutralinoJs CLI version: [neu-cli version]
 3.0.4
* Platform: [Platform specifications] 
window10

**Comment by chenbimo** [comment]
+1

**Comment by chenbimo** [comment]
had somebody resolve it ?

**Comment by chenbimo** [comment]
+1

**Comment by shalithasuranga** [comment]
I am closing this since Unicode support was added to the Windows version of Neutralinojs. Thanks :)
