### ISSUE TITLE
Error compiling master branch for linux

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#441]
**Expected Behavior**  
The compilation turns out fine. But when I open the binary through the terminal I get errors.
  
**Actual Behavior**  
Next the errors obtained after executing the binary 

Terminal:
```bash
ERROR [../core-shared/resources.cpp:makeFileTree] resources::makeFileTree error: ./res.neu is missing.
ERROR [../core-shared/settings.cpp:getConfig] std::exception
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
[1]    235768 abort (core dumped)  ./neutralino
```

Logs:
```log
ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.
ERROR [src/settings.cpp:getSettings] std::exception
```

**Steps to Reproduce the Problem**  
 1. Clone project master ```git clone https://github.com/neutralinojs/neutralinojs/```
 2. Move to neutralinojs folder ```cd neutralinojs```
 3. Build Project ```./build.sh linux```
 4. Move to dist ```cd dist```
 5. Run neutralino ```./neutralino```

**Specifications**  
* NeutralinoJs Version: Master branch
* NeutralinoJs CLI version: not used
* Platform: Linux (Arch linux)

**Comment by shalithasuranga** [comment]
Hey.. Please launch the app with `--load-dir-res` flag. Neutralinojs will look for `res.neu` by default. This behavior will change soon as explained in [this comment](https://github.com/neutralinojs/neutralinojs/issues/420#issuecomment-820961512).

**Comment by shalithasuranga** [comment]
Also, when you are compiling, please use the following flow. The `build` scripts on the root directory are somewhat deprecated.

```
$ git clone https://github.com/neutralinojs/neutralinojs
$ cd neutralinojs/core-linux
$ ./bash.sh
./bin/neutralino --load-dir-res
```
