### ISSUE TITLE
Windows Error Message: "Application was terminated."

### ISSUE THREAD

**Issue by alMubarmij** [neutralinojs/neutralinojs#442]
I just installed the framework.
When I run the command "**neu run**" after creating the new app, I get the following error message: 
"**Application was terminated.**"

**Comment by ibandominguez** [comment]
@alMubarmij are u getting this message?

`ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null

Application was terminated.`

It shows this message, regarding a wrong json file but the path of the file has nothing to do with my computer.

anyone has found a solution?

**Comment by tiptronic** [comment]
Just to add:
Same thing here when just following the 'how to' on MacOSX (11.3.1)

**Comment by ph4un00b** [comment]
same on MACOS
os: 10.14.6

$ npm install -g @neutralinojs/neu
$ neu create me

```
❯ cd me && neu run

------- Notice --------

Neutralino v2 is ready for Linux/Windows. You can try v2.0.0 pre-release.
Please notice that the macOS version is not yet supporting v2 implementaton (still in v1.5.0).
If you are interested, you can help <3 us to implement v2-spec for macOS.
Checkout more info: https://github.com/neutralinojs/neutralinojs

ERROR [/Users/codecey/Desktop/untitled folder/neutralinojs/core-macos/src/settings.cpp:getSettings] [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be string, but is null

Application was terminated.
```

**Comment by Bellisario** [comment]
I have the same problems, but no errors.
I'm using Windows 7 and I can't run or compile the app (compiled app starts with an error).
I tried to run cmd and powershell with this command (also with admin privileges), too but it doesn't work in any case:
 `CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"`

Here is a console output that I see when I try to run the app, that doesn't be visible for a moment and say me I have closed it:
```
------- Notice --------

Neutralino v2 is ready for Linux/Windows. You can try v2.0.0 pre-release.
Please notice that the macOS version is not yet supporting v2 implementaton (sti
ll in v1.5.0).
If you are interested, you can help <3 us to implement v2-spec for macOS.
Checkout more info: https://github.com/neutralinojs/neutralinojs


Application was terminated.
```

**Comment by alMubarmij** [comment]
A quick solution:
Just use version 2.0:
`npm install -g @neutralinojs/neu@2.0`

> 
> 
> I just installed the framework.
> When I run the command "**neu run**" after creating the new app, I get the following error message:
> "**Application was terminated.**"

**Comment by Bellisario** [comment]
Thank you @alMubarmij, resolved with version 2!

**Comment by shalithasuranga** [comment]
Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486  open until we apply a fix. Thanks
