### ISSUE TITLE
Access-Control-Allow-Origin problems

### ISSUE THREAD

**Issue by zigazajc007** [neutralinojs/neutralinojs#445]
**Expected Behavior**  
Login system to work (Fetch json data from server) That works with Electron without any problem, but when I copy paste html, css, js... code from electron to new project neutralinojs it just doesn't allow me to fetch data from server.

I have also tried with:
```yaml
    xhr.setRequestHeader("Access-Control-Allow-Origin", "*");
    xhr.setRequestHeader("Access-Control-Allow-Credentials", "true");
    xhr.setRequestHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
```
and it doesn't work...
**Actual Behavior**  
When i want to send api require I get error:
```yaml
[Error] Origin http://localhost:42759 is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load http://localhost:8080/?action=getPasswords due to access control checks.
[Error] Failed to load resource: Origin http://localhost:42759 is not allowed by Access-Control-Allow-Origin. (localhost, line 0)
```

**Steps to Reproduce the Problem**  
 1. Copy all html, css, js and images folder from https://github.com/Rabbit-Company/Passky-Desktop
 2. Run application and try to login
 3. And it will give you that error

**Specifications**  
* NeutralinoJs Version: 3.0.4?
* NeutralinoJs CLI version: 3.0.4?
* Platform: pop os 20.10

**Comment by Hunlongyu** [comment]
I also have such a problem. Is there a solution?

**Comment by zigazajc007** [comment]
I just needed to implement CORS to server too.

Electron has probably this disabled.
