### ISSUE TITLE
JSON parse error in putData

### ISSUE THREAD

**Issue by uAliFurkanY** [neutralinojs/neutralinojs#446]
**Expected Behavior**  
It should stringify the data correctly, as shown in the documentation.
![Code from the documentation](https://user-images.githubusercontent.com/57134217/118037301-5516c300-b376-11eb-890e-d3ea392cb69c.png)
  
**Actual Behavior**  
`JSON parse error. Please check whether your request payload is correct`

**Steps to Reproduce the Problem**  
Put any JSON object using `Neutralino.storage.putData({ bucket: "bucketName", data: { } })`

**Workaround**  
Stringify/parse the data yourself.  
Either the documentation or the library has to be updated. It's not an annoying workaround but it conflicts with the documentation.

**Specifications**  
* NeutralinoJs Version: 2.0.0
* NeutralinoJs CLI version: 3.0.4
* Platform: Linux Mint 20.1

**Comment by shalithasuranga** [comment]
Hey.. nice catch.. I updated the documentation. Also, noticed that `getData` on Linux returns `content` not `data`. Those things are fixed too. It is true that we need to use `JSON.stringify` similar to https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem
