### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#450]
**Expected Behavior**  
If the option of without decorated borders is enabled I would like to be able to generate a border radius to the webkit. to obtain rounded corners
  
**Actual Behavior**  
Currently the corners are pointed

**Steps to Reproduce the Problem**  
 1. Create new neu project
 2. Set borderless in true
 3. Run project

**Specifications**  
* NeutralinoJs Version: Git Master
* NeutralinoJs CLI version: not used
* Platform: GNU/Linux

**Comment by shalithasuranga** [comment]
Implementing this possible with the transparent window mode + CSS. Thanks so much for reporting this issue :tada:
