### ISSUE TITLE
writeFile success returns null - linux

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#46]
Should return a success message

**Comment by 0x72D0** [comment]
I'll try to do this one

**Comment by 0x72D0** [comment]
I'm a little bit lost right now... can you specify how to trigger this bug?

**Comment by shalithasuranga** [comment]
Hey.. nice @0x72D0  You can build from source and write simple neutralino app which is using `Neutralino.filesystem.writeFile` function. Then you will find the issue.
