### ISSUE TITLE
System files - absolute path

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#468]
**Expected Behavior**  
I would like to be able to use files (either documents or images) that are in any directory on the system, for example:

```
file: ///usr/share/icons/Numix-Circle/48/apps/org.gnome.Screenshot.svg
```

**Actual Behavior**  
When making the call from html to the previous file or even without using the `file: //` at the beginning I cannot see the image. 

**Steps to Reproduce the Problem**  

 1. Start a neutral project
 2. Put an img tag with an absolute path to your directory
 3. Run the project

**Specifications**  
* NeutralinoJs Version: Master Version
* NeutralinoJs CLI version: don´t use cli
* Platform: Linux

**Comment by DiZeroX** [comment]
To add on, my use case is trying to use images in the same directory as the build executables (expand Neutralino.filesystem features).

**Comment by JoaquinDecima** [comment]
It does not work for me, and I cannot do it, I need specifically to take the icons from the OS. I have to check if the reality is to extend the functionality or it will be enough to use multiple paths as ../../ to obtain the Root

**Comment by rince1984** [comment]
You can use the global Variable "NL_CWD" to get the app path.

https://stackoverflow.com/questions/68620523/neutralinojs-open-local-html-file-in-browser

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting the issue. Neutralino or the internal webview implementation doesn't support file URI scheme. Therefore, please pick an alternative way like @rince1984  mentioned.

Eg:
- Reading the file content via the filesystem API.
- Using file select dialog from os API
- Adding the resource to app resources
- Opening the file URL with os.open()
