### ISSUE TITLE
Enable window resizable option

### ISSUE THREAD

**Issue by dipakw** [neutralinojs/neutralinojs#469]
Hi,

I was trying to create a small app for Linux platform with a fixed window size, but it's found this option was not parsed from **_neutralino.config.json_** .

When I looked at the code, the window size was set with a static value WEBVIEW_HINT_NONE.

```
nativeWindow->set_size(width, height, WEBVIEW_HINT_NONE);
```

It seems pretty much intentional rather than a mistake. Do you guys think that this option is not necessary to be dynamic? But it looks pretty obvious to me to this option be dynamic.

If you guys agree with me, then I might be able to make a pull request for this.

**Comment by shalithasuranga** [comment]
Hey.. @dipakw Thanks for using Neutralinojs to create an app. Recently we made a fork of webview to add these kinds of features.  Yeah agree with you, there should be a way to make the window fixed.
Please check https://github.com/neutralinojs/proposals There are several options like `minHeight`, etc .. `resizable` is also there.

If you would like to add `resizable` I think we can add it the same as `fullScreen` properly.

**Comment by shalithasuranga** [comment]
Hey.. I will close this issue since in https://github.com/neutralinojs/neutralinojs/issues/415 we already discussed about `resizable` optional. Thanks for submitting. I already added this to milestone v2.3.0
