### ISSUE TITLE
Remove Debug log

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#47]
/neutralino.js id = 6
url = /assets/app.js id = 7
url = /favicon.ico id = 8
url = /ping id = 9
url = /ping id = 10
url = /ping id = 4

**Comment by lucasvasconcelos** [comment]
@shalithasuranga, this should do the trick: https://github.com/neutralinojs/neutralinojs/pull/49

:)

**Comment by shalithasuranga** [comment]
Thanks 👍
