### ISSUE TITLE
FileOpen / Save dialogs open behind main window

### ISSUE THREAD

**Issue by hypherionmc** [neutralinojs/neutralinojs#472]
**Expected Behavior**  
When opening an OpenFile or SaveFile dialog, I expect it to open above the main window so that user can see it has opened and interact with it.
  
**Actual Behavior**  
The dialogs open behind the main window and you don't notice them unless you see the flashing icon on the taskbar 

**Steps to Reproduce the Problem**  
 1. Use a call to open an OpenFile dialog or SaveFile dialog

**Suggestions**
Maybe add a flag to allow you to change this behavior or just have it open above the window by default.

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework] 2.2.0
* NeutralinoJs CLI version: [neu-cli version] Not sure? Would probably also be 2.2.0
* Platform: [Platform specifications] 

  * OS: Windows 10 Pro 64-bit
  * CPU: AMD

**Comment by JoaquinDecima** [comment]
Do you have the app on so that it is always shown in front of you?

**Comment by hypherionmc** [comment]
You mean AlwaysOnTop? Then nope

**Comment by JoaquinDecima** [comment]
Sorry, I tried to replicate the error but I can't, when generating a dialog to open or save files it overlaps the app in question.

Do you have the code or something more specific? Does the same thing happen in a clean project?

**Comment by hypherionmc** [comment]
I will test again with a clean instance. Maybe Vue or the button click is interfering with it

**Comment by hypherionmc** [comment]
As for code, this is the Vue function that calls the dialog

`loadConfigFile: async function () {

            let response = await Neutralino.os.showDialogOpen({
                title: "Select Config File",
                isDirectoryMode: false,
                filter: "toml"
            });
         //rest is just parsing code
}`

**Comment by hypherionmc** [comment]
Feedback: I tried this with the sample template with only a button added to trigger the dialog, and I get the same result.

**Comment by JoaquinDecima** [comment]
Hello, first of all, excuse the delays, apparently this is in the way that windows manages the dialogs. Unfortunately I do not have this OS or knowledge about the code for this system. Then I leave the respective codes there you can see the anomaly or the change that should be made:

---

DialogOpen
```cpp
string title = input["title"];
if(!input["isDirectoryMode"].is_null() &amp;&amp; input["isDirectoryMode"].get&lt;bool&gt;()) {
    TCHAR szDir[MAX_PATH];
    BROWSEINFO bInfo;
    ZeroMemory(&amp;bInfo, sizeof(bInfo));
    bInfo.hwndOwner = NULL;
    bInfo.pidlRoot = NULL;
    bInfo.pszDisplayName = szDir;
    bInfo.lpszTitle = const_cast&lt;char *&gt;(title.c_str());
    bInfo.ulFlags = 0 ;
    bInfo.lpfn = NULL;
    bInfo.lParam = 0;
    bInfo.iImage = -1;

    LPITEMIDLIST lpItem = SHBrowseForFolder( &amp;bInfo);
    if( lpItem != NULL ) {
        SHGetPathFromIDList(lpItem, szDir );
        output["selectedEntry"] = szDir;
    }else {
        output["selectedEntry"] = nullptr;
    }
}else {
    OPENFILENAME ofn;
    TCHAR szFile[MAX_PATH] = { 0 };
    ZeroMemory(&amp;ofn, sizeof(ofn));
    ofn.lpstrTitle = const_cast&lt;char *&gt;(title.c_str());
    ofn.lStructSize = sizeof(ofn);
    ofn.lpstrFile = szFile;
    ofn.nMaxFile = sizeof(szFile);
    ofn.nFilterIndex = 1;
    ofn.lpstrFileTitle = NULL;
    ofn.nMaxFileTitle = 0;
    ofn.lpstrInitialDir = NULL;
    ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

    if (GetOpenFileName(&amp;ofn)) {
        output["selectedEntry"] = ofn.lpstrFile;
    }else {
        output["selectedEntry"] = nullptr;
    }
}
```

Justo debajo de ese esta en de dialogSave en este archivo:

* https://github.com/neutralinojs/neutralinojs/blob/master/api/os/os.cpp

---

Thank you!

**Comment by hypherionmc** [comment]
Hi. No worries at all. I understand people are busy :)

I do see something that I suspect could be the cause, but I want to do some testing after work to confirm in it is what I think it is. If it is, I'll add a fix for it and PR it back to this repo

**Comment by JoaquinDecima** [comment]
Cool!

If there is something I can help with, let me know and thank you for collaborating with the project!

**Comment by hypherionmc** [comment]
I Will do and you're welcome. I am so glad I came across this. This project is SO MUCH better than electron

**Comment by hypherionmc** [comment]
Some feedback again. I get really weird behavior with this.

I tried today on a different machine and the OpenFile dialog displayed as intended, but if it's set to a folder browser dialog, it hides behind the main window.

On my dev machine I cannot get it to show either above the main window.

I suspect the issue is caused by this: bInfo.hwndOwner = NULL;

Generally, c++ dialogs and message boxes needs a window handle assigned to them, or they open behind the main window. I haven't had a change to test this yet

**Comment by shalithasuranga** [comment]
Thanks all for checking more about this issue. I also will try to reproduce this issue on Windows. will apply a fix and let you know if there is a bug

**Comment by shalithasuranga** [comment]
Hey all. There was a bug. Save/Open dialogs were rendered behind the window and browser(--mode=browser). Now it should render properly.

This fix is not released yet but you guys can check with `bin/neutralino-win.exe` or compiling the latest commit.

**Comment by hypherionmc** [comment]
Thank you very much! I will let you know if I find anything else. Well, I do think there is another issue, but I'll open a new issue for that once I confirm
