### ISSUE TITLE
 code: 'ERR_UNHANDLED_REJECTION'

### ISSUE THREAD

**Issue by dbuldansjah** [neutralinojs/neutralinojs#475]
**Expected Behavior**  
Description about what should be the expected behavior of the framework.
  
**Actual Behavior**  
Description about how the framework is actually behaving and deviating from the expected behavior. 

**Steps to Reproduce the Problem**  
 1. npm install -g @neutralinojs/neu
 2. create new project/app and cd to the new project/app
 3. run neu run --> 

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework]
* NeutralinoJs CLI version: [neu-cli version] node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "".]
{
  code: 'ERR_UNHANDLED_REJECTION'
}
* Platform: visual studio code on windows server 2016

**Comment by JoaquinDecima** [comment]
Hello,

I can see that the error in your JS implementation may have to do with error handling. I ask you please to provide me with the following information:

**NeutralinoJS version:
Operating system:
Main.js code:**

This happens with any creation, I also want to clarify that I see something strange in your way of creating the project where you marked this:

```bash
create new project/app and cd to the new project/app
```

it should be something like that

```bash
mkdir project && cd project && neu create myapp && cd myapp
```

Understanding that project is a folder. I recommend you to see the documentation of the following site https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app

**Comment by dbuldansjah** [comment]
NeutralinoJS version: 4.0.0
Operating system: windows server 2016 
Main.js code:
window.myApp = {
    showInfo: () => {
        document.getElementById('info').innerHTML = NL_APPID + " is running on port " +
                    NL_PORT + " inside " + NL_OS + ".<br/><br/>" + "<span>v" + NL_VERSION + "</span>";
    },
    openDocs: () => {
        Neutralino.app.open({
            url: "https://neutralino.js.org/docs"
        });
    }

};

Neutralino.init();
window.myApp.showInfo();


Just testing the basic minimal example:
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "".]
{
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by JoaquinDecima** [comment]
Mmmm,

I tried to replicate the error and I couldn't. can it be related to the Windows server? On another machine too?

additionally I ask you if possible to use the git tools to format the code to simplify reading and to check the neutralino version since the last one is 2

**Comment by shalithasuranga** [comment]
Hey.. Installing Webview2 runtime will solve this issue as explained in https://github.com/neutralinojs/neutralinojs/issues/610
