### ISSUE TITLE
Fail to launch app on "neu run"

### ISSUE THREAD

**Issue by vicnz** [neutralinojs/neutralinojs#480]
# **entry point not found**
`SetProcessDpiAwarenessContext` could not be found in the dynamic library

CLI v.: 3.2.1
Machine: Win32 64bit, Windows 8.1

**Comment by shalithasuranga** [comment]
Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486  open until we apply a fix. Thanks

**Comment by aianshume** [comment]
> Hey.. Please notice that we created one issue for all windows older versions related to issues. I will close this one and keep #486 open until we apply a fix. Thanks

what the hack you are doing, you transferred all the issue but there is no solution on this page [#486](https://github.com/neutralinojs/neutralinojs/issues/486).

**Comment by shalithasuranga** [comment]
Haha lol.. just created one issue by closing all similar issues for easiness. We can track progress by checking #486 and also we can still navigate to related issues from there
