### ISSUE TITLE
Add APIs for Minimize and Maximize Window (support for custom titlebar)

### ISSUE THREAD

**Issue by alixsep** [neutralinojs/neutralinojs#494]
**Expected Behavior**  
I want to have api's allowing us to minimize or maximize the window, 
Docs are missing those api's which makes the potential to restrict the designers from making custom titlebar for their apps. I myself would like to make a custom titlebar for my app and I simply can't, (or can I and I am missing out something? I couldn't find anything in doc anyways, if the api exists, please update docs then!)
electron.js has these options, and this is a tutorial for it: https://github.com/binaryfunt/electron-seamless-titlebar-tutorial
 
 the api's would be like this:
 
```js
document.getElementById('min-button').addEventListener("click", event => {
    win.minimize();
});

document.getElementById('max-button').addEventListener("click", event => {
    win.maximize();
});

document.getElementById('restore-button').addEventListener("click", event => {
    win.unmaximize();
});

document.getElementById('close-button').addEventListener("click", event => {
    win.close();
});
```

**Specifications**  
* NeutralinoJs Version: 2.4.0
* NeutralinoJs CLI version: 5.1.2
* Platform: Windows 10 Enterprise 1809

**Comment by AOSXAP** [comment]
Created a pull request with the requested features rn , hopefully they will get accepted :smiley: https://github.com/neutralinojs/neutralinojs/pull/500

**Comment by alixsep** [comment]
> Created a pull request with the requested features rn , hopefully they will get accepted 😃 #500

wow thank you!

**Comment by kaesar** [comment]
Neutralinojs is simple and awesome technology. According this feed I was wondering if it is possible add something like **hide** and **show** with the main window. This is because when you use tray (with icon) and set **window.hidden** (in `neutralino.config.json`) you can avoid to use `Neutralino.app.open` and keep in the main window. I mean, maybe is also possible to use a window instead of open a browser in that case. Thanks

**Comment by tinomatic** [comment]
> Neutralinojs is simple and awesome technology. According this feed I was wondering if it is possible add something like **hide** and **show** with the main window. This is because when you use tray (with icon) and set **window.hidden** (in `neutralino.config.json`) you can avoid to use `Neutralino.app.open` and keep in the main window. I mean, maybe is also possible to use a window instead of open a browser in that case. Thanks

Yes, the is definitely needed for many tray app use cases. If neutralino can offer only a single WebView window, it would also be good to be able to change the content while it's hidden.

**Comment by shalithasuranga** [comment]
Closing this because `maximize`, `unmaximize`, `minimize`, and `isMinimized` methods are added to `Neutralino.window` for all supported platforms.  I will add other methods via https://github.com/neutralinojs/neutralinojs/issues/516
