### ISSUE TITLE
Control user mouse

### ISSUE THREAD

**Issue by wtesler** [neutralinojs/neutralinojs#502]
Is there a way to control the user's mouse from inside the framework?

**Comment by shalithasuranga** [comment]
Hey.. do you mean changing the mouse position programmatically?

**Comment by wtesler** [comment]
> Hey.. do you mean changing the mouse position programmatically?

Yeah!

**Comment by shalithasuranga** [comment]
Hey.. I am closing this because this can be done with a Neutralinojs extension (can be written with any language). Please check https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension for an example. Thanks for reporting the issue
