### ISSUE TITLE
> As explained in [here](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app) we need to

### ISSUE THREAD

**Issue by MyBlood** [neutralinojs/neutralinojs#511]
> As explained in [here](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app) we need to

I have done this, but the window still remains blank.
![image](https://user-images.githubusercontent.com/20350848/124993586-3a4a8d00-e04d-11eb-8d03-c0f9c0cbc597.png)
![image](https://user-images.githubusercontent.com/20350848/124993646-52baa780-e04d-11eb-99d2-1b0b3de90950.png)

_Originally posted by @MyBlood in https://github.com/neutralinojs/neutralinojs/issues/473#issuecomment-876761448_

**Comment by georgechitechi** [comment]
Running default windows console as administrator caused this issue, when I run console as normal user app runs fine.
Also using git bash worked fine.

This might help as solutions are sought.

**Comment by MyBlood** [comment]
> Running default windows console as administrator caused this issue, when I run console as normal user app runs fine.
> Also using git bash worked fine.
> 
> This might help as solutions are sought.

I'll give it a try, thanks, mate.

**Comment by MyBlood** [comment]
> Running default windows console as administrator caused this issue, when I run console as normal user app runs fine.
> Also using git bash worked fine.
> 
> This might help as solutions are sought.

I checked this and it turns out I only have one user, and that's the administrator in Windows 10 =(

Do I really need to create a separate user to work with Neutralinojs ?

**Comment by shalithasuranga** [comment]
Hey.. hope @MyBlood  was able to get the application running. If this issue still exists, please try the following actions.

- Try installing Webview2 runtime.
- Try to run the command mentioned in the docs with an elevated console (in admin mode).

I am closing this since it's similar to https://github.com/neutralinojs/neutralinojs/issues/508.. Thank you very much for reporting and discussing this.
