### ISSUE TITLE
README fail, Hello World does not work

### ISSUE THREAD

**Issue by AddictArts** [neutralinojs/neutralinojs#514]
**Expected Behavior**  

What the README says should happen, a hello world app.
 
**Actual Behavior**  

It crashes, OS says the app quit unexpectedly.

**Steps to Reproduce the Problem**  

1. Just follow the README steps

**Specifications**  
* NeutralinoJs Version: latest nam I -g @neutralinojs/neu

--- Global ---
Neutralinojs binaries: v2.4.1
Neutralinojs client: v1.0.0
neu CLI: v5.1.5

--- Project: hello-world (js.neutralino.sample) ---
Neutralinojs binaries: v2.4.1
Neutralinojs client: v1.0.0
johnpywtorak@PYWTURAJ-MBP15A hell

* Platform: Mac OS Big Sur Intel X86

**Comment by joeshae** [comment]
I encountered the same issue.

**Comment by shalithasuranga** [comment]
Ah looks like your devices are 32-bit. Currently, we have only an x64 build for macOS devices. We will add an ia32 binary for macOs. Thanks for reporting this :)

**Comment by AddictArts** [comment]
Hi @shalithasuranga Apple has long left 32 bit. As reported I am running Big Sur which is only 64 bit. Following the readme fails still 2.8 latest.

`% neu run
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-mac_x64 was stopped with error code null
`
The built binary
`hello-world-mac_x64 ; exit;
zsh: segmentation fault  
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
`

**Comment by shalithasuranga** [comment]
There is a bug with `os.setTray` as explained in #615, Now the sample app will work since we temporarily removed `os.setTray` function call.
