### ISSUE TITLE
> Running default windows console as administrator caused this issue, when I run console as normal user app runs fine.

### ISSUE THREAD

**Issue by MyBlood** [neutralinojs/neutralinojs#515]
> Running default windows console as administrator caused this issue, when I run console as normal user app runs fine.
> Also using git bash worked fine.
> 
> This might help as solutions are sought.

I checked this and it turns out I only have one user, and that's the administrator in Windows 10 =(

Do I really need to create a separate user to work with Neutralinojs ?

_Originally posted by @MyBlood in https://github.com/neutralinojs/neutralinojs/issues/511#issuecomment-877345389_

**Comment by shalithasuranga** [comment]
Hey.. we've checked the latest version on Windows 10, and `neu run` and double-click run both worked fine. So, I am closing this one. Thanks for reporting. Please discuss if you still have the same issue with the latest version.
