### ISSUE TITLE
Enhance os.execCommand and IPC

### ISSUE THREAD

**Issue by lmmfranco** [neutralinojs/neutralinojs#519]
This project is really promising, but it lacks something very important: an easy and realiable way to connect to native backend.

In electron we have access to a background thread running node, from which we can communicate with the frontend via IPC with EventEmitters.

I've read in some closed issue that the "recommended way" for this is using `os.execCommand`, but it still lacks many features.
Consider implementing some of the features like node's [child_process](https://nodejs.org/api/child_process.html), like:
 - Cancel the process (kill)
 - Real time stdio/stdout/sterr
 - Displaying exit code

 These changes would at least empower the developer to build their own IPC.

**Comment by KrishnaPG** [comment]
Adding a "message broker" into the C++ would allow the front-end to connect to native backends in any language.

For example, embed a ZeroMQ dealer, or NATS/MQTT broker into the C++ that allows publishers from any languages to provide custom functionality from GO/RUST/NodeJS/C++ and the web-client can make RPC requests to these GO/RUST/C++/NodeJS apps.

**Comment by evandikt** [comment]
Another idea would be to just add a websocket

**Comment by StJohn3D** [comment]
This and rich file system access are probably the two biggest justifications for choosing this kind of technology over a PWA. I'm really excited to give this project a try as a MUCH lighter weight alternative to Electron - but need to have those three bullet points listed by @lmmfranco first.
Subscribed and watching this thread 😄

**Comment by zvikasdongre** [comment]
Any update on this guys?

**Comment by shalithasuranga** [comment]
Hey.. Some modifications are already done and now it supports, exitCode, PID, stdIn, stdOut, background mode and stdErr as explained in https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#api-osexeccommand. But note that exeCommand is sync.

**Comment by sreepathy** [comment]
How to capture output from a running background process and display it? Especially, when it is a streaming data like output from `docker stats`. Giving a small example in documentation for os.execCommand would be highly helpful.

**Comment by sreepathy** [comment]
In electron we can write something like this
```
window.addEventListener('DOMContentLoaded', () => {
  const replaceText = (selector, text) => {
    const element = document.getElementById(selector)
    if (element) element.innerText = text
  }
  var child = require('child_process').execFile('docker', ['stats']);
  // use event hooks to provide a callback to execute when data are available: 
  child.stdout.on('data', function(data) {
      replaceText("docker_status", data );
  });
})
```
How the same can be achieved in Neutralino?

**Comment by UnKnoWn-Consortium** [comment]
An asynchronous ```os.execCommand``` or ```os.spawnProcess``` is the last piece of the puzzle I need to make a full transition from Electron to NeutralinoJS for some of my desktop utility apps.

**Comment by shalithasuranga** [comment]
Hey all.. this feature was implemented -- you can check more details from here: https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#api-process-spawning-api

We will release spawning API with the next release soon, but you can experiment anytime with the `nightly` version ;)

Thanks :tada:
