### ISSUE TITLE
possible support for ios and android?

### ISSUE THREAD

**Issue by Kali95739** [neutralinojs/neutralinojs#522]
Would you possibly consider adding support for android and iOS? Or will it not work

**Comment by Kali95739** [comment]
Like how you support for windows Mac and Linux if you could just add android and iOS that would be awesome

**Comment by zigazajc007** [comment]
Just publish an website and add webview to your android application it works perfectly.

**Comment by shalithasuranga** [comment]
Yeah, @zigazajc007  I agree. Neutralinojs uses the client-server design to support various modes. I am planning to add Chrome mode too.. Then we can run Neutralinojs apps using chrome as the renderer. That model doesn't really fit with mobile devices. Seems like Electronjs also will never officially support mobile platforms. However, if someone wants to create cross-platform apps for all platforms including mobile, I would vote for Flutter because native performance is crucial for mobile devices.

**Comment by topcheese** [comment]
Sorry to jump in like this out of nowhere, but isn't this a design issue?  I'm talking about a responsive design built into the application, which is part of building upon UX thinking.
You have to design it with support for mobile, tablets and big screens in mind.

**Comment by zigazajc007** [comment]
> Sorry to jump in like this out of nowhere, but isn't this a design issue? I'm talking about a responsive design built into the application, which is part of building upon UX thinking.
> You have to design it with support for mobile, tablets and big screens in mind.

This isn't a problem anymore. Now we have css frameworks like Bootstrap, TailwindUI, Foundation, Bulma, Pure, Groundwork...

**Comment by shalithasuranga** [comment]
Hello.. thanks all for discussing this issue. Please consider Neutralinojs as a "desktop application development" framework (As the project title says) like Electron. We will not extend the official implementation for mobile platforms but love to see some forks in the future.

**Comment by Kali95739** [comment]
Sorry I had just came back to this and had a new version of my question I mean can a web app of neutralino run on android or ios browser same as an actual desktop browser with no problem?

**Comment by shalithasuranga** [comment]
Hey @Kali95739 I think you referred to the Neutralinojs [cloud mode](https://neutralino.js.org/docs/configuration/modes#cloud)
 Yeah, a Neutralinojs web app will work on any web browser that supports JavaScript. But, then the story is a bit different. If you call the native API on the cloud mode, Neutralinojs will execute those API calls on the server computer where you run the Neutralinojs process. 

For example, if you trigger `os.execCommand('gedit')` with an HTML button, and you click the button from an Android device, you may see the gedit program is launched in your server computer.

**Comment by Kali95739** [comment]
Ah yes, okay thank you

**Comment by Kali95739** [comment]
Is it possible to use an example say from here https://github.com/neutralinojs/neutralinojs-desktop-samples in a apache server or just a common webserver and it will run successfully on the clients browser or noy really?
