### ISSUE TITLE
DevTools popup always shows when start the application

### ISSUE THREAD

**Issue by siquylee** [neutralinojs/neutralinojs#525]
Everytime I run the app, it always open Microsoft Edge DevTools beside app window even in release mode. How do I disable DevTools popup?

Enviroment:
- Windows 10 version 20H2
- Microsoft Edge version 91.0.864.70

**Comment by shalithasuranga** [comment]
Hey can you try to set `enableInspector` property in the config file to `false` and try.
Documentation: https://neutralino.js.org/docs/developer-environment/neutralino.config.json#modeswindowenableinspector-boolean

**Comment by siquylee** [comment]
Thank you very much. I found it.
