### ISSUE TITLE
Discord server for Neutralino.js

### ISSUE THREAD

**Issue by alixsep** [neutralinojs/neutralinojs#530]
I, along side will many others, would have been glad if a discord server existed as neutralino.js community.

It both allows fans and devs to talk and hear suggestions and it can help neutralino.js get more attention.

**Comment by shalithasuranga** [comment]
@alixsep Nice idea. Btw I haven't used Discord before. Can we create several subgroups like Slack there too?

**Comment by hypherionmc** [comment]
You can have "Categories". Like this: 

![image](https://user-images.githubusercontent.com/63595580/126999839-fbdec6ae-50fd-4ae5-9f2b-090e0c356817.png)

**Comment by hypherionmc** [comment]
And I'd be willing to help you set it up if you want

**Comment by alixsep** [comment]
> @alixsep Nice idea. Btw I haven't used Discord before. Can we create several subgroups like Slack there too?

Slack is ok too but discord userbase is much more consistent and bigger. Electronjs and pretty much most successful repos have a discord server.

**Comment by apoorvcodes** [comment]
I support the fact of a discord server

**Comment by apoorvcodes** [comment]
I would love to help to set it up as well

**Comment by shalithasuranga** [comment]
Hey.. I created a Discord server https://discord.gg/765ESGvG Let's try a bit and we can add the link to Github and the website.

**Comment by hypherionmc** [comment]
And I'm your first member. Yay xD

**Comment by shalithasuranga** [comment]
Thanks for the support. Now the Discord invitation link was added to the website :rocket:
