### ISSUE TITLE
[SUGGESTION] Allow file filtering in Open Dialog

### ISSUE THREAD

**Issue by hypherionmc** [neutralinojs/neutralinojs#531]
**Expected Behavior**  
Currently. the showDialogOpen dialog will show all files in all folders. It would be really nice to have the ability to add a filter, so that it only shows certain extensions.
  
The api function could be:
```javascript
let response = await Neutralino.os.showDialogOpen({
  title: 'Select a file',
  isDirectoryMode: false,
  filter: ["txt", "bmp", "myextension"]
});
```

As far as I know, all operating systems include a filter feature for these dialogs, so it shouldn't be impossible to add

**Comment by hypherionmc** [comment]
I'm busy adding this, so I'll do a PR for it :)

**Comment by shalithasuranga** [comment]
@hypherionmc Thanks this is a great feature for open dialog :+1:

**Comment by hypherionmc** [comment]
I thought this was a feature already, until my app update yesterday and noticed it wasn't. So far I got the filter working on Linux and Windows, but mac is still a bit tricky

**Comment by shalithasuranga** [comment]
Maybe Apple script's `of type {"txt", "bmp"}` syntax will work?

**Comment by hypherionmc** [comment]
It does, but only for common extensions apparently. For example: `of type {"png"}` works, `of type {"toml"}` does not

**Comment by hypherionmc** [comment]
For more context, this is on macOS Big Sur 11.4. Not sure if this is an OS issue, or if just a general bug

**Comment by hypherionmc** [comment]
Okay so doing `type of {"", "toml"}` works fine. Will probably have to do it that way then

**Comment by hypherionmc** [comment]
Found another Linux related bug. When calling the zenity command, it throws a warning from GTKDialog. This warning, is then passed along with the file path to selectedEntry. I added a fix for this as well

**Comment by hypherionmc** [comment]
Also found a similar bug in MacOS. The macOS one just adds a new line to the result returned when you open the file. I should be able to PR this tomorrow. Just installing Visual Studio so I can test the windows build, unless there is another build system I can use?

**Comment by shalithasuranga** [comment]
Thanks, @hypherionmc for the pull request. It's merged and I will release this feature with the next version.
I did a few adjustments to your changes.
- moved the ending newline replacement logic to `excecCommand`
- Displayed `.` before the file extension name on Windows. So on Windows, we can see selectors like `.cpp files` etc.
- Did some minor changes to variable names etc.

**Comment by hypherionmc** [comment]
@shalithasuranga Thank you so much and thank you for allowing me to contribute.

Just something I noticed now while reading your changes, you removed this `entrystring.substr(entrystring.find("/"))` from line 226. This line is responsible for removing the "GTKWarning" from the returned string, so without this, it adds that warning into selectedEntry

**Comment by shalithasuranga** [comment]
Hey.. Thanks for letting me know about that. I haven't got any issue without that. Could you please let me know how to reproduce the GTKWarning you've mentioned. Not sure it's related to the version of Zenity.

**Comment by hypherionmc** [comment]
If you run that command that calls the dialog in the terminal, you should see it. 

This is the message: `Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged`

This happened to me on Zorin OS (Which is an Ubuntu Based OS)

**Comment by shalithasuranga** [comment]
Hmm, now I understood `execCommand` is a bit limited now. I think later we can return both error stream and standard stream from it. But for now, forwarding the error stream to `/dev/null` a good idea?
Could you verify `<zenity command> 2>/dev/null` works for you without the warning?

**Comment by hypherionmc** [comment]
Yes that does work in the command line

**Comment by shalithasuranga** [comment]
Hey.. Thanks for checking. Now I added flag for execCommand. It is called `shouldCombineErrorStream`. For those AppleScritpt calls and Zenity calls, it uses the default value which is `false` I think latest commit will work for your OS too..

**Comment by hypherionmc** [comment]
Hey awesome!! I will run a test on both my machines to see if it still works as intended. Will keep you posted
