### ISSUE TITLE
Windows Binary From Master flagged as Malware

### ISSUE THREAD

**Issue by hypherionmc** [neutralinojs/neutralinojs#543]
The latest Windows binary of Neutralinojs is being flagged as malware on some windows PC's. My antivirus did return it as clean after the file was flagged as suspicious, Another user reported that their pc flagged it as malware. 

For reference: [#1](https://github.com/hypherionmc/simple-rpc-editor/issues/1)

I recompiled the binary on my local machine and tested it again through anti-virus on another pc, and it came back clean

**Comment by shalithasuranga** [comment]
Hmm looks like because it's missing publisher details? maybe could you try to add publisher details with Resoure hacker tool?

**Comment by hypherionmc** [comment]
That's probably what's happening.

If we could figure out a way to do it with res hacker from inside neu cli, it could even allow people to set an icon for the executable on windows

**Comment by shalithasuranga** [comment]
Hm yeah, that's what Electron does. I think they use something similar to res hack. will check more about this. Maybe need to see how electron securely ships pre-built Windows binaries.

**Comment by shalithasuranga** [comment]
I am closing this issue since now the binary looks not false positive for virus guards after adding manifest and developer details. Test done: https://virusscan.jotti.org/en-US/filescanjob/noisom2ydy
