### ISSUE TITLE
HTML5 Video Playback?

### ISSUE THREAD

**Issue by VaiN474** [neutralinojs/neutralinojs#547]
Should it be possible to playback video files? It seems to load other content fine from `/resources` folder but not videos. It will play videos with remote urls fine. Is there a special way they need to be linked to locally?

**Comment by shalithasuranga** [comment]
Ah looks like video extensions are not added yet. Could you let me know the extension you tried to load from the disk? Then we will add it and other video extensions to the static file server.

**Comment by VaiN474** [comment]
only tested on `.mp4` files

**Comment by shalithasuranga** [comment]
Thanks. Then we will add `.mp4` extension and other multimedia extensions support to our static file server.

**Comment by shalithasuranga** [comment]
Added more mime types support including `.mp4`. This feature will be released with the next version :). Thanks for reporting this suggestion :+1:

**Comment by rajkaran** [comment]
@shalithasuranga for ARM it is not including video where as for window (.exe it does).
