### ISSUE TITLE
Change tweet button's message

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#55]
Current tweet has message "Wow: https://github.com/neutralinojs/neutralinojs"

Better to add something :)

**Comment by abhigyank** [comment]
Hello,
Any specific message you have in mind?
I was thinking something like "Wow! Checkout NeutralinoJs -  https://github.com/neutralinojs/neutralinojs" .

**Comment by nm-t** [comment]
I've made this PR: https://github.com/neutralinojs/neutralinojs/pull/56

**Comment by abhigyank** [comment]
Umm. I was already working on this. @nm-t  It isn't very good to work on issues that someone else has already mentioned to be working on. I hope you keep this in mind the next time! Cheers!

**Comment by talinoob** [comment]
@nm-t did the same thing to me this is starting to get ridiculous, stick to your own branch #hatetheplayernotthegame
