### ISSUE TITLE
DevTools don't open

### ISSUE THREAD

**Issue by vanja-san** [neutralinojs/neutralinojs#552]
`I apologize for me bad English.`

**Expected Behavior**
Opening "devtools" at startup
  
**Actual Behavior**
"devtools" does not open

**Steps to Reproduce the Problem**  
1. Create a project
2. Start the project through command "neu run"
3. "devtools" does not open

**Specifications**  
* NeutralinoJs Version: 2.6.0
* NeutralinoJs CLI version: 1.3.0
* Platform: Windows 10 Pro x64 / 21H1 /  19043.1165

---
**I did:**
* [x] Installed NeutrolinoJs according to instructions from the documentation.
* [x] Created a project in desired directory according to instructions from the documentation.
* [x] Used `Checknetisolation.exe` according to instructions from the documentation
* [x] Missed `Step 2: Writing JavaScript, HTML, and CSS`
* [x] Launched the project. Project started, "devtools" is not.
* [x] `neutralino.config.json` => `"enableInspector": true`

`Preview:`
![preview](https://user-images.githubusercontent.com/7201687/129093691-75f09ca9-2e94-45a0-9d67-f321edc98082.gif)

**Comment by shalithasuranga** [comment]
Hello, could you all please check whether you have webview2 installed? If not, an EdgeHTML instance will be used with Neutralino. Then we need to apply a fix to get the automatic devtools window working on EdgeHTML

**Comment by vanja-san** [comment]
> Hello, could you all please check whether you have webview2 installed? If not, an EdgeHTML instance will be used with Neutralino. Then we need to apply a fix to get the automatic devtools window working on EdgeHTML

Which version should I download and install?
![image](https://user-images.githubusercontent.com/7201687/133339534-ccc4ca0a-3277-443d-8a30-4e1d37619884.png)

**Comment by shalithasuranga** [comment]
Hey.. you can download the "Standalone" version for your CPU architecture. I guess it is x64 :)

**Comment by vanja-san** [comment]
@shalithasuranga, it all works now, thanks!

**Comment by shalithasuranga** [comment]
@vanja-san Thanks for the update. This is optional for the users. I mean, your app users don't need to install webview2

**Comment by vanja-san** [comment]
@shalithasuranga But without this installation, my `devtools` didn't work

**Comment by shalithasuranga** [comment]
Ah you mean, it is not automatically opened or didn't work at all?

**Comment by vanja-san** [comment]
@shalithasuranga Is there a hotkey to open it? I don't think it works at all.

**Comment by askdesigners** [comment]
I've noticed that upon opening devtools with the right-click approach, it throws an error in the cli

```
2022-10-14 08:55:30.112 neutralino-mac_x64[48733:10919009] NSWindow warning: adding an unknown subview: <WKInspectorWKWebView: 0x7ffb9e92c580>. Break on NSLog to debug.
2022-10-14 08:55:30.114 neutralino-mac_x64[48733:10919009] Call stack:
(
	0   AppKit                              0x00007fff22f2c135 -[NSThemeFrame addSubview:] + 112
	1   AppKit                              0x00007fff22f2be74 -[NSView addSubview:positioned:relativeTo:] + 203
	2   AppKit                              0x00007fff22f2bd2e -[NSThemeFrame addSubview:positioned:relativeTo:] + 46
	3   WebKit                              0x00007fff3c23a021 _ZN6WebKit17WebInspectorProxy14platformAttachEv + 391
	4   WebKit                              0x00007fff3c67519a _ZN6WebKit17WebInspectorProxy4openEv + 84
	5   WebKit                              0x00007fff3c838be3 _ZN6WebKit17WebInspectorProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 259
	6   WebKit                              0x00007fff3c2858ff _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 125
	7   WebKit                              0x00007fff3c6121d8 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 28
	8   WebKit                              0x00007fff3c267366 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 700
	9   WebKit                              0x00007fff3c266ba4 _ZN3IPC10Connection24dispatchIncomingMessagesEv + 488
	10  JavaScriptCore                      0x00007fff3768753d _ZN3WTF7RunLoop11performWorkEv + 573
	11  JavaScriptCore                      0x00007fff376882aa _ZN3WTF7RunLoop11performWorkEPv + 26
	12  CoreFoundation                      0x00007fff206fbcec __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	13  CoreFoundation                      0x00007fff206fbc54 __CFRunLoopDoSource0 + 180
	14  CoreFoundation                      0x00007fff206fb9d4 __CFRunLoopDoSources0 + 242
	15  CoreFoundation                      0x00007fff206fa3fc __CFRunLoopRun + 893
	16  CoreFoundation                      0x00007fff206f99bc CFRunLoopRunSpecific + 563
	17  HIToolbox                           0x00007fff28942a83 RunCurrentEventLoopInMode + 292
	18  HIToolbox                           0x00007fff289427e5 ReceiveNextEventCommon + 587
	19  HIToolbox                           0x00007fff28942583 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	20  AppKit                              0x00007fff22f02b12 _DPSNextEvent + 864
	21  AppKit                              0x00007fff22f012e5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	22  AppKit                              0x00007fff22ef3609 -[NSApplication run] + 586
	23  neutralino-mac_x64                  0x000000010fb1ec01 _ZN7webview22cocoa_wkwebview_engine3runEv + 165
	24  neutralino-mac_x64                  0x000000010fb20324 _ZN6window11controllers14__createWindowEv + 567
	25  neutralino-mac_x64                  0x000000010fb22892 _ZN6window11controllers4initERKN8nlohmann10basic_jsonINSt3__13mapENS3_6vectorENS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEbxydS9_NS1_14adl_serializerENS5_IhNS9_IhEEEEEE + 1069
	26  neutralino-mac_x64                  0x000000010fabbfca _Z10__startAppv + 635
	27  neutralino-mac_x64                  0x000000010fabcc66 main + 172
	28  libdyld.dylib                       0x00007fff2061ef3d start + 1
	29  ???                                 0x0000000000000007 0x0 + 7
```
