### ISSUE TITLE
Neutralino.window.setDraggableRegion() does not work properly

### ISSUE THREAD

**Issue by aera128** [neutralinojs/neutralinojs#553]
**Expected Behavior**  
Move the window with the mouse in a smooth way with the draggable api
  
**Actual Behavior**  
The window is struggling to move

**Steps to Reproduce the Problem**  
 1. Create a project
 2. Run the project 
 2. Type Neutralino.window.setDraggableRegion('neutralinoapp')  (_or any other html element id_) in the console  or write it in the code before running the app
 3. Try to move the window

![neutralino](https://user-images.githubusercontent.com/26327394/129060492-8e2f25b2-188b-4996-b5ca-d13b817cf697.gif)

**Specifications**  
* Borderless mode enabled or disabled
* Devtools opened or closed
* Neutralino.window.setDraggableRegion() written in code or written in the console
* NeutralinoJs Version: [From version v2.5.0 to v2.6.0]
* NeutralinoJs CLI version: [v6.0.3]
* Platform: [Windows 10 20H2]

**Note**
Does not work at all on Ubuntu 21.04 in Virtualbox

**Comment by grey4owl** [comment]
I would also add that there is **no windows snapping feature** at all, and yes it is very buggy when it moves..

**Comment by shalithasuranga** [comment]
Hey... could you please check whether it behaves the same way if the dev tools window is closed? When I test on Windows it worked fine :)

**Comment by Blatman** [comment]
FWIW - I tried the setDraggableRegion on a MacOS build (10.13.6) with v2.7.0/1.4.0 and got similar results and the debug tools were not in use. It seems that while dragging the window the mouse is allowed to 'escape' from the draggable region so the window just stops.

**Comment by aera128** [comment]
Devtools has no impact on the rest. It's a bug in the setDraggable function and the move function but I have no idea why. However it works fine on another laptop with UbuntuDDE. I don't know if this is because my screen is 120Hz.

Here are other examples in v2.7.0 with and without borderless with and without devtools it is exactly the same result :

![neutralino-borderless](https://user-images.githubusercontent.com/26327394/132143746-97f999ff-c002-4205-911f-f92e8815dda9.gif)
![neutralino-raw](https://user-images.githubusercontent.com/26327394/132143748-a760bee4-6e15-42ad-9b8d-2c6b7c17daf6.gif)
