### ISSUE TITLE
Text files not supported.

### ISSUE THREAD

**Issue by JASFramework** [neutralinojs/neutralinojs#560]
**When calling a .txt file an error occurs saying it is not supported.**  
This is not a huge error and in the meantime, I am using a commented js file to replace a text file.

**--- Global ---**  
Neutralinojs binaries: v2.6.0
Neutralinojs client: v1.3.0
neu CLI: v6.0.3

* Platform: [Parrot OS/Linux]

**Comment by shalithasuranga** [comment]
I guess you meant you can't load txt files to the webview. Now it will work with the latest version.
