### ISSUE TITLE
neutralino-win_x64.exe was stopped with error code 3221225785

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#576]
**Expected Behavior**  
I wanted to try NEU and went through the steps that are indicated in the documentation about creating the first application
  
**Actual Behavior**  
Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-win_x64.exe was stopped with error code 3221225785

**Steps to Reproduce the Problem**  
 1. neu create test
 2. cd test && neu run
 3. ERROR

**Specifications**  
* Neutralinojs binaries: v2.7.0
* Neutralinojs client: v1.4.0
* neu CLI: v6.1.0

**Comment by extorc** [comment]
I have been experiencing the same problem

**Comment by extorc** [comment]
I have found a solution for my problem. Run the app in the `cmd` which is **NOT** the `Admin Privileges CMD`

**Comment by lawrence-dol** [comment]
Same here. The solution from @extorc doesn't apply as my command window is already running as a limited user, i.e. does not have Admin privileges.

**Comment by cd-FileX** [comment]
Workaround to try: https://github.com/neutralinojs/neutralinojs/issues/1094#issuecomment-1519029563

**Comment by Fav** [comment]
mybe you can follow these step

1. download webview2loader.dll
2. copy webview2loader.dll to youapp/bin
3. neu run

**Comment by shalithasuranga** [comment]
Closing this since this issue won't appear with the latest Neutralinojs version on Windows. Thanks for reporting this and discussing :tada:
