### ISSUE TITLE
MacOS - normal bundle structure not working

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#577]
**Specifications**  
* NeutralinoJs Version: 2.7.0
* NeutralinoJs CLI version: 1.4.0
* Platform: iMac 27 High Sierra 10.13.6 

Trying to get a MacOS app working as a normal bundle but paths seem fixed.
Have attached the test app. (The binary has been built for 10.13).

Bundle arrangement -

Top level -  hippo.app/Contents/

2nd Level -  hippo.app/Contents/MacOS/

  contains   hippo.app/Contents/MacOS/neutralino
                   hippo.app/Contents/MacOS/neutralino.config.json
                   hippo.app/Contents/MacOS/resources  (need this here for bundle to work but app resources really needs to be in  hippo.app/Contents/Resources) (contains client library)
                   hippo.app/Contents/MacOS/neutralino.log

2nd Level -  hippo.app/Contents/Info.plist  (property list file)(eg: CFBundleIconFile is automatically located in hippo.app/Contents/Resources)

2nd Level -  hippo.app/Contents/Resources   (should be app resources location)
  contains   hippo.app/Contents/Resources/app.icns  (this is used for the Version window icon).

I can only get it to work if I locate the app resources(with client library) within the MacOS folder where the neutralino binary resides. Ideally the app resources should be in the Resources folder alongside the MacOS folder but I can't get this to work.
The root context of the application appears to be tied to wherever the neutralino binary (controls webserver) resides.

Tried /../Resources/ in the config but neutralino just ignores the dots and appends to the MacOS path.  It seems that the client library (neutralino.js/main.js) needs to be mixed in with the app resources so not sure how to get this to work outside the binary folder.

[Hippo.zip](https://github.com/neutralinojs/neutralinojs/files/7090399/Hippo.zip)

**Comment by malipetek** [comment]
I have made a boilerplate checking internals of this package.
https://github.com/malipetek/neu-svelte-mac

Issue here seems you are including neutralino binary and the html/css/js files. 
What you should do is actually run `neu build` and use binary generated alongside with res.neu.

**Comment by Blatman** [comment]
@malipetek - yes it probably works with the res.neu file which appears to me to be a bundle of the app resources but the issue I have is that normal mac app packaging has the binary in the MacOS folder and the app assets (icons/html/css/etc) in the co-located Resources folder alongside a Info.plist file. Mac apps often use open folders in the package. Neutralino appears to have the issue that the app resources need to be alongside or beneath the binary which means everything in the MacOS folder. Not sure but I think the same rule will apply to the res.neu file as well.

**Comment by malipetek** [comment]
@Blatman yes it requires res.neu in the same directory. Do you know if including `res.neu` in `MacOS` folder instead of `Resources` folder is an anti pattern for mac apps? Would it cause any issues if one would go for publishing it seriously?

**Comment by Blatman** [comment]
@malipatek - not sure if it is an anti pattern, if res.neu was considered an executable it could co-reside with the binary otherwise I would expect it to reside in either the Resources folder or the Frameworks folder. eg: If I use a packaged executable for running node Express then this file would be placed next to the binary in MacOS folder. Certainly if the raw app resources are used as is usual  I just follow the guidance of Apple (https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1) for structuring the bundle. Not being a pro I only make apps for personal use at this stage so not sure how a different bundling arrangement would affect app signing or suchlike. The other consideration would be if a third-party bundling tool was used to produce a Mac bundle then I would likely expect it to follow the Apple recommendations.

**Comment by malipetek** [comment]
I see, I think I found a workaround. Updated the builder script on the boilerplate.
Please check this app: [myapp.app.zip](https://github.com/neutralinojs/neutralinojs/files/7297174/myapp.app.zip)

It executes a bash script when app starts, and script executes the neu executable with cli parameter that points to the `res.neu` in the Resources folder.

**Comment by Blatman** [comment]
I managed to get the app going by replacing the myapp binary with one built on 10.13.6 and the parameterized works fine. Looks like it is called via the Info.plist file so nothing special needed in the main binary. I'm going to try and get the boilerplate working but having hassles with the node_modules folder at the moment.
Neutralino gives the option of using discrete files if the res.neu is unavailable so in theory the parameterized script should still allow that. Might be worth suggesting the parameterized method to the devs to facilitate the mac app bundling as the binary co-located resources approach is OK for linux/win but no good for mac.

**Comment by Blatman** [comment]
Closing this issue for now as the use of a boot file to set the resources path for the binary works OK in 2.8.0 and 3.0.0 - I notice someone posted a Mines.app which uses the same technique.
