### ISSUE TITLE
Unable to init the server and GTK error

### ISSUE THREAD

**Issue by simonemarin** [neutralinojs/neutralinojs#580]
**Expected Behavior**  
I am just trying out the test app as indicated in the starting up docus  
**Actual Behavior**  
io@ioxps:/home/io/nodejs/netralinotest/myapp$ ./bin/neutralino-linux_x64 --load-dir-res --path=. --debug-mode
Unable to init server: Could not connect: Connection refused

(neutralino-linux_x64:22641): Gtk-CRITICAL **: 17:11:09.108: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(neutralino-linux_x64:22641): Gtk-CRITICAL **: 17:11:09.108: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(neutralino-linux_x64:22641): Gtk-CRITICAL **: 17:11:09.108: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)

**Specifications**  
* --- Global ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.0

--- Project: myapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0

* Platform: Ubuntu 64

**Comment by simonemarin** [comment]
It is working now after a reboot, cannot really say why.

**Comment by shalithasuranga** [comment]
hm yeah, a bit strange issue. looks like something related to the X server configurations

**Comment by aoor9** [comment]
Same behavior encounters when booting the app on XUbuntu (xfwm)
