### ISSUE TITLE
Neutralino.os not working

### ISSUE THREAD

**Issue by dipenchand** [neutralinojs/neutralinojs#587]
**Expected Behavior**  
None of `Neutralino.os` methods work.
  
**Actual Behavior**  
I want to run `Neutralino.os.runCommand()` or `Neutralino.os.execCommand()` or `console.log()` but... none of these are  working. But `Neutralino.app.open()` commands are executing. 
There is no output on console except following 2 lines:
```
Starting process: neutralino-mac_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
```

**Steps to Reproduce the Problem**  
 1. `neu create myapp`
 2. Added following lines:
 ```
Neutralino.init(
    Neutralino.os.execCommand({
        command: 'ipconfig'
    })
);
```
 3. `neu run`

**Specifications**  
```
 _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___ 
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/     
--- Global ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.1

--- Project: neu-app (js.neutralino.sample) ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
```
* Platform: **Windows & MacOS** tried with both

**Comment by shalithasuranga** [comment]
Could you try this ;)

```js
Neutralino.init();
let resp = await Neutralino.os.execCommand({
   command: 'ipconfig'
});
console.log(resp.output);
```

**Comment by dipenchand** [comment]
@shalithasuranga 
Thank you so much for clarifying. Now I've few more questions.
- I could just see the following output on browser, but not much details.
  ```
  {
    "needsReload": false,
    "success": true
  }
  ```
- Is there any way to get details output, when command executes?
- I have to run command `node server.js`, then how can I achieve this?
