### ISSUE TITLE
Process-ID(pid) of the App via NL_PID

### ISSUE THREAD

**Issue by benwalksaway** [neutralinojs/neutralinojs#588]
**Context**:
To use the win32(gui) API to access the app's gui, I need the process ID (pid) of the app. I need the process ID because I can react to events outside of the "window" / app.

Maybe it is possible to set the process ID as a global variable (NL_PID)?

Thanks in advance! :)

**Comment by shalithasuranga** [comment]
This is a great idea. I will add it to the next release

**Comment by benwalksaway** [comment]
Thanks for your answer!
I appreciate your work very much. :heart:

Have a great day!  :smiley:

**Comment by shalithasuranga** [comment]
This is added. I will release this feature with the next release. Thanks for adding this feature request.

**Comment by benwalksaway** [comment]
Thank you! :pray:
