### ISSUE TITLE
Add arm64 arch support for Linux

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#593]
For new Raspberry Pi OS boards etc..

**Comment by shalithasuranga** [comment]
I gave a try to compile/test Neutralinojs on arm64 (arch64), but it was not successful. I am adding here the steps I tried. Maybe, another contributor can get it working. 

- Created an arm64 machine with QEMU via virt manager.
- Installed Debian arm64
- Installation was successful
- Installed Genome desktop environment and it was also fine
- But once I log in to Debian, the VM is getting stuck

Maybe, a resource issue since I tried with 4GB RAM

**Comment by shalithasuranga** [comment]
Closing this because now we only release x64 pre-built binaries. See: https://neutralino.js.org/docs/#supported-platforms-and-cpu-architectures

**Comment by williamrijksen** [comment]
Hi,

How could I run my neutralino project on my raspberry pi 4 2GB? 
`dpkg --print-architecture` gives me a `arm64`. 

Running my project returns the following error 
```npx @neutralinojs/neu run --arch arm64
ERROR Unsupported platform or CPU architecture: linux_arm64```

**Comment by shalithasuranga** [comment]
Hey.. @williamrijksen  At the moment, Neutralinojs only provides x64 binaries via the official CLI because we didn't find a clean way to compile non-x64 binaries via GitHub Actions. (Not sure whether they've added the support now -- we need to check further). But, that doesn't mean Neutralinojs doesn't work on non-x64 architectures. You can compile and get binaries on any platform. It doesn't require many configurations -- you can check more details here: https://neutralino.js.org/docs/#supported-platforms-and-cpu-architectures

**Comment by williamrijksen** [comment]
@shalithasuranga thanks for the reply. I tried to compile it on the raspberry pi, but when I want to install the required libraries, I received the following error. 
```
sudo apt install \
    libgtk-3-dev \
    libwebkit2gtk-4.0-37 \
    libwebkit2gtk-4.0-dev \
    libappindicator3-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libappindicator3-dev
```

Do you know what to do?

**Comment by williamrijksen** [comment]
@shalithasuranga probably it has something to do with https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages. Are there any plans to migrate to `libayatana-appindicator`?

**Comment by shalithasuranga** [comment]
Hey.. thanks for checking. yeah seems like we need to check and use the new library since the previous lib seems replaced. We are using a modified version https://github.com/zserge/tray for the tray menu and it uses `libappindicator`. I will check about this further via https://github.com/neutralinojs/neutralinojs/issues/799

Haven't checked further but probably changing current include to `#include <libayatana-indicator/indicator.h>` will work for you seems :)

**Comment by williamrijksen** [comment]
@shalithasuranga I created a PR to fix this issue https://github.com/neutralinojs/neutralinojs/pull/800

**Comment by nmenon** [comment]
@shalithasuranga dunno if https://github.com/nmenon/adocker/blob/main/.github/workflows/docker-image.yml will help
