### ISSUE TITLE
HTTP Status codes

### ISSUE THREAD

**Issue by caramboleyo** [neutralinojs/neutralinojs#595]
When I use an xhr to load a file that does not exist, I get a HTTP Status 200 response. Shouldn't it be 404? How to determine else a xhr tries to fetch a file that does not exist?

```
const response = await fetch('not/existent/file');
```
![image](https://user-images.githubusercontent.com/88926539/133880430-5c09843a-80ed-4f79-a3f1-96c21f3c965f.png)

--- Global ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.1

--- Project ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this. Now the server will return 404 if the file doesn't exist on resources folder or `res.neu` file. I will release this with the next version.
