### ISSUE TITLE
Add maOS ia32 and native arm64 binaries

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#596]
Right now x64 is released for arm64 (will work with Rosetta). But we need a native arm64 binary.

**Comment by shalithasuranga** [comment]
Closing this because now support only x64 pre-built binaries with GitHub actions (https://neutralino.js.org/docs/#supported-platforms-and-cpu-architectures) But developers can build binaries on any CPU architecture.

**Comment by denisw** [comment]
> Closing this because now support only x64 pre-built binaries with GitHub actions (https://neutralino.js.org/docs/#supported-platforms-and-cpu-architectures) But developers can build binaries on any CPU architecture.

I tried building macOS arm64 binaries using the Framework Developer Guide instructions, but I still end up with an x86-64 binary:

```sh
$ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin21.6.0
...

$ python3 scripts/bz.py

  ____        _ _     _ ______     _
 |  _ \      (_) |   | |___  /    (_)
 | |_) |_   _ _| | __| |  / / _ __ _
 |  _ <| | | | | |/ _ ` | / / | '__| |
 | |_) | |_| | | | (_| |/ /__| |  | |
 |____/ \__,_|_|_|\__,_/_____|_|  |_|
    1 {

 BuildZri v1.0.0 - A minimal build automation tool for C++


Compiling Neutralinojs...
OK: Neutralinojs compiled into ./bin/neutralino-mac_x64

$ file bin/neutralino-mac_x64 
bin/neutralino-mac_x64: Mach-O 64-bit executable x86_64
```
