### ISSUE TITLE
Freeze when click on close

### ISSUE THREAD

**Issue by paulocoutinhox** [neutralinojs/neutralinojs#618]
**Expected Behavior**  

When i click on close button it need close the app.
  
**Actual Behavior**  
When i click on close button it don't close. When i try force quit from dock, it freeze and crash.

![image](https://user-images.githubusercontent.com/395096/135707535-de1281f0-375c-4dd1-99c9-f3e7b258dafe.png)

**Steps to Reproduce the Problem**  
 1. List the steps to reproduce the problem
 2. Step 2
 3. Step 3

**Specifications**  
* NeutralinoJs Version: latest
* NeutralinoJs CLI version: latest
* Platform: macos bigsur

**Comment by shalithasuranga** [comment]
Hey.. when you load remote urls with Neutralino, the native API gets automatically disabled. The native API handles window events (In your scenario, close event). Could you please try loading a file from computer? Eg: `/resources/index.html`

**Comment by paulo-coutinho** [comment]
Hi,

In my case im using only the `webview.h` file to load an html page.

**Comment by shalithasuranga** [comment]
Hey all.. we'll add a new config option to inject the client lib to the webview: It's in https://github.com/neutralinojs/roadmap .. Thanks for reporting this :)

Btw @paulo-coutinho Do you mean u got it working by compiling the webview code or Neutralinojs code?

**Comment by paulo-coutinho** [comment]
All forks of webview has the same problem.

Im creating a project like this project that i have called Ezored (github.com/ezored/ezored).

But instead of use native of web interface on mobile/desktop, it will focus on use C++ for all functions/backend and WEB as GUI.

**Comment by elliotwutingfeng** [comment]
> Hey.. when you load remote urls with Neutralino, the native API gets automatically disabled. The native API handles window events (In your scenario, close event). Could you please try loading a file from your computer? Eg: `/resources/index.html`. Make sure that the index.html has `<script src="<js dir path>/neutralino.js"></script>`

This "unable-to-close" problem appears to affect all instances of neutralinojs-cli-appify as well, likely because of the loading of remote urls.

**Comment by shalithasuranga** [comment]
Hey.. Please use this setting https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean to close the process immediately without triggering `windowClose` action

**Comment by elliotwutingfeng** [comment]
Thanks, the following works, with `modes.window.enableInspector` enabled.

1. Go to app root folder (e.g. **<app_name>**), open up `neutralino.config.json`, change the setting `modes.window.exitProcessOnClose` to `true`
2. `cd` to app root folder in Terminal, and run the following
```bash
neu build --release # Rebuild the application
chmod +x ./dist/<app_name>/<app_name>-linux_x64 # Enable file execution permissions

```
However, if I disable the web inspector by setting `modes.window.enableInspector` to `false`, the appified website would freeze on load. I tried this website: https://poolsuite.net/

**Comment by shalithasuranga** [comment]
Hey all.. The app will exit properly if we use this option: https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean in the config. Please check with the latest version. Thanks :tada:
