### ISSUE TITLE
Cannot close window if content is PDF

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#621]
MacOS 10.13.6  NS: 2.8.0  NC:  1.5.0

**Expected Behavior**  
Window should be closable with close button with whatever content.
Being able to hide the window before app close in order to do tidy up should still be allowed with whatever content.
   
**Actual Behavior**  
It appears that the window will only be closable if the content is HTML (Local as per #618) as the close button is controlled from the client lib. If the content is say PDF then the window can only be closed via the Dock icon.

**Comment by shalithasuranga** [comment]
Hey.. we'll add a new option to config to inject the client lib to the webview: It's in https://github.com/neutralinojs/roadmap .. That's for reporting this :)

**Comment by shalithasuranga** [comment]
Now we can set `window.exitProcessOnClose = true` (by default it's true too) to close the app with window close event. If we need to write custom handling before with close event we need to set `window.exitProcessOnClose = false`. This fix will be released with the next version but you can try by building from source too ;)
