### ISSUE TITLE
Can't load source map from devtools: File extension: map is not supported

### ISSUE THREAD

**Issue by Alger23** [neutralinojs/neutralinojs#627]
I use create-react-app generate project, but cannot load source map in browser.

**Expected Behavior**  
Load source map file success
  
**Actual Behavior**  
Cannot load source map for debug

**Steps to Reproduce the Problem**  
1. build react project `yarn build`, build path is `./resources`

files
```
./resources/static/js/2.3109b74c.chunk.js
./resources/static/js/2.3109b74c.chunk.js.map
```

2.  neutralino.config.json set ` "defaultMode": "browser"`

3. open browser with devtools cannot load source map files.

Then I paste url to browser: `http://localhost:61586/resources/static/js/2.3109b74c.chunk.js.map`

I got error message:
```
{"error":"File extension: map is not supported"}
```

**Specifications**  
--- Global ---
Neutralinojs binaries: v2.8.0
Neutralinojs client: v1.5.0
neu CLI: v6.2.0

* Platform: macos big sur

**Comment by Alger23** [comment]
Look like add [mimetype](https://github.com/neutralinojs/neutralinojs/blob/7e2113a838f29714e48f1b5fa30e3d8dc8741cdd/server/router.cpp#L167) can solve this problem.

```
{"map", "application/json"},
```

I did build neutralinojs, and then copy `./bin/neutralino-mac_x64` to `myproject/bin/neutralino-mac_x64`. Source map work fine, but native api request failed. >_<

**Comment by shalithasuranga** [comment]
Ah.. I think I've added a new commit to load a default mime type. Was it not working for u? Not for the release but for the main branch I think

**Comment by Alger23** [comment]
It works. `main` branch can load source map. 
But other native api call failed. I didn't check what happened.

````
Neutralino.storage.getData({
          bucket: 'userSettings'
        }).then(response => {
          if (response.data) {
            setSettings(JSON.parse(response.data));
          }
        }).catch(error => {
          console.log('get settings failed');
          setSettings(defaultSettings);
        });
```

Response:
```
{"error":{"code":"NE_RT_NATRTER","message":"Native method execution error occurred. Failed because of: std::exception"}}
```

**Comment by shalithasuranga** [comment]
Ah, forgot to mention that v3 has breaking changes. Please check https://github.com/neutralinojs/v2-client-specification
`Neutralino.storage.getData('userSettings')` will return the stored data directly.

**Comment by Alger23** [comment]
@shalithasuranga 


In [v2-client-specification README.md](https://github.com/neutralinojs/v2-client-specification/blob/main/README.md) filesystem
```
filesystem.readBinaryFile: filesystem.readBinaryFile(fileLocation, binaryData)
# Should be 
filesystem.readBinaryFile: filesystem.readBinaryFile(fileLocation) 
```

To build execute file by myself is not good idea. Others clone my code will run failed.
If use `neu update` will restore `./bin/*`  and `neutralino.js` to 
```
Neutralinojs binaries: v2.8.0
Neutralinojs client: v1.5.0
```

Can I change Version in `neutralino.config.json` to make `neu update` download different version?
```
    "binaryVersion": "2.8.0",
    "clientVersion": "1.5.0"
```

**Comment by shalithasuranga** [comment]
Hey.. @Alger23  nice catch :D I've update that README. hm I think you meant the CLI needs to download binaries/client based on config's version when other devs clone/run your project right? Right now `neu update` always fetch the latest version based on CLI's config. Could you please add your suggestion to https://github.com/neutralinojs/neutralinojs-cli?
