### ISSUE TITLE
Get Position of window

### ISSUE THREAD

**Issue by MatthijsKamstra** [neutralinojs/neutralinojs#631]
I was trying to "remember" the location of the window...

It's possible to get the width and height of the resized window

```js
		var json = {
			width: window.innerWidth,
			height: window.innerHeight,
		};
```

but not the x and y position of the window		

So that would be my request:

```js
let windowXPos = await Neutralino.window.getX();	// 100
let windowYPos = await Neutralino.window.getY(); //200
// or
let windowPos = await Neutralino.window.getPosition(); // {x:100,y:100}
```

**Comment by danidre14** [comment]
Bumping this feature request. Any change on possibilities of X and Y of window? You can set positions but can you get positions? @shalithasuranga

**Comment by shalithasuranga** [comment]
Hey.. all .. thanks for reporting this and discussing this. This feature will be released soon with the next version
