### ISSUE TITLE
Unable to load images

### ISSUE THREAD

**Issue by StevenStavrakis** [neutralinojs/neutralinojs#636]
**Expected Behavior**  
Setting element background to image should load image into background of element.
  
**Actual Behavior**  
No new background image is loaded. The image URL gives an error. 

**Steps to Reproduce the Problem**  
 1. Generate PNG image using FFMPEG in /resources/images
 2. Attempt to load image into front-end using Javascript

**Specifications**  
* NeutralinoJs Version: 2.8.0
* NeutralinoJs CLI version: 6.2.1
* Platform: Windows

**Comment by StevenStavrakis** [comment]
```//Given a file URI for a video, execute an FFMPEG command and create a single png inside the app
//Return an object with the relative and absolute path for the new image
const generateFrame = async (uri) => {
    console.log("generating Frame")
    let relImageUri =`images/thumbnail-${Date.now()}.png`
    let imageUri = `${NL_CWD}/resources/${relImageUri}`
    await Neutralino.os.execCommand({
        command:`ffmpeg -i "${uri}" -ss 00:00:01.000 -vframes 1 "${imageUri}"`
    })
    getStats(`/${relImageUri}`)
    return {imageUri, relImageUri};
}

//When selecting the video, save the uri to a global state object
//Use uri in generateFrame()
//Set div BG to the uri provided by generateFrame()
const uploadVideoRight = async () => {
    let response = await Neutralino.os.showDialogOpen({
        title: 'Select a file',
        isDirectoryMode: false
    });
    state.video_2 = response.selectedEntry;

    let previewImage = await generateFrame(state.video_2)

    let el = document.querySelector(".videoPreview.right")
    el.style.backgroundImage=`url(${previewImage.relImageUri})`
}```

Hopefully this is enough, let me know if you need anything else.

**Comment by LTVA1** [comment]
I have the same problem. Combined with broken icon I just want to return to 3.0.0 where all worked perfectly. btw how can i do it

**Comment by LTVA1** [comment]
I get this log
```ERROR 2021-12-16 22:16:25,029 Unable to open C:/Users/Georg/Nextcloud/What-happened-in-Taingia/dist/What_happened_in_Taingia/resources/icons/appIcon.png api/debug/debug.cpp:15 georg@GEORG-PC
ERROR 2021-12-16 22:16:46,339 Unable to open C:/Users/Georg/Nextcloud/What-happened-in-Taingia/dist/What_happened_in_Taingia/index.html api/debug/debug.cpp:15 georg@GEORG-PC```

**Comment by Prakashd20** [comment]
> After using my original code, on application exit, I am prompted with this error in console:
> ```2021-10-12 11:30:22,914 Unable to open ./resources/images/thumbnail-1634052621290.png```

It could happen because sources tab of the inspector, there are no available files besides css or js, your images folder exists on different which would have been a issue.

**Comment by shalithasuranga** [comment]
I am closing this since images get loaded properly on all platforms. Thanks for reporting and discussing :tada:

**Comment by Prakashd20** [comment]
was my comment useful to you for solving the acquired issues you faced?
