### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by vagish8962** [neutralinojs/neutralinojs#637]
Hi,

Do we have support for HTTPS also? 

I have to load an iframe that contains HTTPS URL and when I and adding an iframe in the index.html file and try to run it using neu run. My iframe content is not loading.

Please help

**Comment by shalithasuranga** [comment]
Hey.. I've just tested. Usually, iframe's HTTPS URLs work fine if the particular URLs are allowed to be embedded. Please check your URL's `X-Frame-Options` header value.

**Comment by shalithasuranga** [comment]
I am closing this issue since HTTPS URLs worked ok with iframes on the test app. Feel free to discuss and re-open if the issue still exists
