### ISSUE TITLE
API calls executing in exterior directories

### ISSUE THREAD

**Issue by StevenStavrakis** [neutralinojs/neutralinojs#638]
**Expected Behavior**  
```Neutralino.filesystem.writeFile({fileName: "./random.txt", data:"Hello world")}``` should create a file called random.txt in the application directory.

```
Neutralino.os.execCommand({
        command:`ffmpeg -i "${uri}" -ss 00:00:01.000 -vframes 1 output.mp4`
    })
```

Should execute ffmpeg command from the application directory.
  
**Actual Behavior**  
```Neutralino.filesystem.writeFile({fileName: "./random.txt", data:"Hello world")}``` creates random.txt in the directory last used in a file select dialogue.

```
Neutralino.os.execCommand({
        command:`ffmpeg -i "${uri}" -ss 00:00:01.000 -vframes 1 output.png`
    })
```

Executes the ffmpeg command in the directory last used in a file select dialogue.

**Steps to Reproduce the Problem**  
 1. Obtain video file (input.mp4) URL through file select dialogue
 2. Call execCommand for an ffmpeg command using the file path from step one
 3. Find output.png in the directory where input.mp4 was selected from

**Specifications**  
* NeutralinoJs Version: 2.8
* NeutralinoJs CLI version: 6.2.1
* Platform: Windows 10

**Comment by shalithasuranga** [comment]
This is fixed.. will be released soon. Thanks for reporting
