### ISSUE TITLE
Issue regarding the import of the neutralino.js file into index.html of react webpack app development

### ISSUE THREAD

**Issue by Sajad321** [neutralinojs/neutralinojs#656]
Hello Everyone,
I am trying to make a react webpack neutralino boilerplate but I am facing an issue in development mode.

**Expected Behavior**  
To work on react localhost while development
  
**Actual Behavior**  
Error: Neutralino.js Not Found

**Steps to Reproduce the Problem**  
As I was working in the resources there was no issue, But when I try to make the react app starts through npm start and then try to get the URL of the neutralino app to work on the localhost, it seems to have an issue importing the neutralino.js from the index.html.

I tried understanding the structure of working the project in webpack but like all of my projects I did, I didn't need to play with the index.html and importing into it

I tried importing the neutralino.js file in the index.js of react app but there were errors with this way.

What are your suggestions to fix this issue as I want to work in development rather than building my app and running as I have seen multiple repos doing that with CRA way?

Here is the repo with steps to reproduce the issue: 
https://github.com/Sajad321/Neutralino-React-Webpack-Boilerplate

NeutralinoJs Version: 2.8.0
NeutralinoJs CLI version: 1.5.0
Platform: Window-64bit

in the image you can notice the error but when i build and add the files to the index.html it is working fine, What i want is to make this work without building the react app just on dev

![Al-Amjad - Google Chrome 10_18_2021 7_50_54 PM](https://user-images.githubusercontent.com/40560180/137786519-866507d2-7de0-489e-941c-d3a0288449eb.png)

**Comment by shalithasuranga** [comment]
Hi.. @Sajad321, Please import the client library (neutralinojs) from NPM if you use a webpack-based development method as explained in [this page](https://neutralino.js.org/docs/getting-started/using-frontend-libraries/#initializing-native-api-with-neutralinojslib).

Thanks :)
