### ISSUE TITLE
MacOS - window.create not opening windows on 3.0.0

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#659]
Worked OK with 2.8.0 and 3.0.0pre (before the websocket implementation)

Promise resolves but is undefined/pending - seems that the window.create is not using the NL_PATH to the app resources as the rest of the API does.
In this case the NL_PATH is set from the booter executable (using --path) that starts the app.

NL_PATH is '/Users/USER/whatever/APITest.app/Contents/Resources

document.getElementById('openWindow').onclick = async function openWindow(){
//    let owin = Neutralino.window.create(NL_PATH + '/views/index.html', {
    let owin = Neutralino.window.create('/views/index.html', {     // usual setting
        width: 900,
        height: 200,
        hidden: false,
        processArgs: '--window-id=W_VIEWER' 
    })
    .then(function(owin) {
        console.log('OWIN', owin);
    })
    .catch(function(err) {
        console.log('errOWIN', err);
    });
    console.log('OWIN2', owin);
}

[APITest.zip](https://github.com/neutralinojs/neutralinojs/files/7372326/APITest.zip)

**Specifications**  
* NeutralinoJs Version: 3.0.0
* NeutralinoJs CLI version: 2.0.0
* Platform: 10.13/14

**Comment by Blatman** [comment]
@shalithasuranga - jolly good work, I have tried the latest source and the new process arrangement has improved the windows issues. I now find the windows open OK (the setTray crashes but still looking at that).
Just a comment about the execCommand return - I notice that the pid can be returned for the child process and that may be a good idea to have that also for the window to allow window killing if main window exits, etc. At the moment the window.create will just return the "New window instance created" message. At the moment I arrange the subwindows to set pids in storage (using code in windows) that the main window can check on exit and kill as required. If the subwindows returned the pid inherently then that would be simpler - it would also allow pdf subwindows to be killed by a closing main window.

**Comment by shalithasuranga** [comment]
Hey.. nice to see you checked the latest changes. Yeah, did some improvements to the exeCommand (As in https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md). It's mainly for providing stdin to create our plugin system. But, like you mentioned solved some issues with spawning processes too. I will check about your idea for returning pid. Thanks :+1:

**Comment by Blatman** [comment]
Closing since the latest source has addressed the issue.
