### ISSUE TITLE
Server goes offline

### ISSUE THREAD

**Issue by AntonWedemeier** [neutralinojs/neutralinojs#663]
**Expected Behavior**  
I like to try a new version before installing it globally. So I installed it locally. I inserted the application I am working on inside this local environment and it failed. I got NE_CL_NSEROFF (Neutralino server is not reachable) exceptions with Neutralino calls. With version Neutralinojs binaries: v2.8.0, Neutralinojs client: v1.5.0, neu CLI: v6.2.91 all works fine.
  
**Actual Behavior**  
**Steps to Reproduce the Problem**  
To find the course I created a simple test.

I have installed the new 3.0 version in a local environment with “npm install --save-dev @neutralinojs/neu”. Created an application with “node ./node_modules/@neutralinojs/neu create TEST”. Runs the application from within TEST with “node ../node_modules/@neutralinojs/neu run”. The applications runs.

Then inside main.js I added a function that just calls Neutralino.os.getPath (as documented).
async function test() {
  try {
    let downloadsPath = await Neutralino.os.getPath("downloads");
    console.log(`Downloads folder: ${downloadsPath}`);
  } catch (e) {
    console.log(e);
  }
}
test();
Running this also gave the NE_CL_NSEROFF exception.

**Specifications**  
Neutralinojs binaries: v3.0.0
Neutralinojs client: v2.0.0
neu CLI: v7.0.0
on Windows 10

What can cause the Neutralino server to go offline?
Is there a way to test the status of the server inside the program?
Am I doing something wrong?

**Comment by Blatman** [comment]
@AntonWedemeier - just an update - I have been playing with  an app and having problems with the server offline that the ready event should solve. However in my buggy app I found the index.html script code was running twice and on the first run the offline was occurring. It seems that the ready event is not solid (server goes offline again) and any code wrapped with ready to cover the server delay will actually be re-executed with the next ready event (seemed to be ready/off/ready). The server delay always seems to be c. 30ms and it is difficult to trust the ready event. Even tried the serverOffline event but that is also multi-occurring.

What I found to work for me was using the async parameter when calling the associated js file.
<script type="text/javascript" src="js/wc.js" async charset="utf-8"></script>
I moved most of the scripting out of the index page into the js file and the async setting appears to give the websocket server time to settle.

BTW - the latest 3.0.0 source fixes the window.create issues on Mac (a process management library has been implemented).

**Comment by AntonWedemeier** [comment]
Thank you for the update.

You went deeper into it than I did. I am developing an app and I do not want to spent too much time to the tool I use. And from your observations I must conclude that version 3 of Neutralino is not ready to be used as a tool. (BTW, I try the app to run as well on a desktop with Neutralino, as without this tool in a browser.)

In my index file, I only have one script (js-file). That script adds all the other js and css files to the index file and waits for moment that the document.readyState is ‘complete’ before running any of those scripts. I should think that when the document is ready, the server is ready. But I am not a professional and I do not completely understand how the server works.

**Comment by shalithasuranga** [comment]
Hey.. thanks for discussing this. Yeah, the `ready` event is a bit confusing from the developer's perspective because of the other events like DOM loaded, unload, and React's component mount, etc. So now we can call native calls without depending on the `ready` or even `init`.

Now a simple queue will collect all native calls and process them when the WebSocket connection is established. More info: https://github.com/neutralinojs/neutralinojs/blob/73e8ef8ccdac949b562089cf9dc5d417ea9365a0/bin/resources/js/main.js#L15

**Comment by mzy2240** [comment]
I am using the latest version and am currently facing the same problem. Neu-cli is v7.1.0. The server is just offline all the time. Port is set to be 0. No any other errors from the console or logger. System is windows 10.
