### ISSUE TITLE
Question: How to import module

### ISSUE THREAD

**Issue by meilleur102** [neutralinojs/neutralinojs#666]
Hi! Im using neutralino for a desktop application that will download a release from Github and unzip / launch the application. 
The problem I have it's for the import. 
Since I can't download the zip file directly with fetch from the main.js of neutralino (CORS error), I build a ExpressJS server that download the file on the proper folder. 

My problem is when I fetch my server from neutralino, I can't get progress of the download. 
I wanted to use Axios instead of fetch to be able to have some progress but I'm not able to import the module. 
When I import it I have this error : 

Cannot use import statement outside a module

This is how I import the module 

```
import axios from './node_modules/axios/index';
```
and this is what i'm trying to do 
```
function OnLoadDefault(){
    Neutralino.os.execCommand('server.exe');
    axios.get({
        method: 'GET',
        url: 'http://localhost:3000',
        data: MediaKeyStatusMap,
        onUploadProgress: (p) => {
            console.log(p);
        }
    })
 
}
```

If any of you have a tips to get the progress from ExpressJS to neutralino I don't really care what module I use. 
Thanks

**Comment by shalithasuranga** [comment]
Hey.. this is possible with the extension API. you can write an extension to download the file and send the process as an event to the app. 

You can check an example Node extension in: https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension

We will update documentation for extensions API soon.
