### ISSUE TITLE
Add a way to fetch a file descriptor to be able to work with locks

### ISSUE THREAD

**Issue by IvoPereira** [neutralinojs/neutralinojs#676]
**Expected Behavior**  
The FileSystem should have an API that would either, provide locking and awaiting for a lock mechanisms or either expose a file descriptor method so that we can manage the locking ourselves.
  
**Actual Behavior**  
At the moment, there isn't a way to deal with file locking. If I have two asynchronous processes fetching and reading to the same file (in this case to storage), there might happen that I try to read while the other file is being written.

I have faced some strange crashes in some specific systems and I really considering this might be the case.

**Steps to Reproduce the Problem**  
 1. Have two asynchronous processes fetching and reading to the same file
 2. Application crashes

**Comment by danidre14** [comment]
For now I just use a single application and use `awaits` everywhere, but indeed if two separate neu processes (for instance, one added using `Netralino.create` was to access the same storage, there are many inconsistencies waiting to happen.
It can be as simple as making (at least for where neu storage is concerned) a queue serverside that processes the storage requests one by one.

Or it can maybe be more complex but that is out of my knowledge scope.

**Comment by shalithasuranga** [comment]
Hey.. I've just opened two windows and tried the following code on both windows.
```js
setInterval(() => {Neutralino.filesystem.writeFile("test.txt", Math.random().toString().repeat(100));Neutralino.filesystem.readFile("test.txt").then((x) => {console.log(x)});}, 10)
```
Neither process 1 or 2 crashed (on Linux). @IvoPereira If possible could you post a code snippet that crashed the app? Then we can find where is the issue ;)

**Comment by shalithasuranga** [comment]
Hey.. I am closing this since there was no issue found related to multi-threading. Feel free to reactivate this issue again by providing a code that shows multi-threading issues.
