### ISSUE TITLE
Updating 2.8.0 to 3.0.0 returns "neutralino-linux_x64 was stopped with error code 134"

### ISSUE THREAD

**Issue by IvoPereira** [neutralinojs/neutralinojs#677]
**Expected Behavior**  
After making the necessary changes to the current project to be able to update from 2.8.0 to 3.0.0, the project should run exactly as it was running before.
  
**Actual Behavior**  
The project exits with error code 134.

```sh
$ npm run dev:neu

> project@1.0.2 dev:neu
> vite build && neu run

vite v2.3.8 building for production...
✓ 100 modules transformed.
resources/assets/appIcon.efbaade2.png   22.39kb
resources/index.html                    0.61kb
resources/assets/index.0a17ca54.css     16.77kb / brotli: 3.61kb
resources/assets/index.aa7f9b8c.js      101.26kb / brotli: 19.31kb
resources/assets/vendor.10e2b1e1.js     89.52kb / brotli: 30.90kb
Starting process: neutralino-linux_x64  --load-dir-res --path=. --debug-mode
devAPIServer listening at http://localhost:5050
neutralino-linux_x64 was stopped with error code 134
```

**Steps to Reproduce the Problem**  
 1. Follow steps pointed here: https://github.com/neutralinojs/neutralinojs/issues/654 and adapt old API regarding https://github.com/neutralinojs/v2-client-specification
 2. Run npm run dev:neu
 3. Exit code appears

**Specifications**  
Neutralinojs binaries: v3.0.0
Neutralinojs client: v2.0.0
neu CLI: v7.0.0
Platform: Linux x64

**Comment by shalithasuranga** [comment]
Hey.. I am closing this since the dev server component was removed in v4. Hope you will check this issue on v4. Thanks for reporting this issue :)
