### ISSUE TITLE
Can't exit app window

### ISSUE THREAD

**Issue by roktcode** [neutralinojs/neutralinojs#678]
I am using GNOME desktop, during development and after build, the app won't exit when I click the exit button. In dev mode it won't exit until I terminate the process from the command line, and in production it won't exit at all. How can I fix it?

**Comment by VOKSEL0** [comment]
I'm also having this issue!

I'm using Ubuntu 21.10 impish and GNOME 40, I also installed all dev dependencies:
```sh
    libboost-all-dev \
    libgtk-3-dev \ 
    libwebkit2gtk-4.0-37 \ 
    libwebkit2gtk-4.0-dev \
    libappindicator3-dev
```

**Comment by VOKSEL0** [comment]
# Found a way to fix it!
Simply added
```js
Neutralino.init();
Neutralino.events.on("windowClose", () => {
    Neutralino.app.exit();
});
```
to the bottom of my `main.js` file.
This should be documented if it isn't and if it is, we need to be more careful reading 🤣

**Comment by roktcode** [comment]
Oh yeah 😂  Thanks for showing up 🧡

**Comment by shalithasuranga** [comment]
Hey.. all.. Listening to `windowClose` is for custom handling on close. Eg: Showing a question dialog before closing. If you need to exit the process immediately with window close, please use https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean

**Comment by roktcode** [comment]
> Hey.. all.. Listening to `windowClose` is for custom handling the onclose event. Eg: Showing a question dialog before closing. If you need to exit the process immediately with window close, please use https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean

Thanks @shalithasuranga !!

**Comment by DevicyKenitou** [comment]
> Perhaps exitProcessOnClose should be true by default. :-) Good job to the creators! Loving it.

That method is bad, on Windows, when clicking on the default close button, the app freeze during 5 whole seconds before closing...

**Comment by haranobuhardo** [comment]
> exitProcessOnClose

Do you know a way to fix this delay?

**Comment by Soahr** [comment]
Same issue here why is this closed ?

**Comment by easyfrog** [comment]
> > exitProcessOnClose
> 
> Do you know a way to fix this delay?

yes has a long time delay , hwo to resolve it ?
