### ISSUE TITLE
Window size issues on builds

### ISSUE THREAD

**Issue by VOKSEL0** [neutralinojs/neutralinojs#680]
**Expected Behavior**  
The window should be 550px wide by 250px tall and not have a maximize button:
![image](https://user-images.githubusercontent.com/62223763/139557588-eacb29dc-dd65-47ec-b71e-6aa53416f9d3.png)
  
**Actual Behavior**  
![image](https://user-images.githubusercontent.com/62223763/139557592-ad7b0af4-a2e6-41ff-9f7d-08596c4e2205.png)
Can't exit window on either, when clicking X button, it is simply ignored.

**Steps to Reproduce the Problem**  
 1. Use `neu create [app]` to create an app from template
 2. edit `neutralino.config.json` to have these window sizes:
 ```
"width": 550,
"height": 250,
"minWidth": 550,
"minHeight": 250,
"maxWidth": 550,
"maxHeight": 250,
```
 3. `neu run` should work as expected however using `neu build --release` and running doesn't

**Specifications**  
* Neutralinojs binaries: v3.0.0
* Neutralinojs client: v2.0.0
* neu CLI: v7.0.0
* Platform: Ubuntu 20.10 impish, GNOME 40

**Comment by shalithasuranga** [comment]
Ah looks like some issue with sizing, but there are some other ways to make the window fixed. Eg: https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowresizable-boolean

**Comment by VOKSEL0** [comment]
Thank you for commenting! I also tried that but had no luck, I was able to fix the window not being able to close but the size is still broken (only on builds though)

**Comment by VOKSEL0** [comment]
I tried running it in the terminal and for some reason; sizing issues are fixed (not when ran directly from file browser)

**Comment by shalithasuranga** [comment]
Hey.. I just checked on Ubuntu, worked fine for me with the following `window` object.

```json
    "window": {
      "title": "testSize",
      "width": 800, // Note this
      "height": 500, // Note this
      "fullScreen": false,
      "alwaysOnTop": false,
      "icon": "/resources/icons/appIcon.png",
      "enableInspector": true,
      "borderless": false,
      "maximize": false,
      "hidden": false,
      "resizable": false, // Note this
      "exitProcessOnClose": true
    },

```
Result: Fixed window

![image](https://user-images.githubusercontent.com/18402702/139668914-116bd302-9ca9-4485-8da6-e534ee1f5261.png)

**Comment by VOKSEL0** [comment]
Thanks! that worked. It seems like lower resolutions tend to have problems for some reason.
