### ISSUE TITLE
Issue using null in API 

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#683]
**Specifications**  
* NeutralinoJs Version: 3.0.0 latest source
* NeutralinoJs Client Lib version: 2.0.0 latest source
* Platform: Mac 10.13.6 High Sierra

Various API functions are having problems when null is used - usually unless specified the default will apply but the null checking is causing a crash.

All worked OK on 2.8.0

The workround is to specify the default or whatever and not use null.

Using  Neutralino.os.showMessageBox -

    var title = 'App PID',
    content = 'Main window ID is ' + NL_PID,
    type = 'INFO';

//  Neutralino.os.showMessageBox(title, content, null, type);   // null check on choice parameter broken - app crash
    Neutralino.os.showMessageBox(title, content, 'OK', type);   // Works fine

Using  Neutralino.storage.setData -

    var result = Neutralino.storage.setData('Cricket', null)  // fails with error code
    .then(function(result) {
        var title = '"Cricket" bucket removed from storage',
            content = '';
        Neutralino.os.showMessageBox(title, content); 
    })
    .catch(function(err) {
        console.log('errClearStore:',  err);
    });

get Error code: "NE_RT_NATRTER"
          message: "Native method execution error ocurred. Failed because of: std::exception. Make sure that you've provided required parameters properly." 

workround - unable to kill bucket but can empty with "" string.

Using  Neutralino.os.setTray -

    let tray = {
        icon: "/icons/trayIcon.png",
        menuItems: [
            {id: "VERSION", text: "Get version", isDisabled: false, isChecked: false},
        //    {id: "VERSION", text: "Get version", isDisabled: false},  // null check on isChecked broken - app crash
            {id: "SEP", text: "-", isDisabled: false, isChecked: false},
        //    {text: "-", isDisabled: false, isChecked: false},  // null check on id broken - app crash
            {id: "CHECKO", text: "Example: checked", isDisabled: false, isChecked: true},
            {id: "QUESTION", text: "Example: question", isDisabled: false, isChecked: false},
        //    {id: "DISABLED", text: "Example: disabled", isChecked: false},   // null check on isDisabled broken - app crash
            {id: "DISABLED", text: "Example: disabled", isDisabled: true, isChecked: false},
            {id: "NOTIFY", text: "Example: notification", isDisabled: false, isChecked: false},
            {id: "APID", text: "Example: App PID", isDisabled: false, isChecked: false},
            {id: "SEP2", text: "-", isDisabled: false, isChecked: false},
            {id: "QUIT", text: "Quit", isDisabled: false, isChecked: false}
        ]
    };

**Comment by shalithasuranga** [comment]
Hey.. some updates about this. I think we've fixed the `os.setTray` related issue (not released yet). Also, regarding the `null` in other places, yeah `null` fails to map with C++ data type - we need to fix this. But, as you mentioned, there are some workaround using `undefined` also I think

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting the issue in a detailed way. Now Neutralino process will accept `null`. Note that `NE_RT_NATRTER` will be thrown for mismatching data types (Eg: providing a number for string field)
