### ISSUE TITLE
Is there a "skipTaskbar" configuration for the app's window?

### ISSUE THREAD

**Issue by zvikasdongre** [neutralinojs/neutralinojs#687]
**Hello!**, 

I know there is a configuration named "hidden" for app's window but it just hides (as the name suggests) the app completely, which is not what I want. I want the app's window to still be visible but it's icon should not appear in task bar.

Tauri has this config named "[skipTaskbar](https://tauri.studio/en/docs/api/config#tauri.windows.skipTaskbar)".
If it doesn't already exists then consider this issue as an Feature Request.

Or if you have any workaround please tell me!

**Thanks**.

**Comment by michelljunior** [comment]
Hello, you can use "borderless", set true

**Comment by DEVLOPRR** [comment]
> Hello, you can use "borderless", set true

It will disable the borders but not the icon from taskbar

**Comment by shalithasuranga** [comment]
Closing as a duplicate of #509. Thanks for reporting this and discussing :tada:
