### ISSUE TITLE
Neutralinojs.log File Still Logging when set to False (bug)

### ISSUE THREAD

**Issue by danidre14** [neutralinojs/neutralinojs#690]
**Expected Behavior**  
Neutralino's config `logging.enabled: false` and `logging.writeToLogFile: false` should prevent a log file from being created and written.
  
**Actual Behavior**  
Despite having those settings, a log file is still created in my application dist when I launch the `.exe`

**Steps to Reproduce the Problem**  
 1. Include the following in your `neutralino.config.js` file:
 ```javascript
{
    "applicationId":"js.neutralino.sample",
    "defaultMode":"window",
    "port":0,
    "url":"/resources/",
    "enableServer":true,
    "enableNativeAPI":true,
    "logging":{
        "enabled":false,
        "writeToLogFile":false
    },
    "nativeBlockList":[],
    "globalVariables":{},
    "modes":{
        "window":{
            "title":"Rogot Mini 2",
            "width":560,
            "height":420,
            "minWidth":400,
            "minHeight":400,
            "fullScreen":false,
            "alwaysOnTop":false,
            "icon":"/resources/icons/appIcon.png",
            "enableInspector":false,
            "borderless":false,
            "maximize":false,
            "hidden":false,
            "resizable":true,
            "exitProcessOnClose":true
        },
        "browser":{},
        "cloud":{}
    },
    "cli":{
        "binaryName":"neutralino",
        "resourcesPath":"/resources/",
        "clientLibrary":"/resources/js/neutralino.js",
        "binaryVersion":"3.0.0",
        "clientVersion":"2.0.0"
    }
}
```
 2. Build your neu application: `neu build`
 3. Open your application.
 Before opening:
![image](https://user-images.githubusercontent.com/10374096/140678368-6fa8e575-ab93-4627-9b9c-fc16ca9f07d6.png)

After opening:
![image](https://user-images.githubusercontent.com/10374096/140678463-57e0e221-b6d7-4127-9716-262806bcf483.png)

I have even opened the `res.neu` file in Notepad++ to confirm I have the proper configurations:
![image](https://user-images.githubusercontent.com/10374096/140678546-207fb998-c043-406f-bcca-433d697c340d.png)

However, the log file, while empty, is still added to the main directory, which is not the intended user experience at all.

Must I have to create a manual `execCommand` that deletes the log file on every start up? Even if I delete the file myself and re-open the app, the `neutralinojs.log` comes back.
In any case, this goes against the specifications:
![image](https://user-images.githubusercontent.com/10374096/140678861-cd3fe724-893b-429e-af38-883bbe8b7e0c.png)

Please assist accordingly.

Thanks.

**Specifications**  
* NeutralinoJs Version: 3.0.0
* NeutralinoJs CLI version: 2.0.0
* Platform: Windows 10 64 Bit

**Comment by Blatman** [comment]
If there is not a quick fix a quick and dirty workround could be to edit the source main.cpp file and rebuild the server binary.

L22 #define APP_LOG_FILE ""

Remove the file definition - works OK on Mac with no adverse consequences but not as flexible as a config setting.
I found that the logging can be toggled but the file production can't be.

**Comment by shalithasuranga** [comment]
Hey.. all.. this is fixed and will be released with the next version. Thanks for reporting
