### ISSUE TITLE
"The URL can’t be shown" error on newly created project

### ISSUE THREAD

**Issue by zvikasdongre** [neutralinojs/neutralinojs#691]
I Just used `neu create <appname>` and then ran `neu run` and It just shows "The URL can’t be shown".

**Expected Behavior**  
The app should show the contents of `index.html`...

**Actual Behavior**  
...Instead It just shows this line and nothing else. 😕 
![error image](https://user-images.githubusercontent.com/47200577/141071886-a590ae43-9ec5-4021-91dc-6c422a20cc80.png)

**Steps to Reproduce the Problem**  
 1. create a new project using `neu create my_test_app`
 2. `cd` into that directory
 3. run `neu run`

**Specifications**  
* NeutralinoJs Version: v2.7.0
* NeutralinoJs Client version: v1.4.0
* Neu CLI version: v6.1.0
* Platform: Linux Mint 20.2 x86_64

**Comment by shalithasuranga** [comment]
Hey.. Please create the app with Neu CLI version: v7.0.0. If you really need to use Neutralino v2.7, you can update your config's "enableServer" to "enableHTTPServer"

**Comment by zvikasdongre** [comment]
Thanks That worked. 🙂
