### ISSUE TITLE
enableInspector does not show "inspect element" window.

### ISSUE THREAD

**Issue by xcomsw** [neutralinojs/neutralinojs#692]
I recently transferred my project to a different windows 10 PC and I can't seem to make enableInspector work.
Here's my neutralino.config.json file

>   "modes": {
        "window": {
          "title": "qman3",
          "width": 100,
          "height": 100,
          "minWidth": 10,
          "minHeight": 10,
          "fullScreen": false,
          "alwaysOnTop": true,
          "icon": "/resources/icons/appIcon.png",
          "enableInspector": true,
          "borderless": true,
          "maximize": false,
          "maximizable": false,
          "hidden": false,
          "resizable": false,
          "exitProcessOnClose": true
    },

 #The app runs fine but I can't debug my project.

**Comment by shalithasuranga** [comment]
Hey.. could you install the Webview2 runtime and try to debug your project? I think `enableInspector` is not  supported for Edge runtime

**Comment by xcomsw** [comment]
> Hey.. could you install the Webview2 runtime and try to debug your project? I think `enableInspector` is not supported for Edge runtime

that fixed it! Thanks a lot!
