### ISSUE TITLE
Tray icon does not disappear when app exits (Windows)

### ISSUE THREAD

**Issue by jasonpolites** [neutralinojs/neutralinojs#700]
The tray icon sticks around until you mouse-over it if you close the app (even gracefully close). This is observed in the default app scaffold (`neu create myapp`)

Scanning the code, it looks like [`tray_exit()`](https://github.com/neutralinojs/neutralinojs/blob/4cfede165afa29e96e40d93405103112db392325/lib/tray/tray.h#L316) in `lib/tray/tray.h` is never called

```
 $neu version
  _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v3.0.0
Neutralinojs client: v2.0.0
neu CLI: v7.0.1
```

![image](https://user-images.githubusercontent.com/764528/142696798-94718283-ea8f-4f28-a0be-0637d75444b1.png)

**Comment by Antix-Development** [comment]
I can confirm that this still happens with server v4 and client v3.

**Comment by shalithasuranga** [comment]
Hey.. all this was fixed - will be released with the next version. Thanks for reporting :)
