### ISSUE TITLE
Starting empty/default app with "enableServer": false causes app to be unresponsive

### ISSUE THREAD

**Issue by jasonpolites** [neutralinojs/neutralinojs#701]
**Actual Behavior**  
The `enableServer` option in `neutralino.config.json` seems a little confusing as it _suggests_ the server can be disabled, but it also appears that there is a general assumption throughout that this server API exists (?). Either way, setting `"enableServer": false` causes the app to be unresponsive. It cannot be closed, and it appears that the `ready` event is never fired. The only way to exit the app (on Windows) is to force-kill in Task Manager. Also the console still displays `devAPIServer listening at http://localhost:5050` and indeed an HTTP server _is_ running at this address/port
  
**Expected Behavior**  
Either the `enableServer` should maybe not be an option, or setting it to false should have predictable results. It's not really clear what the server is used for, and under what circumstances it's required or not.

**Steps to Reproduce the Problem**  
 1. Follow the getting started guide, and create a new app with `neu create myapp`
 2. Open `neutralino.config.json` and set `"enableServer": false`
 3. Run `neu run`

**Specifications**  
```
> neu version
  _   _            _             _ _             _     
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v3.0.0
Neutralinojs client: v2.0.0
neu CLI: v7.0.1
```

```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19044 N/A Build 19044
```

**Comment by shalithasuranga** [comment]
Hey.. please set https://neutralino.js.org/docs/configuration/neutralino.config.json#modeswindowexitprocessonclose-boolean to true if you want to disable the built-in server. I will check and update the code if we can automatically set this option to true when the server is not used/started.

**Comment by shalithasuranga** [comment]
Now the window will close properly if `enableServer` is `false`. I will update the documentation with more details about `enableServer` when we update docs for v4
