### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by AdamKearn** [neutralinojs/neutralinojs#703]
**Expected Behavior**  
Neutralino should detect the changes to the source code (`/resources` folder) and auto-reload the page to reflect the HTML changes.

---

**Actual Behavior**  
When using ReactJS or Angular the built files are not reflecting the changes/updates until the neutralino window view has been refreshed with `F5` or `ctrl + r`.

Looking at the API on `localhost:5050` you can see that `needsReload` gets set to `true` and as soon as the window has been reloaded it changes to `false`.   

However, you still have to manually refresh the page/window to show the new edits to the code.

---

Before manually reloading:
```
{"needsReload":true,"success":true}
```

After manually reloading:
```
{"needsReload":false,"success":true}
```

---

**Specifications**  
* NeutralinoJs Version: v2.0.0
* NeutralinoJs CLI version: v7.0.1
* Platform: Win 10 x64

**Comment by shalithasuranga** [comment]
Hey.. hot reloading support was added with https://github.com/neutralinojs/neutralinojs-cli/issues/96 we will update docs soon.. Thanks for reporting the issue :)
