### ISSUE TITLE
Bluetooth API Support Needed.

### ISSUE THREAD

**Issue by shahidmau** [neutralinojs/neutralinojs#708]
Hi, I liked the concept of the lightweight portable app. I was trying to play around with it and wanted to implement some bluetooth related app using **[Web Bluetooth API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API)**. 

I tried a very basic example and it did not work on my **macOs** Catalina. The Bluetooth API works only in a few browsers including **Google Chrome**. What I am assuming is that neutralinojs is not using Chrome browser to render the app and it uses **Safari** browser where Web Bluetooth API is not supported.

I suggest a few things.
1. A native support for Bluetooth API and [Web Serial API](https://wicg.github.io/serial/)
2. The way to use Google Chrome while rendering the app.

Thanks to @shalithasuranga and the team for this awesome app.

**Comment by shalithasuranga** [comment]
Hey.. the Neutralino API is minimal and generic for all apps. Therefore, I think implementing an extension for this scenario is better :) But the extension API is not released yet. However, you can check a sample one here https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension

**Comment by shalithasuranga** [comment]
Hello.. Thanks for reporting the issue. I am closing this since now we can extend Neutralino API will API extensions. We will update the documentation soon after the release :). Then you can simply pick any Bluetooth library and use it with the Neutralino app.

**Comment by Beelink** [comment]
@shalithasuranga Do you have any other examples? Because I didn't really catch it
