### ISSUE TITLE
Late loading of config and resources? Flickering on start

### ISSUE THREAD

**Issue by dkirchhof** [neutralinojs/neutralinojs#709]
**Expected Behavior**  
If I open a built application (window mode), it should open the application directly in the configured width and height. It should also have the background color specified in my css file.

**Actual Behavior**  
The application starts in a small white window (like 400 * 400 px). After some milliseconds it changes the size to the configured one (specified in the config file) and sets the background color.

**Steps to Reproduce the Problem**  
 1. Define width and height for the window in the config file
 2. Build a random application via `neu build` 
 3. Start the application via `dist/xyz/xyz-linux_x64`

Actually I observed the same behavior with `neu run`. I fixed it by setting the window to hidden and show it after initialization. But after building the app, it looks like neutralino opens a default window, loads the config and resource files and then changes all the stuff.
```json
{
  ...
  "modes": {
    "window": {
      "hidden": true,
      ...
    }
  }
}
```

```js
Neutralino.events.on("ready", () => {
    Neutralino.window.show();
});
```
**Specifications**  
* Neutralinojs binaries: v3.0.0
* Neutralinojs client: v2.0.0
* Linux running awesomewm

**Comment by DevEarley** [comment]
I am observing similar issue on Windows 10. I have hidden set to true and I see a window flicker at launch.

 "modes": {
    "window": {
      "hidden": true,
      "title": "My-App",
      "width": 0,
      "height": 0,
      "minWidth": 0,
      "minHeight": 0,
      "fullScreen": false,
      "alwaysOnTop": false,
      "icon": "/resources/icons/appIcon.png",
      "enableInspector": false,
      "borderless": false,
      "maximize": false,
      "resizable": false,
      "exitProcessOnClose": false
    }
    

--- Global ---
neu CLI: v7.1.0

--- Project ---
Neutralinojs binaries: v3.0.0
Neutralinojs client: v2.0.0

**Comment by shalithasuranga** [comment]
Closing this since the issue doesn't exist in newer framework versions on Windows 

Thanks :)
