### ISSUE TITLE
windows 10 server won't start

### ISSUE THREAD

**Issue by mzy2240** [neutralinojs/neutralinojs#713]
**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework] how to check?
* NeutralinoJs CLI version: [neu-cli version] v 7.1.0
* Platform: [Platform specifications]  Windows 10 

After import the neutralino.js and init, when try register the event, the console shows no event property. Then I checked the Neutralino object, there is no event method or property. Then I remove the event relevant code, just call the os.showMessageBox command, and the console tells me the server is offline and need to restart the application. Tried 6.2.2, 7.0.1 and 7.1.0, none of the version could start the server. Already enabled all the server and the nativeapi in the config file.

**Comment by mzy2240** [comment]
Ok the problem is neutralino.js has to be put into the js folder inside the dist folder. It does not work if it is just in the dist folder (same dir with index.html).

**Comment by shalithasuranga** [comment]
Closing this since the issue author answered the same issue :) Thanks :tada:
