### ISSUE TITLE
Is there any way to detect the number of monitor available and the screen resolutions thereof?

### ISSUE THREAD

**Issue by mikeliucc** [neutralinojs/neutralinojs#717]
I would like to create a desktop app that would affix itself to the right side of a monitor (of user's choosing). However I would like the app to take up the entire height of the monitor while maintain a fixed width - sort of like the Windows 10 notification bar.

Is there a way to detect the number of monitors currently available and their resolution?

Thanks!

**Comment by shalithasuranga** [comment]
Hey.. the screen details API is in our roadmap (https://github.com/neutralinojs/roadmap#roadmap-2022). We can probably return monitor details and resolutions with screen details API I think. However, you can get monitor (where app window is rendered) height with `window.screen.availHeight`

**Comment by mikeliucc** [comment]
Thanks for the prompt reply. Looking forward to the Screen API and transparency support soon!

And yes, `window.screen.availHeight` and `window.screen.availWidth` does the trick for now (albeit additional coding required during init. For those that might be looking for similar solution in the future, here's what I ended up doing:
```
Neutralino.events.on("ready", () => {
  let win = Neutralino.window;
  win.setSize({
                width:     300,
                height:    window.screen.availHeight - 35,
              });
  win.move(window.screen.availWidth - 300, 0);
  ...
  ...
});

```

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue. Now we have `Neutralino.computer.getDisplays` function to get details about currently connected displays :tada: We will release this feature with the next release
