### ISSUE TITLE
Media (mp4/wav) playback using HTML tags(video/audio) broken since 3.0.0 for Mac app

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#724]
OS:  MacOS 10.13 High Sierra/ MacOS 10.14 Mojave (currently tested)
NS:  Pre 4.0.0

Sorry - previously reported as 714 but got lost in cleanup I think.

Previously prior to 3.0.0  MP4/MP3/WAV all worked OK (pre WebSocket) - since the updates only MP3 works.

Pre400 -
<img width="1025" alt="mediacompare" src="https://user-images.githubusercontent.com/11089335/145538171-7c5584b1-2ba3-4ca9-9c9a-67d33942fbe3.png">

If other browsers (other than Safari) are used to browse to the main window server port all the formats work OK
eg: Chromium -
<img width="1025" alt="mediacompare2" src="https://user-images.githubusercontent.com/11089335/145538132-08e8b7ad-d390-41d9-9d70-071ffc9fca9a.png">

Using standard HTML code - 
eg:
&lt;video width="320" height="240" controls&gt;
        &lt;source src="test.mp4" type="video/mp4"&gt;
        Your browser does not support the video tag.
    &lt;/video&gt; 

Test sample -
[MediaTest.zip](https://github.com/neutralinojs/neutralinojs/files/7691042/MediaTest.zip)

Cheers.

**Comment by shalithasuranga** [comment]
Hey... sorry if you got confused with the issue cleanup. I moved webview-related issues to https://github.com/neutralinojs/webview/issues
