### ISSUE TITLE
Neutralino.os.execCommand second call bloqued

### ISSUE THREAD

**Issue by florentplomb** [neutralinojs/neutralinojs#728]
**Expected Behavior**  

If I call  `Neutralino.os.execCommand('start cmd.exe', { background: true })`, the cmd console opens,  a few moment later, if  I call again the same command, I would like the second cmd opens and thus have 2 cmd console opened 
  
**Actual Behavior**  
I have to exit the first cmd console before that the second console opens, like a queue

**Steps to Reproduce the Problem**  
 1. Call Neutralino.os.execCommand('start cmd.exe', { background: true }) twice

**Specifications**  
* NeutralinoJs Version: "binaryVersion": "3.0.0", "clientVersion": "2.0.0"
* NeutralinoJs CLI version: v7.1.0
* Platform: Window 10

**Comment by florentplomb** [comment]
This is not a neutralinoJs issue it's my fault , I got some trouble with promise on my code.

**Comment by shalithasuranga** [comment]
Hey.. thanks for checking yeah `background`  (in docs) belong to v4. Right now documentation doesn't keep track of previous versions. Looks like we need to keep history from v4 onward ;)
