### ISSUE TITLE
ERROR: Unsupported platform or CPU architecture: win32_ia32

### ISSUE THREAD

**Issue by vicnz** [neutralinojs/neutralinojs#731]
**Expected Behavior**  
Show Error on `neu run` showing error
```bash
ERROR: Unsupported platform or CPU architecture: win32_ia32
```
  
**Actual Behavior**  
start and run binaries

**Steps to Reproduce the Problem**  
 1. `neu run`

**Specifications**  
* NeutralinoJs Version: 4.0.0
* NeutralinoJs CLI version: 8.0.0
* Platform: Windows 10 21H2 x64

**Comment by shalithasuranga** [comment]
Hey.. looks like you are running a 32bit version of Node js on a 64bit computer. There are two ways to solve this 
1. Run the app with `neu run --arch=x64`
2. Install Nodejs 64bit
