### ISSUE TITLE
Issue using "await" keyword

### ISSUE THREAD

**Issue by sreepathy** [neutralinojs/neutralinojs#739]
**Expected Behavior**  
using `await` on a promise should make the statement execution serial.
Expected output:
```
[Log] Object (main.js, line 11)
exitCode: 0
pid: 31116
stdErr: "Python 2.7.18↵"
stdOut: ""
Object Prototype
```  

**Actual Behavior**  
`await` is resulting in syntax error
```
[Error] SyntaxError: Unexpected identifier 'Neutralino'. Expected ';' after variable declaration.
	(anonymous function) (main.js:6)
```

**Steps to Reproduce the Problem**  
 1. create new app with neu (as documented in https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app)
 2. Add the following code to main.js
```
Neutralino.init();
Neutralino.events.on("windowClose", () => {
    Neutralino.app.exit();
});

var info = await Neutralino.os.execCommand('python --version');
console.log(`Your Python version: ${info.stdOut}`);
```
 3. run the app using `neu run`
 4. app will not work as expected
 5. check browser console for the above error

**Notes**
Changing the promise code as below gives the expected output:
```
Neutralino.os.execCommand('python --version').then(function(info) {
    console.log(info);
});
```
Or even this works
```
Neutralino.os.execCommand('python --version').then((info) => console.log(info));
```
So it is an issue due to using of `await` keyword. Wherever await is used similar behaviour is observed.

**Specifications**  
--- Global ---
neu CLI: v8.0.0
Neutralinojs binaries: v4.0.0
Neutralinojs client: v3.0.0
Platform:
```
DISTRIB_ID=neon
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="KDE neon User - Plasma 25th Anniversary Edition"
NAME="KDE neon"
VERSION="5.23"
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - Plasma 25th Anniversary Edition"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
```

**Comment by Blatman** [comment]
FWIW - I get similar errors but usually because I have forgotten to use an async function - await only works within an async function. Also interesting to note that Python version return is stdErr, I haven't managed to figure out why this is so.

**Comment by sreepathy** [comment]
Yes. This code works:
```
Neutralino.init();
Neutralino.events.on("windowClose", () => {
    Neutralino.app.exit();
});
getPyVersion();

async function getPyVersion (){
    var info = await Neutralino.os.execCommand('python --version');
    console.log(`Your Python version: ${info.stdErr}`); 
}
```
Thanks @Blatman  
![image](https://user-images.githubusercontent.com/6497933/146632885-353eee21-1e37-4db9-bfc1-04d098df12f1.png)
