### ISSUE TITLE
Opening folder with showOpenDialog

### ISSUE THREAD

**Issue by lem6ns** [neutralinojs/neutralinojs#753]
I'm prompting a user to choose a folder, but os.showOpenDialog only has support to choose a file.
My idea is this:
```js
let folder = await Neutralino.os.showOpenDialog("Pick a folder.", {
    folder: true
})
```

and the response would be 
```js
console.log(folder) // ["C:\Users\user\Downloads\"] (if they picked Downloads)
```

**Comment by shalithasuranga** [comment]
Hey.. there is a function for that. Could you please use https://github.com/neutralinojs/neutralino.js/blob/2d7e54656f06c479fa782fef16aa5bd12b30795a/src/api/os.ts#L63
(`os.showFolderDialog`) . Looks like it's not listed in docs - We'll add it soon. Thanks for reporting this issue
