### ISSUE TITLE
os.setTray on windows does not support failure

### ISSUE THREAD

**Issue by mcx1230** [neutralinojs/neutralinojs#762]
_   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
neu CLI: v8.1.0

--- Project: neu-app (js.neutralino.sample) ---
Neutralinojs binaries: v4.0.0
Neutralinojs client: v3.0.0

**icon remove**
os.setTray on windows does not support remove icon

**non-ASCII**
os.setTray on windows does not support non-ASCII character

**Comment by shalithasuranga** [comment]
Hey.. I am closing this issue since the icon disappearing issue was fixed with #700. And the Unicode support needs to be added to multiple places - we will apply a fix for it via another issue. Thanks for reporting
