### ISSUE TITLE
window.maximize() hides the taskbar

### ISSUE THREAD

**Issue by KennyMusterer** [neutralinojs/neutralinojs#765]
**Expected Behavior**  
The window is not in front of the taskbar when maximized
  
**Actual Behavior**  
When maximizing the window is extends all the way to the bottom, hiding the taskbar

**Steps to Reproduce the Problem**  
 1. Start application
 2. Maximize the window with the Native API call (Neutralino.window.maximize())

**Specifications**  
* NeutralinoJs Version: v4.0.0
* NeutralinoJs CLI version: v8.1.0
* Platform: Windows 10 Pro

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this issue @KennyMusterer I just tested this on Windows - it didn't hide the taskbar. Not sure whether you have some auto-hide option or some customization/tweak added to the taskbar?

**Comment by thehuckledev** [comment]
> I am closing the issue since it worked as expected with several tests. Please test with the latest version and let us know if the issue still exists :) Thanks

Hi, im still experiencing this issue
