### ISSUE TITLE
Why read all file to string without end of lines (txt)

### ISSUE THREAD

**Issue by Coimbras** [neutralinojs/neutralinojs#769]
**Should be possible read file line by line.**  
When running my function all the contents of file (simple text) goes into a string, not respecting end of files.
conteudo_edm was previous iniciated as array:
conteudo_edm =[]
  
Any idea?

```
async function lerN() {
let entries = await Neutralino.os.showOpenDialog('Abrir um ficheiro', {
    filters: [
        { name: 'ISPOL', extensions: ['edm', 'EDM'] },
        { name: 'All files', extensions: ['*'] }
    ]
});

ficheiro = entries + ''
ficheiro = ficheiro.replace(/\\/g, "/")
conteudo_edm = await Neutralino.filesystem.readFile(entries[0]); //Aqui está a juntar tudo numa string!!!
console.log(conteudo_edm)

```

**Specifications**  
* Platform: Win10

**Comment by KennyMusterer** [comment]
I replicated your code on Windows 10 it runs just fine. Make sure that the file you are reading has line breaks. 

You should be able to read the single lines like that:

   ```
 let entries = await Neutralino.os.showOpenDialog('Select the files', {
      filters: [
        { name: 'All files', extensions: ['*'] }
      ],
      multiSelections: true
});

let content= await Neutralino.filesystem.readFile(entries[0]);
let lines = content.split("\n"));

lines.foreach(line=>{
     //do something with your line
});
```

**Comment by Coimbras** [comment]
I, thanks for reply...
I copy and rearranje your code and now works.
Maybe before some mismatch...i don know. Same text file now works fine.

Thanks for help, iḿ now ready to go on.
