### ISSUE TITLE
Using Neutralino without config window

### ISSUE THREAD

**Issue by HeroinGyrl** [neutralinojs/neutralinojs#771]
Is it possible to create a neutralino window without the default config file by only using javascript?

```js
  const window = Neutralino.Init(..options);
  window.loadUrl('index.html');
```

using the init command to create the websocket connection and the window.
this concept would be good for not using config.json to create the window.

**Comment by shalithasuranga** [comment]
Hey.. thanks for the idea. Neutralino app usually works totally on the renderer side compared to Electron. Also, Neutralino's main process responds to the renderer's requests. So we can't directly run JavaScript without loading a JavaScript file to Neutralino. What you've mentioned is more like Electron's approach, launching the app from the main process. I think your idea is possible if someone made something like node-neutralino which simply uses extensions API to launch and connect with the Neutralino process as neu CLI does.

This idea is already in https://neutralino.js.org/docs/how-to/extensions-overview#using-neutralinojs-from-your-source-files - but we will add more details about the possibility of creating bindings into docs. 

Thanks

**Comment by HeroinGyrl** [comment]
hey, as alternative I found a solution by making the main window hidden and not usable but instead creating a new window from ready event

```js
Neutralino.init();

Neutralino.events.on('ready', () => {
    Neutralino.window.create('https://localhost:7167/', {
        enableInspector: false,
        width: 500,
        height: 300,
        maximizable: false,
        hidden: false,
        exitProcessOnClose: true
    });  
});
```
the problem on doing this is that `exitProcessOnClose` will actually not close the main window.
regarding.

so something like this would fix that.
```js
Neutralino.windows[0].Close(); // close the main window which causes to close the whole application.
```

**Comment by shalithasuranga** [comment]
Hey.. `window.create` returns `pid` of the process, so you can terminate the process chain (window process and the initiator process (Shell) ) in a cross-platform way using `os.exeCommand` and `NL_OS`. Need to think about whether we need to add a window management feature to the library :)

**Comment by HeroinGyrl** [comment]
related to my #448 .net 6 support I managed to create a first test of how to support a blazor application in neutralino.

by using the solution above I configured everything in the ready event and used the native api `Neutralino.os.execCommand` to start the binary file (blazor).

the exec command blocks the thread but never returns since the blazor applications runs until the process is been terminated. so I used `setTimeout`  and wait 1 second to starts the blazor app.

```js
let NEUTRA_PORT = NL_PORT
let NEUTRA_WINDOW = {}
let NEUTRA_ROOT = ""
let NEUTRA_BLAZOR_BINARY = ""
let NEUTRA_BLAZOR_ROOT = ""
let NEUTRA_BLAZOR_FILE = ""

Neutralino.init();

Neutralino.events.on('ready', async event => {
    console.log("starting blazor application ..");

    await SetConfigurationAsync();
    
    setTimeout(() => {
        Neutralino.os.execCommand(NEUTRA_BLAZOR_FILE);        
    }, 1000);

    await Neutralino.window.create('https://localhost:5001', {
        enableInspector: true,
        width: 500,
        height: 550,
        maximizable: false,
        reziesable: true,
        hidden: false,
        exitProcessOnClose: false
    });
});

async function SetConfigurationAsync()
{
    var config = await Neutralino.app.getConfig();

    NEUTRA_WINDOW = config.modes.window;
    NEUTRA_ROOT = `${NL_CWD}${config.documentRoot}`;
    NEUTRA_BLAZOR_BINARY = `${config.cli.binaryName}`;
    NEUTRA_BLAZOR_ROOT = `${NEUTRA_ROOT}blazor/`;
    NEUTRA_BLAZOR_FILE = `${NEUTRA_BLAZOR_ROOT}${NEUTRA_BLAZOR_BINARY}.exe`;
}
```

this is currently all manually made (config, folders, etc) to test the support for .net/blazor
it actually works whenever I start the blazor app manually and then run neutralino everything works fine

![Screenshot 2022-01-15 074326](https://user-images.githubusercontent.com/33988671/149612218-df656638-d376-48cf-ac36-10926ec34a51.png)


but somehow when I let neutralino start the blazor app it cant load some asset files

![Screenshot 2022-01-15 073521](https://user-images.githubusercontent.com/33988671/149612244-d3284e4d-8cb1-4b92-8fb6-79da5cb26e2c.png)

is using `Neutralino.os.execCommand(NEUTRA_BLAZOR_FILE)` not a good way to open a binary file with neutralino?
or is the problem from somewhere else?
regarding

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting this issue and discussing it further. The community is working with the idea mentioned here in this repo: https://github.com/neutralinojs-community/node-neutralino

Let's hope there will be a working Node Neutralino version soon!

Thanks :tada:
