### ISSUE TITLE
macOS Monterey issue

### ISSUE THREAD

**Issue by lexesv** [neutralinojs/neutralinojs#772]
**Actual Behavior**  
Doesn't run on macOS Monterey

**Steps to Reproduce the Problem**  
```
./neutralino-linux_x64    
zsh: exec format error: ./neutralino-linux_x64
```

**Specifications**  
* NeutralinoJs Version: 4.1.0
* NeutralinoJs CLI version: -
* Platform: macOS Monterey, CPU Apple M1

**Comment by shalithasuranga** [comment]
Hey seems like you are trying to execute Linux binary on macOs. Please use macOs binary or use neu CLI to automatically run the correct binary for development.
