### ISSUE TITLE
filesystem文件系统，无法实现文件末尾追加写入

### ISSUE THREAD

**Issue by qilecms** [neutralinojs/neutralinojs#773]
### filesystem file system, how to implement appending data at the end of the file

neu CLI: v9.1.0

--- Project: hello-world (js.neutralino.sample) ---
Neutralinojs binaries: v4.0.0
Neutralinojs client: v3.0.0

`   Neutralino.filesystem.writeFile(NL_CWD+'/web/webdata2.txt', sitename);`

**Comment by shalithasuranga** [comment]
Please check [`filesystem.appendFile`](https://neutralino.js.org/docs/api/filesystem#filesystemappendfilefilename-data) documentation.

Thanks :)
