### ISSUE TITLE
windows11 menu not showing

### ISSUE THREAD

**Issue by qilecms** [neutralinojs/neutralinojs#774]
--- Global ---
neu CLI: v9.1.0

--- Project: hello-world (js.neutralino.sample) ---
Neutralinojs binaries: v4.1.0
Neutralinojs client: v3.0.0

**windows11 64 bit the following code is invalid**

`let tray = {
  icon: '/resources/icons/trayIcon.png',
  menuItems: [
    {id: "about", text: "About"},
    {text: "-"},
    {id: "quit", text: "Quit"}
  ]
};

Neutralino.os.setTray(tray);`

**Comment by shalithasuranga** [comment]
Hi.. @qilecms, thanks for reporting this issue. Could you please provide the behavior or error message of this code snippet? Then, we can check why it's not working. The tray menu typically works fine on Windows. We can re-open this issue when you provide more information :)

Thanks :tada:
