### ISSUE TITLE
macOS builded application, fails to load random resources

### ISSUE THREAD

**Issue by chiptoe** [neutralinojs/neutralinojs#779]
**Expected Behavior**  
Resources like .css, .js, should load successfully at application start.
  
**Actual Behavior**  
When I kill / start mac application multiple times using `neu run`, resources loads always successfully.
When I kill / start mac application multiple times using builded executable file, random resources are not loaded. At 1. start resources A,B,C does not load, at 2. start resources C,G does not load, etc...

![image](https://user-images.githubusercontent.com/13163919/151443063-33d4b3d0-e650-407f-a552-24fac0eb95c2.png)
![image](https://user-images.githubusercontent.com/13163919/151443190-774355ec-9bf7-4c74-8ebb-5e787642d1d2.png)

**Steps to Reproduce the Problem**  
 1. Build mac application
 2. Run executable file
 3. Inspect errors in console
![image](https://user-images.githubusercontent.com/13163919/151443456-6ff8d916-bb25-45e6-bce8-abb6bcdc1cd9.png)

**Specifications**  
* NeutralinoJs Version: v3.1.0
* NeutralinoJs CLI version: v9.1.1
* Neutralinojs binaries: v4.2.0
* Platform: macOS Big Sur
* borwser userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"

**Comment by chiptoe** [comment]
Bundling all scripts and css solved my problem.

**Comment by DEVLOPRR** [comment]
> Bundling all scripts and css solved my problem.

Kindly then close this issue

**Comment by harshithgupta28** [comment]
yeah sure! thank you

**Comment by shalithasuranga** [comment]
Closing this since the latest Neutralinojs static server has no issues. Thanks so much for reporting this issue and discussing about the specific problem :tada:
