### ISSUE TITLE
Missing permission to execute the native method

### ISSUE THREAD

**Issue by jonasmoeller** [neutralinojs/neutralinojs#781]
**Expected Behavior**  
Should throw no error at all-
  
**Actual Behavior**  
Throws error saying:
`Uncaught (in promise) {"code":"NE_RT_NATPRME","message":"Missing permission to execute the native method"}`

**Steps to Reproduce the Problem**  
No real reproducing step. This happened after a fresh install.

**Specifications**  
* NeutralinoJs Version: v3.1.0
* NeutralinoJs CLI version: v4.2.0
* Platform: Windows 64bit

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this. some configuration issue was there in the default template - now it's fixed :)

**Comment by crazy4groovy** [comment]
Same issue for me:

`{"code":"NE_RT_NATPRME","message":"Missing permission to execute the native method"}`

What is the fix, so I can implement locally? Thanks

**Comment by crazy4groovy** [comment]
I'm guessing it's this in `neutralino.config.json`:

```
"nativeAllowList": [
    "app.*",
    "os.*",
    "filesystem.*",            // <<<<added
    "extensions.*"
  ],
```

**Comment by shalithasuranga** [comment]
Hey.. Earlier, in the default template, any API request was allowed - so I updated it by adding the APIs used in the sample app. Therefore, if you need to use another API, you need to add it into the `nativeAllowList`. Also, if you use many APIs, you can block stuff you don't use via `nativeBlockList`. We will highlight these things in the documentation soon. Please check more info: https://neutralino.js.org/docs/configuration/neutralino.config.json#nativeblocklist-string

**Comment by ofceab** [comment]
Hey, I'm trying to run a command by using **Neutralino.os.runCommand** and I also add this permission **"os.execCommand"** but I still get the same error : 

Uncaught (in promise) {"code":"NE_RT_NATPRME","message":"Missing permission to execute the native method"}

**Comment by shalithasuranga** [comment]
Ah okay.. Thanks for checking. `"nativeAllowList": ["os.execCommand"],` like setup will work

**Comment by jonasmoeller** [comment]
Hey, I still got the error.
I added this:
`"nativeAllowList": [
        "app.*",
        "os.*",
        "filesystem.*",
        "extensions.*"
      ]`

**Comment by ofceab** [comment]
Hey, Can you provide the code which is request that permission ?

**Comment by jonasmoeller** [comment]
`Uncaught (in promise) {"code":"NE_RT_NATPRME","message":"Missing permission to execute the native method"}`

**Comment by ofceab** [comment]
but what is the native permission you're looking for ?

**Comment by jonasmoeller** [comment]
It happens on refresh I have no clue which native permission this is I never used Neutralino before and tbh I don't know why the Node Package you can download has bugs in it.

**Comment by armandsalle** [comment]
Same bug here on my M1 MacbookAir with the clipboard API

**Comment by m6tm** [comment]
If you want to use "window" namespace or "os", ... you must add it in **neutralino.config.json** on "nativeAllowList"

**Comment by jonasmoeller** [comment]
Still no answer to my question, I get an Error with no info of what is being blocked.
`{code: 'NE_RT_NATPRME', message: 'Missing permission to execute the native method'}`
This happens on a refresh in Code where it should refresh the window right?

**Comment by m6tm** [comment]
That means you have to uninstall everything and then install again. I advise you not to use **npm** but rather **yarn** to install the **neu CLI**.

**Comment by shalithasuranga** [comment]
Hey.. all Now we can see the native method name with the error message (fixed via https://github.com/neutralinojs/neutralinojs/issues/821). It will be released with the next version. As a workaround, for now, we can indeed check the WebSocket connection from DevTools and find which native method is failing (Find the sent message that contains the id of the errored response message).
