### ISSUE TITLE
Toggle alwaysOnTop for window mode

### ISSUE THREAD

**Issue by i1Fury** [neutralinojs/neutralinojs#785]
There is an option in the config for the window mode that makes the window always on top:
![image](https://user-images.githubusercontent.com/30241586/151925488-a446eb14-ab0f-40b4-97c5-90f1f4f5ee53.png)
I would like a button in my app to toggle this on/off, but there is no native API method for this. There is, however, methods to resize the window, show it, and hide it...

**Comment by i1Fury** [comment]
We already have a [setAlwaysOnTop](https://github.com/neutralinojs/neutralinojs/blob/main/api/window/window.cpp#L268) cpp function defined in the window api. It just has to be modified to take a boolean, have the ability to disable it, and has to be hooked to the js api. @shalithasuranga

**Comment by shalithasuranga** [comment]
This is added and will be released with the next version - thanks for suggesting this. Please note that we need to add `window.isAlwaysOnTop` too later. Needs a workaround for https://gitlab.gnome.org/GNOME/gtk/-/issues/682 so cannot be added with this issue :)
