### ISSUE TITLE
Expose all file paths with "/" on Windows

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#787]
On Windows, "/" works okay.. Implement this change after verifying with older Windows versions

**Comment by orent** [comment]
At the API level, Windows and even DOS has always supported forward slash as a path separator. It is only in the command line that it isn’t always supported because forward slash is used for the option character.

**Comment by soshimee** [comment]
For me, both cmd and powershell seem to support slash as path separator?

**Comment by orent** [comment]
cmd builtins and standard tools report "Invalid switch"
