### ISSUE TITLE
Extensions are broken or the docs are incomplete

### ISSUE THREAD

**Issue by themer-works** [neutralinojs/neutralinojs#790]
Hi there, thanks for this excellent project!

I've followed the docs on using extensions 100% but they don't seem to work no matter what I try.

**Expected Behavior**  
Extensions work.
  
**Actual Behavior**  
No idea what I'm doing wrong or how to make extensions work. I try to echo from a command but it does nothing.

**Steps to Reproduce the Problem**  
Clone this repo and run `neu run` and observe that nothing is logged to the terminal.

https://github.com/themer-works/neu-extensions-reproduction

**Specifications**  
* NeutralinoJs Version: v4.2.0
* NeutralinoJs CLI version: v3.1.0
* Platform: MacOS 12.1 M1

**Comment by serg06** [comment]
I'm on Windows, but my extensions don't work with `neu run` either. They only work `neu build` + manually running `dist/hello-world/hello-world-win_x64.exe`.

Notes on getting it working:
- make sure you kill all processes (from neu run, neu build, and your extension) in between attempts
- stdout/stderr from the extension doesn't seem to get printed anywhere, so if you want to print debugging messages, you can do something like writing them to a file on your machine
- it's non-obvious how to reply to the websocket message; [here's an exampe](https://github.com/neutralinojs/neutralinojs/blob/main/bin/extensions/sampleextension/main.js). Notice the `data` it sends: an `event` corresponding to the one you listen to with `Neutralino.events.on`, and a `data` that gets passed to your event handler.

**Comment by themer-works** [comment]
Aha! Thank you @serg06 , I finally got it working after realizing it will print the stderr/stdout if you run `neu run --verbose` and then quit the dev app - when it quits it will print any stdout from the extension that was output while it was running 🤔 the DX here isn't great. Turns out I had a typo in the path to my extension binary but since the stderr is discarded and not added to the neu log I couldn't figure out what was going on.

**Comment by themer-works** [comment]
Huh, turns out I can get it to work for `neu run` but not `neu build` 🙈 I guess the path is wrong there too but it's super hard to figure out what to change with the way it is. Since there's no `--verbose` for running the final app and extension errors aren't included in the neu log I'm shooting in the dark 🤔 I guess I'll keep messing around

**Comment by themer-works** [comment]
@serg06 I opened a PR which streams the stdout of extensions to the main process. Looks nice 😄
<img width="511" alt="Screen Shot 2022-02-08 at 7 19 33 PM" src="https://user-images.githubusercontent.com/99006348/153115529-ac11081d-7411-4445-8df1-f8979a6ccddb.png">
