### ISSUE TITLE
Polyfilling path and fs node packages?

### ISSUE THREAD

**Issue by ruifortes** [neutralinojs/neutralinojs#792]
Hi. Sorry if this is a stupid question but...
I want to use a glob library (fast-glob in this case) but it needs access to node's path and I guess fs internal packages.
How should I go about using this in neutralino?
Thanks

**Comment by DEVLOPRR** [comment]
Does this [Question](https://stackoverflow.com/q/24558442/14516016) Help?

**Comment by shalithasuranga** [comment]
Closing this since it's already answered. Also, there are some browser friendly `path` implementations like https://github.com/browserify/path-browserify. Another possibilities are to polyfill `path` with Neutralinojs APIs and using `path` in a Node.js-based extension :tada:
