### ISSUE TITLE
MacOS - extensions command path in config doesn't work

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#795]
NS 430
NC 320
MacOS 10.13 Intel/MacOS 12.1 M1

Just can not get extensions working using the sample code - I have attached a sample app package built for 10.13 and will run on 12.1 M1 also.

getStats shows the extensions as loaded but not connected.

To kick off the extension in the sample the main.js in the sampleextension folder needs to run as specified in the config file for the command key. The main.js is not run so the extension will never connect.
The main.js contains the WS setup code -

const NL_PORT = argv['nl-port'];
const NL_TOKEN = argv['nl-token'];
const NL_EXTID = argv['nl-extension-id'];

let client = new WS(`ws://localhost:${NL_PORT}?extensionId=${NL_EXTID}`);

Have tried command paths (as per docs) - 

   "command": "node ${NL_PATH}/extensions/sampleextension/main.js"  (needs node to use main.js?)
   "command": "${NL_PATH}/extensions/sampleextension/main.js" (not a command just a path)
   "commandDarwin": "node ${NL_PATH}/extensions/sampleextension/main.js" (needs node to use main.js?)
   "commandDarwin": "${NL_PATH}/extensions/sampleextension/main.js" (not a command just a path)

What I am not sure about is if node is required as a command how is it supported with the app package - I thought the extension was to be used to allow node working with Neutralino - do the extensions only work in the Neu-CLI environment which uses node modules?

[NeuExtnSample.zip](https://github.com/neutralinojs/neutralinojs/files/8007946/NeuExtnSample.zip)

**Comment by themer-works** [comment]
Sounds like we're running into similar problems. https://github.com/neutralinojs/neutralinojs/issues/790

**Comment by Blatman** [comment]
@themer-works  - yeah I think there may be 2 issues here because you are getting the ws transaction at least starting whereas I can't get the js file (as per config path) containing the code to run.

I will have to try the CLI again to see if I can get as far as you but I find the CLI useless since I don't use a resources.neu package and the folder structure isn't aligned to normal mac app packaging.

**Comment by Blatman** [comment]
@shalithasuranga - tried the latest CLI (using neu run) and the extension works because the CLI is using the node that is globally installed on the machine. Once the app is packaged as a mac app node is no longer available so extension won't work.

CLI test - NL_PATH is .
Full command is  ./extensions/sampleextension/main.js

Mac App sample - NL_PATH is /Users/USER/Desktop/NeuExtnSample.app/Contents/Resources
Full command is  /Users/USER/Desktop/NeuExtnSample.app/Contents/Resources/extensions/sampleextension/main.js

Seems to me that extensions will only ever work in apps if node is somehow bundled - would this be right?

**Comment by Blatman** [comment]
@shalithasuranga - OK that was a fun game - I have managed to get the extension working in the mac app by packaging the sampleextension folder with node using caxa.

https://github.com/leafac/caxa     (easy to use)

The config command altered to -

"command": "${NL_PATH}/extensions/sampleextension"

The package (sampleextension) replaces the folder of the same name.
The packaged sampleextension runs the packaged node (I used v14.9.0) and allows the main.js to use require so the bundled websocket module works OK.

So now it connects I just need to see if this is going to be feasible to run node modules with my apps.
The sampleextension package weighed in at c. 30M

**Comment by shalithasuranga** [comment]
Hey.. @Blatman  Thanks for checking further and finding and posting the solution. Yeah, we can bundle source and node to a portable binary too. But, please note that, like you already noticed the extensions can become larger than Neutralinojs if we pick Node.js (then it's like Electron). The sample extension is just an example to show how to connect with the extension system.  We've added `commandLinux`, `commandWindows` etc for this reason. So we can write very lightweight extensions in C++ and Rust, etc . Perhaps, in the future, someone can build C++-based SQLite connectors, etc with the extension system :)

**Comment by Blatman** [comment]
Yeah the size issue is not too bad if only a few node modules are required and the overall app size is still less a lot less than NWjs/Electron since the later version browsers are getting bigger by the minute and large numbers of node modules add to that.
