### ISSUE TITLE
Can't find app path

### ISSUE THREAD

**Issue by cataghg** [neutralinojs/neutralinojs#796]
In my neutralino.config.json file I wanna open the index.html located in the app folder, but I can't find a way to find it using 
`"url": "./index.html"`

Is there another way to do it? Or is it impossible?

**Comment by shalithasuranga** [comment]
Hey.. In the Neutralinojs environment, the framework handle resources relative to the app directory with a URL-like format. So, "/index.html" will work. However, it's great to put resources into a separate directory :)

**Comment by cataghg** [comment]
`/index.html` didn't work, it throws a screen at me with "The URL can’t be shown". 
Here my config file `{
"applicationId":"kewllab.game",
"url":"/index.html",
"defaultMode":"window"


}
`

**Comment by shalithasuranga** [comment]
ah seems like you creating a configuration from scratch. Please make sure to set `enableServer` to true for enabling resources server. If you plan to use native API, you need to set `enableNativeAPI` to true too.

**Comment by cataghg** [comment]
I made it work... kinda. I am trying to use this for a game but now everything besides the gui renders only once than stops...very odd...
