### ISSUE TITLE
Check the possibility of using libayatana-appindicator instead of libappindicator

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#799]
Reason: https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages

**Comment by williamrijksen** [comment]
https://github.com/neutralinojs/neutralinojs/pull/800/files @shalithasuranga checked it on my raspberry pi, fixed the issue.

**Comment by shalithasuranga** [comment]
Thanks @williamrijksen Now the pull request was merged :) :rocket:
