### ISSUE TITLE
Extension websocket server closes on MacOS in sample extension

### ISSUE THREAD

**Issue by themer-works** [neutralinojs/neutralinojs#801]
**Expected Behavior**  
The sample extension should communicate with the neu window via the extension websocket

https://github.com/neutralinojs/neutralinojs/blob/main/bin/extensions/sampleextension/main.js
  
**Actual Behavior**  
The neu window doesn't connect and instead logs "Extension isn't loaded!" to the terminal.

**Steps to Reproduce the Problem**  
1. Run the neu app in the `bin` dir of this repo. Run the app and look at the terminal to see it wont connect.
2. Use a websocket client and attempt to connect using the correct url. When adding an extension id the connection will close. If you leave out the extension id it will connect but it wont work because there's no extension id.

**Specifications**  
* NeutralinoJs Version: v4.2.0
* NeutralinoJs CLI version: v3.1.0
* Platform: MacOS 12.1 M1

**Comment by themer-works** [comment]
You can see here that it connects when you leave out the extension id, but closes when it's included
<img width="1108" alt="Screen Shot 2022-02-07 at 8 38 52 PM" src="https://user-images.githubusercontent.com/99006348/152919254-b29fb789-d97c-402c-a97e-daafc6d02bc3.png">

**Comment by Blatman** [comment]
@themer-works  - Hey that weasel is pretty nifty - tried it out with my sample app and it works as long as the extn id is entered in lowercase - uppercase will fail (the console logging is always uppercase however). 

https://mhgolkar.github.io/Weasel/

**Comment by Blatman** [comment]
Trying further with Weasel (using FF) I find that it connects but messaging does not work - if I send a message I get -

ERROR 2022-02-08 16:44:20,805 Unable to parse native call payload: std::exception api/debug/debug.cpp:16 user@unknown-host

This error I think comes from L180 in neuserver.cpp in the handleMessage function.

**Comment by themer-works** [comment]
I was using weasel to try to debug the problem but it also doesn't connect from the sample app for me from the nodejs sample extension without weasel. What platform are you on?

**Comment by themer-works** [comment]
This is what I get when running the sample app for the sample extension
<img width="810" alt="neu" src="https://user-images.githubusercontent.com/99006348/153095771-cbf7a07f-a2cc-46ef-bf46-693ae75e60cb.png">

The websocket isn't connecting so it logs from this line https://github.com/neutralinojs/neutralinojs/blob/main/bin/resources/js/main.js#L22

**Comment by themer-works** [comment]
It looks like the extensions e2e tests are potentially producing false positives too. I can run the tests with no errors but if I run the code from the extensions test in the sample app it errors:
<img width="802" alt="Screen Shot 2022-02-08 at 4 39 19 PM" src="https://user-images.githubusercontent.com/99006348/153099973-391110c3-0e9f-46a1-921c-0e976c591520.png">

**Comment by themer-works** [comment]
<img width="897" alt="Screen Shot 2022-02-08 at 4 43 19 PM" src="https://user-images.githubusercontent.com/99006348/153100211-40a2cc4b-d9a3-4e76-879b-fbbba3252942.png">

**Comment by themer-works** [comment]
Wow, it's because you can't have a dash in your extension name... `foo-bar` bad `foobar` good 🤦 

I'll PR that to the docs! Because holy crap that was hard to figure out

**Comment by Blatman** [comment]
Looks like a good bug found there - I found sample extension to work within the CLI (uses global node install) but it fails in a normal mac app bundle (#795).
 I thought that extensions may provide a way of bringing node into apps but the way I see it the extensions need node to start and therefore fail to connect.

I didn't get quite the same issue as the extension name didn't have a '-' in it. BTW: I test on 10.13/10.14 Intel and 12.2 M1.

Cheers

**Comment by fix** [comment]
Guys for people hitting the issue again (ie the extension id is legit, but bumping to error connecting to the websocket server), It seems that somehow the loopback localhost is not allowed for some reason.

Connecting to ws://127.0.0.1:port?extensionId=...  works for me
