### ISSUE TITLE
starter template crashes on windows 10 - error code 3221225477

### ISSUE THREAD

**Issue by gui3** [neutralinojs/neutralinojs#808]
**Expected Behavior**  
I tried running the starter template following the instructions on [this link](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app) on my work machine.
- neu is istalled globally.
- **I tried running the `CheckNetIsolation.exe` command before -> no changes**
- **i tried installing WebView2 runtime -> no changes**
  
**Actual Behavior**  
the application crashes instantly after `neu run`, 
the app window is blank and this dialog appears :

![erreur_neutralino_2](https://user-images.githubusercontent.com/45894433/155148744-4186e690-8c26-4ce9-9138-4916023aadb4.jpg)

the french message says "Microsoft Edge cannot read nor write in his data directory : "

The console shows the following : 
```
$ neu run
neu: INFO Starting process: neutralino-win_x64.exe  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
INFO 2022-02-22 13:57:16,871 Auth info was exported to ./.tmp/auth_info.json api/debug/debug.cpp:14 <my-user-name>@AIB-A0064-P
neu: INFO neu CLI connected with the application.
neu: WARNING neutralino-win_x64.exe was stopped with error code 3221225477
```

Since it's a work machine, I have **no control over Windows updates** and my version (windows 10 version 21H1 build 19043.1083) dates back to may 2021. This could be a source of the problem ?

**Steps to Reproduce the Problem**  
 1. get a similar windows build?
 2. `npm install -g @neutralinojs/neu`
 3. `neu create <project name>` project name was 'test' in my case
 4. `cd <project name>`
 5. `neu run`

**Specifications**  
* NeutralinoJs Version: binaries 4.3.0 - client 3.2.0
* NeutralinoJs CLI version: 9.2.0
* Platform: windows 10 version 21H1 build 19043.1083

**Comment by tukusejssirs** [comment]
It crashes on Arch Linux, too.

```bash
--- Global ---
neu CLI: v9.3.1

--- Project: ---
Neutralinojs binaries: v4.6.0
Neutralinojs client: v3.5.0
```

**Comment by pathange-s** [comment]
@gui3 Please check if this issue is because of the reasons mentioned in [here](https://github.com/neutralinojs/neutralinojs/issues/613). If yes, there's a temporary fix that can help you out. We are working on bringing support for Unicode, and hope it will be out soon.

**Comment by shalithasuranga** [comment]
Closing this since the Windows Unicode support was added via #1102. If a specific feature doesn't support Unicode still, I think we can create a separate issue. 

Thanks :tada:
