### ISSUE TITLE
Is there any way to download files manually?

### ISSUE THREAD

**Issue by zheung** [neutralinojs/neutralinojs#809]
Connecting to Github is very difficult in my region. It's very easy to cause network timeout or reset.
The cli always redownloads the file after a failure. I can't even create the initial `hello-world`

Is there any way to download files manually?
Or is it possible to download files through proxy settings?

![screenshot1](https://user-images.githubusercontent.com/894004/155253897-2645f24c-d4a0-44c6-bfad-abc970579a61.png)
![screenshot2](https://user-images.githubusercontent.com/894004/155253928-3b3966ce-584a-4e10-84dc-601a0302325d.png)

**Comment by DEVLOPRR** [comment]
1. Download the latest Neutralino Binaries Either from this Neutralino's github [release page](https://github.com/neutralinojs/neutralinojs/releases) Or From Neutralino's [Source Forge Page](https://sourceforge.net/projects/neutralinojs/files/)

2. Make a New Folder For your project if not already created one.
3. Inside your project folder make 2 new folders `bin` and `www`.
4. Extract All The Binaries from the .zip file you downloaded in the 1st step and put them inside the `bin` folder
5. also download the `neutralino.js` client file from the [GitHub Releases](https://github.com/neutralinojs/neutralino.js/releases) and put the `neutralino.js` file somewhere inside your project folder.
6. inside the `www` folder put all of your html, css and js stuff
7. in your project folder make a new file `neutralino.config.json` and copy paste everything below inside your config file.

```json
{
  "applicationId": "js.neutralino.sample",
  "version": "1.0.0",
  "defaultMode": "window",
  "documentRoot": "/www/",
  "url": "/",
  "enableServer": true,
  "enableNativeAPI": true,
  "nativeAllowList": [
    "app.*"
  ],
  "modes": {
    "window": {
      "title": "myApp",
      "width": 800,
      "height": 500,
      "minWidth": 400,
      "minHeight": 200,
      "icon": "/www/icon.png"
    }
  },
  "cli": {
    "binaryName": "myApp",
    "resourcesPath": "/www/",
    "extensionsPath": "/extensions/",
    "clientLibrary": "/www/neutralino.js",
    "binaryVersion": "4.3.0",
    "clientVersion": "3.1.0"
  }
}
```

8. Replace the `binaryVersion` and `clientVersion` inside the `cli` property with the binary version and the `neutralino.js` client file you downloaded (example the binary version for `neutralinojs-v4.3.0.zip`)

9. Replace the path to `clientLibrary` in `cli` property in the config json file with the path of the `neutralino.js` file you downloaded and placed somewhere inside your project folder.
10. Finally Run `pnpx neu run` in the project folder.

**Comment by zheung** [comment]
> 1. Download the latest Neutralino Binaries Either from this Neutralino's github [release page](https://github.com/neutralinojs/neutralinojs/releases) Or From Neutralino's [Source Forge Page](https://sourceforge.net/projects/neutralinojs/files/)
> 2. Make a New Folder For your project if not already created one.
> 3. Inside your project folder make 2 new folders `bin` and `www`.
> 4. Extract All The Binaries from the .zip file you downloaded in the 1st step and put them inside the `bin` folder
> 5. also download the `neutralino.js` client file from the [GitHub Releases](https://github.com/neutralinojs/neutralino.js/releases) and put the `neutralino.js` file somewhere inside your project folder.
> 6. in your project folder make a new file `neutralino.config.json` and copy paste everything below inside your config file.
> 
> ```json
> {
>   "applicationId": "js.neutralino.sample",
>   "version": "1.0.0",
>   "defaultMode": "window",
>   "documentRoot": "/www/",
>   "url": "/",
>   "enableServer": true,
>   "enableNativeAPI": true,
>   "tokenSecurity": "one-time",
>   "nativeAllowList": [
>     "app.*"
>   ],
>   "modes": {
>     "window": {
>       "title": "myApp",
>       "width": 800,
>       "height": 500,
>       "minWidth": 400,
>       "minHeight": 200,
>     }
>   },
>   "cli": {
>     "binaryName": "myApp",
>     "resourcesPath": "/www/",
>     "extensionsPath": "/extensions/",
>     "clientLibrary": "/www/neutralino.js",
>     "binaryVersion": "4.3.0",
>     "clientVersion": "3.1.0"
>   }
> }
> ```
> 
> 7. inside the `www` folder put all of your html, css and js stuff and replace the `resourcesPath` in `cli` and `documentRoot` in your config file with the name of your folder where your html, css and js stuff is. if you named that folder `www` no need to change anything.
> 8. Replace the `binaryVersion` and `clientVersion` inside the `cli` property with the binary version and the `neutralino.js` client file you downloaded (example the binary version for `neutralinojs-v4.3.0.zip`)
> 9. Replace the path to `clientLibrary` in `cli` property in the config json file with the path of the `neutralino.js` file you downloaded and placed somewhere inside your project folder.
> 10. Finally Run `pnpx neu run` in the project folder.

it works fine. Thanks a ton!

**Comment by beibeibeibei2022** [comment]
Pay attention to `neutralino.config.json > modes > window > icon`,
which will cause errors [Build Error -- neu: ERROR Error: ENOENT: no such file or directory, stat './undefined'](https://github.com/neutralinojs/neutralinojs-cli/issues/158)
