### ISSUE TITLE
Is it possible to use fixed ports for multiple windows?

### ISSUE THREAD

**Issue by pkulijing** [neutralinojs/neutralinojs#813]
I‘ve been using fixed port number for my main app (i.e. specifying `port` in the config file. When I attempt to spawn a child window using `window.create`, an address-in-use error is reported:
```
terminate called after throwing an instance of 'websocketpp::exception'
  what():  Address already in use
Aborted (core dumped)
```
The doc states that each window is a new app instance, so I think the error is because the children window is attempting to use the same fixed port as the main app. After changing port to 0 (i.e. automatic port), the error is gone. 

So I'm wondering if it's possible to specify fixed ports for multiple windows? Controlling ports is sometimes necessary in company intranet (e.g only a few ports are allowed to be exposed for external visit).

**Comment by DEVLOPRR** [comment]
When changing the port to 0 it uses some random port for every new instance of Neutralino Window, As of now there is no way to specify the port for children windows, i think @shalithasuranga will add it sooner or later.

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting and discussing this issue. The following code snippet will work: 

```js
Neutralino.window.create('/', {processArgs: '--port=<port_number>'})
```
