### ISSUE TITLE
Updater to new version

### ISSUE THREAD

**Issue by jwhijazi** [neutralinojs/neutralinojs#816]
I'm trying to use Neutralino.updater to update existing application.
I have created update_manifest.json file with the following configuration:
```
{
    "applicationId": "js.neutralino.sample",
    "version": "1.0.6",
    "resourcesURL": "http://localhost:90/neu_app/resources.neu",
    "data": {
    }
}
```
Then I copied the generated files to this folder and allowed **.json** files and **.neu** MEMI types on IIS configuration.
Files can be downloaded manually from localhost:90 successfully.

When I run the code to update I got a message: 

`neutralino.config.json file is missing or corrupted.`

Update Code:

    ```
let url = 'http://localhost:90/neu_app/update_manifest.json';
    let manifest = await Neutralino.updater.checkForUpdates(url);

    if (manifest.version != NL_APPVERSION) {
      await Neutralino.updater.install();
      await Neutralino.app.restartProcess();
    }
    else {
      Neutralino.os.showMessageBox("Liteman", "You are using the latest version.", null, "WARNING");
      console.log('You are using the latest version!');
    }
 
```

**Comment by jwhijazi** [comment]
Hello again,
Thanks for the support, but the problem still not fixed,  even after updating to version 4.4.0.

**Comment by shalithasuranga** [comment]
Hello. Could you please let us know in which OS you've tried the above codes?

**Comment by jwhijazi** [comment]
Windows 10,
In console.log I got the below error when calling updater.install:

code: "NE_RT_NATRTER"
message: "Native method execution error occurred. Failed because of: Unknown exception. Make sure that you've provided required parameters properly."

Also I noticed that when the resources.neu file is downloaded from local IIS server its corrupted because all \n characters are replaced with \r\n
P.S. I have setup the MIME TYPE in IIS for .neu files as application/octet-stream

**Comment by shalithasuranga** [comment]
Thanks for providing more details. Perhaps, this issue is related with #619 Let's do some tests and identify :)

**Comment by jwhijazi** [comment]
Hi again,
Also it will be great to add cache flag (true, false) in the Neutralino.updater.checkForUpdates method to remove cache and get the new manifest.json file.

**Comment by shalithasuranga** [comment]
Closing this since the original issue is solved. Thanks so much for reporting this issue :tada:
