### ISSUE TITLE
Neutralino.window.setDraggableRegion is malfunctioning on windows

### ISSUE THREAD

**Issue by m6tm** [neutralinojs/neutralinojs#820]
**Neutralino.window.setDraggableRegion is malfunctioning on windows**  

**Actual Behavior**
What happens is that I initiate the window drag instruction with Neutralino.window.setDraggableRegion, it works but there is a very big problem in rendering. I am on a windows system. Here is a video of the problem:

https://user-images.githubusercontent.com/62152044/156894974-371a0e0e-8733-4500-b8aa-e92423777001.mp4
  
**Steps to Reproduce the Problem**  
 1. Created a project on Windows
 2. Set draggable window region : Neutralino.window.setDraggableRegion('domid')
 3. Run test

**Specifications**  
* NeutralinoJs Version: 4.3.0
* NeutralinoJs CLI version: 9.1.2
* Platform: Windows

**Comment by DEVLOPRR** [comment]
I saw some issues on Linux too

**Comment by shalithasuranga** [comment]
Closing this since the latest version doesn't have a rendering issue with the draggable region feature on Windows. Thanks for reporting :tada:
