### ISSUE TITLE
Windows 11 Neutralino.window.setSize does not take effect

### ISSUE THREAD

**Issue by pashangshangpo** [neutralinojs/neutralinojs#823]
Expected Behavior

Neutralino.window.setSize sucess

Actual Behavior

The execution succeeded but the size did not change

![image](https://user-images.githubusercontent.com/28686832/157019300-71b94955-5edd-4d7f-b7dc-298883f044d9.png)

Specifications

NeutralinoJs Version: v3.2.0
NeutralinoJs CLI version: v4.3.0
Platform: Windows 11 64bit

**Comment by pashangshangpo** [comment]
neutralino.config.json

{
  "applicationId": "xxxx",
  "version": "1.0.0",
  "defaultMode": "window",
  "port": 0,
  "documentRoot": "/build/",
  "url": "/",
  "enableServer": true,
  "enableNativeAPI": true,
  "tokenSecurity": "one-time",
  "logging": {
    "enabled": false,
    "writeToLogFile": false
  },
  "nativeAllowList": [
    "app.*",
    "os.*",
    "filesystem.*",
    "window.*",
    "extensions.*"
  ],
  "modes": {
    "window": {
      "title": "xxxx",
      "width": 600,
      "height": 400,
      "icon": "/public/appIcon.png",
      "enableInspector": true,
      "exitProcessOnClose": true
    },
    "browser": {
      "nativeBlockList": [
        "app.*",
        "os.*",
        "filesystem.*",
        "window.*",
        "extensions.*"
      ]
    }
  },
  "cli": {
    "binaryName": "xxxx",
    "resourcesPath": "/build/",
    "extensionsPath": "/extensions/",
    "clientLibrary": "/public/neutralino.js",
    "binaryVersion": "4.3.0",
    "clientVersion": "3.2.0",
    "frontendLibrary": {
      "patchFile": "/index.html",
      "devUrl": "http://localhost:3000"
    }
  }
}

**Comment by Kantyash** [comment]
Any luck with this?

**Comment by Kantyash** [comment]
Ok, so, idk if this is a universal solution but it didn't work on a friend's PC either but it works now after installing the Webview2 Runtime.

**Comment by shalithasuranga** [comment]
We are linking this issue to the main #648. Thanks so much for reporting and discussing :tada:
