### ISSUE TITLE
Option to Disable Web Security in WebView2

### ISSUE THREAD

**Issue by MissinA** [neutralinojs/neutralinojs#836]
I hope it will be more convenient to send network requests in neutralinojs window program.
**I made different attempts under Windows and Mac respectively. They can work well:**
In neutralinojs/lib/webview/webview.h
I hope you can add it, Thanks for amazing project!! 

for mac os > line 706 :
`    // [[config preferences] setValue:@NO forKey:@"webSecurityEnabled"];
    ((id(*)(id, SEL, id, id))objc_msgSend)(
      ((id(*)(id, SEL))objc_msgSend)(config, "preferences"_sel), 
      "setValue:forKey:"_sel,
      ((id(*)(id, SEL, BOOL))objc_msgSend)("NSNumber"_cls, "numberWithBool:"_sel, 0),
      "webSecurityEnabled"_str
    );`

for windows >  line 1018
` SetEnvironmentVariableW(L"WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", L"--disable-web-security  --user-data-dir");`

**Comment by shalithasuranga** [comment]
Closing as a duplicate of #586. Thanks for reporting and discussing this issue :tada:
