### ISSUE TITLE
Bug In Window Draggable Region

### ISSUE THREAD

**Issue by pegvin** [neutralinojs/neutralinojs#837]
**Expected Behavior**
When setting a custom drag able and dragging the window via the region, the cursor position & the point from where i started dragging should be same

**Actual Behavior**  
The cursor position & the point from where i started dragging don't match

**Steps to Reproduce the Problem**  
 1. Make a new html element with a id in the index.html file: `<div id="myDrag">This is a draggable region</div>`
 2. In JavaScript set the dragable region using the `window` API: `Neutralino.window.setDraggableRegion("myDrag")`
 3. Run the application and drag the html element with id `myDrag`

**Specifications**  
* NeutralinoJs Version: 4.4.0
* NeutralinoJs Client Version: 3.3.0
* NeutralinoJs CLI version: 9.2.0
* Platform: XUbuntu x64

**Additional Information**
* This Bug is available in all the platforms

**Video**

https://user-images.githubusercontent.com/75035219/158386772-a834758b-7577-4dd5-b2c7-dd37a5978825.mp4

[Video From m6tm](https://github.com/neutralinojs/neutralinojs/issues/820)

**Comment by dipit-s** [comment]
I have been trying to figure this issue out, It happens so that this feature works fine in case of border-less windows, I am going through the gtk documentation to figure out how to fix this issue.(So far I believe changes shall be made in the windows 'move' api). I would like to resolve this issue. Could you please assign this to me?

**Comment by DEVLOPRR** [comment]
This issue occurs in all platforms, and the borderless window movement is handled by the JavaScript Code and not the Windows Manager For That OS.

See the Implementation In JavaScript: https://github.com/neutralinojs/neutralino.js/blob/main/src/api/window.ts#L93

**Comment by m6tm** [comment]
Has anyone already solved the problem?

**Comment by DEVLOPRR** [comment]
No

**Comment by Bullhoff** [comment]
Adding this to the setDraggableRegion function mostly solved it for me: 

```javascript
let rect = document.body.getBoundingClientRect()
let fixX = rect.left		// Width of body offset
let fixY = rect.top + 25  	// Height of body offset + Windows 10 default titlebar height
//let fixY = rect.top 		// (if borderless)

let scale = window.devicePixelRatio	// Scale factor for the monitor

yield S((e.screenX - r - fixX)*scale, (e.screenY - s - fixY)*scale);
//yield S(e.screenX - r, e.screenY - s);
``` 

The window.devicePixelRatio value seem to only give the primary monitor scale, so if moving the window to a secondary display that has different scaling it starts behaving as in the video.

**Comment by m6tm** [comment]
> Adding this to the setDraggableRegion function mostly solved it for me:
> 
> ```js
> let rect = document.body.getBoundingClientRect()
> let fixX = rect.left		// Width of body offset
> let fixY = rect.top + 25  	// Height of body offset + Windows 10 default titlebar height
> //let fixY = rect.top 		// (if borderless)
> 
> let scale = window.devicePixelRatio	// Scale factor for the monitor
> 
> yield S((e.screenX - r - fixX)*scale, (e.screenY - s - fixY)*scale);
> //yield S(e.screenX - r, e.screenY - s);
> ```
> 
> The window.devicePixelRatio value seem to only give the primary monitor scale, so if moving the window to a secondary display that has different scaling it starts behaving as in the video.

You dont explain where do we past this code to the setDraggableRegion function. So it's not solved for me.

**Comment by Bullhoff** [comment]
> 

It was mostly meant  to point the devs to the issue, but if you want to use it as a temporary solution just go to the built library at ./resources/neutralino.js and search for and replace "yield S(e.screenX - r, e.screenY - s);" with the code above. 

Also i noticed it still jumped a bit when not going borderless, but adding this to the above made it perfect for me, not sure where that extra margin comes from though so you might not need it:  
fixX += 7
fixY += 5

**Comment by Reza-245** [comment]
in windows 10 is ok, but ive same problem in windows 11

**Comment by shalithasuranga** [comment]
Closing this since the latest client library version contains a throttling optimization for calling the `window.move` function. Thanks for reporting and discussing this :tada:
