### ISSUE TITLE
Neutralino will not run w/o libayatana-appindicator on Fedora

### ISSUE THREAD

**Issue by onkoe** [neutralinojs/neutralinojs#840]
**Expected Behavior**  
`neu run` launches your program on Fedora 35.  
**Actual Behavior**  
Currently, due to the lack of packaged ayatana-appindicators on Fedora Linux, neutralino fails to run. It spits out the following: 
```
barrett@soda ~/D/Project> neu run
neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
bin/neutralino-linux_x64: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
neu: WARNING neutralino-linux_x64 was stopped with error code 127
```

**Steps to Reproduce the Problem**  
 1. Be running any version of Fedora Linux 
 2. Type `neu run` into your terminal while running any version of Neutralino past #800 
 3. Nothing happens :( 

**Specifications**  
* NeutralinoJs Version: binaries v4.4.0, client v3.3.0
* NeutralinoJs CLI version: CLI v9.2.0
* Platform: Fedora Linux 35 Everything, amd64

**Comment by DEVLOPRR** [comment]
Can you try This [package](https://fedora.pkgs.org/35/fedora-x86_64/libappindicator-gtk3-12.10.0-31.fc35.x86_64.rpm.html)

**Comment by onkoe** [comment]
No change, sadly. I've also tried all of the other packages that mention "ayatana" whatsoever - none of them affect the crash. :(

**Comment by pathange-s** [comment]
@onkoe `any version of Neutralino past [this](https://github.com/neutralinojs/neutralinojs/pull/800) ?`
Was this fixed after merging this pull request ?

**Comment by Mar0xy** [comment]
The issue is ayatana's appindicator package that is needed isn't available on fedora but on opensuse so if you want to run neutralino you would need to somehow currently deal with being able to install the opensuse rpm file of libayatana which leads you down a rabbit hole here is a list of all files:
[libayatana-appindicator3-1](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/libayatana-appindicator3-1-0.5.90-1.3.x86_64.rpm.html)
[libayatana-indicator3-7](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/libayatana-indicator3-7-0.9.0-1.6.x86_64.rpm.html)
[libayatana-ido3-0_4-0](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/libayatana-ido3-0_4-0-0.9.0-1.3.x86_64.rpm.html)

**Comment by onkoe** [comment]
@pathange-s The opposite - that PR removed compatibility with Fedora for the near future without action from Neutralino

**Comment by pathange-s** [comment]
@shalithasuranga can you please look into this ? I am not sure about further conversation

**Comment by GGGav** [comment]
I just hit the same error on Ubuntu 20.04.4.

**Comment by onkoe** [comment]
@GGGav I think you can fix this by installing the libayatana-indicator package in Ubuntu's Universe repos. Try ``sudo apt install  libayatana-indicator3-7`` if you have these repos enabled. That said, I don't have an Ubuntu computer and can't test for you. You may [find other related packages here](https://pkgs.org/search/?q=libayatana-indicator).

**Comment by GGGav** [comment]
@onkoe Thanks for the quick response.  `sudo apt install libayatana-appindicator3-1` fixed it for me.

**Comment by shalithasuranga** [comment]
I think we need to dynamically load tray menu support as explained in: https://github.com/neutralinojs/neutralinojs/issues/847 will try to release a patch version with this fix soon since causes portability issues.

**Comment by elliotwutingfeng** [comment]
On Manjaro Linux I had to install **libayatana-appindicator** from the AUR with

```sh
yay -S libayatana-appindicator
```

This would probably work for Arch and EndeavourOS
