### ISSUE TITLE
how do I deal with error code 127?

### ISSUE THREAD

**Issue by planetjunkie** [neutralinojs/neutralinojs#846]
Hey uh I was trying to run my first neutralino app and uh I got this error

![image](https://user-images.githubusercontent.com/79197022/160469138-28cf2bfa-923b-4f85-a27f-ef7f0799fa84.png)

Can anyone help?

**Comment by DEVLOPRR** [comment]
> Hey uh I was trying to run my first neutralino app and uh I got this error
> 
> ![image](https://user-images.githubusercontent.com/79197022/160469138-28cf2bfa-923b-4f85-a27f-ef7f0799fa84.png)
> 
> Can anyone help?

You don't have lib ayatana, install it with "sudo apt-get install libayatana-appindicator-3.0.1

**Comment by planetjunkie** [comment]
im on fedora

**Comment by pathange-s** [comment]
Check [this](https://github.com/neutralinojs/neutralinojs/issues/840) out. Might help
