### ISSUE TITLE
window.enableInspector

### ISSUE THREAD

**Issue by cer1969** [neutralinojs/neutralinojs#849]
Is there a way to change "window.enableInspector" to false when I run neu build?
(apart from editing neutralino.config.json)

It would be nice to have an option like **--window-enable-inspector** in neu cli.

**Comment by pathange-s** [comment]
Disabling `enableInspector` in neutralinojs.config.json might help :)

**Comment by cer1969** [comment]
> Disabling `enableInspector` in neutralinojs.config.json might help :)

As I said in the original post, that's what I currently do.

**Comment by pathange-s** [comment]
Ah, I guess, woke up just now.

**Comment by pathange-s** [comment]
> It would be nice to have an option like **--window-enable-inspector** in neu cli.

@shalithasuranga What do you think about this ? Instead of editing the config file repeatedly, we can have one such flag if needed. Let me know

**Comment by shalithasuranga** [comment]
Hello all.. you can set enableInspector to `false` and use `neu run -- --window-enable-inspector` to start the development mode. After the `--` parameter, you can provide any internal CLI argument to the Neutralinojs process.

**Comment by pathange-s** [comment]
@shalithasuranga I see there's no flag `--window-enable-inspector` in the docs. Also putting this flag, toggles false to true but not true to false ie, using this flag, I am able to enable inspector for false but not disable it from enabled.

Please try to re read [this](https://github.com/neutralinojs/neutralinojs/issues/849#issue-1185805353) carefully

**Comment by shalithasuranga** [comment]
Please check: https://neutralino.js.org/docs/cli/neu-cli#neu-run (Last sentence)
Here, I suggested keep enableInspector as `false` in config, so you won't get the inspector in the production app. When you are developing, use `neu run -- --window-enable-inspector`, so you will get the inspector ;)

**Comment by pathange-s** [comment]
Can we use the flag to toggle `enableInspector` value instead of just setting false -> true ? I mean, when ever we pass the flag, opposite of the one in config.json will be used to run the app.

**Comment by shalithasuranga** [comment]
Hey @pathange-s, I think `<param>=false` will work for this one too. You can read more details about this syntax in https://neutralino.js.org/docs/cli/internal-cli-arguments#--chrome-argsarg_list 's (tip section)

**Comment by pathange-s** [comment]
Cool ! Read this long back, this didn't strike. Great, in this case. So, @cer1969 you can run the app as `neu run -- --window-enable-inspector=false` to get your job done.

**Comment by cer1969** [comment]
Any option is good to me (I use npm to run this tasks). 
Right now --window-enable-inspector always return an "error: unknown option".

**Comment by pathange-s** [comment]
@cer1969 does this error still persists ?

**Comment by cer1969** [comment]
I'am using neutralino binaries 4.4.0 in windows 11 and --window-enable-inspector is an unknown option

**Comment by shalithasuranga** [comment]
Seems like `--` is missing. The correct command is `neu run -- --window-enable-inspector` .. After `--`, you can enter any supported internal CLI argument.

**Comment by cer1969** [comment]
Running from the command line (in pwsh):

`--- Global ---
neu CLI: v9.2.0

--- Project: xxxxx ---
Neutralinojs binaries: v4.4.0
Neutralinojs client: v3.3.0
Project version: v1.0.0

PS> neu run -- --window-enable-inspector
**error: unknown option '--window-enable-inspector'**
`

**Comment by cer1969** [comment]
I think the problem is powershell.
It's works ok if I use cmd.exe as shell.

**Comment by pathange-s** [comment]
What ?! Let me check it once

**Comment by cer1969** [comment]
I think the problem is that powershell ignores "--" parameter and is not passed to javascritpt.
If I run this it works:
neu run "--" --window-enable-inspector

**Comment by pathange-s** [comment]
@cer1969 Close the issue if its resolved.
