### ISSUE TITLE
Missing Build Scripts?

### ISSUE THREAD

**Issue by sergei202** [neutralinojs/neutralinojs#854]
First off, awesome project, very excited to see what what it can do on a Raspberry Pi.

I'm trying to follow the [Framework Developer Guide](https://neutralino.js.org/docs/contributing/framework-developer-guide/) to build Neutralinojs on a Raspberry Pi, but I'm can't find `build_linux.sh` anywhere in the repo.  Did it get (re)moved or are the docs missing a step?

Thanks again!

**Comment by rkharsan** [comment]
The build system was changed recently. Now you need to have Python installed, and run `python build/bz.py` or `python3 build/bz.py`. You still need the dependencies mentioned, except for `libayatana-appindicator3-dev`.

**Comment by DEVLOPRR** [comment]
> First off, awesome project, very excited to see what what it can do on a Raspberry Pi.
> 
> I'm trying to follow the [Framework Developer Guide](https://neutralino.js.org/docs/contributing/framework-developer-guide/) to build Neutralinojs on a Raspberry Pi, but I'm can't find `build_linux.sh` anywhere in the repo. Did it get (re)moved or are the docs missing a step?
> 
> Thanks again!

The main branch contains the latest code being worked on and contains the code that is not production ready so if something new is added in main branch it will not be listed in docs till the next release, the older versions are in different branch like v4.3.0's code is in it's own branch, checkout the GitHub branches of Neutralinojs.

**Comment by shalithasuranga** [comment]
Thanks all for discussing this and reporting the issue. Closing this issue since now the documentation is already updated :tada:
