### ISSUE TITLE
setting documentRoot causes the builded add to show 404 page

### ISSUE THREAD

**Issue by anotherempty** [neutralinojs/neutralinojs#855]
**Description**
when setting the **documentRoot** inside _neutralino.config.json_, `neu run` works fine but when building with `neu build`, the builded app doesn't find the customized **documentRoot** folder
I understand it's not a big issue but would be cool if it works as intended

- change the _resources_ folder to any name
- change the documentRoot value to the new _resources_ folder name
- optional : try `neu run` : works fine
- then do `neu build` : the builded app shows a 404 error

Specs
 - OS: win 10 x64
 - Neutralinojs version: v4.4.0
 - Neutralinojs client library version: v3.3.0
 - Neutralinojs CLI version: v9.2.0

**Comment by DEVLOPRR** [comment]
The `documentRoot` property is from where the neutralinojs server is starting from, it can be any location and it will work, but the `resourcesPath` property is where all your code is which will be bundled when building the app, so changing it doesn't effect in development but when building the app it can't find the folder to bundle & so it throws an error.

**Comment by anotherempty** [comment]
thanks, so all I have to do is setting `documentRoot` and `resourcesPath` to the same value
