### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by elliotwutingfeng** [neutralinojs/neutralinojs#858]
**Is your feature request related to a problem? Please describe.**
Could you provide an SVG version of your logo? This makes it possible to for me to submit your logo to https://github.com/simple-icons/simple-icons , which only accepts SVG vectorised logos.

NeutralinoJS meets their >5k GitHub star popularity requirement, so it's a great opportunity to promote use of this project.

Developers who use NeutralinoJS can then proudly embed badges with the NeutralinoJS logo on their project READMEs.

Examples of such badges include

<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"><img src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E" alt="JavaScript"/></a>
<a href="https://nodejs.org"><img src="https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white"/></a>

etc.

**Describe the solution you'd like**
Provide an official SVG version of the NeutralinoJS logo.

**Describe alternatives you've considered**
Tried converting the existing PNG logos to SVG but the results aren't good.

**Additional context**
nil

**Comment by pathange-s** [comment]
Will do by EOD

**Comment by DEVLOPRR** [comment]
Hey there! Thanks for helping out the project for reaching more people!

I've tried my best to replicate the Logo from PNG to SVG in Figma, which you can see [here](https://www.figma.com/file/tG6zVEGmpRUjHWCfgL3829/NeutralinoJs-Logo)

And this is the SVG I Exported From There:

![NeutralinoJs Logo SVG](https://user-images.githubusercontent.com/75035219/162959002-1f126941-6a0b-4dfd-b8c8-143583bad951.svg)

**Comment by pathange-s** [comment]
Cool then. Just started working on it. If this works, I will discontinue my work.

**Comment by elliotwutingfeng** [comment]
Thanks all. I've submitted your icon for review at https://github.com/simple-icons/simple-icons/pull/7319

**Comment by shalithasuranga** [comment]
Thanks all for working on this. Happy to see Neutralinojs is becoming popular. We've created this repo: https://github.com/neutralinojs/design-guide and added the SVG logo too.

**Comment by elliotwutingfeng** [comment]
The Neutralinojs icon has finally been [accepted](https://github.com/simple-icons/simple-icons/commit/b4c360acbf403f0d2b4238dd3b432cfbc16b0d56). Based on the release schedules, the logo should be available at https://simpleicons.org next Sunday, and badges available in the first week of October 2022.
