### ISSUE TITLE
Error at "Neutralino.computer.getMemoryInfo()"

### ISSUE THREAD

**Issue by MohamedAli00949** [neutralinojs/neutralinojs#865]
**Describe the bug**
When I used this the code below from docs. It throws the error shown in the image below.

**The code**
`let memoryInfo = await Neutralino.computer.getMemoryInfo();
console.log("Your ram size: " + Math.round(memoryInfo.total / 1000000) + "GB");`

**Screenshots/Screen recordings**
![image](https://user-images.githubusercontent.com/76850143/163669262-aad5f133-f8a8-4c9f-a815-b38b925dc639.png)

**Specifications**  
 - OS: [Windows 10 x64]
 - Neutralinojs version: [v4.4.0]
 - Neutralinojs client library version: [v3.3.0]

**Comment by pathange-s** [comment]
Adding `"computer.*"` to nativeAllowList should solve your issue. We are working on a FAQs section and this is mentioned [there](https://github.com/neutralinojs/neutralinojs.github.io/pull/195/). Hopefully, upcoming developers can resolve this without creating an issue and wait for it.


This error occurs when permissions are not given to execute the function of the respective method. To be able to run this add the `method.func` to the `nativeAllowList`. To allow all functions of a method, add `method.*`. For more information check [here](https://neutralino.js.org/docs/configuration/neutralino.config.json/#nativeallowlist-string).

**Comment by pathange-s** [comment]
Here you go,

![image](https://user-images.githubusercontent.com/76244077/163690973-1b9abfd4-9de2-41f8-88f4-39a01541e401.png)

**Comment by shalithasuranga** [comment]
Hey.. all closing the issue since it's answered, thanks for reporting and discussing :tada:
