### ISSUE TITLE
Cpp support?

### ISSUE THREAD

**Issue by rdwnsjjd** [neutralinojs/neutralinojs#867]
Does your project supports cpp in backend and web-framework such as reactjs and vuejs in frontend?

**Comment by pathange-s** [comment]
Not sure about the former, but for the front-end, web frameworks like React.js and Vue.js are supported.

**Comment by DEVLOPRR** [comment]
No, C++ backend isn't supported but you are not limited to write only JavaScript You can write your code in C++, compile it and use it in NeutralinoJs Via [Extensions](https://neutralino.js.org/docs/how-to/extensions-overview)

**Comment by shalithasuranga** [comment]
Hey.. thanks for discussing this and also reporting the issue. Seems like the question is already answered, but I will also give a summary before closing the issue.

- Frontend choice: Developers can use any JavaScript framework or absolutely no framework (Vanilla Js and HTML). The frontend library is independent, so you can use any web technology in the frontend.
- Backend choice: We are trying to offer generic native API needs from the built-in native API, but you can write a backend in any technology for Neutralinojs apps with the extensions API. You can also fork and add C++ code to the built-in API, but, then you won't be able to update Neutralinojs from the official releases ;)
