### ISSUE TITLE
Did you guys drop support for 32bit?

### ISSUE THREAD

**Issue by shadichy** [neutralinojs/neutralinojs#869]
**Is your feature request related to a problem? Please describe.**
Yes, I need 32 bit version

**Describe the solution you'd like**
have Neutralino for Linux 32 bit

**Describe alternatives you've considered**
NW.js

**Additional context**
please give me an answer

**Comment by DEVLOPRR** [comment]
Officially Neutralinojs doesn't offer 32 bit binaries but this [Fork](https://github.com/Neutralinojs-Community/Neutralinojs) gives 32 bit binaries, currently only linux binaries are added but soon windows binaries will be added too, maybe tomorrow or day after tomorrow.

**Comment by shadichy** [comment]
thanks
now i can do things

**Comment by shadichy** [comment]
how about armhf and arm64?

**Comment by DEVLOPRR** [comment]
trying to get arm VMs working, as soon as they work i'll add the arm binaries too

**Comment by DEVLOPRR** [comment]
Hey there, i've added Windows Binaries Too, [Check it Out](https://github.com/neutralinojs-community/neutralinojs)

**Comment by shadichy** [comment]
I have a little bit issue compiling the 32bit community version on Arch Linux 32, but that's ok
btw thank u so much
that's all what I need
