### ISSUE TITLE
is there a way to make window click through ?

### ISSUE THREAD

**Issue by slauko** [neutralinojs/neutralinojs#870]
Hello, just wanted to ask, if there already is a way to ignore the mouse and click through the window to areas below ? 
i really love to code overlays, i saw on the roadmap that transparency also is beeing worked on, i guess a click through ability could be pretty handy in combination :)

maybe an api to manually turn mouse detection on the window on and off, or automatically on transparent areas 
(i guess first one would be easier to manage)

**Comment by sidharthkumar2019** [comment]
I think a keyboard shortcut should be made for that.

**Comment by slauko** [comment]
> I think a keyboard shortcut should be made for that.

i mean, a function should be made for that, so u can code that shortcut yourself if needed, for example when pressing a menu button or something like that :)

**Comment by shalithasuranga** [comment]
Hello. Thanks for reporting this issue and discussing. Closing this since we track the progress of this task via #320 :tada:

**Comment by laugexd** [comment]
> Hello. Thanks for reporting this issue and discussing. Closing this since we track the progress of this task via [#320](https://github.com/neutralinojs/neutralinojs/issues/320) 🎉

i don't understand why this issue has been closed, i am working on making an app that uses transparent windows, but i can't find any way to click through the transparent parts of the app to interact with whatever apps lie behind it, which was the entire point of this issue.

Am i missing something that allows this, or was this issue marked as closed incorrectly?

I am on windows 11 if that makes any difference.
