### ISSUE TITLE
Add time related information to `filesystem.getStats` result.

### ISSUE THREAD

**Issue by HappyStriker** [neutralinojs/neutralinojs#876]
Hello,

with this issue I would like to propose an extension to the return object of the `filesystem.getStats` method. It currently only returns the information about the checked item being a file or directory and its size. In certain scenarios it would be great to also have access to the file creation and last file modification dates.

So please consider extending the return object from the current state of

```javascript
{
  isDirectory: false,
  isFile: true,
  size: 11
}
```

to something like

```javascript
{
  isDirectory: false,
  isFile: true,
  size: 11,
  createdAt: 1650956224,
  modifiedAt: 1650956224
}
```

where both times are numbers represent the milliseconds in unix time.

Thank you very much for considering this feature request. Keep on the great work on Neutralino!

Sincerely,
Happy Striker

**Comment by pathange-s** [comment]
Are you suggesting an update for the extension or a new extension itself ?

**Comment by HappyStriker** [comment]
I would consider it as an update to the existing `filesystem.getStats` method.

**Comment by pathange-s** [comment]
With this phrase
>  propose an extension
I thought you were proposing a new extension which was not necessary. That's why clarified it.

@shalithasuranga , I think this is cool according to me (what do you suggest ?) and you can go forward to create a pull request. Or, I may get assigned for this issue and will do it.

**Comment by jmo84** [comment]
Not having a modification timestamp in getStats is to me the biggest missing piece of functionality in this framework. There's a workaround but it's complicated and adds a lot of unnecessary code to any given app using this framework. Please modify getStats as soon as you can. No doubt many other people think this is a high priority feature. Thanks!

**Comment by pathange-s** [comment]
Will work on this in that case.

**Comment by pathange-s** [comment]
I have started to work on implementing this. Its easy except for handing type conversions between times.
A couple of quick questions: @HappyStriker @jmo84 

- I was able to find that `statBuffer.st_mtime` returns the last modified time. But I couldn't find a similar method depiciting `createdAt` Can you help me with this ?
- In what form is the output expected ? (for ex: 5124235346 milliseconds ?)

Also please check [this](https://github.com/neutralinojs/neutralinojs/pull/877) pull request which has the following update.

**Comment by HappyStriker** [comment]
For the first question I am not exactly sure what you mean, but maybe you task about the format to represent the result, which could be a `Date` object, created from the unix time like

```javascript
console.log(new Date(1653654435000));  // "2022-05-27T12:27:15.000Z"
```

Although, at least me personally, I would prefer the result to be number and not a `Date` object, so the expected output format for `createAt` and `modifiedAt` is the unix time in milliseconds, as JavaScript, opposite to other languages, describes the unix time in milliseconds, eg:

```javascript
console.log(+new Date(2022, 04, 27, 14, 27, 15)); //  1653654435000
//                    YYYY  MM  DD  HH  MM  SS
```

If the related `C` API does not result in a milliseconds description of the creation or modification date, then simply multiply it by `1000`, to meet JavaScripts expectations.

**Comment by pathange-s** [comment]
@HappyStriker In the first question, I was able to find a method to return last modified time, but `stat.h` doesn't have any method for `created time`

**Comment by HappyStriker** [comment]
Well unfortunately I can not be of any help in `C` related questions.

**Comment by pathange-s** [comment]
https://docs.python.org/3/library/stat.html#stat.ST_CTIME
Take a look at this

**Comment by pathange-s** [comment]
@HappyStriker you can now pull and checkout to [this](https://github.com/neutralinojs/neutralinojs/pull/877) pull request and check the output. Please check and let me know.

**Comment by jmo84** [comment]
@pathange-s Only modified timestamp is useful in my case and in my guess most people's use cases. Most OS's set the modified timestamp upon creation of a file, so don't worry about exposing a creation timestamp. 

My app needs to know if any file that a user has loaded has changed. Currently, my app remembers every opened file's last modified timestamp and then it checks periodically to see if any of them have changed and then updates the UI. So any data type, whether it's number, string, or Date, as long as JavaScript's equality checks say it's different than an old timestamp, then it works.

**Comment by HappyStriker** [comment]
> @HappyStriker you can now pull and checkout to [this](https://github.com/neutralinojs/neutralinojs/pull/877) pull request and check the output. Please check and let me know.

So I just have cloned the pr, compiled it and concluded the tests and it works as expected. Thanks!

**Comment by HappyStriker** [comment]
In case this change gets merged: Here is the proper [Pull Request for the documentation](https://github.com/neutralinojs/neutralinojs.github.io/pull/204).

**Comment by pathange-s** [comment]
Cool ! Thought of doing it once the PR gets merged. Anyways, thanks ! Also, we got to update the test suite to check these values returned and update WIN32 with the same.

**Comment by pathange-s** [comment]
@HappyStriker @jmo84 If the PR looks good to you guys, please do consider commenting `LGTM / verified functionality` so that it becomes easy and gets a quicker merge.

**Comment by pathange-s** [comment]
@HappyStriker @jmo84 Thanks for your time, guys ! I have updated the pull request with support for Linux, Windows and macOS. Hope you guys will check it out and verify it soon.

**Comment by HappyStriker** [comment]
Great work @pathange-s! Unfortunately I will not be able to test your changes in macOS, Windows 10 and Ubuntu 22.04 before tuesday.

**Comment by pathange-s** [comment]
No issues, I tested it on windows 10, ubuntu 20.04 Most probably it should work on Ubuntu 22.04 too. For macOS, i will try borrowing someone's. Else you test it.

**Comment by pathange-s** [comment]
@HappyStriker let me know if you will be able to test it on macOS 12 and 22.04 Ubuntu. Else, I will try a way out for testing.

**Comment by HappyStriker** [comment]
Will test it in a few hours 👍

**Comment by pathange-s** [comment]
Hurray ! Great, thanks for testing em out. Drop a LGTM comment on the PR to receive a faster merge. 😉

**Comment by HappyStriker** [comment]
I hope [this](https://github.com/neutralinojs/neutralinojs/pull/877#issuecomment-1117560755) is what you meant by the LGTM post?

**Comment by pathange-s** [comment]
YES @HappyStriker  ! Had great discussion, would you mind sending me a request on discord ? Sai | Sainath#2973

**Comment by HappyStriker** [comment]
Wonderful, I am glad that I could be of any help.
Sorry, but I do not use Discord.

**Comment by HappyStriker** [comment]
> In case this change gets merged: Here is the proper [Pull Request for the documentation](https://github.com/neutralinojs/neutralinojs.github.io/pull/204).

Additionally here is the [PR](https://github.com/neutralinojs/neutralino.js/pull/47) to add the two new attributes in the client side library.

**Comment by pathange-s** [comment]
Cool ! Would have dropped this if I knew it. Anyways, I guess everything is done and wrapped to get this feature for the next release 🎁

**Comment by jmo84** [comment]
Separate-but-related issue: the TypeScript interface needs to be updated to match the C++ changes.

https://github.com/neutralinojs/neutralino.js/blob/main/src/api/filesystem.ts#L8
