### ISSUE TITLE
neutralino.config.json file is missing or corrupted on macOS

### ISSUE THREAD

**Issue by genki-angel** [neutralinojs/neutralinojs#884]
Hello,

I am trying to run my application on macOS 12. However, after renaming the binary to *.app and making it executable, if i try to execute the program I get this error.

![image](https://user-images.githubusercontent.com/20613342/167232497-719143b5-138a-4766-9c4d-6b80079876f3.png)

This error does not repeat on other Linux distros or on Windows.

**Specifications**  
 - OS: macOS Monterey 12.3.1
 - Neutralinojs version: v4.5.0
 - Neutralinojs client library version: v3.4.0
 - Neutralinojs CLI version: v9.3.0

**Comment by Ayman161803** [comment]
Cant seem to recreate this bug on Catalina. Will try to execute the same on monterey. Also, make sure you have the ``resource.neu`` asar in the same directory as the ``.app`` file

**Comment by Blatman** [comment]
@genki-angel - I have attached a sample MacOS app which may be of assistance - it is a basic app bundle that does not require attaching .app to the Neutralino binary, you could plonk your files into it and it should work

[Archive.zip](https://github.com/neutralinojs/neutralinojs/files/8644880/Archive.zip)

**Comment by Ayman161803** [comment]
Check out #577  which addresses a similar issue and goes over the ``.app`` package structure. Hopefully, we get to see a neu-cli builder plugin soon through GSoC :)

**Comment by Jaimefun** [comment]
help i dont know how to add .app helppp
