### ISSUE TITLE
error 127

### ISSUE THREAD

**Issue by nobody48sheldor** [neutralinojs/neutralinojs#889]
I was trying out neutrino and I had the error 127 even with the "hello world" example

I install neutralino via `npm install -g @neutralinojs/neu` and install `libayatana-appindicator` (through AUR) and updated `webkit2gtk`

and I still got `neutralino-linux_x64 was stopped with error code 127`

**Comment by DEVLOPRR** [comment]
can you share the contents of your `neutralinojs.log` ?

**Comment by nobody48sheldor** [comment]
I don't have one since I can't run the app

**Comment by pathange-s** [comment]
Can you give the steps to reproduce the issue ?

Try following the steps in the documentation to create an app and run it.

**Comment by nobody48sheldor** [comment]
well first you install neutralino, and you create a hello world app, and then you ask an issue on the repo because you got, like me, the error 127, if you do

using arch linux vanilla
