### ISSUE TITLE
static linking webwiev2?

### ISSUE THREAD

**Issue by slauko** [neutralinojs/neutralinojs#898]
Yo,
Just wanted to ask if it is somehow possible to static link the webview2 lib since I'd like to only have 1 standalone file on windows to share when my program gets deployed ? :)

**Comment by slauko** [comment]
sorry for the edits.. love it when u write something on phone while still half sleeping and autocorrection in native language kicks in 😂

**Comment by DEVLOPRR** [comment]
The DLL `webview2loader.dll` isn't whole webview instead it's just a small library which helps us to locate webview2 runtime on the client's system.

The official docs say:
> `WebView2Loader.dll` is a small component that helps apps locate the WebView2 Runtime, or Microsoft Edge preview channels, on the device.

the actual webview runtime big maybe 150-200 MB.

**Comment by slauko** [comment]
> The DLL `webview2loader.dll` isn't whole webview instead it's just a small library which helps us to locate webview2 runtime on the client's system.
> 
> The official docs say:
> 
> > `WebView2Loader.dll` is a small component that helps apps locate the WebView2 Runtime, or Microsoft Edge preview channels, on the device.
> 
> the actual webview runtime big maybe 150-200 MB.

Oh, okay .. still is there a possibility in static linking this little helper dll into the build windows exe ? 
I like to keep folders clear u know 😄 or imagine i send it to some of my friends and they are putting the file on desktop they dont always want the dll on desktop too, just as an example ^^

**Comment by DEVLOPRR** [comment]
yea that is a valid reason, let's see what we can do.

**Comment by craigtao** [comment]
WebView2Loader.dll, Is the source code open?

**Comment by Aworldc** [comment]
My workaround for the moment is to make a python script to start the app, and use pyinstaller to pack that script, python.exe, and the outputs of `neu build` into a single executable.

**Comment by marskid** [comment]
[Distribute a WebView2 app as a single executable file](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/static?source=recommendations)
AND
On Windows and Linux, you can even hide the zip file by appending the zip file to the end of nw or nw.exe.
You can run following command on Windows to achieve this:
copy /b nw.exe+package.nw app.exe

or following command on Linux:
cat nw package.nw > app && chmod +x app 
[NW.js  Package and Distribute](https://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/)

**Comment by pegvin** [comment]
@marskid Might be contradicting my old statements but it is indeed possible to statically link `Webview2Loader.dll` but statically linking whole webview2 isn't possible and if it was then you should be using electron.

As for how to statically link, you can look into how i'm doing it in my project, [arujs](https://github.com/pegvin/arujs)

**Comment by nicorac** [comment]
@marskid That's great! Could you rebase your fork on current version and create a PR?

**Comment by nicorac** [comment]
> @marskid That's great! Could you rebase your fork on current version and create a PR?

Nevermind, the version of WebView you've used in your fork is outdated (about 1.0.705.50, released 2 years ago); sadly it doesn't build anymore on current main.

I've upgraded to the latest avaliable (1.0.1774.30, released 8 days ago) but it requires some more fixes to make it work (it changed a lot in the latest versions...).

Will push a PR when ready 😉

**Comment by nicorac** [comment]
PR created: https://github.com/neutralinojs/neutralinojs/pull/1109

**Comment by nicorac** [comment]
@slauko: PR was merged, so Neutralino won't need WebView2Loader.dll anymore in the future...
