### ISSUE TITLE
Native API calls not working

### ISSUE THREAD

**Issue by 0ctopirate** [neutralinojs/neutralinojs#902]
**Describe the bug**
Trying to call any Native API is failing.

**To Reproduce**
1. Use the following config:

```json
{
  "applicationId": "app.test.org",
  "version": "0.1.0",
  "defaultMode": "window",
  "documentRoot": "/dist/",
  "url": "/index.html",
  "enableServer": true,
  "enableNativeAPI": true,
  "tokenSecurity": "one-time",
  "modes": {
    "window": {
      "title": "testapp",
      "minWidth": 800,
      "minHeight": 500,
      "icon": "/src/assets/icons/icon.png",
      "enableInspector": true
    }
  },
  "cli": {
    "binaryName": "testapp",
    "resourcesPath": "/dist",
    "extensionsPath": "/extensions/",
    "clientLibrary": "/neutralino.js",
    "binaryVersion": "4.5.0",
    "clientVersion": "3.4.0"
  }
}
```
2. Try and run a native API like so:

```js
<button onClick={async () => {
            console.log("exiting app")
            await Neutralino.debug.log("testing")
            await Neutralino.app.exit()
}}>
```

**Expected behavior**
The app to output "testing" to the debug log and to exit. Instead, only the console.log statement runs.

**Screenshots/Screen recordings**
<img width="673" alt="image" src="https://user-images.githubusercontent.com/79027861/169954787-44201a94-908a-453b-9494-42cebb5611db.png">

**Specifications**  
 - OS: M1 Mac Monterrey
 - Neutralinojs version: v4.5.0
 - Neutralinojs client library version: v3.4.0
 - Neutralinojs CLI version: v9.3.0

**Additional context**
Maybe I don't understand the docs, but it seems like if `enableNativeAPI` is set to true, it should work? The docs mentioning this say that `If you don't use any native API functions, you can set this option to true.`, which would be the opposite of what the name implies.

**Comment by pegvin** [comment]
`enableNativeAPI` tells neutralinojs that you want to keep it enabled, it doesn't tell that what native API you want to enable.

for specifying what native api you want to use you use `nativeAllowList`:
```json
"nativeAllowList": [
  "os.getEnv",
  "storage.*"
]
```

**Comment by 0ctopirate** [comment]
I added the following to the config:

```json
  "nativeAllowList": [
    "app.*",
    "window.*",
    "os.*"
  ],
```

But I am still getting the following:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/79027861/169967410-98c1cb51-be69-4da4-b018-25ca6f3800b0.png">

**Comment by pegvin** [comment]
can you share the output of `console.log(Neutralino)`?

**Comment by shalithasuranga** [comment]
Not sure whether `init()` is called somewhere in the app code ;)

**Comment by 0ctopirate** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/79027861/169969659-fc85b36f-74ab-45b6-a0e2-63968f988821.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/79027861/169969783-6d9592f9-9e73-4842-8dd4-5122bda53528.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/79027861/169969721-af7085c9-b3e3-49f0-9b3c-10c79042f5a9.png">

My index.js:

```js
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter as Router } from 'react-router-dom';

import { routes } from './routes';
import { styles } from './styles';

// render the main component
createRoot(document.getElementById('app')).render(
    <React.StrictMode>
        { styles }
        <Router>
            { routes }
        </Router>
    </React.StrictMode>
);

// initialize neutralino
window.Neutralino.init();

// doesn't work, intended for fullscreen use
// Neutralino.events.on('ready', () => {
//     Neutralino.window.focus()
// });
```

**Comment by pegvin** [comment]
call the `Neutralino.init` function before rendering anything

**Comment by 0ctopirate** [comment]
1. https://github.com/neutralinojs/neutralinojs.github.io/blob/main/docs/how-to/use-a-frontend-library.md#configuring-the-frontend-app
2. The screen is now fully white, nothing is rendering
3. I should have mentioned before, I have been getting these errors since I started writing the code that may be related, but I don't think so
<img width="672" alt="image" src="https://user-images.githubusercontent.com/79027861/169971042-09babc13-9484-466e-bb5f-ded75eb9d086.png">

**Comment by mingjun97** [comment]
I guess you launch the neu with `--frontend-lib-dev` args?

**Comment by 0ctopirate** [comment]
> I guess you launch the neu with `--frontend-lib-dev` args?

I don't use hot-reloading. I use --watch with my webpack build (config below) and rightclick->reload when it rebuilds.

Is `--frontend-lib-dev` required for using native API calls?

webpack.config.js:

```js
const webpack = require('webpack');
const path = require('path');
const fs = require('fs');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const neutralino = fs.readFileSync('./neutralino.js', 'utf8');

const config = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      },
      {
        test: /\.(ttf)$/i,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      },
    ]
  },
  resolve: {
	modules: [path.resolve(__dirname, 'src'), 'node_modules'],
	extensions: ['.js', '.jsx']
  },
  plugins: [
    new HtmlWebpackPlugin({
      templateContent: ({ htmlWebpackPlugin }) => `
	  	<!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <script>${neutralino}</script>
          <style>
            html {
              margin: 0px;
              padding: 0px;
              overflow: hidden;
            }

            body {
              position: absolute;
              margin: 0px;
              padding: 0px;
              width: 100%;
              height: 100%;
              overflow: auto;
            }
          </style>
          <title>${htmlWebpackPlugin.options.title}</title>
        </head>
        <body>
          <div id="app"></div>
        </body>
      </html>`,
      filename: 'index.html',
    })
  ]
};

module.exports = config;
```

**Comment by mingjun97** [comment]
The following works for me:
0. Make sure neu is in running status. And you will see this in command line.
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/15214491/169973523-19db9bac-9ca8-4694-84f1-9729201786b9.png">

1. Create a symbol link for the `./.tmp/auth_info.json` file inside your react folder. **Use full path** here.
```bash
cd myreact-app/src             # cd into your react src folder
ln -s /path/to/neu/app/folder/.tmp/auth_info.json ./auth_info.json   # create a symbol link for the auth_info.json
```

2. Put the following code inside your `index.js` before the `window.Neutralino.init();`. 

```
if (!window.NL_PORT){
  let auth_info = require("./auth_info.json");
  window.NL_PORT = auth_info.port;
  window.NL_TOKEN = auth_info.accessToken;
}
```

**Comment by mingjun97** [comment]
I think the root cause for your issue is that the Neutralino failed to inject the auth_info.json to your frontend. The solution is just try to find a way to inject the auth_info.json into your frontend manually.

**Comment by 0ctopirate** [comment]
I will try this - note that setting `"tokenSecurity": "none",` also doesn't help... might not be an auth issue but I think you may be right

**Comment by mingjun97** [comment]
I guess `"tokenSecurity": "none"` just bypass the token verification. The Neutralino still don't know which port to be connected though. 🤣

**Comment by 0ctopirate** [comment]
It works! @mingjun97 you are a legend.

I really like this library, it sucks this has to be done with a method that is not portable at all. Just imagining trying to push this to a repo is making my skin crawl. There has to be a better way of injecting the right values in, right? Couldn't ``Neutralino.init()`` set those window values, or at least have an option in the config to? I guess I could have the `require` read from .tmp, but I still don't like that solution.

**Comment by mingjun97** [comment]
I did encounter this issue 3 days ago when I try to build app with neutralinojs and react app. And solved it by this monkey patch.

I notice that the documentations  said something about the hot-reload for inject the auth_info.

![image](https://user-images.githubusercontent.com/15214491/169977484-40f73ea5-cbcf-4aa1-af39-66c7ddedf596.png)

Ideally the auth_info should be injected right inside the file in config. That would make tons of sense I guess.

I'm not sure if it's a MacOS issue or common error.

**Comment by mingjun97** [comment]
I mean could be as easy as write code into that patch file like `<script> var NL_TOKEN=blabla; NL_PORT=balbal </script>`. 🤔 And 
* Rewrite this for new instance.
* Delete this for production bundle.

**Comment by 0ctopirate** [comment]
If you're not using something like create-react-app and you have access to webpack config and you don't want to use symlink, you can add ``path.resolve(__dirname, '.tmp')`` and something like ``import auth from 'auth_info.json';``.

Still have no idea how to actually ``neu build`` with this setup though lol.

**Comment by 0ctopirate** [comment]
> I notice that the documentations said something about the hot-reload for inject the auth_info.

I never saw this part myself but yeah, it would make a lot more sense to do it in the way you describe it. It's a huge hack right now.

**Comment by mingjun97** [comment]
That would be cool! I never used webpack before actually. Thanks for let me know! I'm not a frontend nerd though. lol

**Comment by 0ctopirate** [comment]
I'll close this issue when I figure out how to build this. Currently my index.js looks like this:

```js
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter as Router } from 'react-router-dom';

import { routes } from './routes';
import { styles } from './styles';

// render the main component
createRoot(document.getElementById('app')).render(
    <React.StrictMode>
        { styles }
        <Router>
            { routes }
        </Router>
    </React.StrictMode>
);

try {
    const auth = require('auth_info.json');

    if (!window.NL_PORT) {
        window.NL_PORT = auth.port;
        window.NL_TOKEN = auth.accessToken;
    }
} catch {
    console.error('Auth file not found, native API calls will not work');
}

// initialize neutralino
window.Neutralino.init();
```

When running ``neu build`` and checking console for output, all I get is the "Auth file not found" message. I don't think I understand how the OTT security system works for built binaries.

**Comment by techo207** [comment]
I think you could be missing this import on main index.html

<script src="http://localhost:54380/__neutralino_globals.js"></script>
