### ISSUE TITLE
Mode specific display of logo on README.md

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs#910]
Currently, only the light mode of the logo is present in the README.md. We can have two different versions, one for dark mode and one for light mode. Check [this](https://dev.to/arnavkr/using-darklight-mode-specific-images-in-github-markdown-3iln) blog for further help.

**Comment by rakshitgondwal** [comment]
Hey, I would like to solve this issue, can you tell me how should I start proceeding with this issue? 
I mean should I make a logo specifically for the dark mode first?

**Comment by pathange-s** [comment]
Yes

**Comment by rakshitgondwal** [comment]
What kind of changes do you want me to make to the logo? @pathange-s 
I was thinking to change the Neutralino written in black to white?
Do you have any other ideas?

**Comment by rakshitgondwal** [comment]
@pathange-s

**Comment by prakrit55** [comment]
Hello there this can be solved thereby making it in dark mode by adding the line

![Termux Logo](https://camo.githubusercontent.com/bcd2e8e127e0587f421465b88ef9e6791a9d07764412c38211ae09ae51a933c6/68747470733a2f2f63646e2e7261776769742e636f6d2f6e65757472616c696e6f6a732f6e65757472616c696e6f6a732e6769746875622e696f2f62363637663263322f646f63732f6e6c6c6f676f2e706e67#gh-dark-mode-only)

**Comment by prakrit55** [comment]
Or this can be used

![Dark(https://camo.githubusercontent.com/bcd2e8e127e0587f421465b88ef9e6791a9d07764412c38211ae09ae51a933c6/68747470733a2f2f63646e2e7261776769742e636f6d2f6e65757472616c696e6f6a732f6e65757472616c696e6f6a732e6769746875622e696f2f62363637663263322f646f63732f6e6c6c6f676f2e706e67){theme = dark}

**Comment by karandeeppotato** [comment]
where can i find the dark version of this logo or should i have to make one myself

**Comment by karandeeppotato** [comment]
where can i find the dark version of this logo or should i have to make one myself

**Comment by pegvin** [comment]
@karandeeppotato: https://www.figma.com/file/tG6zVEGmpRUjHWCfgL3829/NeutralinoJs-Logo
