### ISSUE TITLE
How can I sign my MacOS app I've built with Neutralino?

### ISSUE THREAD

**Issue by iamandras** [neutralinojs/neutralinojs#913]
Hi,

NeutralinoJS is a great tool, I like that it is so lightweight.
I've built a macOS app and now I would like to sign it. 
How can I do it? I already enrolled in the Apple Dev program, I created a Developer ID certificate.

I tried to do it the way how Electron apps are signed without any luck.

Can you help me?

Thanks,
Andras

**Comment by jagrider** [comment]
@iamandras Did you end up resolving your question? If so, do you mind sharing the resources you used to determine the solution? Thanks!

**Comment by iamandras** [comment]
@jagrider 
Well, I realized that nobody will help me here, so  I migrated my codebase to Electron :)
It is much bigger (~140MB), but it has many benefits: for example, I can run any NodeJS libraries in it and it has a much-much bigger community to help.

After a few days of struggle, I was able to sign and notarize my app.
In case you're interested I documented the steps: https://www.rocketride.io/blog/macos-code-sign-notarize-electron-app
