### ISSUE TITLE
Borderless Window in "window" Mode not resizable on edges?

### ISSUE THREAD

**Issue by jonasmoeller** [neutralinojs/neutralinojs#919]
**Describe the bug**
Not sure if this is a "bug" but a borderless window on Windows 11 with uses Edge is not resizable on the corners?
As far as I know this should work with chrome? I am not sure if there is a flag for this or if its just edge.

**To Reproduce**
1. Set borderless mode to true
2. Try resizing the window on the corners/edges

**Expected behavior**
It should be resizable.

**Specifications**  
 - OS: Windows 11 x64
 - Neutralinojs version: 
 - Neutralinojs client library version: 3.5.0
 - Neutralinojs CLI version: 4.6.0

**Additional context**
I am aware that this has probably something to do with edge itself, but it would be nice if someone could look at it.
Working with Electron the normal behavior of this borderless windows is normally that they're resizable by mouse.

**Comment by addoyle** [comment]
I just filed this same bug (#948), calling `setSize()` does seem to enable the behavior, but it seems to cause a rendering bug in that it adds this annoying white bar at the top.

```js
// You can even call it with its own current size
window.Neutralino.window.setSize(window.Neutralino.window.getSize());
```
