### ISSUE TITLE
Add url option to os.showOpenDialog and os.showFolderDialog

### ISSUE THREAD

**Issue by pkulijing** [neutralinojs/neutralinojs#926]
**Is your feature request related to a problem? Please describe.**
Currently `os.showOpenDialog` and `os.showFolderDialog` will show the working directory of the application on start. Often it's preferable to use another folder as the starting point to accelerate the selection process, e.g. the folder used the last time, or a default data storage folder configured by the user.

**Describe the solution you'd like**
This can be solved by adding a "startingPoint" (maybe not the best name)  option to the APIs and show that folder on start.

**Describe alternatives you've considered**
N/A

**Additional context**
I haven't used the API but I think the issue applies also to `os.showSaveDialog`

**Comment by kodaloid** [comment]
I added code in a recent pull request that will enable this #923 , however it will require a further change in neutralino.js which I've also submitted a pr for before you can use it.

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting this issue. Closing this issue since #923 already answered this feature request. We will release this feature soon with the next release :tada:
