### ISSUE TITLE
readFile to accept pos, size

### ISSUE THREAD

**Issue by exebook** [neutralinojs/neutralinojs#927]
Allow random file read by adding two more parameters to `fileRead(name)` --> `readFile(name, pos, size)`, so when `pos` is not `null`/`undefined` the file will be seek to `pos` and only `size` characters/bytes read.

Thanks

**Comment by shalithasuranga** [comment]
Hey.. thanks for sending this great idea. In the next release, you can use `size` and `pos` options with `readFile` (in characters) and `readBinaryFile` (in bytes). You can experiment this feature with today's nightly builds too :tada:

Thanks
