### ISSUE TITLE
Under Linux workflow to run test suite, error occured

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs#936]
**Describe the bug**

Please check[ line no: 39, 40, 41](https://github.com/neutralinojs/neutralinojs/runs/6843325856?check_suite_focus=true#step:7:40).
This is probably because an instance of an app starts on the same port which already has another app running.

**Expected behavior**

The test suite should be configured to first test a feature, then exit the app and thereafter run other tests. That is, the port should be freed up before another instance starts.

**Comment by shalithasuranga** [comment]
Closing this since the test suite works fine now on Linux. Thanks for discussing :tada:
