### ISSUE TITLE
Neutralinojs cannot be used for a commercial application delivered by an independent software vendor

### ISSUE THREAD

**Issue by kasajian** [neutralinojs/neutralinojs#941]
Neutralinojs cannot be used for a commercial application delivered by an independent software vendor.

The reason is because a product delivered to a customer should be able to be installed and run without the end-user requiring Administrator privilages.

The documentation states there are cases when the end-user may need to issue the following line:
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"

The end-user would have to be an Administrator to do that.

Furthermore, the documentation is vague about whether this is needed in all cases or some cases.   This vagueness prevents an ISV from making a decision in using this framework.   If the details given were more specific, then it's possible for an ISV to make a determination if the subset of the conditions under which such a setting is unnecessary applies to them.

The wording of the documentation should be updated to be more explicit.  If there are any conditions under which it is not necessary for a user to issue this command, then list.  That way potential can make a decision on this technology.

**Comment by danidre14** [comment]
I think to solve this one needs to look into neu bundler; to create installable applications for all distributable versions.
For windows, they'll have an installer they allow to run once and it should issue that line if needed, during installation.
