### ISSUE TITLE
How to inject js lib to call Neutralino API from remote URLs?

### ISSUE THREAD

**Issue by lexesv** [neutralinojs/neutralinojs#942]

**Comment by kikixxNFT** [comment]
Seems like #586 was looking at tackling this but not sure if it's exactly the same. I'm also looking for a way to inject a script into remote URL.

Looks like there's an executeJavascript function which uses eval on nativeWindow but it doesn't look to be usable from JS code.

@shalithasuranga  Is there any option for window mode? Or is it only possible with chrome mode and loading a chrome extension?

**Comment by lexesv** [comment]
Please pay attention to my question.

**Comment by zeyios** [comment]
By Editing C++ codes, we can insert our own JS,

I have tried that it works. Maybe we can add an "injectJS" param in `neutralino.config.json` and read it in C++, then apply to webview.

![image](https://github.com/neutralinojs/neutralinojs/assets/10176630/8125fc9e-f470-43cd-8699-70d855f3a8c1)
