### ISSUE TITLE
Single Executable

### ISSUE THREAD

**Issue by cheetahbyte** [neutralinojs/neutralinojs#943]
**Is your feature request related to a problem? Please describe.**
I discovered NeutralinoJS a day ago and was actually pretty excited right away. I actually like the idea of replacing Electron.
However, I'm quite frustrated that I always need the `resources.neu` in addition to the executable (e.g. to send the app/program to friends). I think this is just inconvenient. 

**Describe the solution you'd like**
I would like to see a solution where the required files (which are currently in the `resources.neu`) are in the executable.

**Comment by pegvin** [comment]
#789 ?
