### ISSUE TITLE
支持golang和python

### ISSUE THREAD

**Issue by passerbyo** [neutralinojs/neutralinojs#951]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Screen recordings**
If applicable, add screenshots/screen recordings to help explain your problem.

**Specifications**  
 - OS: [e.g. Windows 10 x64]
 - Neutralinojs version: [e.g. v4.3.0]
 - Neutralinojs client library version: [e.g. v3.3.0]
 - Neutralinojs CLI version: [e.g. v9.1.2]

*Note: you can enter the `neu version` command to find these details*

**Additional context**

**Comment by pegvin** [comment]
@shalithasuranga Close the issue.

**Comment by shalithasuranga** [comment]
Hey @passerbyo Please update the issue with a clear title and description, then we can discuss it further. We can re-open this after updating :tada:
