### ISSUE TITLE
No Unicode support in Windows

### ISSUE THREAD

**Issue by kolbasa** [neutralinojs/neutralinojs#960]
**Describe the bug**
I am trying to build an open source application for all platforms and all languages.
In my use case, I need simple access to the file system.
Unfortunately, this is impossible for most languages on Windows.

For example, the following command cannot be executed on most computers:
```js
await Neutralino.filesystem.readDirectory('C:\\Users\\Michael'); // never resolves
```
This is because Windows places appropriately translated default folders in the home directory.

You might think that you could build a workaround with `Neutralino.os.execCommand`. 
Unfortunately, the problem runs through the entire native api.

```js
await Neutralino.os.execCommand('dir C:\\Users\\Michael'); // never resolves
```

That's a shame when you have to categorically exclude most European countries from using it.

**Specifications**  
- OS: Windows 11 x64, Windows 10 x64
- Neutralinojs version: v4.6.0
- Neutralinojs client library version: v3.5.0
- Neutralinojs CLI version: v9.3.1

**Comment by pathange-s** [comment]
Hey @kolbasa, sorry for the inconveniences. There have been several efforts put in by the organisation to bring support for the same.
It was also included in the GSoC ideas list to get the support asap. Check [here](https://github.com/neutralinojs/gsoc2022#2-support-unicode-characters-in-neutralinojs-windows-version). But, still developers are working on it to get a workaround for this.

**Comment by kolbasa** [comment]
Not a problem. Neutralinojs is a great project! Eventually it will work! 👍

**Comment by onemen** [comment]
Can anyone update when this will be fixed?

**Comment by kolbasa** [comment]
I have given up hope. The problem has existed for so long. I would switch to another framework.

**Comment by pegvin** [comment]
you can look at pegvin/arujs but it's very new tho but is Unicode compatible.

**Comment by onemen** [comment]
@pegvin
> you can look at pegvin/arujs but it's very new tho but is Unicode compatible.

Is it possible to use some of the code from arujs as an extension in neutralino to replace `Neutralino.filesystem` ?

**Comment by pegvin** [comment]
@onemen nopes, cause AruJs Uses The IPC Provided By WebView Itself and Neutralino Uses WebSockets To Transfer All The Data...

**Comment by onemen** [comment]
@pegvin
is it possible to compile AruJs code to an exe, then i can call it with   `Neutralino.os.execCommand(arujs_code.exe);`
i do it now for an hash function that i use, without an extension.

**Comment by pegvin** [comment]
Come Discord.... (I'll be editing this comment to the final answer, as i really don't want to create a big thread here)

**Comment by OsiPog** [comment]
> You might think that you could build a workaround with Neutralino.os.execCommand.
Unfortunately, the problem runs through the entire native api.
> ```js 
> await Neutralino.os.execCommand('dir C:\\Users\\Michael'); // never resolve
> ```

But I made this workaround work with `os.spawnProcess()` (Neutralino v9.3.1):

```js
let py = await Neutralino.os.spawnProcess('python');

Neutralino.events.on('spawnedProcess', (evt) => {
    console.log(evt.detail)
});
    
await Neutralino.os.updateSpawnedProcess(py.id, 'stdIn', 'print("ÜüÄäÖöẞ")');
await Neutralino.os.updateSpawnedProcess(py.id, 'stdInEnd');
```
Output:
```
{action: 'stdOut', data: 'ÜüÄäÖöẞ\r\n', id: 0}
{action: 'exit', data: 0, id: 0}
```

Here python recieves the Unicode string successfully and prints it out. The printed string is also successfully read by Neutralino (seen in the output).

**Comment by onemen** [comment]
I did something similar, but with node. (i've compiled the scripts with [pkg](https://github.com/vercel/pkg) to `.exe` file).

The only 'problem' with this approach is that it add about 400ms to the start time and about 39000KB for `.exe` file

**Comment by shalithasuranga** [comment]
Closing this since the Windows Unicode support was added via #1102. If a specific feature doesn't support Unicode still, I think we can create a separate issue. 

Thanks :tada:
