### ISSUE TITLE
Apple menu support.

### ISSUE THREAD

**Issue by aleph1** [neutralinojs/neutralinojs#962]
**Is your feature request related to a problem? Please describe.**
At present, it isn't possible to use os.setTray on Mac, and this also limits the types of applications that can be created using neutralino.js. The current application I am building needs a comprehensive native menu.

**Describe the solution you'd like**
Ideally full Apple menu support using NSApp, NSMenu, and NSMenuItem.

**Describe alternatives you've considered**
Any workaround to this issue flies in the face of Apple's guidelines, as well as standard conventions for applications running on macOS.

**Additional context**
I might be able to take a look at implementing this on Mac, but have little to no experience with app development on Windows/Linux. Ideally I would utilize an API of os.setMenu(options), with options.menuItems being a list of menu items to display. Ideally it would be possible to do some more complex binding between the other NSMenu methods relating to menus, but for an initial implementation each calls to os.setMenu() would just trigger a native NSMenu.removeAllItems call (https://developer.apple.com/documentation/appkit/nsmenu/1518234-removeallitems).

Is this something that would be considered for inclusion in the core library?

**Comment by yfi** [comment]
+1

**Comment by liamlevesqueP8** [comment]
+1

**Comment by aleph1** [comment]
I am very close to having this running on Mac OS. Would this functionality be a candidate for including in the core? I am less familiar with Windows and Linux, but could probably get the latter version running using [GTK](https://www.gtk.org) like [Tray.h](https://github.com/neutralinojs/neutralinojs/blob/main/lib/tray/tray.h) uses. However, I would likely need someone to take over writing the required code for Windows.

**Comment by shalithasuranga** [comment]
Hello. thanks so much for posting and discussing this issue. I am closing this due to previous similar issues #507 and #615 :tada:
