### ISSUE TITLE
Why not reading all accessible environment variable?

### ISSUE THREAD

**Issue by mp3846** [neutralinojs/neutralinojs#966]
Is it because of security reasons to not provide a method like Neutralino.os.getEnvs() to get all of them? If no please consider this as a feature request

**Comment by mp3846** [comment]
I know than it can be done like this:

```
(async () => {
        const { stdErr, stdOut } = await Neutralino.os.execCommand('pwsh -Command "dir env:"')
        console.log('error', stdErr)
        console.log('envs', stdOut)
})()
```

But considering all operating systems and writing more code to extract env names and giving os.execCommand permission I thought it would be simpler to have a method for it

**Comment by shalithasuranga** [comment]
Hey @mp3846 Thanks for reporting this issue. Yeah, it's a nice feature. We will be able use 'os.getEnvs' with the next release. Tomorrow's nightly release will include this feature as an experimental feature I guess :tada:
