### ISSUE TITLE
readBinaryFile fails with accentuated filenames

### ISSUE THREAD

**Issue by jesuscc1993** [neutralinojs/neutralinojs#968]
**Describe the bug**
readBinaryFile fails to read files with accentuated filenames (e.g.: `"sauté.jpg"`).

**To Reproduce**
1. Save any file with `"sauté"` as filename
2. Try to load the file with `readBinaryFile`
3. Verify you get a `{ code: "NE_FS_FILRDER", message: "Unable to open FILEPATH" }` exception (where `FILEPATH` is the path to the file you just saved)

You can try the same steps, using `"saute"` (without an accent), as the filename to see that the operation succeeds then.

**Expected behavior**
Accentuated files should be successfully read like any other file.

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: v4.7.0
 - Neutralinojs client library version: v3.6.0
 - Neutralinojs CLI version: v9.3.1

**Comment by kolbasa** [comment]
I think it is the same problem that I have described here: https://github.com/neutralinojs/neutralinojs/issues/960

**Comment by jesuscc1993** [comment]
I saw your issue and while the title seems like it might be related the description of your problem did not really seem related to my problem. If the owners think it is, indeed, the same issue, they can then close this ticket as duplicate.
