### ISSUE TITLE
[Issue/Bug] New Window with window.create won't open on WebView2 Version 104 on Windows

### ISSUE THREAD

**Issue by blacklightprism** [neutralinojs/neutralinojs#969]
Hi!
I'm developing an App with Neutralino on Windows 10.
Since WebView2 was updated from Version 103 to Version 104, the API Neutralino.window.create seems to be broken.
New windows won't open. For a very short time, the window flashes in background, but then does not resize, come to foreground and display the content like before but instead crashes and closes.

Tested on a PC with Windows 10 (WebView2 104) where it does not work and on a PC with Windows 11 (WebView2 103) where it is working.

No error logs in neutralinojs.log file and no info in console from DevTools in open main window.

To recreate this issue: 
1. create new app from sample: `neu create test`
2. add `window.*,` in line 18 in neutralino.config.json (to nativeAllowList)
3. add this function in main.js:
`function openAgain() {
    Neutralino.window.create("/index.html", {
        title: "Window title",
        exitProcessOnClose: true
    });
}`
4. add link to execute function in index.html:
`<a href="#" onclick="openAgain();">Open in new Window</a>`

Expected behaviour: Working with WebView2 Version 103, Crashing with WebView2 Version 104.
(To find out which WebView Version is installed, go in system settings to section apps, search in list for WebView and click to reveal version information)

--- Global ---
neu CLI: v9.3.1
--- Project: test (js.neutralino.sample) ---
Neutralinojs binaries: v4.7.0
Neutralinojs client: v3.6.0
Project version: v1.0.0

Has anybody encountered the same problem?

Regards Marc

**Comment by cer1969** [comment]
I have the same problem on windows 11.
Same neutralino and webview2 versions.

**Comment by DanMB** [comment]
I have the same issue with version 104 on Windows 10

**Comment by arianoweb** [comment]
to me, open for 2 second without configuration, after close

**Comment by chadams** [comment]
same issue, window.create is erroring now after being on WebView2 104

```
Faulting application name: membership-sailing-challenges-win_x64.exe, version: 0.0.0.0, time stamp: 0x622a35e6
Faulting module name: membership-sailing-challenges-win_x64.exe, version: 0.0.0.0, time stamp: 0x622a35e6
Exception code: 0xc0000005
Fault offset: 0x0000000000122f22
Faulting process id: 0x4074
Faulting application start time: 0x01d8bbc16326bb1b
Faulting application path: C:\Users\chada\Desktop\membership-sailing-challenges-release-2.2.27\membership-sailing-challenges\membership-sailing-challenges-win_x64.exe
Faulting module path: C:\Users\chada\Desktop\membership-sailing-challenges-release-2.2.27\membership-sailing-challenges\membership-sailing-challenges-win_x64.exe
Report Id: 3533006f-cf8f-4d55-a1d3-7ea229bf62da
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by chadams** [comment]
It might be worth flagging this as a BUG

Here is a reference on distributing WebView2 version 103 specifically. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#:%7E:text=recently%20added%20APIs.-,Details%20about%20the%20Fixed%20Version%20runtime%20distribution%20mode,-For%20constrained%20environments

**Comment by chadams** [comment]
@blacklightprism were you able to resolve this? My app is completely broken atm because window.create always crashes and closes.

**Comment by blacklightprism** [comment]
No @chadams, wasn't able to resolve this.

**Comment by chadams** [comment]
@blacklightprism were you able to work around it somehow?

**Comment by blacklightprism** [comment]
Unfortunately not. Maybe I'm going to make a web-app and use tabs for multiple windows until this works again.
WebView Version 105 doesn't work on my site either.

**Comment by blacklightprism** [comment]
Problem seems to not longer exist on my side.
Upgraded to neutralino v4.8.0 -> working, after downgrade to v4.7.0 it keeps working.
Webview 105.0.1343.53
