### ISSUE TITLE
Extensions example missing enableExtensions

### ISSUE THREAD

**Issue by MrAmericanMike** [neutralinojs/neutralinojs#972]
Not much as a bug, but a detail missing in the Extensions example provided in the repository.

The `neutralino.config.json` at https://github.com/neutralinojs/neutralinojs/tree/main/bin is missing the `"enableExtensions": true,` for it to work properly.

**Comment by shalithasuranga** [comment]
Hi.. @MrAmericanMike, Thanks for reporting this issue. Yes, it's done like that intentionally since we don't need extensions in everytime we use the Neutralinojs test app. We can enable extensions anytime using the `--enable-extensions` CLI argument :tada:
