### ISSUE TITLE
Does not run resource script

### ISSUE THREAD

**Issue by JoaquinDecima** [neutralinojs/neutralinojs#976]
**Describe the bug**
I create an App with a `.sh` script in my resource. Although when I run it with `neu run` I can use it without problems, it does not find the script when I compile it. How should be the path to use to be able to run those `.sh` or what is the best way?

**To Reproduce**
1. Create a project
2. create any sh script in `/resources/scripts/myscript.sh`
  ```bash
  #!/usr/bin/env bash
  cd "/home/"$USER
  pwd
  ```
3. Call it from our neutralino main.js
```javascript
Neutralino.os.execCommand('./resources/scripts/myscript.sh');
```
4. Build and run
5. See error

**Expected behavior**
Compiling it should work the same as when using `neu run`

**Screenshots/Screen recordings**
![Screenshot_20220824_194438](https://user-images.githubusercontent.com/11674229/186536572-2d531a5b-1f9f-47ba-81c4-5f4d2ab0784c.png)

**Specifications**  
 - OS: Linux x64
 - Neutralinojs version: 4.7.0
 - Neutralinojs client library version: 3.6.0
 - Neutralinojs CLI version: 9.3.1

*Note: you can enter the `neu version` command to find these details*

**Additional context**
CODE in job https://gitlab.com/legionlinuxgamers/minecraft-launcher

**Comment by kolbasa** [comment]
(I am not a neutralinojs expert.)
Personally I would just write a build script which copies all your script files to the `dist` folder after the `new build --release`.

**Comment by gaoDean** [comment]
+1, this would be nice to fix, but kolbasa's approach works as well.

**Comment by JoaquinDecima** [comment]
I particularly solved it as @kolbasa said. I don't know how good it is though, but it works.

**Comment by shalithasuranga** [comment]
Hello @JoaquinDecima, native APIs don't work with bundled resources, but we recently added `getFiles()`, `extractFile(path, dest)`, `readFile(path)`, and `readBinaryFile(path)` functions to the `resources` module, so you can use them to take bundled resources out from the `resources.neu` file to get them working with all native APIs.  Thanks so much for reporting this issue :tada:
