### ISSUE TITLE
Puppeteer in Neutralino

### ISSUE THREAD

**Issue by garv-shah** [neutralinojs/neutralinojs#990]
Is it possible to use Puppeteer in Neutralino?

With my current code, `import puppeteer from "puppeteer";` throws an error, stating `TypeError: Module specifier, 'puppeteer' does not start with "/", "./", or "../".`

Is there any way to run node.js commands from the client side?

Thanks!

**Comment by hv6erT** [comment]
Yes it is possible but you need to understand difference between Neutralino and Node JS (including Electron, NW.JS and others). 

1. Firstly, Neutralino **DOES NOT** provide NodeJS. You can connect it using extension api.
2. Secondly, Neutralino is like a browser with additional filesystem api and other great modules. There are some cons of it:
- You cannot use require() function - it is NodeJS api
- To import files using ES module syntax you need to set enableServer option to true in neutralino.config.json. Then you should specify relative path to your module, example: 
`import MyFavoriteModule from '../modules/someModule.js';`
- There are some other limitations check here: [Docs](https://neutralino.js.org/docs/)

All of those limitations, no Node built-in, makes Neutralino faster and smaller.

**Comment by shalithasuranga** [comment]
Closing this since the issue has been answered. Thanks for discussing :tada:
