### ISSUE TITLE
Use the same image size and spaces for dark/light theme logos in README.md

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#992]
- Upload modified images to the `media` directory
- Update https://github.com/neutralinojs/design-guide as well

**Comment by karandeeppotato** [comment]
Didn't noticed that the sizes of the light theme logo and dark theme logo are different.

Anyways, I am willing to solve this issue. 😅

**Comment by pathange-s** [comment]
@karandeeppotato looks like this is a very small issue. Please update us once you are done fixing it. Thanks for showing up.

**Comment by FixxooXD** [comment]
is anyone working in this issue?

**Comment by karandeeppotato** [comment]
@FixxooXD hey!
Thanks for showing up.... I was a bit busy with my college work so I guess you can have this issue

**Comment by karandeeppotato** [comment]
@FixxooXD hey


Hope you doin' well

Are you working on this issue?

**Comment by FixxooXD** [comment]
@karandeeppotato  sorry i was busy this week  i didn't  work in this issue  if you want you can work in this issue

**Comment by karandeeppotato** [comment]
@shalithasuranga hey... A small request

Can you put this issue under hacktoberfest tag ...😅

Hehe
