### ISSUE TITLE
To update the Wiki 

### ISSUE THREAD

**Issue by kingkartick** [neutralinojs/neutralinojs#997]
👋 👋 Hey Neutralino !! . I am  new in  the dev community ,but using neutralino from a time now . Just saw the wiki  and if possible would like to add Some points in it for the new  upcoming devs .

**Comment by RavieshMaini** [comment]
Just saw the feature-request and would like to help you in this.

**Comment by shalithasuranga** [comment]
Hello thanks everyone for the interest with Neutralinojs. Feel free to submit a pull request with your suggestions. Thanks :tada:
